### ISSUE TITLE
--preScript: invalid placed argument

### ISSUE THREAD

**Issue by dkottmann** [claeis/ili2db#104]
java -Xmx1024m -jar /opt/ili2pg/ili2pg.jar --dbport 5432 --dbdatabase wfs_agg --dbschema ili_lwb_biodiversitaetsfoerderflaechen_staging --dbusr '***' --dbpwd '***' --schemaimport --createGeomIdx --defaultSrsCode 21781 --createBasketCol --createFkIdx --sqlEnableNull --idSeqMin 4600000000000000001 --idSeqMax 9223372036854775807 --oneGeomPerTable --createEnumTxtCol --disableValidation --preScript /home/rails/geodienste-config/current/ili_agg/sql/lwb_biodiversitaetsfoerderflaechen/PreScript.sql /home/rails/geodienste-config/current/ili_agg/ili/lwb_biodiversitaetsfoerderflaechen/Biodiversitaetsfoerderflaechen_Qualitaetsstufe_II_und_Vernetzung_LV03_V1_4.ili

/home/rails/geodienste-config/current/ili_agg/sql/lwb_biodiversitaetsfoerderflaechen/PreScript.sql: invalid placed argument

same Problem with option --postScript

**Comment by dkottmann** [comment]
Info: ili2pg-3.9.0-20170620

**Comment by claeis** [comment]
fixed in ili2pg-3.10.6
