### ISSUE TITLE
Nutzungsplanung: ili2pg dangling references but correct data

### ISSUE THREAD

**Issue by dkottmann** [claeis/ili2db#105]
http://models.geo.admin.ch/ARE/Nutzungsplanung_V1_1.ili
ili2pg Version: ili2pg-3.9.0-20170620

**Error dangling references (Example) during Import with ili2pg:** 
`Error: unknown referenced object Nutzungsplanung_LV95_V1_1.Rechtsvorschriften.Dokument TID x4791_21827_besch referenced from Nutzungsplanung_LV95_V1_1.Geobasisdaten.Typ_Dokument TID x1_nokogde:x4791_21827_besch`

Data ist valid (ilivalidator 1.3.0).

**Data (Example):**
Object in Typ_Dokument: 
`<Nutzungsplanung_LV95_V1_1.Geobasisdaten.Typ_Dokument><Typ REF="x1_nokogde"></Typ><Vorschrift REF="x4791_21827_besch"></Vorschrift></Nutzungsplanung_LV95_V1_1.Geobasisdaten.Typ_Dokument>`

Referenced Objects in Rechtsvorschrift: 
`<Nutzungsplanung_LV95_V1_1.Rechtsvorschriften.Rechtsvorschrift TID="x4791_21827_besch"><Titel>Beschluss: Departement_fuer_Bau_und_Umwelt</Titel><OffizielleNr>DBU_89</OffizielleNr><Kanton>TG</Kanton><publiziertAb>2004-08-16</publiziertAb><Rechtsstatus>inKraft</Rechtsstatus><TextImWeb><Nutzungsplanung_LV95_V1_1.MultilingualUri><LocalisedText><Nutzungsplanung_LV95_V1_1.LocalisedUri><Language>de</Language><Text>http://oereblex.tg.ch//api/geolinks/2181</Text></Nutzungsplanung_LV95_V1_1.LocalisedUri></LocalisedText></Nutzungsplanung_LV95_V1_1.MultilingualUri></TextImWeb><Bemerkungen>Genehmigung Schutzplan Natur- und Kulturobjekte</Bemerkungen></Nutzungsplanung_LV95_V1_1.Rechtsvorschriften.Rechtsvorschrift>`

References in data should be ok. (defined for "Rechtsvorschrift", which inherits "Dokument")

**Comment by claeis** [comment]
fixed in ili2pg-3.10.6
