### ISSUE TITLE
MultipleGeomAttrs on smart2inheritance problem

### ISSUE THREAD

**Issue by mejiafabiandj** [claeis/ili2db#107]
creating a class that inherits from a parent with multiple geometry attributes, classes of all geometries are not created neither in parent or child class

![image](https://user-images.githubusercontent.com/3708192/30224092-05653a72-9493-11e7-9fa6-a829ffa959d4.png)

![image](https://user-images.githubusercontent.com/3708192/30223930-6a523f44-9492-11e7-8095-61091cfa1224.png)

result as:

![image](https://user-images.githubusercontent.com/3708192/30223954-7ea7540c-9492-11e7-9945-474efa61e2fa.png)

if there is not inheritance works fine

![image](https://user-images.githubusercontent.com/3708192/30224058-e08d3100-9492-11e7-9996-8dd0c26b5e35.png)

![image](https://user-images.githubusercontent.com/3708192/30224035-c7b3ff24-9492-11e7-8842-99930d4d9e8c.png)

i'm using these parameters:

--schemaimport --trace --dbfile "test\data\MultipleGeomAttrs\MultipleGeomAttrs2.gdb" --fgdbXyResolution 0.001 --fgdbXyTolerance 0.001 --createEnumTabs --createNumChecks --createGeomIdx --createFk --createMetaInfo  --**smart2Inheritance** --defaultSrsAuth EPSG --defaultSrsCode 3116 "test\data\MultipleGeomAttrs\MultipleGeomAttrs2.ili"

[MultipleGeomAttrs2.zip](https://github.com/claeis/ili2db/files/1288687/MultipleGeomAttrs2.zip)

**Comment by claeis** [comment]
affects also ili2gpkg (and ili2pg with --oneGeomPerTable)

**Comment by claeis** [comment]
What DB schema would you expect: a second helper table or in the existing helper table a alternative/second FK to the main table?

**Comment by mejiafabiandj** [comment]
As we are using smart2, would be enough to create a secondary feature class including only geometry and its ID will be a FK in the main table, but it should be the same for parent and child Classes, so at the end we  will have 4 tables for the example above: ClassA(Point), ClassA_Surface, ClassB(point), ClassB(Surface)

**Comment by claeis** [comment]
One secondary table per main table (as proposed by the comments) requires more effort

**Comment by claeis** [comment]
3.12.0
