### ISSUE TITLE
use/create a repository for the generated jars

### ISSUE THREAD

**Issue by claeis** [claeis/ili2db#108]

**Comment by claeis** [comment]
repos url: http://jars.interlis.ch
ch.interlis:ili2pg:3.10.7

**Comment by claeis** [comment]
``ch.interlis:ili2pg:3.10.+``

**Comment by mejiafabiandj** [comment]
is it possible to add ili2gpkg to the repo?

**Comment by claeis** [comment]
will do so, when i do  #126
