### ISSUE TITLE
CREATE EXTENSION IF NOT EXISTS "uuid-ossp"

### ISSUE THREAD

**Issue by m-kuhn** [claeis/ili2db#116]
Forwarding this issue

https://github.com/opengisch/projectgenerator/issues/111

**Comment by claeis** [comment]
Did you check the already existing option --setupPgExt? Or do I miss something?

**Comment by m-kuhn** [comment]
I guess this concerns the `IF NOT EXISTS` part, is that already implemented with `--setupPgExt`?

CC @zigertiger

**Comment by edigonzales** [comment]
[https://github.com/claeis/ili2db/blob/06239885d0710057056df594ee316668a98e3fb5/ili2pg/src/ch/ehi/ili2pg/PgCustomStrategy.java#L60](https://github.com/claeis/ili2db/blob/06239885d0710057056df594ee316668a98e3fb5/ili2pg/src/ch/ehi/ili2pg/PgCustomStrategy.java#L60)

**Comment by claeis** [comment]
yes, version>=3.9.0
