### ISSUE TITLE
ili2pg: incomplet schema of imported models

### ISSUE THREAD

**Issue by mirjamzehnder** [claeis/ili2db#120]
The Model "Bewirtschaftungseinheit" is imported in the Model "Nutzungsflächen". When importing the schema of "Nutzungsflächen" with ili2pg, the Topic "Bewirtschaftungseinheit_LV95_V1_3.Gueltigkeitsdauer" isn't implemented in the schema. 
When than importing the data, first the XTF of "Bewirtschaftungseinheit" followed by the XTF "Nutzungsfläche", the following Error appears:
![grafik](https://user-images.githubusercontent.com/28288352/31621106-3940ac2c-b299-11e7-9a0c-bbed37f3a606.png)

Why the Topic "Bewirtschaftungseinheit_LV95_V1_3.Gueltigkeitsdauer" isn't implemented in the schema "Nutzungsflächen"?
![grafik](https://user-images.githubusercontent.com/28288352/31649489-6e37ce68-b313-11e7-881d-219100497632.png)

How can we add this topic?

When importing only the XTF of "Nutzungsflächen", the referenced objects are missing:
![grafik](https://user-images.githubusercontent.com/28288352/31649567-cd9de374-b313-11e7-9de7-1a03602d0514.png)

Leaving away the Topic "Bewirtschaftungseinheit_LV95_V1_3.Gueltigkeitsdauer" in the XTF "Bewirtschaftungseinheit" is no option, as this would cause a manual extra effort.

http://models.geo.admin.ch/BLW/Nutzungsflaechen_V1_4.ili
http://models.geo.admin.ch/BLW/Bewirtschaftungseinheit_V1_3.ili
[nf_bwe_SH.zip](https://github.com/claeis/ili2db/files/1390007/nf_bwe_SH.zip)

**Comment by edigonzales** [comment]
The following works for me:

_Bewirtschaftungseinheiten_

`java -jar ~/apps/ili2pg-3.9.1/ili2pg.jar --dbhost geodb-dev.fubar.eu-central-1.rds.amazonaws.com --dbdatabase xanadu2 --dbusr XXXXX --dbpwd YYYYY --nameByTopic --disableValidation --defaultSrsCode 2056 --strokeArcs --createGeomIdx --createFkIdx --createEnumTabs --beautifyEnumDispName  --models Bewirtschaftungseinheit_LV95_V1_3 --dbschema ai_landwirtschaft --schemaimport `

`java -jar ~/apps/ili2pg-3.9.1/ili2pg.jar --dbhost geodb-dev.fubar.eu-central-1.rds.amazonaws.com --dbdatabase xanadu2 --dbusr XXXXX --dbpwd YYYYY --nameByTopic --disableValidation --defaultSrsCode 2056 --strokeArcs --createGeomIdx --createFkIdx --createEnumTabs --beautifyEnumDispName  --models Bewirtschaftungseinheit_LV95_V1_3  --dbschema ai_landwirtschaft --import landwirtschaftliche_zonengrenzen_kataloge_20140701.xml`

`java -jar ~/apps/ili2pg-3.9.1/ili2pg.jar --dbhost geodb-dev.fubar.eu-central-1.rds.amazonaws.com --dbdatabase xanadu2 --dbusr XXXXX --dbpwd YYYYY --nameByTopic --disableValidation --defaultSrsCode 2056 --strokeArcs --createGeomIdx --createFkIdx --createEnumTabs --beautifyEnumDispName  --models Bewirtschaftungseinheit_LV95_V1_3  --dbschema ai_landwirtschaft --import bearbeitungsstatus_kataloge_20140701.xml`

`java -jar ~/apps/ili2pg-3.9.1/ili2pg.jar --dbhost geodb-dev.fubar.eu-central-1.rds.amazonaws.com --dbdatabase xanadu2 --dbusr XXXXX --dbpwd YYYYY --nameByTopic --disableValidation --defaultSrsCode 2056 --strokeArcs --createGeomIdx --createFkIdx --createEnumTabs --beautifyEnumDispName  --models Bewirtschaftungseinheit_LV95_V1_3 --dbschema ai_landwirtschaft --import bwe_SH.xtf `

_Nutzungsflächen_

`java -jar ~/apps/ili2pg-3.9.1/ili2pg.jar --dbhost geodb-dev.fubar.eu-central-1.rds.amazonaws.com --dbdatabase xanadu2 --dbusr XXXXX --dbpwd YYYYY --nameByTopic --disableValidation --defaultSrsCode 2056 --strokeArcs --createGeomIdx --createFkIdx --createEnumTabs --beautifyEnumDispName  --models Nutzungsflaechen_LV95_V1_4 --dbschema ai_landwirtschaft --schemaimport`

`java -jar ~/apps/ili2pg-3.9.1/ili2pg.jar --dbhost geodb-dev.fubar.eu-central-1.rds.amazonaws.com --dbdatabase xanadu2 --dbusr XXXXX --dbpwd YYYYY --nameByTopic --disableValidation --defaultSrsCode 2056 --strokeArcs --createGeomIdx --createFkIdx --createEnumTabs --beautifyEnumDispName  --models Nutzungsflaechen_Kataloge_V1_4  --dbschema ai_landwirtschaft --import Nutzungsflaechen_V1_4_Kataloge_20170322.xml`

`java -jar ~/apps/ili2pg-3.9.1/ili2pg.jar --dbhost geodb-dev.fubar.eu-central-1.rds.amazonaws.com --dbdatabase xanadu2 --dbusr XXXXX --dbpwd YYYYY --nameByTopic --disableValidation --defaultSrsCode 2056 --strokeArcs --createGeomIdx --createFkIdx --createEnumTabs --beautifyEnumDispName  --models Nutzungsflaechen_LV95_V1_4 --dbschema ai_landwirtschaft --import nf_SH.xtf `

**Comment by claeis** [comment]
just list all the models (separated by semicolons) that your *data/application* requires after --models while you do the --schemaimport (e.g. --models  Bewirtschaftungseinheit_LV95_V1_3;Landwirtschaftliche_Zonengrenzen_Kataloge_V1_2;Bearbeitungsstatus_V1_2;Bewirtschaftungseinheit_LV95_V1_3;Nutzungsflaechen_LV95_V1_4

**Comment by romefi** [comment]
Bewirtschaftungseinheit_LV95_V1_3 is mentioned as imports in Nutzungsflaechen_LV95_V1_4.ili:

_ IMPORTS Bewirtschaftungseinheit_V1_3,GeometryCHLV03_V1,Bearbeitungsstatus_V1_2,Units,Nutzungsflaechen_Kataloge_V1_4;_

Shouldn't the topic Bewirtschaftungseinheit_LV95_V1_3.Gueltigkeitsdauer also be generated in the schema? All other topics of Bewirtschaftungseinheit_LV95_V1_3 are generated. Is this a "bug" because the topic  Gueltigkeitsdauer appears in both models and are identical or are there another reason why it isn't generated?

**Comment by claeis** [comment]
No, ili2db doesn't use the IMPORTs from the ili-models to evaluate the set of tables to be created (That would often lead to many not needed tables, such as tables from model CoordSys). 

ili2db evaluates the set of tables to be created by deep following the data references (given by the ASSOCATIONs of the seed models).
