### ISSUE TITLE
support smart mapping of structures to JSON

### ISSUE THREAD

**Issue by claeis** [claeis/ili2db#128]
Gefaehrdung_Hecke = (Unterweidung, Rodung, Verwaldung);
STRUCTURE Gefaehrdung =
   Gefaehrdung_Hecke: Gefaehrdung_Hecke;
END Gefaehrdung;
CLASS Hecken_Feldgehoelze_Basis (ABSTRACT) =
  ...
  !!@ili2db.mapping=JSON
  Gefaehrdung_Hecke: BAG {0..*} OF Gefaehrdung;
  ...
END Hecken_Feldgehoelze_Basis;

**Comment by claeis** [comment]
to JSONB in Postgres (to get indexing)

**Comment by m-kuhn** [comment]
On GeoPackage side this could be implemented via the 'schema' extension with 'application/json' in gpkg_data_columns as the 'mime_type'.

http://www.geopackage.org/spec/#extension_schema

---------

If JSON (or JSON_TEXT) should be used as column type for SQLITE it will require a separate extension (http://www.geopackage.org/spec/#r5)

For more information see https://lists.osgeo.org/pipermail/gdal-dev/2018-November/049306.html

**Comment by claeis** [comment]
@m-kuhn any preference of how to encode the type of the structure?

```json
{

    "@type": "Model.Topic.StructA",
    "attrA": [{
        "@type": "Model.Topic.StructB",
        "attrB": "b1"
    }, {
        "@type": "Model.Topic.StructB",
        "attrB": "b2"
    }]
}
```

**Comment by m-kuhn** [comment]
How are these structures mapped in postgres currently?

I was expecting

`["b1", "b2"]`

**Comment by claeis** [comment]
see attached sample
[20181221-Json23.zip](https://github.com/claeis/ili2db/files/2703586/20181221-Json23.zip)
