### ISSUE TITLE
check that --createBasketCol is used (if required)

### ISSUE THREAD

**Issue by claeis** [claeis/ili2db#130]
If a TOPIC EXTENDs another topic and doesn't extend all CLASSes of the base topics, --createBasketCol must be used to get a a correct export. ili2db should check this (and report an error if not the case).

**Comment by claeis** [comment]
should also check:

    TOPIC Geobasisdaten =
        BASKET OID AS TypeID

**Comment by signedav** [comment]
Thanks👍
