### ISSUE TITLE
Ili2fgdb: Issue with wrong references when importing XML catalog and data separately

### ISSUE THREAD

**Issue by hjaeggi** [claeis/ili2db#131]
References to external XML catalog are not mapped correctly with ili2fgdb, when I import the catalog (xml-file) first and afterwards the data (xtf-file) referencing the catalog. The result I get is, that all references point to the first entry of the external catalog. This leads to the situation that the entries are formally correct (validation does not throw an error) but substantively wrong.

Do I have to define an additional parameter to get the correct references or is there any other solution for this problem?

Example: 
Model Wildruhezonen

Reference Attribute "Bestimmungen" from Class Wildruhezonen_LV95_V1_1.Wildruhezonen.Wildruhezone_Teilobjekt 
to Wildruhezonen_Codelisten_V1_1.Codelisten.Bestimmungen_CatRef

parameters used for import

java -d64 -jar ili2fgdb.jar --trace --import --dbfile WRZ_import.gdb --defaultSrsAuth EPSG --defaultSrsCode 2056 --fgdbXyResolution 0.0001 --fgdbXyTolerance 0.001 --modeldir http://models.interlis.ch/;http://models.geo.admin.ch --dataset Wildruhezonen_Catalogues_V1_1.xml --importTid --createBasketCol --smart2Inheritance --createEnumTabs --beautifyEnumDispName --sqlEnableNull --log ili2fgdb_XMLimport.log Wildruhezonen_Catalogues_V1_1.xml

java -d64 -jar ili2fgdb.jar --trace --import --dbfile WRZ_import.gdb --defaultSrsAuth EPSG --defaultSrsCode 2056 --fgdbXyResolution 0.0001 --fgdbXyTolerance 0.001 --modeldir http://models.interlis.ch/;http://models.geo.admin.ch --dataset SG00110.xtf --importTid --createBasketCol --smart2Inheritance --createEnumTabs --beautifyEnumDispName --sqlEnableNull --log ili2fgdb_XTFimport.log SG00110.xtf

http://models.geo.admin.ch/BAFU/Wildruhezonen_V1_1.ili
http://models.geo.admin.ch/BAFU/Wildruhezonen_Catalogues_V1_1.xml
[SG00110.zip](https://github.com/claeis/ili2db/files/1521153/SG00110.zip)

**Comment by claeis** [comment]
No, no additional parameter required. 
Can reproduce the issue. Seems to be a bug in ili2fgdb (but works fine with ili2pg). Will further analyze issue.

**Comment by hjaeggi** [comment]
Unfortunately our tests with ili2fgdb version 3.11.3 still indicate the same problem. The references from the attribute "Bestimmungen" in Wildruhezonen_LV95_V1_1.Wildruhezonen.Wildruhezone_Teilobjekt point to the first catalog entry instead of showing the variation of the original entries. The same problem occurs with other models with external xml-catalogs and correspondent test data.

Part of the problem seems that ili2fgdb assigns new TIDs and thus new references as foreign keys to the original data. There also seems to be a problem with the separation of the import process in two separate steps (step1: import xml-catalog, step 2: import xtf-data). References within the xtf-data import (step 2) process (e.g. from Wildruhezonen_LV95_V1_1.Wildruhezonen.Wildruhezone_Teilobjekt to Wildruhezonen_LV95_V1_1.Wildruhezonen.Wildruhezone) are mapped correctly, whereas references from xtf-data to xml-catalog (step 1 and 2) are not mapped correctly.

The parameters used are the same as mentioned above.

**Comment by claeis** [comment]
The TID from that transfer file is not the column t_id. ili2db uses this new generated primary key to link objects.

I checked and it looks fine. see gdb file [ceis.gdb.zip](https://github.com/claeis/ili2db/files/1960487/ceis.gdb.zip).
The following text is a text dump from the attachment.
```
OGRFeature(wildruhezone_teilobjekt):70
  T_Id (Integer) = 301
  T_basket (Integer) = 46
  T_Ili_Tid (String) = 269
  teilobjnummer (String) = 00
  zusatzinformationen (String) = Wildruhezone mit Vorschriften im Winter
  bestimmungen (Integer) = 7
  bestimmungen_kt (String) = (null)
  bestimmungen_kt_de (String) = (null)
  bestimmungen_kt_fr (String) = (null)
  bestimmungen_kt_rm (String) = (null)
  bestimmungen_kt_it (String) = (null)
  bestimmungen_kt_en (String) = (null)
  schutzzeit (String) = 16.12. bis Ende Skisaison
  wrz (Integer) = 116  --> references wildruhezone:67; see below
  MULTIPOLYGON (((2754797.4586 1205996.5103,2754776.7373 ...)))

OGRFeature(wildruhezone):67
  T_Id (Integer) = 116
  T_basket (Integer) = 46
  T_Ili_Tid (String) = 35
  objnummer (Integer) = 35
  kanton (String) = SG
  aname (String) = Zanuz
  schutzstatus (Integer) = 5 --> references schutzkategorie_catalogue:1; see below
  grundlage (String) = Schutzverordnung
  beschlussjahr (Integer) = 2009
  mutationsdatum (DateTime) = 2009/05/08 00:00:00
  mutationsgrund (String) = (null)
  mutationsgrund_de (String) = Erfassung Geometrie
  mutationsgrund_fr (String) = (null)
  mutationsgrund_rm (String) = (null)
  mutationsgrund_it (String) = (null)
  mutationsgrund_en (String) = (null)

OGRFeature(schutzkategorie_catalogue):1
  T_Id (Integer) = 5
  T_basket (Integer) = 4
  T_Ili_Tid (String) = 1001
  code (String) = S10
  description (String) = (null)
  description_de (String) = rechtsverbindlich
  description_fr (String) = contraignant
  description_rm (String) = (null)
  description_it (String) = vincolante
  description_en (String) = (null)
```

**Comment by hjaeggi** [comment]
The references in your sample ceis.gdb are also wrong. All entries of the attribute "Bestimmungen" contain the value "7" which is the first entry in the catalog. This value is by chance correct for your example above, but not for other objects. For example for the wildruhezonen object with objnummer (Integer) = 38 and aname (String) = Wartau the correct value in wildruhezone_teilobjekt would be bestimmungen (Integer) = 21.

**Comment by claeis** [comment]
ok, I see the issue

**Comment by claeis** [comment]
3.12.2
