### ISSUE TITLE
ili2pg: Doesn't consider the option --defaultSrsCode 2056 anymore because of wrong meta attributes in GeometryCHLV95_V1

### ISSUE THREAD

**Issue by pramisters** [claeis/ili2db#134]
In one case I noticed a strange behaviour of the latest Version 3.11.0 of ili2pg:
It generates geometry columns with SRS 21781 although "--defaultSrsCode 2056" was used.

When I use version 3.10.7 instead with the exact same ili-model and the exact same java command it works fine.

In the CHANGELOG.txt (3.11.0) it says:
 - read CRS from ili

What does that mean? What was changed/added here?

**Comment by pramisters** [comment]
I found the error:
The base modell CHBase_Part1_GEOMETRY_20110830.ili was changed a few days ago:

!! 2017-11-27 | KOGIS | Meta-Attributes @furtherInformation adapted and @CRS added (line 30, 43 and 49)

But the meta attributes for LV95 are wrong:
It says !!@CRS=EPSG:21781 instead of !!@CRS=EPSG:2056

**Comment by mirjamzehnder** [comment]
The error in the modell CHBase_Part1_GEOMETRY_20110830.ili has just been corrected

**Comment by pramisters** [comment]
Thanks for the fast correction!

But, ili2pg still takes the old, wrong Version of GeometryCHLV95_V1 which is \obsolete/GeometryCHLV03_V1_o2_.ili

The logfile of ili2pg says:
`Warning: model GeometryCHLV95_V1: broken version chain; use version 2015-11-12; others ignored
`

That means that the metadata in ilimodels.xml is not correct. To be more precise, the value for the tag <precursorVersion> of the new entry for GeometryCHLV95_V1 in line 460 must be "2015-11-12" and not "2015-11-27". The same data error can be found in line 439 for the LV03 entry.

**Comment by mirjamzehnder** [comment]
Thanks for the testing, should again be corrected.

**Comment by pramisters** [comment]
Thanks, works fine again.
