### ISSUE TITLE
Topology errors?

### ISSUE THREAD

**Issue by ChrisVolz** [claeis/ili2db#136]
My problem may be specific and difficult to answer. Perhaps someone has an idea how to deal with it...

I have a polygon dataset in an Esri GDB. This GDB can be exported to Interlis1 (.itf) with success. The validation afterwards, however, fails due to topology errors (overlaps, gaps,...).

My problem is: I cannot detect any errors in the feature dataset. Visually, everything is ok. The ArcMap-Topolgy-Check is ok. Importing the dataset in GRASS, cleaning the topogly, exporting to shp and re-importing in the GDB does not help. Using the Interlis-Viewer no problems can be visually detected.

It seems that the feature dataset is ok, but the validator does not succeed. Somebody has an idea what can cause the problem and how to tackle it? Has someone used the ili2fgdb-tool on non-trivial polygon-datasets with success?
 
best regards,
Chris

**Comment by claeis** [comment]
- Try the additional option ``--trace``, that gives a more detailed log.
- Try to isolate the curve segments, that reproduce the problem (example https://github.com/claeis/iox-ili/blob/master/src/test/data/Itf/Test2LV95_05AreaHole.itf)

**Comment by ChrisVolz** [comment]
Dear claeis

I have now isolated the problem further and I am quite sure, that something is wrong with the provided tools. My workflow:

1) I have downloaded an .itf file and .ili file from the Kanton Solothurn.
2) This .itf file and .ili file passes the validator.
3) I create a GDB from the .ili file (--schemaimport) using the ili2fgdb-tool
4) I import the .itf file (--import) to the created GDB using the ili2fgdb-tool
5) I export the GDB (--export) to a new .itf file using the ili2fgdb-tool
6) The validation of the exported .itf file fails.

In my opinion this must not happen. The data seems to be changed somewhere in this process. Unfortunately I have no idea how to tackle this problem...

regards

[nat_dornach.zip](https://github.com/claeis/ili2db/files/1538611/nat_dornach.zip)

**Comment by ChrisVolz** [comment]
Additional note:

I tried the same workflow using POSTGIS instead of GDB. The same result - the exported .itf fails the validator...

**Comment by claeis** [comment]
which versions did you use?

**Comment by ChrisVolz** [comment]
my used versions:

- ili2fgdb-3.10.9
- ili2pg-3.11.0
- ilivalidator-1.5.0

ArcGIS 10.1

Postgresql 10.1, POSTGIS 2.4

**Comment by ChrisVolz** [comment]
Sorry for posting such a lot ;)

I have further isolated the problem to following situation:

-  I have a GDB with only 1 dataset containing 2 Polygons
- ThePolygons are topological correct
- Export with ili2fgdb to .itf 
(java -jar ili2fgdb.jar --export --models Naturgefahrenkarte_SO_V11 --dbfile bbb.gdb export.itf)
- The export.tif file has "double lines" and, hence, is topological incorrect

The files are attached to this posting. I hope this allows for an easier bug-test?
[doppelte_linien.zip](https://github.com/claeis/ili2db/files/1551452/doppelte_linien.zip)

**Comment by ChrisVolz** [comment]
An additional info:
The ili2fgdb-tools seem to work with INTERLIS2. The validation suceeds. The problem with duplicated lines is limited to INTERLIS1. Is there are tool for converting from INTERLIS2 to INTERLIS1 ?
