### ISSUE TITLE
ili2pg: Wrong references after export

### ISSUE THREAD

**Issue by dkottmann** [claeis/ili2db#139]
If option -ImportTid is used, data is not valid anymore after export. (probably due to different reference values? It seems like ili2pg uses wrong Tid-Values for export. ili2pg shoud "know", which reference values to use. )

ilivalidator on original data --> everything ist fine
then import with option -ImportTid
then export
then validation fails, see [ilivalidator_after_export.log](https://github.com/claeis/ili2db/files/1579266/ilivalidator_after_export.log)

Maybe this is related to issue https://github.com/claeis/ili2db/issues/131 (see there for example data)

**Comment by claeis** [comment]
ili2pg-3.11.1
