### ISSUE TITLE
read all ili-meta-attributes into a new ili2db meta table

### ISSUE THREAD

**Issue by m-kuhn** [claeis/ili2db#140]
It would be nice to have access to all meta attributes - also those unknown to ili2db.

For example with a new table `ili2db_meta_attrs` with 3 attributes `object_name`, `attr_name`, `attr_value`.

@claeis Corrections of the proposed names welcome

**Comment by claeis** [comment]
Create only if option --createMetaInfo present.

Create a new table that includes all meta attributes, including the ones, that are related to ili model elements that are not mapped to a db element.

```
CREATE TABLE t_ili2db_meta_attrs (
 ilielement varchar(255) NOT NULL, -- qualified ili name of concerned ili model element
 attr_name character varying(1024) NOT NULL, -- meta attribute name
 attr_value character varying(1024) NOT NULL -- meta attribute value
); 
```

**Comment by claeis** [comment]
ili2pg-3.11.2
