### ISSUE TITLE
Inject meta attributes which are not in the ili-model

### ISSUE THREAD

**Issue by m-kuhn** [claeis/ili2db#141]
Add a new flag to use an additional configuration file that adds more information to the model.
The syntax shall be based on the `toml` files used by the ilivalidator (sections are qualified interlis names, key/value pairs meta attributes). See [example Beispiel1.toml from ilivalidator](https://github.com/claeis/ilivalidator/blob/master/docs/Beispiel1.toml).

**Comment by marioba** [comment]
Hi @claeis, how do I call the option? `--importMetaAttrs`?

**Comment by claeis** [comment]
```--iliMetaAttrs metaattrs.toml```

**Comment by claeis** [comment]
ili2pg-3.11.2
