### ISSUE TITLE
ver4-translation: compiler fails on import

### ISSUE THREAD

**Issue by dkottmann** [claeis/ili2db#144]
Used options at schemaimport of model "Waldabstandslinien_LV95_V1_1" (among others): 
--ver4-translation --models 'Waldabstandslinien_LV95_V1_1;DistancesParRapportALaForet_MN95_V1_1'

Compiler fails on import with ili2pg 3.10.7. 

```
Error: /home/rails/.ilicache/jdbc&003apostgresql&003awfs_agg/ili_npl_waldabstandslinien_lv95_staging/DistancesParRapportALaForet_MN95_V1_1.ili:141:There is no model "Waldabstandslinien_LV95_V1_1".
Error:   There is no model "Waldabstandslinien_LV95_V1_1".
compiler failed
```

See full ilivalidator and ili2pg log attached. 
[ilivalidator_ili2pg.log](https://github.com/claeis/ili2db/files/1617905/ilivalidator_ili2pg.log)

**Comment by claeis** [comment]
What is the result of SELECT file,modelname FROM t_ili2db_model?

**Comment by dkottmann** [comment]
![select_file_modelname](https://user-images.githubusercontent.com/23079469/34781723-e5f14302-f626-11e7-8bef-ed23601223de.png)

**Comment by claeis** [comment]
The table contents indicate that the --schemaimport was done with a version <3.10.6. Issue is ficed in versions>=3.10.6.

**Comment by dkottmann** [comment]
Thanks. Error cannot be reproduced after --schemaimport with version 3.10.7
