### ISSUE TITLE
Import fails with --strokeArcs option

### ISSUE THREAD

**Issue by hdus** [claeis/ili2db#148]
Import with option --strokeArcs leeds to the error below. When the option is disabled the import works fine. I can send the corresponding data directly.

![grafik](https://user-images.githubusercontent.com/1764477/35621841-11365fba-0686-11e8-9966-51c54d0dde24.png)

**Comment by claeis** [comment]
Can you add just the line to the issue, like for example

    OBJE 4827_errorline
    STPT 2643072.984 1233588.996
    ARCP 2643069.053 1233592.102
    LIPT 2643065.209 1233595.315
    ELIN

**Comment by claeis** [comment]
And what ili2db/iox-ili version?

**Comment by hdus** [comment]
OBJE 30136 27272
STPT 2631283.882 1225988.140
ARCP 2631284.773 1225995.819
LIPT 2631288.558 1226002.560
LIPT 2631293.029 1226007.765
ARCP 2631297.503 1226017.040
LIPT 2631296.768 1226027.312
LIPT 2631291.391 1226042.921
LIPT 2631286.162 1226061.578
ARCP 2631283.024 1226079.139
LIPT 2631283.372 1226096.975
ARCP 2631284.240 1226100.891
LIPT 2631285.872 1226104.555
LIPT 2631316.696 1226158.457
ARCP 2631319.368 1226161.486
LIPT 2631323.021 1226163.211
LIPT 2631334.784 1226166.063

**Comment by hdus** [comment]
ili2pg 3.11.1 with iox-ili-1.20.1 (Download from http://eisenhutinformatik.ch/interlis/ili2pg/ili2pg-3.11.1.zip)

**Comment by claeis** [comment]
ili2pg-3.11.2
