### ISSUE TITLE
Error: multiple area-refs to polygon tids

### ISSUE THREAD

**Issue by hdus** [claeis/ili2db#150]
Please explain what does the error message "multiple area-refs to polygon tids .." mean and what causes this error?

**Comment by claeis** [comment]
Given an AREA attribute, there are more than one main object that reference all the same polygon (built from the lines ahead of the main table in the ITF).

**Comment by hdus** [comment]
That means that this error is caused by incorrect data?

**Comment by hdus** [comment]
ilivalidator doesn't throw any errors.

**Comment by claeis** [comment]
yes, this is triggered by incorrect data. ilivalidator should show the same (as this messsage comes from common code).

**Comment by hdus** [comment]
How can I find the incorrect objects in the data?

**Comment by hdus** [comment]
And how to fix it?

**Comment by claeis** [comment]
import with --skipPolygonBuilding --importTid; and either
- edit data with your GIS and export the modified data again, or
- edit the ITF with a text editor (you can see the the TID of main object in the GIS/db in column t_ili_tid)

**Comment by claeis** [comment]
ili2pg-3.11.2
