### ISSUE TITLE
integration_geodienste.ch AV DM01: compiler failed

### ISSUE THREAD

**Issue by VeraDiaz** [claeis/ili2db#154]
Importing a AV DM01-File  on integration.geodienste.ch I get the following error (Validation was done successfully):

Info: ilifile </home/rails/.ilicache/jdbc&003apostgresql&003awfs_agg/ili_av_lv95_staging/DM.01-AV-CH_LV95_24f_ili1.ili>
Error: /home/rails/.ilicache/jdbc&003apostgresql&003awfs_agg/ili_av_lv95_staging/DM.01-AV-CH_LV95_24f_ili1.ili:1572:The domains of the attributes MD01MOCH24MN95F.NPA_Localite.Mise_a_jourLoc.Perimetre and DM01AVCH24LV95D.PLZOrtschaft.OSNachfuehrung.Perimeter do not match.
Error: /home/rails/.ilicache/jdbc&003apostgresql&003awfs_agg/ili_av_lv95_staging/DM.01-AV-CH_LV95_24f_ili1.ili:1632:The domains of the attributes MD01MOCH24MN95F.NPA_Localite.Mise_a_jourNPA6.Perimetre and DM01AVCH24LV95D.PLZOrtschaft.PLZ6Nachfuehrung.Perimeter do not match.
Error: /home/rails/.ilicache/jdbc&003apostgresql&003awfs_agg/ili_av_lv95_staging/DM.01-AV-CH_LV95_24f_ili1.ili:1674:The domains of the attributes MD01MOCH24MN95F.Adresses_des_batiments.Mise_a_jourBAT.Perimetre and DM01AVCH24LV95D.Gebaeudeadressen.GEBNachfuehrung.Perimeter do not match.
compiler failed

Regards 
Vera

[sz.zip](https://github.com/claeis/ili2db/files/1722916/sz.zip)

**Comment by edigonzales** [comment]
Seems to be a problem with some inconsistency between the different models (german and french) according to geodienste.ch. It is addressed to swisstopo.

**Comment by dkottmann** [comment]
models have been corrected on models.geo.admin.ch and deployed on integration.geodienste.ch
retests pending...

**Comment by edigonzales** [comment]
I still get the same error.

**Comment by dkottmann** [comment]
flushed ilicache on integration.geodienste.ch. 
retest successful
