### ISSUE TITLE
Model implementation fail (MGDM Langsamverkehr; hpm_network)

### ISSUE THREAD

**Issue by zigertiger** [claeis/ili2db#161]
The model hpm_network_V1 (http://models.geo.admin.ch/ASTRA/Hpm_Network_V1.ili) throws an error upon implementation using ili2pg:

java.io.IOException: failed to add constraint route_route_type_fkey to table _wanderwege.route
  failed to add constraint route_route_type_fkey to table _wanderwege.route
    ERROR: relation "_wanderwege.route_type" does not exist

ili2c throws no errors.

**Comment by renato1987** [comment]
Which version of ili2pg and ili2c did you use?
Which settings you made?
Please send a logfile with the thrown error messages.

**Comment by renato1987** [comment]
Can reproduce the issue.

**Comment by zigertiger** [comment]
I work with the projectgenerator QGIS plugin which applies "standard" ili2pg options:

java.exe -jar C:\Users\peter.staub\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\projectgenerator\libili2db\bin\ili2pg-3.11.2\ili2pg.jar --schemaimport --dbhost srv-gis-05.glnet.ch --dbusr gisuploadmanager --dbpwd *** --dbdatabase glarus --dbschema _wanderwege --setupPgExt --coalesceCatalogueRef --createEnumTabs --createNumChecks --coalesceMultiSurface --coalesceMultiLine --strokeArcs --beautifyEnumDispName --createUnique --createGeomIdx --createFk --createFkIdx --createMetaInfo --smart1Inheritance --defaultSrsCode 2056 --models hpm

**Comment by claeis** [comment]
Problem is the reference to a concrete extension class (route_type), which is an extension of an already concrete base class (hpm_catalog_item).

Requires fixing in schema-import, data-import and data-export

**Comment by claeis** [comment]
fixed in 3.11.3
