### ISSUE TITLE
Missing tables in create schema statement

### ISSUE THREAD

**Issue by sjib** [claeis/ili2db#17]
The following tables are not created / deleted with the option --createscript / -dropscript:

- CREATE SEQUENCE schemaname.t_ili2db_seq
- CREATE TABLE vsadss2015_2_d_251.t_key_object

**Comment by sjib** [comment]
Is table t_key_object replaced with sequence t_ili2db_seq in the 3.x versions? Which field contains the actual counter? Is this information relevant for an export?

**Comment by claeis** [comment]
Starting with ili2pg-2.4.0, ili2pg uses a sequence based id generator. ili2gpkg still uses a table based id generator. 

To query the current value of a PG sequence, see https://www.postgresql.org/docs/9.6/static/functions-sequence.html

The id generator (sequence or table based) is not used, while exporting data.

**Comment by claeis** [comment]
fixed by commit e6b3afe4e25c70834f9b031895de976765f09086
