### ISSUE TITLE
Disable specific checks on Topic

### ISSUE THREAD

**Issue by leader80** [claeis/ili2db#170]
Dear all, 
while checking the validity of the data (in behalf of a specific Federal or Cantonal model), is it possible to define a skip of specific checks on a Topic, tables or attributes?

Thanks!

**Comment by claeis** [comment]
ili2db off-topic, pls create issue in ilivalidator repo

**Comment by giodegiorgi** [comment]
it's actually not off-topic since we need to import data non compliant to the model, that is not ilivalidator, is ili2db.

**Comment by giodegiorgi** [comment]
Please reopen.

**Comment by claeis** [comment]
use --disableValidation or disable any single validation in the toml file that you can pass with --validConfig

**Comment by giodegiorgi** [comment]
but if we disable a specific check, is it for all topics? or can I also selective decide which one is in or out of the validation?

**Comment by leader80** [comment]
please reopen since is not skipping the checks even if I create a TOML.

**Comment by claeis** [comment]
Pls add more details (data/model/config) so that I see which checks are not skipped.
