### ISSUE TITLE
Correct Data not imported into DB with ili2pg

### ISSUE THREAD

**Issue by mizehn** [claeis/ili2db#174]
When I import the Data "ow_kbs_MGDM_V1_3_FLA.xtf" with ili2pg I get no error in the Logfiles but no data enters the DB (tables are empty).

When I delete the Part "KbS_Basis_V1_3" from the XTF, the data gets imported into the DB.
![bsp_kbs_ow_fla](https://user-images.githubusercontent.com/28288352/40471589-63f52f2e-5f37-11e8-99c8-cf6d5fbbe275.png)

ili2pg import options:
'--modeldir %ILI_FROM_DB --replace --createGeomIdx --defaultSrsCode 2056 --createBasketCol --sqlEnableNull --createEnumTxtCol --disableValidation'

Data and Logfiles:
[ow_kbs_MGDM_V1_3_FLA_github.zip](https://github.com/claeis/ili2db/files/2034289/ow_kbs_MGDM_V1_3_FLA_github.zip)

What is the problem with the Part "KbS_Basis_V1_3"? Why does it make a difference?

**Comment by claeis** [comment]
1) the codelists that are owned by a federal agency must not be part of a cantonal data transfer file
2) the import option --replace requires the option --dataset
3) I can not read the "log" files (.msg)

**Comment by mizehn** [comment]
1.: Import worked for BE with this Data: https://geodienste.ch/atom/kataster_belasteter_standorte/BE.xml where the Codelist is also part of the transfer file
2.: --dataset was probably used as well

**Comment by claeis** [comment]
Somehow the model KbS_LV95_V1_3 is not found/known during --import/--replace. I have to further analyze why. 

As a workaround, you can add --models KbS_LV95_V1_3 to the import/replace cmdline.

**Comment by claeis** [comment]
The import of BE works, because the KbS_LV95_V1_3.Belastete_Standorte comes before KbS_Basis_V1_3.Codelisten

**Comment by claeis** [comment]
3.11.4
