### ISSUE TITLE
ili2gpkg 3.11.3 - Export to xtf faild

### ISSUE THREAD

**Issue by kuhnpa** [claeis/ili2db#177]
changing ili2gpkg version from 3.10.5 to 3.11.3 a working process, exporting KBS-xtf for the AI delivery fails.
[BALISKBS_MGDM_export.log](https://github.com/claeis/ili2db/files/2068935/BALISKBS_MGDM_export.log)
Testing with the latest ilivalidator 1.8.1 produces the following error.log
[20180604_KbS_LV95_V1_3_BE.log](https://github.com/claeis/ili2db/files/2068940/20180604_KbS_LV95_V1_3_BE.log)
I can still export the xtf with the 3.10.5 version.
Any idea why this can happen?

**Comment by claeis** [comment]
Can you export the xtf with ili2gpkg option --disableValidation?

**Comment by claeis** [comment]
Can you provide me the gpkg file?

**Comment by kuhnpa** [comment]
[BALISKBS_mgdm.zip](https://github.com/claeis/ili2db/files/2076186/BALISKBS_mgdm.zip)

**Comment by claeis** [comment]
export with --disableValidation works.
Validation with ilivalidator-1.8.1 of that file also works. So, the transfer to the AI should not be a problem. 

I'm still investigating, why the export with enabled validation fails.
