### ISSUE TITLE
Specific Disable of geometry creation

### ISSUE THREAD

**Issue by leader80** [claeis/ili2db#179]
Dear Claude,

there are some topic of our model that are not used and maintained anymore, is it possible to disable the geometry creation/check selectively for specific topics?

Thanks
G.

**Comment by claeis** [comment]
No, only in general with ```--skipGeometryErrors```

**Comment by leader80** [comment]
dear Claude, 
is it possible to implement it via Toml file?
Because for very complex situation where we have some old data (which aren't maintained anymore) we want to insert them without checking the geometry or the geometry constraints.

Thanks
G

**Comment by claeis** [comment]
won't implement
