### ISSUE TITLE
NullPointerException if optional references are null ("@“)

### ISSUE THREAD

**Issue by edigonzales** [claeis/ili2db#18]
When no value is set for an optional references the import does not work with latest master:

`java -jar /Users/stefan/Apps/ili2pg/ili2pg-3.5.0.jar --dbdatabase xanadu2 --dbusr stefan --dbpwd ziegler12 --dbschema av_avdpool_ng_350 --sqlEnableNull --createFkIdx --createGeomIdx --createBasketCol --models DM01AVSO24LV95 --disableValidation --nameByTopic --defaultSrsCode 2056 --dataset 2549 --trace --log fehler.log --replace /Users/stefan/tmp/av_tmp_test/254900.itf`

`Info: doObject(): DM01AVSO24LV95.Gebaeudeadressen.Gebaeudeeingang oid 2500 {Status real, InAenderung nein, IstOffizielleBezeichnung ja, Im_Gebaeude BB, Gebaeudeeingang_von -> 2402 REF {}, Lage COORD {C1 2611643.529, C2 1233377.329}, AttributeProvisorisch nein, GWR_EDID 0, Hausnummer 19} (ch.ehi.ili2db.fromxtf.TransferFromXtf)
java.lang.NullPointerException
    ch.ehi.ili2db.mapping.NameMapping.mapIliClassDef(Unknown Source)
    ch.ehi.ili2db.converter.AbstractRecordConverter.getSqlType(Unknown Source)
    ch.ehi.ili2db.fromxtf.FromXtfRecordConverter.writeRecord(Unknown Source)
    ch.ehi.ili2db.fromxtf.TransferFromXtf.writeObject(Unknown Source)
    ch.ehi.ili2db.fromxtf.TransferFromXtf.doObject(Unknown Source)
    ch.ehi.ili2db.fromxtf.TransferFromXtf.doit(Unknown Source)
    ch.ehi.ili2db.base.Ili2db.transferFromXtf(Unknown Source)
    ch.ehi.ili2db.base.Ili2db.runUpdate(Unknown Source)
    ch.ehi.ili2db.base.Ili2db.run(Unknown Source)
    ch.ehi.ili2db.AbstractMain.domain(Unknown Source)
    ch.ehi.ili2pg.PgMain.main(Unknown Source)
`

`TABLE Gebaeudeeingang =
      Entstehung: -> GEBNachfuehrung;  !! Beziehung 1-mc
      Gebaeudeeingang_von: OPTIONAL -> Lokalisation;`

[254900.itf.zip](https://github.com/claeis/ili2db/files/612191/254900.itf.zip)

**Comment by claeis** [comment]
Bug: code tries to get the target class by reference-id, but reference-id is null

**Comment by claeis** [comment]
Bug: code creates NOT NULL on FK column for OPTIONAL reference attribute
