### ISSUE TITLE
--createEnumTabs with --createFk should create FKs to enum tabs

### ISSUE THREAD

**Issue by claeis** [claeis/ili2db#19]

**Comment by gacarrillor** [comment]
This also occurs for domains that are written inline, i.e., into the CLASS definition. 

![Image of Inline Enum](http://downloads.tuxfamily.org/tuxgis/tmp/ai/inline_enum_01.png)

Moreover, the generated attribute type in PostgreSQL is `character varying`, 

![Attribute type](http://downloads.tuxfamily.org/tuxgis/tmp/ai/inline_enum_02.png)

which doesn't match the PK's type (`itfcode:integer`) of the generated enum table: 

![Generated enum table](http://downloads.tuxfamily.org/tuxgis/tmp/ai/inline_enum_03.png)

In the generated enum table, `ilicode` is `character varying`, but doesn't have a `UNIQUE` constraint to serve as FK either.

**Comment by claeis** [comment]
Any good idea, how to create a FK in case of extended attributes?

    DOMAIN
      Enum1 = (Test1, Test2, Test3 (Test3a, Test3b));
      Enum2 EXTENDS Enum1 = (Test2 (Test2a, Test2b));
    
    CLASS ClassA1 =
    	attr1 : Enum1;
    END ClassA1;
    
    CLASS ClassA2 EXTENDS ClassA1 =
    	attr1 (EXTENDED): Enum2;
    END ClassA2;

Results in two enum element tables, that have no common PK:

![enum23b](https://cloud.githubusercontent.com/assets/13584583/24460179/cb283f32-149d-11e7-96d3-255389375ec2.PNG)

**Comment by gacarrillor** [comment]
Couldn't ilicode be used as FK? It would just need a UNIQUE constraint.

**Comment by claeis** [comment]
no, ilicode would not be unique in the union of all extended enums.

With ``Enum3 EXTENDS Enum1 = (Test2 (Test2a, Test2b));`` there would be two times the same ilicode values (but from different domains).

**Comment by pka** [comment]
Adding a FK gets difficult when `ClassA1` and `ClassA2` are stored in the same table. In this case, the same OR mapping strategy had to be applied to `Enum1` and `Enum2` to get a common PK. As an alternative it's maybe possible to add view on `Enum1` and `Enum2` with a synthetic PK which can be referenced.

**Comment by gacarrillor** [comment]
I agree with Pirmin. In that case, `Enum1` and `Enum2` could be condensed into a single `Enum`, be it a table or a view.

@claeis, in the union of all extended enums, `ilicode` + domain name should be enough to make each value unique, if that's what we want.

**Comment by claeis** [comment]
unfortunately this commit 43a59b9 includes changes that break schema mapping compatibility to 3.x versions.
