### ISSUE TITLE
ili2pg 3.11.5: error column X of relation X does not exist

### ISSUE THREAD

**Issue by dkottmann** [claeis/ili2db#191]
see attached log: 
[log_lwb_nutzungsflaechen.txt](https://github.com/claeis/ili2db/files/2201151/log_lwb_nutzungsflaechen.txt)

Data validates with ilivalidator 1.9.2
Error does not occur with ili2pg 3.11.2

**Comment by claeis** [comment]
Can not reproduce it. Can you add the log of the --schemaimport?

**Comment by dkottmann** [comment]
I can reproduce this error  on --import with ili2pg 3.11.5 based on schema created with ili2pg 3.11.2. 

t_ili2db_settings: 

![grafik](https://user-images.githubusercontent.com/23079469/43630732-68fc6eae-9701-11e8-9a0e-a6e581d58baf.png)

**Comment by claeis** [comment]
Could reproduce it. 
The issue happens, when the --schemaimport was done with a ili2db version <3.11.3 (before #161 was fixed)
