### ISSUE TITLE
ili2fgdb - Copy gdb, followed by import creates new table structure

### ISSUE THREAD

**Issue by kuhnpa** [claeis/ili2db#192]
Hi
Obviously ili2fgdb is not running as fast as the other ili2db products. Due to this fact, I want to create a master table structure in a gdb, which I want to use to copy into other folders and import data there.
I have a python script running to create the whole table structure, copy the gdb to another folder (arcpy.copy_Management) and then import the data with ili2fdgb (3.11.3).
In this case before the import takes place, ili2fgdb always recreates the table structure.
Is there a specific reason for that?
Thanks.
[0002be092101010100001_import.log](https://github.com/claeis/ili2db/files/2214123/0002be092101010100001_import.log)
[0002be092101010100001_schema.log](https://github.com/claeis/ili2db/files/2214124/0002be092101010100001_schema.log)

**Comment by claeis** [comment]
Any wording suggestions?

**Comment by kuhnpa** [comment]
It depends, what exactly the running process does.
If the compatibility of the import file is checked against the existing db, maybe:
"compare table structure"

**Comment by claeis** [comment]
currently, no verification is done.

It's an info about the next task it is is going to do: mapping the ili model to table definitions and creating the tables in the db (if they do not yet exist).

**Comment by kuhnpa** [comment]
Then I would suggest:
create table structure, if not existing...

**Comment by claeis** [comment]
3.12.2
