### ISSUE TITLE
ili2fgdb cannot handle non optional domains in Interlis1 Files

### ISSUE THREAD

**Issue by Brainie123** [claeis/ili2db#200]
[ili2fgdb_mandatory_problem_ili1.zip](https://github.com/claeis/ili2db/files/2263035/ili2fgdb_mandatory_problem_ili1.zip)

I got an error like Error: line 0: SG_Gewaessernetz_kt_V30_ILI10_LV95.Gewaessernetz.Route: tid 7919: Attribute KmRichtung requires a value. However the Attribute KmRichtung is filled with values!
Setting up the attributes to OPTIONAL suppress the error but the data is not exported.

See attached example

**Comment by claeis** [comment]
3.12.2
