### ISSUE TITLE
Dotted values as keys in toml files

### ISSUE THREAD

**Issue by m-kuhn** [claeis/ili2db#205]
When trying to specify ili2db meta-attributes in TOML files I ran into some issues

```ini
["Nutzungsplanung_LU_300.MultiPoint"]                                           
ili2db.mapping = "MultiPoint"
```

Result:

```
Info: run import meta-attributes from toml file
Invalid key on line 2: ili2db.mapping
```

Changed according to [TOML key specs](https://github.com/toml-lang/toml#keys)

```ini
["Nutzungsplanung_LU_300.MultiPoint"]
"ili2db.mapping" = "MultiPoint"
```

Ends up in the t_ili2db_meta_attrs as a quoted value and is (probably therefore) not properly mapped.

```
Nutzungsplanung_LU_300.MultiPoint; "ili2db.mapping"; MultiPoint
```

I assume that quoted values in keys need some additional preprocessing to have quotation and dotting handled correctly.

CC @marioba

**Comment by claeis** [comment]
Correct would be
````
["Nutzungsplanung_LU_300.MultiPoint"]
"ili2db.mapping" = "MultiPoint"
````

Should result in a record in t_ili2db_meta_attrs where ```attrName=ili2db.mapping```

**Comment by m-kuhn** [comment]
And if I read the specs correctly, this would be the proper way to use unquoted dotting. But it's a nice to have.

```
["Nutzungsplanung_LU_300"]
MultiPoint."ili2db.mapping" = "MultiPoint"
```

**Comment by claeis** [comment]
I want to keep the file structure in a pure INI file style, that is a set of sections and in each section a set of key/value pairs.

**Comment by m-kuhn** [comment]
Wouldn't it be more appropriate to put in a `.ini` file instead of a `.toml` file in this case?

**Comment by claeis** [comment]
yes, would be better

**Comment by claeis** [comment]
3.12.2

**Comment by m-kuhn** [comment]
Thanks @claeis 

Concerning ini vs. toml, I am a bit confused now. I see that an [external Toml library](https://github.com/mwanji/toml4j) is used, which I assume is based on the toml standard whereas this patch enforces ini-style. Am I missing something?

https://github.com/mwanji/toml4j

**Comment by claeis** [comment]
I will/can not change the format of an input file as part of a non-major release. I can not change the TOML standard.

I fixed the way the java objects returned from the external Toml library are mapped to the java objects used by ili2db/ilivalidator.

**Comment by m-kuhn** [comment]
My main question is, what to communicate: ini or toml. So far it has been toml (triggered by ili validator if I am not wrong), but since [your comment](https://github.com/claeis/ili2db/issues/205#issuecomment-413209132) I am no longer sure about that. It looks like the easiest (no api break, no communication change) would be to stick to toml and forget ini.

**Comment by m-kuhn** [comment]
What's the difference between "file format" and "concept"?
So far I'm reading this as file extension `.toml`, content INI. I assume that's not what you mean?

**Comment by m-kuhn** [comment]
Or to come back to my previous statement 

>  It looks like the easiest (no api break, no communication change) would be to stick to toml and forget ini.

Why not just go this way?

**Comment by claeis** [comment]
That's fine (I just don't want nested TOML objects...)

**Comment by m-kuhn** [comment]
If "don't want" translates to "discourage", that's fine. Important is, that it doesn't violate a standard it pretends to follow:

I.e:

Supporting this style would be incompatible and should IMO not be allowed by ili2db:

```toml
["Nutzungsplanung_LU_300.MultiPoint"]                                           
ili2db.mapping = "MultiPoint"
```

This should be the mandatory style to write this:

```toml
["Nutzungsplanung_LU_300.MultiPoint"]                                           
"ili2db.mapping" = "MultiPoint"
```

This should be allowed (but can be discouraged and skipped for now as unimplemented):

```toml
["Topic.Table"]                     
AttributeA.MetaAttributeZ = 1
AttributeB.MetaAttributeY = 2
```

**Comment by claeis** [comment]
I will switch to ini, but will allow for ```"``` around names and values (claeis/iox-ili#41).

**Comment by m-kuhn** [comment]
Thanks for clarification
