### ISSUE TITLE
T_Id aus Katalogimport nicht korrekt übernommen

### ISSUE THREAD

**Issue by ech-mauh** [claeis/ili2db#214]
Import Katalog aus xml:
java -jar ili2fgdb.jar --import --dataset Kt_Code --importTid --createBasketCol --defaultSrsCode 2056 --smart2Inheritance --nameByTopic --dbfile SG_413_Muolen.gdb Kt_Code.xml

Import Daten aus xtf:
java -jar ili2fgdb.jar --import --dataset Data_SG --nameByTopic --defaultSrsCode 2056 --smart2Inheritance --dbfile SG_413_Muolen.gdb SG_413_Muolen_NP_2_180528_nup_ili23.xtf

In der resultierenden FileGeodatabase verweist die Referenz aus der Tabelle gde_code immer auf denselben Wert (kt_code=5) obwohl in den Ursprungsdaten unterschiedliche Referenzen vorliegen.

[Call.zip](https://github.com/claeis/ili2db/files/2336115/Call.zip)

**Comment by pbuerki** [comment]
Gerne würden auch wir ili2fgdb für die Import und Export der XTFs nutzen und haben zusammen mit Esri dieses Verhalten beobachtet. V.a. beim Übernehmen von mehreren Datensätzen nach Interlis 2.3 wäre die Missübersetzung sehr hinderlich. Wir können allerdings nicht ausschliessen, ob es sich hier um einen Bedienungsfehler handelt. 

Für weitere Auskünfte stehen wir sehr gerne zur Verfügung.

**Comment by claeis** [comment]
Bitte Programm (die jar-Dateien) nicht zusenden/in die zip-Datei packen. Die Angabe welche Programm-Version genügt (sieht man im log oder mit --version)

**Comment by claeis** [comment]
Duplicates #131

**Comment by pbuerki** [comment]
Meine Version war: ili2fgdb-3.11.3-20180412
ech-mauh: hatte eine noch aktuellere Version. 
Bis wann dürfen wir auf eine Bearbeitung hoffen? Da wir an diversen Ecken gerne ili2fgdb einsetzen möchten, eilt es sehr, dass wir einen sauberen Im- und Export hinbekommen. 
Besten Dank für die Unterstützung.
