### ISSUE TITLE
Dataset nicht löschbar, falls Basketreihenfolge != Topicreihenfolge im Modell

### ISSUE THREAD

**Issue by edigonzales** [claeis/ili2db#215]
Falls die Reihenfolge der Baskets im Transferfile nicht der Reihenfolge der Topics im Modell entspricht, kann ein Datensatz (--dataset) nicht gelöscht/replaced
 werden. Oder die Reihenfolge entspricht nicht anderen Rahmenbedingungen. Gemäss Kap. 3.2.5 ist die Reihenfolge der Objekte im Transfer beliebig, insbesondere innerhalb des Behälters. Heisst für mich entsprechend, dass die Reihenfolge der Behälter auch egal ist. 

`Error:   ERROR: update or delete on table "rechtsvorschrften_dokument" violates foreign key constraint "erschlssngsplhnbjkt_dkment_dokument_fkey" on table "erschlssngsplnung_typ_erschliessung_flaechenobjekt_dokument"
  Detail: Key (t_id)=(417) is still referenced from table "erschlssngsplnung_typ_erschliessung_flaechenobjekt_dokument".`

Anbei zwei XTF. Eines von Hand korrigiert, das funktioniert.

Ich glaube, dass Objekte falsch "t_basket"-Werte beim Import zugewiesen bekommen. Die DELETE-Befehle löschen dann eben nichts und es führt zu diesem SQL-Error.

[Archive.zip](https://github.com/claeis/ili2db/files/2371957/Archive.zip)

**Comment by claeis** [comment]
Die Reihenfolge der Baskets im XTF spielt keine Rolle, muss insbesondere auch nicht der Reihenfolge der TOPICs im Modell entsprechen.

**Comment by edigonzales** [comment]
PostGIS. 
ili2pg - 3.12.2

Temporärer Workaround: Import _ohne_ basket/dataset-Optionen in z.B. GeoPackage. Anschliessend Export nach XTF. Reihenfolge Baskets im XTF ist nun den Topics im Modell entsprechend.

**Comment by edigonzales** [comment]
Passiert mit --replace und --delete.

**Comment by edigonzales** [comment]
Kann es momentan nicht mehr nachvollziehen. Läuft durch:

```
java -jar /Users/stefan/apps/ili2pg-3.12.2/ili2pg-3.12.2.jar --dbhost 192.168.50.8 --dbdatabase edit --dbusr ddluser --dbpwd ddluser --createBasketCol --createDatasetCol --disableValidation --nameByTopic --createFkIdx --defaultSrsCode 2056 --models SO_Nutzungsplanung_20171118 --dbschema nplso --schemaimport

java -jar /Users/stefan/apps/ili2pg-3.12.2/ili2pg-3.12.2.jar --dbhost 192.168.50.8 --dbdatabase edit --dbusr ddluser --dbpwd ddluser --createBasketCol --createDatasetCol --disableValidation --nameByTopic --createFkIdx --defaultSrsCode 2056 --models SO_Nutzungsplanung_20171118 --dbschema nplso --dataset fubar --replace 2614_2018-09-11.xtf

java -jar /Users/stefan/apps/ili2pg-3.12.2/ili2pg-3.12.2.jar --dbhost 192.168.50.8 --dbdatabase edit --dbusr ddluser --dbpwd ddluser --createBasketCol --createDatasetCol --disableValidation --nameByTopic --createFkIdx --defaultSrsCode 2056 --models SO_Nutzungsplanung_20171118 --dbschema nplso --dataset fubar --replace 2614_2018-09-11.xtf
```
