### ISSUE TITLE
Build fatjar

### ISSUE THREAD

**Issue by leader80** [claeis/ili2db#217]
Dear all,

since the introduction of Gradle as build tool I'm not able to build fatjar anymore, can you please fix this?

Bests
G.

**Comment by edigonzales** [comment]
Ciao Giovanni
since I am/was (depends...) a fan of fatjars: why you need it? What is your use case? All resources should be available from maven repos. The interlis stuff can be found here: jars.interlis.ch. Except - of course - the oracle database jdbc jar...

Stefan

**Comment by leader80** [comment]
Hoi Stefan,
thanks for your reply, we are build an automatic data loader process (based on ili2pg) and we have to provide all the necessary files to the sysadmins, therefore to avoid any missing dependency we would like to use a fatjar.

Bests
Giovanni

**Comment by claeis** [comment]
you can/should do this in your own project/build, because it is only one specific deployment use case (out of an unnumbered one).

**Comment by leader80** [comment]
I tried to build the ili2pg but it keeps returning errors at runtime.

**Comment by edigonzales** [comment]
[https://github.com/edigonzales/ili2pg-fatjar](https://github.com/edigonzales/ili2pg-fatjar)

`gradle jar`

GUI does not work b/c of missing resources: `java.util.MissingResourceException: Can't find bundle for base name ch.ehi.basics.wizard.wizard, locale en_CH`

**Comment by edigonzales** [comment]
Ah sorry. Did not read your answer good enough. With my build script I get the same error but only when using —gui. I can do e.g. —importschema with my fatjar without any problems.

**Comment by leader80** [comment]
super danke :)!

**Comment by leader80** [comment]
> Ah sorry. Did not read your answer good enough. With my build script I get the same error but only when using —gui. I can do e.g. —importschema with my fatjar without any problems.

 java -jar ili2pg-3.12.2.jar --schemaimport
no dburl given
Info: ili2pg-3.12.2-816b1d9384cf964489c804408fad12c85eea8d4d
Info: ili2c-4.7.9-20180705
Info: iox-ili-1.20.9-0e947c9f9e3d29aa52fb8cfe9d27c95760589398
Info: java.version 1.8.0_152
Info: user.name <t141405>
Info: maxMemory 14897152 KB
Info: currentTime 2018-09-19 17:04:47
no models given

**Comment by edigonzales** [comment]
You have to convince @claeis.

If your use case includes some deployment pipeline / provisioning tasks you should do this there (as Claude suggested). 

But also a good reason to enjoy the beautiful autumn sun in Bellinzona and discuss this topic :)
