### ISSUE TITLE
Fehlermeldung Info: validate multiplicity of role - error

### ISSUE THREAD

**Issue by sjib** [claeis/ili2db#220]
Wie muss ich diese Fehlermeldung interpretieren?
Stimmt da in den Daten etwas nicht oder im Datenmodell?

> Info: validate target of role DSS_2015.Siedlungsentwaesserung.Wasserfassung_GrundwasserleiterAssoc.GrundwasserleiterRef...
> Info: validate target of role DSS_2015.Siedlungsentwaesserung.Wasserfassung_OberflaechengewaesserAssoc.OberflaechengewaesserRef...
> Info: validate multiplicity of role DSS_2015.Siedlungsentwaesserung.Wasserfassung_GrundwasserleiterAssoc.GrundwasserleiterRef...
> Info: validate multiplicity of role DSS_2015.Siedlungsentwaesserung.Wasserfassung_OberflaechengewaesserAssoc.OberflaechengewaesserRef...
> Error: ...import failed
> Error:     ch.ehi.ili2db.base.Ili2db.runUpdate(Ili2db.java:727)
> Error:     ch.ehi.ili2db.base.Ili2db.runImport(Ili2db.java:223)
> Error:     ch.ehi.ili2db.base.Ili2db.run(Ili2db.java:203)
> Error:     ch.ehi.ili2db.AbstractMain.domain(AbstractMain.java:460)
> Error:     ch.ehi.ili2pg.PgMain.main(PgMain.java:70)
>

**Comment by sjib** [comment]
Hier das Datenmodell dazu:

> CLASS Wasserfassung EXTENDS SIA405_Base.SIA405_BaseClass =  
> !! Entnahme von Grundwasser durch technische Massnahmen
>   ATTRIBUTE
>     Art: (          !! Art der Trinkwasserfassung
>       Brauchwasser,
>       Trinkwasser,
>       unbekannt
>     );
>     Bemerkung: TEXT*80;  !! Allgemeine Bemerkungen
>     Bezeichnung: MANDATORY TEXT*20;
>     Lage: Base.LKoord;  !! Landeskoordinate Ost/Nord
> END Wasserfassung;
> 
> ASSOCIATION Wasserfassung_GrundwasserleiterAssoc =    !! Assoziation
>   GrundwasserleiterRef  -- {0..1} Grundwasserleiter; !! Rolle1 - Klasse1 / Rôle1 - Classe1
>   Wasserfassung_GrundwasserleiterAssocRef -- {0..*} Wasserfassung; !! , Rolle2 - Klasse2 / Rôle2 - Classe2
> END Wasserfassung_GrundwasserleiterAssoc;
> 
> ASSOCIATION Wasserfassung_OberflaechengewaesserAssoc =    !! Assoziation
>   OberflaechengewaesserRef  -- {0..1} Oberflaechengewaesser; !! Rolle1 - Klasse1 / Rôle1 - Classe1
>   Wasserfassung_OberflaechengewaesserAssocRef -- {0..*} Wasserfassung; !! , Rolle2 - Klasse2 / Rôle2 - Classe2
> END Wasserfassung_OberflaechengewaesserAssoc;

**Comment by claeis** [comment]
please add the complete log (there should be an ```Error``` message nearer to the start)

**Comment by claeis** [comment]
The lines that start with ```Info``` are not errors but pure information to show what happens

**Comment by sjib** [comment]
Ok thanks for the hint - I found the error. I thought the error must be at the point where "Error: ...import failed" shows up:

> Error: line 91019: DSS_2015.Siedlungsentwaesserung.Privat: tid xch080qwzPR000016: Unique is violated! Values ch080qwzPR000006 already exist in Object: xch080qwzPR000006

This is now clear to me. Thanks
