### ISSUE TITLE
create db tables ony in a derived language

### ISSUE THREAD

**Issue by claeis** [claeis/ili2db#221]
Do not create tables  in the original language.
The derived language to use is specified by a new cmdline option.

**Comment by mizehnder** [comment]
Which cmdline option can be used for this?
With the TRANSLATION OF model names, the tables are created in the original language.

**Comment by beistehen** [comment]
Did you try `--nameLang`?

**Comment by mizehnder** [comment]
Thanks, didn't see that, works with it for the table-names. But shouldn't it also use the domains from the other Language?
![grafik](https://user-images.githubusercontent.com/82505753/116534023-53fb8580-a8e2-11eb-9541-2fd29c05a657.png)

**Comment by claeis** [comment]
support for multi-lingual domains would require a new/different t_ili2db_xx table (see #350)

**Comment by mizehnder** [comment]
But wouldn't that be a separate issue? #350 is for a user interface. 
I would just expect, that when I import a translated model in ili2db, ALL translated parts of the model, like the classnames, attributnames, domains, enumerations etc. are imported in the db-schema.
