### ISSUE TITLE
ili2gpkg: WKB-Geometriekodierungsprobleme

### ISSUE THREAD

**Issue by edigonzales** [claeis/ili2db#227]
1. GPKG-Datei anlegen mit ili2gpkg. Geometrie = `GeometryCHLV95_V1.LineWithAltitude`
2. Daten in QGIS verändern (Sachattribute)
3. Export geht schief: `Error: Object 3770: failed to convert polyline
Error:   com.vividsolutions.jts.io.ParseException: Unknown WKB type 234`

Beispiel einer Originalgeometrie: `47500002000008084143F0B208B439584143F0B78E353F804132B95AFFBE76D44132B964FBE76C910080000002000000024143F0B208B439584132B964FBE76C91407BDE4189374C004143F0B78E353F804132B95AFFBE76D4407BE1DB22D0E500`

Beispiel einer Geometrie, wo das Objekt verändert wurde: `4750000508080000683BDF6FFFE44341002B87B602E543412B3333D3110633416791ED9C150633410023DBF97E507D40009CC420B0647D4001EA03000002000000002B87B602E543412B3333D3110633410023DBF97E507D40683BDF6FFFE443416791ED9C15063341009CC420B0647D40`

**Comment by claeis** [comment]
fixed with https://github.com/claeis/iox-ili/commit/ca7f4571fea6fe5513fb1557f14e5e01f229f1b7
