### ISSUE TITLE
ili2db schema import: missing fk in one-to-many relationships with attributes

### ISSUE THREAD

**Issue by AlejoTellezF** [claeis/ili2db#228]
In a schema import process, when the model has a one-to-many relationship with attributes, in the relationship table there are attributes corresponding to fields but there is not a FK (or field) to link the tables.

**Model uml**
![onetomany_uml](https://user-images.githubusercontent.com/6115334/48802071-14c1b700-ecdc-11e8-8fa6-43a4c259d9fd.JPG)

**Model ili file:**

INTERLIS 2.3;

MODEL Model (en)
VERSION "2018-08-17"  =
  TOPIC Topic =
    CLASS ManyPart =
    END ManyPart;
    CLASS OnePart =
    END OnePart;
    ASSOCIATION Association =
      one_part -- {0..1} OnePart;
      many_part -- {0..*} ManyPart;
      atribute : TEXT*20;
    END Association;
  END Topic;
END Model.

**ER diagram of database created by ili2db command:**
![onetomany_er](https://user-images.githubusercontent.com/6115334/48801096-7896b080-ecd9-11e8-84e1-d69dd6d7bbb6.JPG)

**ili2db command**
--schemaimport --dbdatabase ili_test --smart2Inheritance --dbusr postgres --dbpwd ***** --modeldir E:\workspace\UMLEjercicio\Tests --createFkIdx --createFk --dbschema test_onetomany --createMetaInfo E:\workspace\UMLEjercicio\Tests\Test_OneToMany.ili

**Comment by AlejoTellezF** [comment]
The solution works but it makes possible a many-to-many relationship between tables, so it's not possible to preserve referential integrity into database because of that type of relationship

**actual solution:**
![actual_solution](https://user-images.githubusercontent.com/6115334/52976253-bd90b880-3396-11e9-94dc-cc1e7942bf79.JPG)

We (Swissphoto-Incige technical team) think that the best option is try to preserve referential integrity using a one-to-many relationship between the one-part table and the many-part table _and_ another relationship (one-to-one type) between many-part table and association table

**Suggested solution:**
![expected_1](https://user-images.githubusercontent.com/6115334/52976895-4ad50c80-3399-11e9-9b9f-61b92d920feb.JPG)

**Comment by claeis** [comment]
I dislike the suggested solution, because it introduces a new/additional pattern (FK in manypart and additional table). Currently there are only two patterns:

- FK in manypart, no intermediate table (for 1:n assoc without attr)
- intermediate table with FKs (for n:n assoc and for 1:n assoc with attr)

This new pattern introduces code complexity in ili2db and any client that use the data (QGIS, ...).

**Comment by AlejoTellezF** [comment]
With that in mind, another possible solution is to add a UNIQUE constraint to many_part FK into association table. That way, database avoid many to many behaviour. 
¿What do you think about it?
![actual_solution_modification](https://user-images.githubusercontent.com/6115334/53023062-7fdd6f80-342a-11e9-8f90-a2567af9564d.jpg)

**Comment by claeis** [comment]
Yes, I will do it that way, add a UNIQUE on the many_part FK column
