### ISSUE TITLE
Fehler beim polymorphen Schreiben von Modellen mit CatalogueObjects

### ISSUE THREAD

**Issue by edigonzales** [claeis/ili2db#229]
Ich erweitere ein Klasse in einem kantonalen Modell um ein einzelnes Attribut. Ansonsten entspricht das Modell dem [MDM](http://models.geo.admin.ch/BAFU/LBK_Haupt_uebrigeStrassen_V1_1.ili). Das Exportieren der Daten in das Kantonsmodell funkioniert. Das Exportieren in das MDM wirft einen Fehler (siehe unten). Einige Attribute der Klasse `pointofdetermination
[Archive.zip](https://github.com/claeis/ili2db/files/2609084/Archive.zip)
` referenzieren ein Katalogobjekt. Fehlen diese Referenzierungen funktioniert der Export.

Angehängt das erweiterte Modell, Katalog und Export in das kantonale und in das Bundesmodell. 

[Archive.zip](https://github.com/claeis/ili2db/files/2609085/Archive.zip)

`Info: dumpObjHelper(): SELECT r0.T_Id, r0.T_Type,r0.determination_remark,r0.lr_day,r0.lr_night,r0.mcd_street,r0.mcn_street,ST_AsEWKB(r0.geometry_pod),r0.id_pod,r0.egid,r0.edid,r0.address_pod,r0.exposure_limit_date,r0.operation_status,r0.pointofdetermination_t,r0.exposure_limit_value_d,r0.exposure_limit_value_n,r0.dispersion_calculation,r0.incl_highway FROM avt_strlaerm1.immission_strasse_pointofdetermination r0 WHERE r0.T_Type='so_vt_l0181122immission_strasse_pointofdetermination' (TransferToXtf.java:838)
java.lang.NullPointerException
    ch.interlis.iox_j.filter.ReduceToBaseModel.translateObject(ReduceToBaseModel.java:199)
    ch.interlis.iox_j.filter.ReduceToBaseModel.translateAttrValue(ReduceToBaseModel.java:254)
    ch.interlis.iox_j.filter.ReduceToBaseModel.translateObject(ReduceToBaseModel.java:217)
    ch.interlis.iox_j.filter.ReduceToBaseModel.filter(ReduceToBaseModel.java:182)
    ch.ehi.ili2db.toxtf.TransferToXtf.doBasket(TransferToXtf.java:446)
    ch.ehi.ili2db.toxtf.TransferToXtf.doit(TransferToXtf.java:224)
    ch.ehi.ili2db.base.Ili2db.transferToXtf(Ili2db.java:2087)
    ch.ehi.ili2db.base.Ili2db.runExport(Ili2db.java:1537)
    ch.ehi.ili2db.base.Ili2db.run(Ili2db.java:211)
    ch.ehi.ili2db.AbstractMain.domain(AbstractMain.java:460)
    ch.ehi.ili2pg.PgMain.main(PgMain.java:70)`

**Comment by claeis** [comment]
Es ist ein Programmfehler. (Allerdings scheint mir das Modell diskussionswürdig)
