### ISSUE TITLE
add constraints on numerical types

### ISSUE THREAD

**Issue by claeis** [claeis/ili2db#23]
```
CREATE TABLE example (
number integer,
CONSTRAINT number_constraint CHECK (number BETWEEN 0 AND 50)
);
```

**Comment by claeis** [comment]
fixed

**Comment by gacarrillor** [comment]
Unfortunately, I haven't been able to get this to work. Is there any special option to enable numeric CHECK CONSTRAINTS or any reference commit (used to close this issue) that I can skim through?

**Comment by claeis** [comment]
--createNumChecks

**Comment by gacarrillor** [comment]
Thank you. The problem is that --createNumChecks was not appearing as an option in the command line help. See https://github.com/claeis/ili2db/pull/52
