### ISSUE TITLE
ili2db schema import: extended attributes are mapped as a redundant field

### ISSUE THREAD

**Issue by yesidpol** [claeis/ili2db#230]
In a schema import process, when a model has an extended attribute into a subclass, ili2db does not extend it but creates two fields. For instance, in the below model, the extended attribute **attr** is mapped in table as **attr** and **attr1**.

**Model**
INTERLIS 2.3;
MODEL Model1 (en)
AT "mailto:PC3@localhost"
VERSION "2018-11-21"  =
  TOPIC topic1 =
    CLASS ParentClass =
      attr : TEXT*20;
    END ParentClass;
    CLASS Subclass
    EXTENDS ParentClass =
      attr (EXTENDED) : MANDATORY TEXT*20;
    END Subclass;
  END topic1;
END Model1.

**UML**
 
![image](https://user-images.githubusercontent.com/29440924/48920821-3ac89200-ee69-11e8-90b3-669bb6dfe896.png)

ER diagram of database created by ili2db command:

![image](https://user-images.githubusercontent.com/29440924/48920829-4451fa00-ee69-11e8-9806-3108e8818bdd.png)
 
--schemaimport --dbdatabase issues --dbschema test1 --coalesceMultiLine --smart2Inheritance --dbusr postgres --dbpwd ****** --modeldir E:\models --createFk --models Model1 --createNumChecks

**Comment by AlejoTellezF** [comment]
It only happens for version 3.12.3 (commits between Sep 7, 2018 and Nov 7, 2018).
For version 3.12.2 works fine

**Comment by claeis** [comment]
should be fixed in the latest 4.0 snapshot (due to changes related to issue #19)
