### ISSUE TITLE
missleading error messages

### ISSUE THREAD

**Issue by behrm** [claeis/ili2db#231]
the table "T_ILI2DB_BASKET" given in the following Error-Message:

no baskets with given topic names in table postgis_test.T_ILI2DB_BASKET
    ch.ehi.ili2db.base.Ili2db.getBasketSqlIdsFromModel(Ili2db.java:1916)
    ch.ehi.ili2db.base.Ili2db.runExport(Ili2db.java:1449)
    ch.ehi.ili2db.base.Ili2db.run(Ili2db.java:211)
    ch.ehi.ili2db.AbstractMain.domain(AbstractMain.java:460)
    ch.ehi.ili2pg.PgMain.main(PgMain.java:70)

does not exist in my postGIS-DB.

However a table with the following name does exist: "t_ili2db_import_basket"

Please check equivalent  error-messages for correctness too!

**Comment by claeis** [comment]
This error message indicates, that there were no records, but the table exists. If the table would not exist, the error message would be:  ```failed to query T_ILI2DB_BASKET```
