### ISSUE TITLE
meaning of "DEPRECATED, do not use" in Table Meta-Data

### ISSUE THREAD

**Issue by behrm** [claeis/ili2db#232]
The tables "t_ili2db_import_basket" and "t_ili2db_import_object" have meta-data "DEPRECATED, do not use".

Often, if a peace of software is marked as deprecated, there is a replacement available. So please, is there a foreseeable upcoming replacement for this tables?

**Comment by claeis** [comment]
No, the idea is to remove it without a replacment.

**Comment by behrm** [comment]
OK, good to know thank you. The column "t_basket" in various tables will remain?

**Comment by claeis** [comment]
yes, t_basket is a FK to T_ILI2DB_BASKET and required for models with extended topics.

**Comment by behrm** [comment]
thank You!
