### ISSUE TITLE
ignore ordering of JSON properties

### ISSUE THREAD

**Issue by edigonzales** [claeis/ili2db#245]
```
Info: process data...
Info: data <fubar_json.xtf>
Info: SO_Nutzungsplanung_Publikation_20190116.Nutzungsplanung BID <SO_Nutzungsplanung_Publikation_20190116.Nutzungsplanung>...
Info: SO_Nutzungsplanung_Publikation_20190116.Nutzungsplanung.Grundnutzung...
Info: dumpObjHelper(): SELECT r0.T_Id, r0.T_Ili_Tid,r0.typ_bezeichnung,r0.typ_abkuerzung,r0.typ_verbindlichkeit,r0.typ_bemerkungen,r0.typ_kt,r0.typ_code_kommunal,r0.typ_nutzungsziffer,r0.typ_nutzungsziffer_art,r0.typ_geschosszahl,ST_AsEWKB(r0.geometrie),r0.name_nummer,r0.rechtsstatus,r0.publiziertab,r0.bemerkungen,r0.erfasser,r0.datum,r0.bfs_nr,(r0.dokumente#>>'{}')::text FROM arp_npl_pub.nutzungsplanung_grundnutzung r0 (TransferToXtf.java:954)

java.lang.NullPointerException
    ch.ehi.ili2db.json.Iox2json.readOneObject(Iox2json.java:357)
    ch.ehi.ili2db.json.Iox2json.read(Iox2json.java:272)
    ch.ehi.ili2pg.converter.PostgisColumnConverter.toIomStructureFromJson(PostgisColumnConverter.java:666)
    ch.ehi.ili2db.toxtf.ToXtfRecordConverter.addAttrValue(ToXtfRecordConverter.java:694)
    ch.ehi.ili2db.toxtf.ToXtfRecordConverter.convertRecord(ToXtfRecordConverter.java:399)
    ch.ehi.ili2db.toxtf.TransferToXtf.dumpObjHelper(TransferToXtf.java:970)
    ch.ehi.ili2db.toxtf.TransferToXtf.dumpObject(TransferToXtf.java:946)
    ch.ehi.ili2db.toxtf.TransferToXtf.doBasket(TransferToXtf.java:469)
    ch.ehi.ili2db.toxtf.TransferToXtf.doit(TransferToXtf.java:252)
    ch.ehi.ili2db.base.Ili2db.transferToXtf(Ili2db.java:2156)
    ch.ehi.ili2db.base.Ili2db.runExport(Ili2db.java:1598)
    ch.ehi.ili2db.base.Ili2db.run(Ili2db.java:214)
    ch.ehi.ili2db.AbstractMain.domain(AbstractMain.java:499)
    ch.ehi.ili2pg.PgMain.main(PgMain.java:70)
```

`propName` is 't_id',` jg.getValueAsString()` is '4'

**Comment by edigonzales** [comment]
Seems that it needs something like `\"@type\":\"Json23.TestA.Farbe\"`. Import/export tested wit test data from repository.

**Comment by edigonzales** [comment]
Muss "@type" das erste Attribut sein?

Export funktioniert: 
`"[{\"r\":10,\"@type\":\"Json23.TestA.Farbe\",\"g\":11,\"b\":12,\"name\":\"f1\",\"active\":false},{\"@type\":\"Json23.TestA.Farbe\",\"r\":20,\"g\":21,\"b\":22,\"name\":\"f2\",\"active\":false}]"`

Export funktioniert nicht:
`
"[{\"@type\":\"Json23.TestA.Farbe\",\"r\":10,\"g\":11,\"b\":12,\"name\":\"f1\",\"active\":false},{\"@type\":\"Json23.TestA.Farbe\",\"r\":20,\"g\":21,\"b\":22,\"name\":\"f2\",\"active\":false}]"`

**Comment by edigonzales** [comment]
https://stackoverflow.com/questions/38297906/json-data-save-into-postgresql-become-different-order

**Comment by claeis** [comment]
Im allgemeinen spielt die Reihenfolge keine Rolle (ausser eben die technischen vor den fachlichen Attributen).

**Comment by edigonzales** [comment]
Wenn man es schafft die Reihenfolge so zu speichern, wie gewünscht, bleibt aber immer noch das Risiko, dass "::text" bei "SELECT r0.T_Id,(r0.farben#>>'{}')::text FROM json_test.testa_auto r0" die Reihenfolge wieder ändert.

**Comment by claeis** [comment]
d.h. ich muss es anpassen...
