### ISSUE TITLE
Empty (json) structures in exported xtf

### ISSUE THREAD

**Issue by edigonzales** [claeis/ili2db#246]
`IomObject.toString() = SO_Nutzungsplanung_Publikation_20190116.Nutzungsplanung.Dokumente {dok_t_id 5, id fubar, textimweb https://geo.so.ch/docs/ch.so.arp.zonenplaene/Zonenplaene_pdf/124-Buesserach/Reglemente/124_ZR_GP.pdf, titel Zonenreglement Gesamtplan}`

`id`, `titel`, `textimweb` sind Attribute der Struktur gemäss ili-Modell. Ins exportierte XTF werden nur die Tags geschrieben. Keine Attribute:

```
<Dokumente><SO_Nutzungsplanung_Publikation_20190116.Nutzungsplanung.Dokumente></SO_Nutzungsplanung_Publikation_20190116.Nutzungsplanung.Dokumente><SO_Nutzungsplanung_Publikation_20190116.Nutzungsplanung.Dokumente></SO_Nutzungsplanung_Publikation_20190116.Nutzungsplanung.Dokumente></Dokumente>
```

Keine Fehlermeldung.

**Comment by claeis** [comment]
Was steht im DB-Record?
Was ist der Unterschied zu ```ch.ehi.ili2pg.Json23Test.exportXtf()```?

**Comment by edigonzales** [comment]
Scheint ein Gross-/Kleinschreibungsproblem zu sein. Wenn ich die Attribute im ili-Modell klein schreibe, funktionierts.  Respektive umgekehrt: wenn das JSON (dh. die Query die zum JSON führt) in der DB Gross-/Kleinschreibung berücksichtigt und exakt den Namen im ili-Modell entspricht, funktioniert es auch.

Bei den "normalen" Attributen kümmere ich mich nie um Gross-/Kleinschreibung in den Queries.

**Comment by claeis** [comment]
Gross-/Kleinschreibung ist in ili und json relevant.
