### ISSUE TITLE
JSON-Stringobjekt vs. JSON-Array

### ISSUE THREAD

**Issue by edigonzales** [claeis/ili2db#247]
Wie legt ili2pg die Daten in JSON ab resp. was verlangt ili2pg? Ist das Root-Element ein JSON-Stringobjekt und keine Array?

**Comment by edigonzales** [comment]
Beisst sich mit:  http://old.opengis.ch/2018/11/13/visualize-postgres-json-data-in-qml-widgets/

**Comment by claeis** [comment]
- mit ```!!@ili2db.mapping=JSON``` ist das Root-Element ein JSON Objekt oder ein Array mit JSON Objekten
- mit ```!!@ili2db.mapping=ARRAY``` ist das Root-Element ein Array mit JSON Werten (String,Numeric oder Boolean). (Aber nur: Falls die ili STRUCTURE ARRAY fähig ist, und die db keinen ARRAY Datentyp kennt (also nicht bei postgres)!)

**Comment by edigonzales** [comment]
Sind bei `!!@ili2db.mapping=JSON` nicht einfach die Anführungszeichen ganz zu Beginn und am Ende überflüssig?

```
"[{\"@type\":\"Json23.TestA.Farbe\",\"r\":10,\"g\":11,\"b\":12,\"name\":\"f1\",\"active\":false},{\"@type\":\"Json23.TestA.Farbe\",\"r\":20,\"g\":21,\"b\":22,\"name\":\"f2\",\"active\":false}]"
```

Wäre nicht logischer:

```
[{\"@type\":\"Json23.TestA.Farbe\",\"r\":10,\"g\":11,\"b\":12,\"name\":\"f1\",\"active\":false},{\"@type\":\"Json23.TestA.Farbe\",\"r\":20,\"g\":21,\"b\":22,\"name\":\"f2\",\"active\":false}]
```
Als Konsequenz müsste dann aber das Escapen des Quotings weg.

**Comment by edigonzales** [comment]
```
SELECT
  farben->0
FROM
  json_test.testa_auto
```
würde in meiner Welt `{"@type":"Json23.TestA.Farbe","r":10,"g":11,"b":12,"name":"f1","active":false}` liefern. Jetzt liefert es einfach den ganzen String zurück.

https://www.postgresql.org/docs/10/functions-json.html 
Erstes Beispiel.
