### ISSUE TITLE
Kataloge: alle Referenzen werden in allen ...CatRef-Tabellen abgebildet

### ISSUE THREAD

**Issue by zigertiger** [claeis/ili2db#256]
Wenn in einem Modell z.B. drei Kataloge definiert werden:
- kat1, kat2, kat3 mit den Katalogreferenzen
- katref1, katref2, katref3, dann
werden im PostGIS-Schema in allen drei ...catref-Tabellen jeweils alle drei referenzstrukturen inkl. FKey-Constraints abgebildet:

TABLE katref1_catref ...
  reference_kat1 bigint,
  reference_kat2 bigint
  reference_kat3 biging
...
CONSTRAINT ... FOREIGN KEY (reference_kat1) REFERENCES kat1 ...
CONSTRAINT ... FOREIGN KEY (reference_kat2) REFERENCES kat2 ...
CONSTRAINT ... FOREIGN KEY (reference_kat3) REFERENCES kat3 ...

Das ist insbesondere dann ein unangenehmes Problem, wenn man mehrwertige Katalogverweise im Modell definiert (... BAG {0..*} OF katref1) und dann die gegenseitige Referenzierung von Objekt und Katalogeintrag im Sinne einer m:n-Beziehung über die Tabelle katref1 manuell bewirtschaften muss.

Es sollten jeweils nur die einen, zutreffenden Referenzen pro Tabelle erzeugt werden.

**Comment by claeis** [comment]
Bitte Modell ergänzen, damit ich genau sehe, welche Klassen/Strukturen/Attribute EXTENDS oder EXTENDED sind.

**Comment by zigertiger** [comment]
sehr gerne:
https://models.geo.gl.ch/DBU/GL_Biotope_V1.ili

**Comment by claeis** [comment]
already improved in 4.0
