### ISSUE TITLE
ili2gpkg: no MultiPoint support? (--coalesceMultiPoint)

### ISSUE THREAD

**Issue by zigertiger** [claeis/ili2db#257]
Unser Modell https://models.geo.gl.ch/DBU/GL_Biotope_V1.ili hat MultiPoint-Objekte (Klasse TO_Punkt). Die MultiPoint-Geometrie ist im Basismodell https://models.geo.gl.ch/GL/GL_Basis_20190212.ili definiert und verfügt über das Metaattribut !!@ili2db.mapping=MultiPoint.

Das Modell hat folgende Vererbungsstruktur: 
Teilobjekt{A} 
<|--- TO_Punkt (Geo_Obj: MultiPoint)
<|--- TO_Linie (Geo_Obj: MultiLine)
<|--- TO_Flaeche (Geo_Obj: MultiSurface)

Im GPKG werden die MultiSurface sauber umgesetzt: als Tabelle «teilobjekt» mit Typ MultiPolygon.
Die MultiLine werden als Tabelle «to_linie_geo_obj» mit Typ MultiLine, aber ohne Attribute (Vererbung) umgesetzt.
Die MultiPoint werden nicht umgesetzt. Es gibt eine Tabelle «pointstructure» vom Typ Point und eine Tabelle «multipoint» ohne Geometrie. Die Attribute fehlen auch hier (?)

Wie kann die Vererbungsstruktur mit Multigeometrien in GPKG richtig umgesetzt werden?

**Comment by claeis** [comment]
Ist ein Programmfehler. Kann es reproduzieren. Problem ist, dass die Geometrie-Attribute in den spezialisierten Klassen gleich heissen.
