### ISSUE TITLE
Java Version

### ISSUE THREAD

**Issue by m-kuhn** [claeis/ili2db#262]
Ili2db only works with java 8 (newer version require some tricks and workarounds if working at all).
Compatibility with newer Java Versions (11/12) would decrease the risk of people running into issues on first setup.

**Comment by edigonzales** [comment]
Some ideas:

- GraalVM to get native executables. No Java needed (but different versions for different OS).
- I think with Java >9 and the introduction of the module thing (jigsaw?) you can really create small packages that contain a JRE with only the stuff you need.

**Comment by claeis** [comment]
New JVM versions should work with ili2db-4.0/ilivalidator-1.11 releases.

To run older ili2db/ilivalidator releases, the simplest solution is to install an older JRE (for example 1.8).
