### ISSUE TITLE
ili2pg issue with itf in utf8 encoding

### ISSUE THREAD

**Issue by aipog** [claeis/ili2db#263]
Dear Claude,
we are facing a problem when we try to load itf data that are encoded in utf8.
For example, while checking the dimension of a string the ili2pg is shooting an excepion:
```
Error: Object 401747 at (line 224024,col 0)
Error:   ERROR: value too long for type character varying(30)
Error: failed to query TI_MU_version1_7_mn95.t_ili2db_seq
Error:   ERROR: current transaction is aborted, commands ignored until end of transaction block
Error:     ERROR: value too long for type character varying(30)
org.postgresql.util.PSQLException: ERROR: current transaction is aborted, commands ignored until end of transaction block
  ERROR: current transaction is aborted, commands ignored until end of transaction block
    ERROR: value too long for type character varying(30)
```
Are you planning to implement the possibility to accept utf8 encoded files for itf?

Thank you.
Giosia

**Comment by claeis** [comment]
I have no plan to support UTF-8 encoded ITF files. I think, a superseded standard should not be extended. If you need to transfer characters that are not included in ISO-8859-1 use Interlis 2/XTF.

Which tool was used to create this UTF-8 encoded ITF file?

**Comment by aipog** [comment]
We receive ift file generated by Geobox tool that integrate IMbatch.exe in Autodesk Map3D. The itf file contains characters as é è or other accents and the itf is encoded in utf-8.

**Comment by edigonzales** [comment]
Are you sure it is UTF-8 encoded? 

You can test it with jEdit: http://www.jedit.org/

If I open an ITF file, jEdit will open it as UTF-8 and I will see some strange characters where the Umlaute should be and an error will be prompted:
```
/Users/stefan/sources/camel-components/src/test/data/254900_fail.itf:
The file could not be loaded correctly (some data might be lost) with
the encoding "UTF-8".
(java.nio.charset.MalformedInputException: Input length = 1)
Try selecting a different encoding.
It can be selected with the menu File->Reload with Encoding.
If you want it to be done automatically, add the candidates into
"List of fallback encodings" in Encodings pane of Global Options.
```

I need to "reload with encoding..." (ISO-8859-1) the file.

**Comment by aipog** [comment]
Yes of course. If I open the itf file with notepad++ the editor say UTF-8. Now in our workflow we check the file with uchardet and if the file is UTF-8 we change the encoding with iconv.
