### ISSUE TITLE
ili2pg --delete failed for empty dataset

### ISSUE THREAD

**Issue by mizehn** [claeis/ili2db#275]
An empty XTF-File was imported to ili2pg:
https://www-integration.geodienste.ch/data_agg/import_tasks/3815/logs
[laerm_leer_ch.zip](https://github.com/claeis/ili2db/files/3073618/laerm_leer_ch.zip)

With the options: '--modeldir '%ILI_FROM_DB;/home/rails/geodienste-config/current/ili_agg/ili/npl_laermempfindlichkeitsstufen' --ver4-noSchemaImport --replace --createGeomIdx --defaultSrsCode 2056 --createBasketCol --sqlEnableNull --createEnumTxtCol --disableValidation'

This dataset can't be deleted when importing a new correct XTF-File like:
[laerm_test.zip](https://github.com/claeis/ili2db/files/3073624/laerm_test.zip)
https://www-integration.geodienste.ch/data_agg/import_tasks/3816/logs
With the same options.

 ili2pg --delete failed for dataset SO_laerm_leer_ch.xtf

Import worked again after deleting the dataset manually in the DB, any other options?

**Comment by claeis** [comment]
can not reproduce with ili2db 4.0.0
