### ISSUE TITLE
ili2fgdb - «dangling references» zwischen KT_Codeliste und Gde_Codeliste

### ISSUE THREAD

**Issue by pbuerki** [claeis/ili2db#276]
[Call_Export_ili2fgdb.zip](https://github.com/claeis/ili2db/files/3083883/Call_Export_ili2fgdb.zip)

Verwendete Version: 3.12.2 von http://www.eisenhutinformatik.ch/interlis/ili2fgdb/

Wir erhalten die Fehlermeldung "Dangling References" (zwischen Kt_Code und Gde_Code) beim Import/Export mit ili2fgdb, obwohl wir nichts an den Daten geändert haben. Uns stellt sich dabei die Frage, ob es sich um eine Missübersetzung im Tool von ili2fgdb handelt oder ob wir weitere Parameter beim Einlesen setzen müssen.

Folgende Befehle haben wir verwendet (die verwendeten Files sind im Anhang enthalten): 

**Import Katalog:**
java -jar ili2fgdb-3.12.2.jar --import --dataset KT_Code --createBasketCol --importTid --defaultSrsCode 2056 --smart2Inheritance --nameByTopic --trace --log Logfile_import_kt_code.log --dbfile SG_413_Muolen.gdb Kt_Code.xml
 
**Import xtf:**
java -jar ili2fgdb-3.12.2.jar --import --dataset Muolen --createBasketCol --importTid --defaultSrsCode 2056 --smart2Inheritance --nameByTopic --trace --log Logfile_import_muolen.log --dbfile SG_413_Muolen.gdb SG_413_Muolen_2_181207_nup_ili23.xtf
 
**Export xtf (nur dataset Muolen):**
java -jar ili2fgdb-3.12.2.jar --export --trace --dataset Muolen --models SG_Nutzungsplanung_gd_V21_ILI23_LV95 --log Logfile_export_muolen.log --disableValidation --dbfile SG_413_Muolen.gdb SG_413_Muolen_Export.xtf

**Comment by claeis** [comment]
Das Modell ist falsch/hat einen Fehler. Die externen Objekte (die in den Katalogen) müssen eine stabile OID haben. Evtl. hilft --importTid (Workaround) beim ersten Import.

**Comment by pbuerki** [comment]
Wir arbeiten bereits mit --importTid (wie Sie es bereits vorgeschlagen haben). Es funktioniert aber trotzdem nicht. Besten Dank für ihre Unterstützung.

**Comment by claeis** [comment]
fixed in 4.0.1

**Comment by pbuerki** [comment]
Thank you very much for taking care. Where can I download version 4.0.1?

On _http://www.eisenhutinformatik.ch/interlis/ili2fgdb/_ is just 4.0.0 published. Thanks again!

**Comment by edigonzales** [comment]
http://jars.interlis.ch/ch/interlis/ili2fgdb/4.0.1-SNAPSHOT/

Look at the last modified column or http://jars.interlis.ch/ch/interlis/ili2fgdb/4.0.1-SNAPSHOT/maven-metadata.xml (-2 hours i guess).
