### ISSUE TITLE
ili2fgdb: Import failed caused by required T_Ili_Tid 

### ISSUE THREAD

**Issue by pbuerki** [claeis/ili2db#279]
Thank you very much for creating new Snapshot of ili2fgdb. 

Now we are receiving an Error while importing (with --importTid) - see message below (or in attachement). In our comprehension ili2fgdb should create this column. Are we wrong? 
[Logfile_import_kt_code.log](https://github.com/claeis/ili2db/files/3110886/Logfile_import_kt_code.log)
 
Our import line in command window: _java -jar ili2fgdb-4.0.1-SNAPSHOT.jar --import --dataset KT_Code --createBasketCol --importTid --defaultSrsCode 2056 --smart2Inheritance --nameByTopic --trace --log Logfile_import_kt_code.log --dbfile SG_413_Muolen_401Snapshot.gdb Kt_Code.xml_

Thank you very much for your answer. 

_Error: failed to transfer data from file to db
Error:   **TID import requires a T_Ili_Tid column**
Error:       ch.ehi.ili2db.fromxtf.TransferFromXtf.doit(TransferFromXtf.java:205)
Error:       ch.ehi.ili2db.base.Ili2db.transferFromXtf(Ili2db.java:2175)
Error:       ch.ehi.ili2db.base.Ili2db.runUpdate(Ili2db.java:715)
Error:       ch.ehi.ili2db.base.Ili2db.runImport(Ili2db.java:233)
Error:       ch.ehi.ili2db.base.Ili2db.run(Ili2db.java:211)
Error:       ch.ehi.ili2db.AbstractMain.domain(AbstractMain.java:529)
Error:       ch.ehi.ili2fgdb.FgdbMain.main(FgdbMain.java:70)
Error: ...import failed
Error:     ch.ehi.ili2db.base.Ili2db.runUpdate(Ili2db.java:750)
Error:     ch.ehi.ili2db.base.Ili2db.runImport(Ili2db.java:233)
Error:     ch.ehi.ili2db.base.Ili2db.run(Ili2db.java:211)
Error:     ch.ehi.ili2db.AbstractMain.domain(AbstractMain.java:529)
Error:     ch.ehi.ili2fgdb.FgdbMain.main(FgdbMain.java:70)_

**Comment by claeis** [comment]
add --createTidCol to your --schemaimport command line

**Comment by pbuerki** [comment]
Thanks for your response. We have worked (til now) without --shemaimport. The direct data import perfomed well (without errors). Do you have any idea why this is not working now?

**Comment by claeis** [comment]
add --createTidCol and --doSchemaImport to your --import commandline

In 3.x ili2db did an implicit schema import during data import (and --importTid created implicitly the now missing column), this is no longer the default.

**Comment by claeis** [comment]
But I recommend to split schema import from data import...
