### ISSUE TITLE
ili2gpkg 3.12.2 - can't find the cause for error when exporting xtf

### ISSUE THREAD

**Issue by kuhnpa** [claeis/ili2db#281]
When exporting from the gpkg I get the following error:
"Error: no baskets with given topic names in table T_ILI2DB_BASKET"
I can't find the error in the relation between basket and dataset in the gpkg.
gpkg (zipped) and export log are attached.
can anyone help?
[Waldabstandslinien_LV95_V1_1_BE_351.zip](https://github.com/claeis/ili2db/files/3138029/Waldabstandslinien_LV95_V1_1_BE_351.zip)
[Waldabstandslinien_LV95_V1_1_BE_351.log](https://github.com/claeis/ili2db/files/3138030/Waldabstandslinien_LV95_V1_1_BE_351.log)

**Comment by edigonzales** [comment]
`T_ILI2DB_BASKET` and `geobasisdaten_waldabstand_linie` share identical `T_Id` values.

**Comment by claeis** [comment]
What are the commandline parameters of the export?

**Comment by kuhnpa** [comment]
> 
> 
> `T_ILI2DB_BASKET` and `geobasisdaten_waldabstand_linie` share identical `T_Id` values.

Is this a problem?


I pass those parameters (full paths removed) to the subprocess function in Python:
[java.exe, -jar, \\ili2gpkg-3.12.2\\ili2gpkg.jar, --export, --dbfile, Waldabstandslinien_LV95_V1_1_BE_351.gpkg, --disableValidation, --trace, --log, Waldabstandslinien_LV95_V1_1_BE_351.log, --models, Waldabstandslinien_LV95_V1_1, Waldabstandslinien_LV95_V1_1_BE_351.xtf]

**Comment by claeis** [comment]
Try the latest snapshot http://jars.interlis.ch/ch/interlis/ili2gpkg/4.1.0-SNAPSHOT/ili2gpkg-4.1.0-20190502.114818-4-bindist.zip

With 
```--export3  --dbfile Waldabstandslinien_LV95_V1_1_BE_351.gpkg --disableValidation --trace --log ceis.log --models Waldabstandslinien_LV95_V1_1 ceis.xtf```

**Comment by kuhnpa** [comment]
I've found the reason for the error. In the batch process running a FME-Script using a workspaceRunner to export each gpkg was already terminated (only the main file) and the export (ili2gpkg) started, although the FME-Subprocess waas not terminated yet. So the table T_ILI2DB_BASKET was still empty.
