### ISSUE TITLE
new meta attr to map EXTERNAL references as t_ili_tid FK

### ISSUE THREAD

**Issue by claeis** [claeis/ili2db#283]
Enable import of data with EXTERNAL references, without importing the referenced objects. To enable this, the reference value from the XTF (the TID (t_ili_tid in the DB) of the reference object) should be used as FK column (instead of the currently created FK column (that references the t_id in the DB)). And in the DB, no FK constraint should be created (even with --createFK), to enable a dangling reference.

**Comment by ech-mauh** [comment]
Could you please make an example?

**Comment by pbuerki** [comment]
As I understand your message correctly, we do not have to import (for example) an external Catalog manually - ili2db will create reference directly. This would be rather great. Did you already have time for creating an example?

Thanks for your response.

**Comment by pbuerki** [comment]
As we are not able to use our "old" commands from older versions, we will be very grateful if you could give a short working example of the new command line. Thank you very much!

**Comment by claeis** [comment]
Please only one question/problem per issue

**Comment by pbuerki** [comment]
In fact it is just one question. We are both not able to use old import commands with ili2fgdb 4.1 . Could you please make an example (including --createFK) how import/export would run properly? Thank you very much.

**Comment by claeis** [comment]
@pbuerki see https://github.com/claeis/ili2db/blob/master/docs/ili2db.rst#migration-von-3x-nach-4x

**Comment by sjib** [comment]
> Enable import of data with EXTERNAL references, without importing the referenced objects. To enable this, the reference value from the XTF (the TID (t_ili_tid in the DB) of the reference object) should be used as FK column (instead of the currently created FK column (that references the t_id in the DB)). And in the DB, no FK constraint should be created (even with --createFK), to enable a dangling reference.

@claeis Is what you describe above

-  a plan to integrate this new option for EXTERNAL references without importing the referenced objects in ili2db (new feature) 
- or is it a description on how to use ili2db as is to not create reference errors when having EXTERNAL references?

For me it is not clear whether I would need to wait for a new feature to be implemented to use it our qwat/qgep project or just set flags differently. If it is just flags then do I understand right to not use the --createFK flag. Or are there any others to avoid?

**Comment by claeis** [comment]
This issue is about a new feature.

(Ignoring reference errors is already possible, but you would loose data (the references to unresolvable objects)).

**Comment by sjib** [comment]
Thanks for clarification. Is there any roadmap when this will be implemented? With the VSA-KEK datamodel (see https://www.vsa.ch/models/2019/VSA_KEK_2019_2_d_LV95-20210416.ili) we have a couple of these EXTERNAL references and would be happy to have this new feature added quickly.

**Comment by claeis** [comment]
Soon, but no date yet

**Comment by edigonzales** [comment]
@sjib Perhaps you can ask for commercial support?

**Comment by m-kuhn** [comment]
Thank you @claeis
