### ISSUE TITLE
ili2pg - Export von binären Strings

### ISSUE THREAD

**Issue by snoopy21** [claeis/ili2db#286]
Bei einem Export per ili2pg aus einer PostGIS-DB treten zwei verschiedene Fehler auf:
- binärer String wird nach 76 Zeichen unterbrochen und geht auf einer neuen Zeile weiter, anstatt alles auf einer Zeile zu belassen
- binärer String wird beim Export umgewandelt z.B. "iVBORw0KGgoAAAANSUhEUgAAAEgAAAAkCAMAAAAdBYxUAAABoVBMVEUAAAB/AACqAADaAADkAADMAADkAADjAADkAADYAADiAADfAADkAADkAADjAADkAADeAADiAADgAADgAADdAADiAADkAADkAADkAADlAADkAADkAADkAADkAADkAADkAADhAADkAADkAADkAAC/AADiAADkAADiAADkAADkAADdAADjAADiAADkAADgAADkAADkAADjAADjAADjAADaAADkAADjAADkAADkAADfAADjAADkAADkAADkAADjAADiAADkAADjAADkAADhAADjAADkAADlAADkAADhAADMAADkAADkAADkAADkAADkAADkAADkAADkAADiAADkAADkAADhAADkAADjAADkAADkAADkAADkAADkAADiAADkAADkAADkAADjAADkAADXAADhAADjAADiAADkAADkAADgAADjAADfAADUAADkAADfAADkAADkAADjAADkAADjAADkAADlAADjAADkAADkAADjAADhAADlAADlAADkAADkAADUAADjAADiAADjAADjAADkAADhAADkAADkAADkAADlAADmAAAl2+ZpAAAAi3RSTlMAAgMHEwW/XasULAjB+S/zHwkqIR4b7sNVu7X9MYZfWDOjk+gEWvIt/HIXhFmHMub+QHpJDn9w+/Eoz/jb66g1j5XRPLNpdmIiCr3J9dVOiOBzZLCONKaU6dr3zNA2J/D6b3wNRXk/wu0ZHCAGrxBNe0G6vFexZnTlik/Y9su+DCVjeG60PdSckv//M2v0zgAAAeRJREFUSImtVmdT21AQlGTZGMcFd1romN57Nb0l1NAC6Z1OKhA6BAj7q9GMwcD47ullwn7QnHbv7d28JikKBev0XwspMNA6w7SQAzz+F6NTHNCCeuypPpP3cbR5hjitDhP1sj6WF8giBX3YeMzhq6zRDOwqxS9/sRtP7SUpUlBrHpF0HyZlLYTIxqI1Ful1Mk316jSf3FHsvg5r8dbcJ4nbKF0ouwn9HpfDzMcfcRUxFXK98TgLPeQ03qIgjEazWgZUO3bEGbVI0ySMFL0qQ9iSthcKkkJl+sp9oiVVXOlHDkl7dxEVD5REGXITyffJXPr6ISO4izuIQX9CKXR6adV3WlD3UU7QJbCRC6Omo4E2qm9bo46EZsMWld6PJ6u0kbJkJelA8xt3Ituy8PSI8WFRiG+J5E9M0dm+TN6ppDCRK39HXw3B5ucSvZlDfYYTccL9+uxFlYpWeqavYW2/uDu2u5357OnzGZXihlqRdPuWjVGmpY8YF/ooSpEr4r+JA6+buJV5telllDgaES6IRcYOHTDLFkBLw69YNMicGVkER8ZiwYYtQGdEt3//T4E4LOf48CBGDeiUTU1x1nxyMreT4mgKlcoa+arz8y99jOi8u9PMUAFUcNrnWem/DmM+8/K4X8Ir7+lDMnseAUAAAAAASUVORK5CYII=" nach "aVZCT1J3MEtHZ29BQUFBTlNVaEVVZ0FBQUVnQUFBQWtDQU1BQUFBZEJZeFVBQUFCb1ZCTVZFVUFBQUIvQUFDcUFBRGFBQURrQUFETUFBRGtBQURqQUFEa0FBRFlBQURpQUFEZkFBRGtBQURrQUFEakFBRGtBQURlQUFEaUFBRGdBQURnQUFEZEFBRGlBQURrQUFEa0FBRGtBQURsQUFEa0FBRGtBQURrQUFEa0FBRGtBQURrQUFEaEFBRGtBQURrQUFEa0FBQy9BQURpQUFEa0FBRGlBQURrQUFEa0FBRGRBQURqQUFEaUFBRGtBQURnQUFEa0FBRGtBQURqQUFEakFBRGpBQURhQUFEa0FBRGpBQURrQUFEa0FBRGZBQURqQUFEa0FBRGtBQURrQUFEakFBRGlBQURrQUFEakFBRGtBQURoQUFEakFBRGtBQURsQUFEa0FBRGhBQURNQUFEa0FBRGtBQURrQUFEa0FBRGtBQURrQUFEa0FBRGtBQURpQUFEa0FBRGtBQURoQUFEa0FBRGpBQURrQUFEa0FBRGtBQURrQUFEa0FBRGlBQURrQUFEa0FBRGtBQURqQUFEa0FBRFhBQURoQUFEakFBRGlBQURrQUFEa0FBRGdBQURqQUFEZkFBRFVBQURrQUFEZkFBRGtBQURrQUFEakFBRGtBQURqQUFEa0FBRGxBQURqQUFEa0FBRGtBQURqQUFEaEFBRGxBQURsQUFEa0FBRGtBQURVQUFEakFBRGlBQURqQUFEakFBRGtBQURoQUFEa0FBRGtBQURrQUFEbEFBRG1BQUFsMitacEFBQUFpM1JTVGxNQUFnTUhFd1cvWGFzVUxBakIrUy96SHdrcUlSNGI3c05WdTdYOU1ZWmZXRE9qaytnRVd2SXQvSElYaEZtSE11YitRSHBKRG45dysvRW96L2piNjZnMWo1WFJQTE5wZG1JaUNyM0o5ZFZPaU9CelpMQ09OS2FVNmRyM3pOQTJKL0Q2YjN3TlJYay93dTBaSENBR3J4Qk5lMEc2dkZleFpuVGxpay9ZOXN1K0RDVmplRzYwUGRTY2t2Ly9NMnYwemdBQUFlUkpSRUZVU0ltdFZtZFQyMUFRbEdUWkdNY0ZkMXJvbU41N05iMGwxTkFDNloxT0toQTZCQWo3cTlHTXdjRDQ3dWxsd243UW5IYnY3ZDI4SmlrS0JldjBYd3NwTU5BNnc3U1FBenorRjZOVEhOQ0NldXlwUHBQM2NiUjVoaml0RGhQMXNqNldGOGdpQlgzWWVNemhxNnpSRE93cXhTOS9zUnRQN1NVcFVsQnJIcEYwSHlabExZVEl4cUkxRnVsMU1rMzE2alNmM0ZIc3ZnNXI4ZGJjSjRuYktGMG91d245SHBmRHpNY2ZjUlV4RlhLOThUZ0xQZVEwM3FJZ2pFYXpXZ1pVTzNiRUdiVkkweVNNRkwwcVE5aVN0aGNLa2tKbCtzcDlvaVZWWE9sSERrbDdkeEVWRDVSRUdYSVR5ZmZKWFByNklTTzRpenVJUVg5Q0tYUjZhZFYzV2xEM1VVN1FKYkNSQzZPbW80RTJxbTlibzQ2RVpzTVdsZDZQSjZ1MGtiSmtKZWxBOHh0M0l0dXk4UFNJOFdGUmlHK0o1RTlNMGRtK1RONnBwRENSSzM5SFh3M0I1dWNTdlpsRGZZWVRjY0w5K3V4RmxZcFdlcWF2WVcyL3VEdTJ1NTM1N09uekdaWGlobHFSZFB1V2pWR21wWThZRi9vb1NwRXI0citKQTYrYnVKVjV0ZWxsbERnYUVTNklSY1lPSFRETEZrQkx3NjlZTk1pY0dWa0VSOFppd1lZdFFHZEV0My8vVDRFNExPZjQ4Q0JHRGVpVVRVMXgxbnh5TXJlVDRtZ0tsY29hK2Fyejh5OTlqT2k4dTlQTVVBRlVjTnJuV2VtL0RtTSs4L0s0WDhJcjcrbERNbnNlQVVBQUFBQUFTVVZPUks1Q1lJST0="
Eigentlich könnte 1 zu 1 der binärer String aus der DB übernommen werden. Die DB wurde auch per ili2pg erzeugt und es geht um das beigelegte Modell [SZ_Waldabstandslinien_2018-08-27.zip](https://github.com/claeis/ili2db/files/3192027/SZ_Waldabstandslinien_2018-08-27.zip) und genauer um die Klasse typ und das Attribut Symbol.
Verwendet wurde ili2pg in der Version 3.12.2

**Comment by claeis** [comment]
Der binäre Block wird 1 zu 1 aus der DB gelesen, der Zeilenumbruch erfolgt beim XML-Schreiben. Was gem. https://www.w3.org/TR/xmlschema-2/#base64Binary valid ist.

**Comment by snoopy21** [comment]
Ich habe das Ganze nochmals geprüft und bin meinem Problem vielleicht näher gekommen. Wenn ich das die DB in PostgreSQL erzeuge wird für das Attribut symbol der Datatyp "bytea" gewählt. Ich lege nun darin einen base46 encodierten String ab. Nun sollte beim Export im xtf wieder derselbe String darin sein, wie kann ich das erreichen?
Punkto Zeilenumbruch, besten Dank für den Hinweis, ich werde dies der Abgabestelle weiterleiten.

**Comment by claeis** [comment]
Kommt auf das Abfrage-Tool an, ob und wie es bytea umwandelt. Mit JAVA/JDBC ist es einfach byte[] (also kein base64).

**Comment by claeis** [comment]
Und man kann immer mit encode()/decode() base64 in bytea umwandeln.

**Comment by snoopy21** [comment]
Da ich die Exporte per ili2pg mache, müsste ich somit das xtf nachträglich nochmals konvertieren. Könnte man hier nicht einen zusätzlichen Parameter in ili2db dafür vorsehen?

**Comment by claeis** [comment]
Ja, und wie erfolgt der Import?

**Comment by snoopy21** [comment]
Bisher war es eine Ersterfassung, in welcher ich die Daten generell per QGIS erfasst habe, ausser die Symboldaten, welche per DBEaver erfasst wurden (Base64 encodierter String). Da dies mittels QGIS bzw. pgAdmin nicht klappte. Nun habe ich in ein neues Schema die exportierten Daten, bei welchen ich die Base64 codierten Strings eingefügt hatte, wieder importiert. Erstaunlicherweise zeigt mir nun DBeaver die Symbole als Bild an und ich kann Files reinladen. Wenn ich diese Daten wieder exportiere, kommen tatsächlich die Base64 codierten Strings. Von daher hat sich meine Anfrage erledigt. Besten Dank für die Geduld.
