### ISSUE TITLE
BASKET OID AS INTERLIS.UUIDOID: Problem bei XTF-Export aus PostGIS

### ISSUE THREAD

**Issue by pramisters** [claeis/ili2db#287]
Ich habe das MGDM PlanerischerGewaesserschutz_V1_1.ili erweitert u.a. mit OIDs als UUIDs für die Baskets. --> ZG_PlanerischerGewaesserschutz_V1_1.

`` TOPIC GWSZonen EXTENDS PlanerischerGewaesserschutz_LV95_V1_1.GWSZonen =
    BASKET OID AS INTERLIS.UUIDOID;  !! Erweiterung des MGDM-TOPIC um OID-Deklaration
    OID AS INTERLIS.UUIDOID;  !! Erweiterung des MGDM-TOPIC um OID-Deklaration``

Mit FME habe ich dann ein modellkonformes XTF-File (d.h. mit UUIDs für die Baskets) erzeugt und mit ili2pg in die PostGIS-DB importiert. Die UUIDs sind korrekt in den t_ili_tid-Spalten vorhanden, auch in der Basket-Tabelle t_ili2db_basket.

Beim Export der Daten mit ili2pg werden nun aber für die BIDs nicht die UUIDs exportiert sondern die TOPIC-Namen, wie ZG_PlanerischerGewaesserschutz_V1_1.GWSZonen (bei den anderen Objekten werden die TIDs korrekt mit den UUIDs befüllt)

Bei der Validierung mit dem iliValidator kommt es folglich zu dem Fehler:

`Error: ZG_PlanerischerGewaesserschutz_V1_1.GSBereiche: tid ZG_PlanerischerGewaesserschutz_V1_1.GSBereiche: value <ZG_PlanerischerGewaesserschutz_V1_1.GSBereiche> is not a valid BID`

Ist das noch ein Bug von ili2pg ?

[ZG_PlanerischerGewaesserschutz_V1_1.txt](https://github.com/claeis/ili2db/files/3203624/ZG_PlanerischerGewaesserschutz_V1_1.txt)

[PlanerischerGewaesserschutz_KGDM_Import.txt](https://github.com/claeis/ili2db/files/3203628/PlanerischerGewaesserschutz_KGDM_Import.txt)
[PlanerischerGewaesserschutz_KGDM_Export.txt](https://github.com/claeis/ili2db/files/3203630/PlanerischerGewaesserschutz_KGDM_Export.txt)

**Comment by zigertiger** [comment]
Did you apply both ili2pg-Options --importTid and --importBid?

**Comment by zigertiger** [comment]
did you apply both ili2pg options --importTid **and** --importBid?

**Comment by zigertiger** [comment]
if yes, I tend to say it is an ili2pg export bug... Maybe you should ask Claude directly...

**Comment by claeis** [comment]
´´´--importTid´´´  and ´´´--importBid´´´ are only required, if the model has no ´´´OID AS´´´ definitions.

**Comment by pramisters** [comment]
So, it's a bug when it "loses" previously present BIDs at export (as in my example) ?

![t_ili2db_basket](https://user-images.githubusercontent.com/23503534/58153623-cdf35080-7c6f-11e9-9507-22eef6a09adc.png)

**Comment by claeis** [comment]
Kann das Problem (mit 4.1.x) nicht reproduzieren.

**Comment by pramisters** [comment]
Hast Du mein Modell und mein XTF genommen?

Ich hab's nochmal gemacht (alles mit 4.1.0)  und erhalte immer folgendes LOG beim Export: 
[pgs_export_4_1_0.log](https://github.com/claeis/ili2db/files/3247944/pgs_export_4_1_0.log)

**Comment by pramisters** [comment]
Hier noch die Logs vom Schema-Anlegen und vom Daten-Import:
[debug_schema_creation.txt](https://github.com/claeis/ili2db/files/3248000/debug_schema_creation.txt)
[debug_data_import.txt](https://github.com/claeis/ili2db/files/3248001/debug_data_import.txt)

**Comment by claeis** [comment]
Nein, ich hatte https://github.com/claeis/ili2db/blob/master/test/data/Oid23/Oid2.ili verwendet zum verifizieren. Und jetzt aber auch noch mit Deinen Daten: gleicher Befund, funktioniert.

**Comment by claeis** [comment]
```
java -jar ili2pg-4.1.0.jar --schemaimport --dbhost didblx02 --dbport 5432 --dbusr pgs --dbpwd pgs --dbdatabase test --dbschema planerischer_gewaesserschutz --defaultSrsCode 2056 --importTid --createGeomIdx --createEnumTabs --coalesceCatalogueRef --coalesceMultiSurface --coalesceMultiLine --coalesceMultiPoint --expandMultilingual --coalesceArray --createMetaInfo --strokeArcs --createFk --createFkIdx --createNumChecks --createUnique --beautifyEnumDispName --smart2Inheritance --log debug_schema.txt --trace ZG_PlanerischerGewaesserschutz_V1_1.ili

 

java -jar ili2pg-4.1.0.jar --import --dbhost didblx02 --dbport 5432 --dbusr pgs --dbpwd pgs --dbdatabase test --dbschema planerischer_gewaesserschutz --log debug_data.txt --trace PlanerischerGewaesserschutz_KGDM.xtf

 

java -jar ili2pg-4.1.0.jar --export --models ZG_PlanerischerGewaesserschutz_V1_1 --dbhost didblx03 --dbport 5432 --dbusr pgs --dbpwd pgs --dbdatabase test --dbschema planerischer_gewaesserschutz --trace --log planerischer_gewaesserschutz.log pgs_export_4_1_0.xtf
```

**Comment by claeis** [comment]
Die BID kann nur exportiert werden, wenn ili2db erkennt, welcher Record zu welchem Basket gehört. D.h. beim ```--schemaimport``` muss die Option ```--createBasketCol``` verwendet werden (was beim vorliegenden Fall nicht der Fall war).

**Comment by pramisters** [comment]
Rein von der Logik her müsste es aber im vorliegenden Fall möglich sein.

Denn pro TOPIC existiert genau nur 1 Basket . Somit ist die Zuweisung der Records zu einem Basket eindeutig (der Record weiss ja, zu welchem TOPIC er gehört). Es wäre schön wenn in diesem Standardfall bei Eindeutigkeit die BIDs exportiert würden.

Das Problem ist einfach, dass 't_basket' mit einem Wert befüllt werden muss (t_id aus t_ili2db_basket) , der dem User nicht bekannt ist und der bei jedem Import ändern kann (globale Sequenz!). D.h. es besteht die Gefahr, dass für das Erfassen des 't_basket' das Erfassungswerkzeug (z.B. QGIS) oder ein Default-Wert in der DB immer wieder angepasst werden muss.

**Comment by claeis** [comment]
Die Zuweisung eines Records zu einem Basket ist nicht immer eindeutig, d.h. bei gewissen Modellen muss man --createBasketCol benutzen.

Trotzdem, wenn die Zuweisung möglich ist, und es nur ein Basket pro TOPIC hat, ist der --export machbar. Ich passe die Programmlogik an.

**Comment by pramisters** [comment]
Vielen Dank! Das vereinfacht die Sache sehr.
