### ISSUE TITLE
Nutzungsplanung Kanton Solothurn, Vorschrift

### ISSUE THREAD

**Issue by aweb777** [claeis/ili2db#29]
Mit dem Datenmodell SO_Nutzungsplanung_20161129.ili tritt beim Export mit ili2pg ein Fehler auf. (Vermutlicher) Grund: Das Wort "Vorschrift" kommt in zwei Associationen vor. 
![sshot-1](https://cloud.githubusercontent.com/assets/24860761/21580594/4827ed5a-d003-11e6-9fe8-9977857db706.png)
Nähere Beschreibung: https://interlis2.ch/index.php?p=/discussion/28/export-mit-ili2pg-nutzungsplanung-kanton-solothurn-attribut-vorschrift#latest

**Comment by uncoyote** [comment]
Salü Claude 
Bei einem FK Vorschrift_1 oder ähnlich: Wie weiss ich als Anwender von ili2db beim Weg db -> ili welcher FK für welche Beziehung steht? Wieso im FK nicht den Klassennamen verwenden auf den die Beziehung zeigt (im vorliegenden Fall Dokument und Plandokument)?

**Comment by claeis** [comment]
Normalerweise wird fuer FK Spalten der Rollenname verwendet. Der ist im ili-Modell eindeutig.
Je nach O/R Mapping, sind aber fuer eine Assoziation mehrere FK Spalten notwendig (Damit ergaebe sich nur mit dem Rollenname alleine im DB Schema ein Namenskonflikt).
Um Namenskonflikte im DB Schema zu verhindern, ergaenzt ili2pg den Namen mit einer Laufnummer (auch in anderen Kontexten; nicht nur bei FK Spalten).
Welche DB Spalte welchem Ili Modellelement entspricht, sieht man in der Tabelle t_ili2db_attrname.

**Comment by claeis** [comment]
Modell (ili) wahr fehlerhaft. ili2c-4.6.1 stellt den Fehler fest.
