### ISSUE TITLE
--createEnumTxtCol is broken

### ISSUE THREAD

**Issue by edigonzales** [claeis/ili2db#3]
When using `--createEnumTxtCol` option it adds a second column e.g. `art` -> `art_txt`. But `art` contains still the text representation like `Gebaeude` instead of `0`.

`
java -jar /home/stefan/Apps/ili2pg-3.4.0/ili2pg.jar --dbhost localhost --dbdatabase xanadu2 --dbusr stefan --dbpwd ziegler12 --dbschema av_bellach --import --createGeomIdx --defaultSrsCode 21781 --sqlEnableNull --createEnumTxtCol --models DM01AVSO24 254200/254200.itf 
`

Tested with ili2pg-3.4.0.

**Comment by claeis** [comment]
use `--createEnumColAsItfCode` to control the mapping of the enumeration value column. `--createEnumTxtCol` controls only the creation of the additional column.
