### ISSUE TITLE
ili2gpkg Fehler beim Export von Daten mit Referenz auf Katalog

### ISSUE THREAD

**Issue by CoNussberger** [claeis/ili2db#30]
Wenn ich die Daten des Modells perimerter_ln_soemmerungsflaechen_20140701.ili aus einem Geopackage exportieren möchte erhlate ich die Fehlermeldung:

Error: failed to query Bearbeitungsstatus_V1_2.Status.BS_Katalog_Prozess_Status
Error:   [SQLITE_ERROR] SQL error or missing database (no such table: catalogues_item)

Beim Import des Katalogs in das entsprechende Modell wird kein "catalogues_item" erstellt. Dementsprechend kann auch beim Export keins gefunden werden.

Hier die verwendeten Befehle:
Import:
java -jar ili2gpkg.jar --import --defaultSrsCode 2056 --createEnumTabs --nameByTopic --t_id_Name gpkg_id --modeldir http://models.geo.admin.ch/ --dbfile Y:\Anwend\AGRAR\MGDM_LandwirtschaftlicheBewirschaftung\leere_gpkg\perimeter_ln_soemmerungsflaechen.gpkg --models Perimeter_LN_Soemmerungsflaechen_LV95_V1_2 Y:\Anwend\AGRAR\MGDM_LandwirtschaftlicheBewirschaftung\Modelle\perimeter_ln_soemmerungsflaechen_kataloge_20140701.xml 

Export:
java -jar ili2gpkg.jar --export --trace --log Y:\Anwend\AGRAR\MGDM_LandwirtschaftlicheBewirschaftung\XTF\ln_soemm_log.txt --models Perimeter_LN_Soemmerungsflaechen_LV95_V1_2 --dbfile Y:\Anwend\AGRAR\MGDM_LandwirtschaftlicheBewirschaftung\GELAN\Archiv\perimeter_ln_soemmerungsflaechen_subset.gpkg Y:\Anwend\AGRAR\MGDM_LandwirtschaftlicheBewirschaftung\XTF\perimeter_ln_soemmerungsflaechen_subset.xtf

Mehr Infos unter : https://interlis2.ch/index.php?p=/discussion/30/ili2gpkg-fehler-beim-export-von-daten-mit-referenz-auf-katalog#latest

**Comment by claeis** [comment]
Beim Auflösen der Fremdschlüssel, wird die Zielklasse falsch auf den DB-Tabellennamen abgebildet.
