### ISSUE TITLE
ili2fgdb: no ViewableWrapper found bei Katalogimport

### ISSUE THREAD

**Issue by mizehn** [claeis/ili2db#301]
Schemaimport KbS V1_4:
java -d64 -jar C:\iliTools\ili2fgdb-4.1.0\ili2fgdb-4.1.0.jar --trace --schemaimport --defaultSrsCode 2056 --createBasketCol --createEnumTabs --modeldir http://models.interlis.ch/;http://models.geo.admin.ch --models KbS_LV95_V1_4 --dbfile \\dat\KbS_V1_4.gdb --log \\dat\schemaimport_KbS_aug19.txt

funktioniert:
[schemaimport_KbS_aug19.txt](https://github.com/claeis/ili2db/files/3471531/schemaimport_KbS_aug19.txt)

Katalogimport KbS V1_4:
java -d64 -jar C:\iliTools\ili2fgdb-4.1.0\ili2fgdb-4.1.0.jar --trace --import --modeldir http://models.interlis.ch/;http://models.geo.admin.ch --models KbS_LV95_V1_4 --dataset KbS_Codetexte_V1_4.xml  --dbfile \\dat\KbS_V1_4.gdb --log \\dat\catalogueimport_KbS_aug19.txt \\dat\KbS_Codetexte_V1_4.xml

Error:
Info: doObject(): KbS_Basis_V1_4.Codelisten.Deponietyp_Definition oid DepTypB {Code DepTypB, Definition LocalisationCH_V1.MultilingualText {LocalisedText [LocalisationCH_V1.LocalisedText {Language de, Text Deponietyp B}, LocalisationCH_V1.LocalisedText {Language fr, Text Décharge de type B}, LocalisationCH_V1.LocalisedText {Language it, Text Discarica tipo B}]}} (TransferFromXtf.java:1117)
Error: no ViewableWrapper found for KbS_Basis_V1_4.Codelisten.Deponietyp_Definition
Error:     ch.ehi.ili2db.fromxtf.TransferFromXtf.writeObject(TransferFromXtf.java:1495)
Error:     ch.ehi.ili2db.fromxtf.TransferFromXtf.doObject(TransferFromXtf.java:1109)
Error:     ch.ehi.ili2db.fromxtf.TransferFromXtf.doit(TransferFromXtf.java:580)
Error:     ch.ehi.ili2db.base.Ili2db.transferFromXtf(Ili2db.java:2178)
Error:     ch.ehi.ili2db.base.Ili2db.runUpdate(Ili2db.java:715)
Error:     ch.ehi.ili2db.base.Ili2db.runImport(Ili2db.java:233)
Error:     ch.ehi.ili2db.base.Ili2db.run(Ili2db.java:211)
Error:     ch.ehi.ili2db.AbstractMain.domain(AbstractMain.java:533)
Error:     ch.ehi.ili2fgdb.FgdbMain.main(FgdbMain.java:70)
Log: [catalogueimport_KbS_aug19.txt](https://github.com/claeis/ili2db/files/3471535/catalogueimport_KbS_aug19.txt)

Modell: http://models.geo.admin.ch/BAFU/KbS_V1_4.ili
Katalog: http://models.geo.admin.ch/BAFU/KbS_Codetexte_V1_4.xml

Wo liegt das Problem?

**Comment by claeis** [comment]
ili2db merkt nicht, dass via Referenz-Attribute auch Klassen im KbS_Basis_V1_4 (für die Katalog-Objekte) für konsistente Daten nötig sind. Das muss ich fixen. Workaround: Beim Schema Import das Modell der referenzierten Klassen auch angeben (im vorliegenden Fall also `` --models KbS_LV95_V1_4;KbS_Basis_V1_4``

**Comment by claeis** [comment]
Indem Fall muss beim Schema Import das Modell KbS_Basis_V1_4 angegeben werden, weil der Bezug zu den Katalog-Objekten nicht explizit über ein Referenzattribut erfolgt, sondern nur implizit über den Aufzählwert. D.h. es ist für ili2db unmöglich, festzustellen, dass zu KbS_LV95_V1_4  auch das Modell KbS_Basis_V1_4 gehört.
