### ISSUE TITLE
ili2pg: No T_basket in CreateEnumTab-Tables

### ISSUE THREAD

**Issue by mizehn** [claeis/ili2db#302]
Schemaimport with the following options:
--schemaimport --createGeomIdx --defaultSrsCode 2056 --createBasketCol --createFkIdx --sqlEnableNull --oneGeomPerTable --createEnumTxtCol --disableValidation --createEnumTabs --models 'Grundwasservorkommen_LV95_V1'

Doesn't generate a T_basket entry in the tables generated by --createEnumTabs, for example the table 'grundwasserleiter_festgestein_art', even though --createBasketCol is used.

Model: http://models.geo.admin.ch/BAFU/Grundwasservorkommen_V1.ili

**Comment by pramisters** [comment]
This behaviour of ili2pg is correct.
Enum-Tables never get t_basket columns, because these tables don't contain user data that needs to be linked to baskets.

**Comment by mizehn** [comment]
But we need the T_basket in all tables created at schemaimport fo the schematransformation from LV95 to LV03. Or is it a problem for other cases if there is a t_basket column in the Enum-Tables?
