### ISSUE TITLE
Fieldname added a in front

### ISSUE THREAD

**Issue by leader80** [claeis/ili2db#307]
Dear all,

with ili2pg4, by importing a property of class with the name geometry we saw that an "a" char is appended in front of the column name, is it possible to avoid this behavior?

Regards
G.

**Comment by claeis** [comment]
If a colunm oder table name would conflict with the reserved word list (as known to ili2db), an 'a' is prepended. The reserved word list used by ili2db is the super-set of the reserved words of all ili2db supported db's.
