### ISSUE TITLE
prescript and postscript should be written into sql script

### ISSUE THREAD

**Issue by edigonzales** [claeis/ili2db#309]
Das SQL im prescript und und postscript wird nicht in das SQL-Skript geschrieben, das mit `--createscript`. In Analogie mit dem "interaktiven" Modus sollte das aber in das resultierene SQL-Skript geschrieben werden.

**Comment by claeis** [comment]
Das würde dazu führen, dass im generierten createscipt evtl. Dinge gemacht werden, die im genereierten dropscript nicht wieder entfernt werden.

**Comment by claeis** [comment]
Wird wegen der Asymetrie, die entstehen würde (createscript/dropscript) nicht implementiert.
