### ISSUE TITLE
ili2pg JAR not working

### ISSUE THREAD

**Issue by leader80** [claeis/ili2db#31]
Hi all,

I'm trying to build ili2pg.jar from the git repo (with java8):
git clone https://github.com/claeis/ili2db/

Build process with Apache Ant:

- ant -f build-ili2pg.xml
- build/ili2pg.jar
- libs/ili2c.jar and libs/postgresql-9.1-901.jdbc4
- Move the three jars in the same directory and try
- java -jar ili2pg.jar --help

Results:
The build process is successful and the jar is created, but when I try to use it is not working:

λ java -jar ili2pg.jar --help
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.NoClassDefFoundError: ch/ehi/basics/settings/Settings

Any idea about this issue?

**Comment by claeis** [comment]
copy ili2pg.jar from build/jar to . OR copy libs/* to build/jar/libs
