### ISSUE TITLE
concurrent execution of ili2fgdb.jar ... known limitations

### ISSUE THREAD

**Issue by behrm** [claeis/ili2db#311]
Gibt es Einschränkungen für den parallelen Betrieb von mehreren Instanzen ili2fgdb (mit jeweils exklusiver Zuordnung einer Filegeodatabase)? Gibt es bei Temporärdateien eine Garantie für exklusiven Zugriff unter mehreren Instanzen ili2fgdb?

**Comment by claeis** [comment]
Nein, keine bekannt.
