### ISSUE TITLE
Unexpected children class name in M:M relation

### ISSUE THREAD

**Issue by seralra96** [claeis/ili2db#312]
In a model with two abstract parent classes, Class A with one child (Class AA) and Class B with two children (Class BA and Class BB), a many to many relationship between the two parent classes gives us different behaviours. 

- **Model UML**

![image](https://user-images.githubusercontent.com/25961499/67961540-d742fa80-fbc9-11e9-96c5-ccad213971ef.png)

- **Model Interlis**

```
INTERLIS 2.3;

 MODEL test_relation (es)
 AT "mailto:PC-1@localhost"
 VERSION "2019-10-31"  =

  TOPIC test_relation =

    CLASS Class_A (ABSTRACT) =
    END Class_A;

    CLASS Class_B (ABSTRACT) =
    END Class_B;

    CLASS Class_AA
    EXTENDS Class_A =
    END Class_AA;

    CLASS Class_BA
    EXTENDS Class_B =
    END Class_BA;

    CLASS Class_BB
    EXTENDS Class_B =
    END Class_BB;

    ASSOCIATION classa_classb =
      Class_A -- {0..*} Class_A;
      Class_B -- {0..*} Class_B;
    END classa_classb;

   END test_relation;

END test_relation.
```

When making a schemaimport (smart 2 inheritance) the generated intermediate (or relationship) table creates the fields to make the relation between the parent classes, but we observe that the abstract class that has only one child does not generate the attribute name as in the class that has two children. We would expect the behavior to be the same regardless of the number of children the class have.

- **Schema import current result**

![image](https://user-images.githubusercontent.com/25961499/67963246-4c173400-fbcc-11e9-9881-528068e59327.png)

- **Schema import expected result**

![image](https://user-images.githubusercontent.com/25961499/67964987-38b99800-fbcf-11e9-884e-7e7d7497dd58.png)

**Comment by claeis** [comment]
It is intended as it is.

The FK col name ``class_a`` (the unqualified role name) is more intuitive than ``class_a_class_aa`` (the role name qualified with the target table).
