### ISSUE TITLE
Error: Exporting content of base-class in extension-model

### ISSUE THREAD

**Issue by pbuerki** [claeis/ili2db#313]
Dear @claeis 
We have a model which extends an existing base model. Now we want to export all contents wich belongs to extension (Geometries from extension model, Documents from Base model). But if we export we could not specify that we would merge all in the same dataset. Export is possible for creating 2 datasets in the same XTF. But if would do it so, there will occur errors during import, because of missing relations for example to "Documents". 

Is there any possibilty to export all contents in the same dataset? I have attached screenshot-examples of "IST" and "SOLL". 

Thanks for your support. 

Kind regards, 
Pascal

IST
![IST](https://user-images.githubusercontent.com/42838243/68927792-dba21280-0788-11ea-9c4c-6dca02d572f1.png)

SOLL
![SOLL](https://user-images.githubusercontent.com/42838243/68927793-dc3aa900-0788-11ea-9908-fb98cfe07728.png)

**Comment by pbuerki** [comment]
Thanks for your response. 

Here are the models:
[Ortsplanung_Gewaesserraum_TG06.ili.txt](https://github.com/claeis/ili2db/files/3850700/Ortsplanung_Gewaesserraum_TG06.ili.txt)
[Ortsplanung_Basis_TG06.ili.txt](https://github.com/claeis/ili2db/files/3850702/Ortsplanung_Basis_TG06.ili.txt)

We have used: ili2fgdb-4.1.0.jar 

We tried export as follows: 
java -jar ili2fgdb-4.1.0.jar --export --trace --models Ortsplanung_Gewaesserraum_TG06;Ortsplanung_Basis_TG06 --log export_GWRaum.log --disableValidation --dbfile OP_Gewaesserraum_TG06.gdb OP_Gewaesserraum_TG06_export.xtf

**Comment by edigonzales** [comment]
I think you have to omit the base model in the export command:

```
java -jar /Users/stefan/apps/ili2pg-4.3.2/ili2pg-4.3.2.jar --dbhost localhost --dbport 54321 --dbdatabase edit --dbusr admin --dbpwd admin --dbschema ortsplanung --nameByTopic --sqlEnableNull --defaultSrsCode 2056 --modeldir ".;http://models.geo.admin.ch" --models Ortsplanung_Gewaesserraum_TG06 --schemaimport
```

Add some dummy data....

```
java -jar /Users/stefan/apps/ili2pg-4.3.2/ili2pg-4.3.2.jar --dbhost localhost --dbport 54321 --dbdatabase edit --dbusr admin --dbpwd admin --dbschema ortsplanung --nameByTopic --sqlEnableNull --defaultSrsCode 2056 --modeldir ".;http://models.geo.admin.ch" --models Ortsplanung_Gewaesserraum_TG06 --disableValidation --export fubar.xtf
```
see attached xtf.
[fubar.xtf.zip](https://github.com/claeis/ili2db/files/3851619/fubar.xtf.zip)

**Comment by claeis** [comment]
The finest control of what gets exported is with the parameter ``--baskets`` (instead of ``--models``). 

But I think the model is wrong (doesn't support), for what you try to achieve (you need roles marked as EXTERNAL to enable associations between objects of different baskets).

**Comment by pbuerki** [comment]
Thank you very much for your support. 

@edigonzales If we omit the base model, the table "Beschluesse" from base model would not be exported (at least in ili2fgdb). 

@claeis :
The model (Ortsplanung_Gewaesserraum_TG06.ili) is defined an extension of Ortsplanung_Basis_TG06.ili . And according to the developper (of the model) and the following Guides (
https://www.interlis.ch/download/interlis2/ili23_glossar_d.pdf
https://www.interlis.ch/download/interlis2/ili2-refman_2003-05-13_d.pdf Kap. 1.4.5 S. 15) )
should the model work as long as the table "Beschluesse" and the contents of the extension model are part of the same basket. According to the developper it is also supported in FME with ili2fme. 
Could you specify how "external" should be applied regarding your suggestion?

**Comment by claeis** [comment]
Sorry, I misunderstand the question. I thought, that you would like to export them in different baskets (but that was not the question...). This would require:

```
   ASSOCIATION ID_GewR_Linie_Genehmigung =
   	  rGewR_Linie (EXTERNAL) -- {0..*} GewR_Linie;
	  ID_Genehmigung -- {1} Beschluesse;
   END ID_GewR_Linie_Genehmigung;
```

Similar with all other associations that reference ``Beschluesse``
