### ISSUE TITLE
Export with --baskets fails

### ISSUE THREAD

**Issue by andreasneumann** [claeis/ili2db#318]
In ili2pg-4.3.2 I currently cannot filter exports by basket ids (option --baskets). A filter by dataset name (--dataset) seems to work fine.

The output error I get is:
`no basket with BID 3 in table agi_oereb_annex.T_ILI2DB_BASKET`

Here is the content of my t_ili2db_basket table:

```
t_id   dataset            topic                            t_ili_tid   attachmentkey                                            domains          
3      1                  OeREB_ExtractAnnex_V1_0.Annex                ch.so.agi.OeREB_extractAnnex-AktiveGemeinden.xtf-3       	
1332   1330               OeREB_ExtractAnnex_V1_0.Annex                ch.so.agi.OeREB_extractAnnex-KatatasterAmt.xtf-1332      	
1337   1335               OeREB_ExtractAnnex_V1_0.Annex                ch.so.agi.OeREB_extractAnnex-Stammdaten.xtf-1337         	
```

**Comment by andreasneumann** [comment]
Here is my export command:

```
java -jar /opt/ili2pg/ili2pg-4.3.2/ili2pg-4.3.2.jar --dbhost dbhostname --dbport 5432 \
--dbdatabase edit --dbusr username --dbpwd xxxx --dbparams dbparams.txt \
--export  --dbschema agi_oereb_annex \
--models OeREB_ExtractAnnex_V1_0 --modeldir 'http://models.geo.admin.ch/;http://geo.so.ch/models;' \
--baskets 3 \
test.xtf
```

**Comment by zigertiger** [comment]
how about `—baskets ”3“`?

**Comment by andreasneumann** [comment]
not working either

**Comment by claeis** [comment]
The value after the option is the BID, which is in the column t_ili_tid of table t_ili2db_baskets. See also 
https://github.com/claeis/ili2db/blob/master/docs/ili2db.rst#t_ili2db_basket. And in your DB, there is no BID. Use --importBid or TOPIC ... BASKET OID AS in the model.

**Comment by andreasneumann** [comment]
Ah - thanks. So I was looking at the wrong column. Seems to work fine, if I include a value in the correct column "t_ili_tid".

Thanks for clarifying. We can close this one.
