### ISSUE TITLE
java.lang.UnsatisfiedLinkError (sqlite-3.8.11.2-...-sqlitejdbc.dll is not a valid win32 application)

### ISSUE THREAD

**Issue by m-kuhn** [claeis/ili2db#319]
I am trying to run ili2gpkg in a Windows environment. The process dies with an error message about sqlite-3.8.11-[SOMEUUID]-sqlitejdbc.dll not being a valid Win32 application.

I am not completely sure, where this sqlite dll comes from since the error message points to a temporary location. The file itself does not exist any more after the process died (but similar files with a different UUID do still exist).

Does anyone have an idea what to look for?
Can I provide additional information?

```
C:\Users\exogikuh>"C:\Program Files (x86)\Common Files\Oracle\Java\javapath\java.exe" -jar \\srsofaioi15496\xenusers$\exogikuh\Desktop2016\ili2gpkg-4.3.2.jar --schemaimport --dbfile //srsofaioi15496/xenusers$/exogikuh/Downloads/test.gpkg --coalesceCatalogueRef --createEnumTabs --createNumChecks --coalesceMultiSurface --coalesceMultiLine --coalesceMultiPoint --coalesceArray --beautifyEnumDispName --createUnique --createGeomIdx --createFk --createFkIdx --createMetaInfo --expandMultilingual --importTid --smart2Inheritance --strokeArcs --models SO_AfU_Gefahrenkartierung_20181129 //srsofaioi15496/xenusers$/exogikuh/Downloads/SO_AfU_Gefahrenkartierung_20181129.ili

Info: dburl <jdbc:sqlite://srsofaioi15496/xenusers$/exogikuh/Downloads/test.gpkg>
Info: dbusr <>

java.lang.UnsatisfiedLinkError: C:\Users\exogikuh\AppData\Local\Temp\sqlite-3.8.11.2-4542b1f4-17b1-4b54-9832-4031d8ed5dea-sqlitejdbc.dll: %1 ist keine zulässige Win32-Anwendung

Exception in thread "main" java.lang.UnsatisfiedLinkError: org.sqlite.core.NativeDB._open(Ljava/lang/String;I)V
        at org.sqlite.core.NativeDB._open(Native Method)
        at org.sqlite.core.DB.open(DB.java:161)
        at org.sqlite.core.CoreConnection.open(CoreConnection.java:220)
        at org.sqlite.core.CoreConnection.<init>(CoreConnection.java:76)
        at org.sqlite.jdbc3.JDBC3Connection.<init>(JDBC3Connection.java:24)
        at org.sqlite.jdbc4.JDBC4Connection.<init>(JDBC4Connection.java:23)
        at org.sqlite.SQLiteConnection.<init>(SQLiteConnection.java:45)
        at org.sqlite.JDBC.createConnection(JDBC.java:114)
        at org.sqlite.JDBC.connect(JDBC.java:88)
        at java.sql.DriverManager.getConnection(Unknown Source)
        at java.sql.DriverManager.getConnection(Unknown Source)
        at ch.ehi.ili2db.base.AbstractJdbcMapping.connect(AbstractJdbcMapping.ja
va:31)
        at ch.ehi.ili2db.base.Ili2db.connect(Ili2db.java:1789)
        at ch.ehi.ili2db.base.Ili2db.readSettingsFromDb(Ili2db.java:187)
        at ch.ehi.ili2db.AbstractMain.domain(AbstractMain.java:546)
        at ch.ehi.ili2gpkg.GpkgMain.main(GpkgMain.java:67)
```

**Comment by edigonzales** [comment]
The xerial sqlite jdbc used by ili2gpkg is not a pure java implementation of a jdbc driver. For Linux, Windows and macOS it uses natively compiled sqlite engines packed into the jar file.

https://repo1.maven.org/maven2/org/xerial/sqlite-jdbc/3.28.0/sqlite-jdbc-3.28.0.jar

```
jar tf sqlite-jdbc-3.28.0.jar | grep dll
```

**Comment by edigonzales** [comment]
@schmandr Kann es sein, dass es Probleme mit den Permissions sind? Eine Anwendung darf nicht auf eine DLL auf dem Temp zugreifen?

**Comment by edigonzales** [comment]
https://bitbucket.org/xerial/sqlite-jdbc/issues/113/javalangunsatisfiedlinkerror

**Comment by edigonzales** [comment]
https://github.com/xerial/sqlite-jdbc/issues/97
https://github.com/xerial/sqlite-jdbc/issues/130

Betrifft sogar die gleiche Version.

**Comment by edigonzales** [comment]
Temp-Verzeichnis kann man notfalls überschreiben: `-Djava.io.tmpdir=/path/to/tmpdir`.

**Comment by schmandr** [comment]
> @schmandr Kann es sein, dass es Probleme mit den Permissions sind? Eine Anwendung darf nicht auf eine DLL auf dem Temp zugreifen?

Ja, das könnte gut sein, dass bei uns nicht nur die Ausführung von .exe grundsätzlich gesperrt ist, sondern auch von .dll.

**Comment by schmandr** [comment]
> Temp-Verzeichnis kann man notfalls überschreiben: `-Djava.io.tmpdir=/path/to/tmpdir`.

Aber überall dort, wo wir hinschreiben können, können wir nichts ausführen, was ja sicherheitstechnisch sinnvoll ist.

Mögliche Lösungen könnten sein, für DLLs einen bestimmten Ort eben doch "erlauben zu lassen", oder ili2pg _samt Abhängigkeiten_ installieren zu lassen.

**Comment by edigonzales** [comment]
Kannst du die beiden Varianten beim AIO abklären? 

Auch mit dem Wissen, dass out-of-the-box auch bei einer fixen Installation ili2gpkg (resp. sqlite) die DLL ins User-Temp kopiert. Das würde so ja noch nichts bringen. Oder ist meine Annahme falsch?

**Comment by edigonzales** [comment]
Soweit ich es nachvollziehen kann: Beim Aufruf wird die für das OS passende native Bibliothek (in unserem Fall die DLL) aus dem Jar entpackt und ins User-Temp kopiert. Das ist nicht etwas, was man selber machen muss/darf/soll.

**Comment by claeis** [comment]
Extrakt aus dem JAR kann man glaub übersteuern, indem man org.sqlite.lib.path und org.sqlite.lib.name setzt.

 https://github.com/xerial/sqlite-jdbc/blob/de1cace2078f7845e340bc49997ecabf848558b0/src/main/java/org/sqlite/SQLiteJDBCLoader.java#L298

**Comment by edigonzales** [comment]
Was ist der Stand?

**Comment by schmandr** [comment]
Es wird Januar.

**Comment by edigonzales** [comment]
Stand?

**Comment by schmandr** [comment]
Ticket ist beim AIO eröffnet und dort in Abklärung.

**Comment by schmandr** [comment]
Das AIO konnte dies lösen: Es brauchte die Konfiguration einer Ausnahme in AppSense, dass die entsprechende DLL ausgeführt werden darf. (Aktiv ab morgen.)

@claeis Du kannst diesen Issue schliessen (ich habe die Berechtigung nicht)
