### ISSUE TITLE
Problem with exporting to Bundesmodell  from extended model

### ISSUE THREAD

**Issue by xerocobra** [claeis/ili2db#324]
Dear All,

I am trying to extend the “**streetemission class**” from the MGDM “**LBK_Haupt_uebrigeStrassen_LV95_V1_1**”.
However, when creating data in Postgres and then exporting to the MGDM it doesn’t export the attributes of the abstract class “inputdata_estreet”. Exporting to the extended model works fine and all data, including the new attribute, is being exported.

Could someone please tell me if there is a problem with the way how the extension of the  model is done or did I use the import/export utility incorrectly?

Below is mein extended model as well as import export scripts.

Thank you very much in advance,
Michal

`INTERLIS 2.3;

/** !!------------------------------------------------------------------------------
 *  !! Version    | wer | Aenderung
 *  !!------------------------------------------------------------------------------ 
 *  !! 2019-12-15 | cst | Initialversion
 *  !!==============================================================================
 */
!!@ technicalContact=mailto:agi@bd.so.ch
MODEL OW_Strassenlaerm_20191217 (de)
AT "http://www.geo.so.ch/models/AVT"
VERSION "2019-08-06"  =
  IMPORTS GeometryCHLV95_V1,CHAdminCodes_V1,LBK_Haupt_uebrigeStrassen_LV95_V1_1,LBK_Haupt_uebrigeStrassen_Codelisten_V1_1;
 
  /** Erweiterung des MGDM-TOPIC um OID-Deklaration. Import aller Klassen ohne weitere Zusaetze.
   */
  TOPIC Emission_Strasse
  EXTENDS LBK_Haupt_uebrigeStrassen_LV95_V1_1.Emission_Strasse =
    OID AS INTERLIS.UUIDOID;
	DEPENDS ON LBK_Haupt_uebrigeStrassen_Codelisten_V1_1.Codelisten;
	
	DOMAIN
	  strassen_eigentuemer_type = (Bund, Kanton, Gemeinde);
	

    CLASS inputdata_Estreet_OW (ABSTRACT)
    EXTENDS LBK_Haupt_uebrigeStrassen_LV95_V1_1.Emission_Strasse.inputdata_Estreet =
    END inputdata_Estreet_OW;

	
	CLASS inputdata_EsonROAD (EXTENDED) = END inputdata_EsonROAD;
	CLASS inputdata_EStl86 (EXTENDED) = END inputdata_EStl86;
    CLASS inputdata_tram (EXTENDED) = END inputdata_tram;

	/** Erweiterung Klasse streetemission aus MGDM um zusaetzliches Attribut
     */	
    CLASS streetemission (EXTENDED) =
	  /** Strasseneigentuemer
       */
	  strassen_eigentuemer : strassen_eigentuemer_type;
	  /*strassen_eigentuemer : TEXT*20;*/
	END streetemission;

	ASSOCIATION inputdata_EsonROAD2streetemission(EXTENDED) =
    END inputdata_EsonROAD2streetemission;
	
	ASSOCIATION streetemission2inputdata_EStl86(EXTENDED) =
    END streetemission2inputdata_EStl86;
	
	ASSOCIATION streetemission2inputdata_tram(EXTENDED) =
    END streetemission2inputdata_tram;
  END Emission_Strasse;

  /** Erweiterung des MGDM-TOPIC um OID-Deklaration. Import aller Klassen.
   */
  TOPIC Immission_Strasse
  EXTENDS LBK_Haupt_uebrigeStrassen_LV95_V1_1.Immission_Strasse =
    OID AS INTERLIS.UUIDOID;
	DEPENDS ON LBK_Haupt_uebrigeStrassen_Codelisten_V1_1.Codelisten;

    CLASS affected_analysis (EXTENDED) = END affected_analysis;
    CLASS dispersion_calculation (EXTENDED) = END dispersion_calculation;
    CLASS noisebarrier (EXTENDED) = END noisebarrier;

	/** Erweiterung Klasse pointofdetermination aus MGDM um zusaetzliche Attribute
     */
    CLASS pointofdetermination (EXTENDED) =
	  /** Immissionsgrenzwert Tag [dBA]
       */
	  grenzwert_tag : 0 .. 100;
	  /** Immissionsgrenzwert Nacht [dBA]
       */
	  grenzwert_nacht : 0 .. 100;
	  /** Laerm-Empfindlichkeitsstufe
       */
	  empfindlichkeitsstufe : TEXT*4;
    END pointofdetermination;

    ASSOCIATION dispersion_calculation2pointofdetermination(EXTENDED) =
    END dispersion_calculation2pointofdetermination;

  END Immission_Strasse;

END OW_Strassenlaerm_20191217.`

Import script:
`
java -jar ili2pg.jar --dbhost localhost --dbport 5432 --dbdatabase abgabe_kgdm_ow --dbusr postgres --dbpwd postgres --nameByTopic --disableValidation --defaultSrsCode 2056 --expandMultilingual --strokeArcs --createGeomIdx --createFkIdx --createEnumTabs --beautifyEnumDispName --createTidCol --modeldir "http://models.geo.admin.ch;." --models "LBK_Haupt_uebrigeStrassen_LV95_V1_1;OW_Strassenlaerm_20191217" --dbschema hauptstrassen --schemaimport
pause
java -jar ili2pg.jar --dbhost localhost --dbdatabase abgabe_kgdm_ow --dbusr postgres --dbpwd postgres --nameByTopic --defaultSrsCode 2056 --expandMultilingual --strokeArcs --createGeomIdx --createFkIdx --createEnumTabs --beautifyEnumDispName  --importTid --modeldir "http://models.geo.admin.ch;." --models OW_Strassenlaerm_20191217 --dbschema hauptstrassen --import LBK_Haupt_uebrigeStrassen_Catalogues_V1_1.xml
pause
exit
`

Export scripts:
`
java -jar ili2pg.jar --dbhost localhost --dbdatabase abgabe_kgdm_ow --dbusr postgres --dbpwd postgres --trace --log K:\Interlis\Klogfile_a.txt --nameByTopic --defaultSrsCode 2056 --expandMultilingual --strokeArcs --createGeomIdx --createFkIdx --createEnumTabs --beautifyEnumDispName  --exportTid --modeldir "http://models.geo.admin.ch;." --models OW_Strassenlaerm_20191217 --dbschema hauptstrassen --export K:\Interlis\ili2pg\strassenlaerm_ow_20191211y.xtf
pause
java -jar ili2pg.jar --dbhost localhost --dbdatabase abgabe_kgdm_ow --dbusr postgres --dbpwd postgres --trace --log K:\Interlis\Blogfile_a.txt --nameByTopic --defaultSrsCode 2056 --expandMultilingual --strokeArcs --createGeomIdx --createFkIdx --createEnumTabs --beautifyEnumDispName  --exportTid --modeldir "http://models.geo.admin.ch;." --models LBK_Haupt_uebrigeStrassen_LV95_V1_1 --dbschema hauptstrassen --export K:\Interlis\ili2pg\strassenlaerm_MGDM_ow_20191212y.xtf
pause
exit
`

**Comment by zigertiger** [comment]
I think, when you try to export according to an extended base model, you have to apply the ili2pg command line option

`
--exportModels
`

to achieve correct polymorphic writing. In your case, the commad line snippet would look like:

`
... --models OW_Strassenlaerm_20191217 --exportModels LBK_Haupt_uebrigeStrassen_LV95_V1_1 ...
`

**Comment by xerocobra** [comment]
Thank you very much! Works fine now!
