### ISSUE TITLE
failed to build polygons of DM01 - invalid ring lines

### ISSUE THREAD

**Issue by jthalmann** [claeis/ili2db#327]
Import ergibt immer noch einen Fehler für Gunzwil. Das ITF hat auch beim AV-Import DM01LU mittels FME Probleme gemacht. Wir korrigieren es seither manuell vor einem Import. 

Error: DM01AVCH24LV95D.Bodenbedeckung.BoFlaeche_Geometrie: invald ring line tids 6966, 6968, 7026, 7027, 7028
Error: failed to build polygons of DM01AVCH24LV95D.Bodenbedeckung.BoFlaeche.Geometrie
Error: invalid ring lines

**Comment by mizehn** [comment]
Handelt sich um denselben Fehler wie hier: https://github.com/claeis/ili2db/issues/308

**Comment by claeis** [comment]
wie #308
