### ISSUE TITLE
schema issue from ili2pg process

### ISSUE THREAD

**Issue by leader80** [claeis/ili2db#33]
Hi All,

we are currently intensively testing the ili2pg code for the DB creation, right now with the geodata 81.2.

Two main problems from our side:

- In the table is missing the primary key
- the geometry used for line and surfaces is not compatible with Qgis

Log:
```
ERROR: Geometry type (LineString) does not match column type (CompoundCurve)
ERROR: Geometry type (Polygon) does not match column type (CurvePolygon)
```

Do you have any idea?
thanks
G.

**Comment by leader80** [comment]
The interlis file is shoing the following format:

```
Linie2 = POLYLINE WITH (STRAIGHTS) VERTEX GeometryCHLV95_V1.Coord2;
Polygon2 = SURFACE WITH (STRAIGHTS) VERTEX GeometryCHLV95_V1.Coord2 WITHOUT OVERLAPS>0.001;
```
which basically should be interpreted to: Linestring and Polygon 

Thanks
G.

**Comment by claeis** [comment]
Which model? Without model, I can not try to reproduce the issue.

**Comment by leader80** [comment]
Hi Claude,

 geodata 81.2: http://www.bafu.admin.ch/umwelt/12877/15717/15782/index.html?lang=en

Direct link:
http://www.bafu.admin.ch/umwelt/12877/15717/15782/index.html?lang=en&download=NHzLpZeg7t,lnp6I0NTU042l2Z6ln1ad1IZn4Z2qZpnO2Yuq2Z6gpJCHeoJ,gmym162epYbg2c_JjKbNoKSn6A--

thanks
G.

**Comment by claeis** [comment]
Currenty, ili2pg doesn't use the model to switch between Polygon and CurvePolygon (LineString and CompoundCurve). Polygon and LineString can be enforced by using --strokeArcs

**Comment by claeis** [comment]
see new feature #34
