### ISSUE TITLE
ili2pg fills up disk during area validation of data containing a huge polygon

### ISSUE THREAD

**Issue by schmandr** [claeis/ili2db#333]
I'm trying to export data that contains a huge polygon (lots of vertices, many holes) with ili2pg. This basically works well, but the area validation part of the export creates Gigabytes of temporary files (15GB+) until it stops with a

```
Info: validate AREA Hazard_Mapping_LV95_V1_2.hazard_mapping.assessment_area.area...
Error: failed to close xml output
Error: javax.xml.stream.XMLStreamException: java.io.IOException: No space left on device
Error: java.io.IOException: No space left on device
Error: No space left on device
failed to run ili2pg
java.lang.IllegalStateException: java.io.IOException: No space left on device
```

I assume the reason for this is probably that huge polygon contained in `Hazard_Mapping_LV95_V1_2.hazard_mapping.assessment_area` (highlighted in yellow here): ![huge_polygon](https://user-images.githubusercontent.com/3601534/74138413-dc184100-4bf1-11ea-8c7b-c86188f1c289.png)
With `--disableAreaValidation` the export completes successfully.

What can we do if we want to run it with area validation? And is there a way to easily find out which geometry is actually causing the problem? (I'm thinking of cases where it's less obvious than here.)

(I have demo .xtf data ready, but it's 37MB (zipped) in size so I can't upload it here.)

**Comment by andreasneumann** [comment]
Sampledata was sent to Claude via webtransfer.so.ch for investigation

**Comment by claeis** [comment]
Heap usage seems normal (I used java -Xmx2G -jar ilivalidator.jar data.xtf). I will now investigate disk usage.
![JVM-Xmx2G](https://user-images.githubusercontent.com/13584583/74933375-1baa0e80-53e4-11ea-9a4f-04e3b86e81c0.PNG)

**Comment by andreasneumann** [comment]
I just also ran
`java -Xmx2G -jar /opt/ilivalidator-1.11.3/ilivalidator.jar --log hazardmapping_validation.log hazardmapping.xtf`
and it seems to complete fine.

Lot's of (33413) "is not a valid OID" errors first, as the OIDs seem to start with a "digit", but then I get a number of "intersection" errors in the class "Hazard_Mapping_LV95_V1_2.hazard_mapping.assessment_area" with pairs of tids and an intersection coordinate.

I am attaching my log-file:
[hazardmapping_validation.zip](https://github.com/claeis/ili2db/files/4231220/hazardmapping_validation.zip)

**Comment by andreasneumann** [comment]
I just tried a ili2pg-3.11.2 export with increased Xmx with the following command:

`java -Xmx2G -jar /opt/ili2pg/ili2pg-3.11.2/ili2pg.jar --dbhost localhost --dbport 5432 --dbdatabase test --dbusr user --dbpwd pw --export --dbschema afu_gefahrenkartierung_mgdm --models Hazard_Mapping_LV95_V1_2 --modeldir 'http://models.geo.admin.ch/;http://geo.so.ch/models;' --log test_gefahrenkartierung_ili2pg3-11-2.log test_gefahrenkartierung_ili2pg3-11-2.xtf`

It seemed to work fine with the "-Xmx2G".

It produced the logfile attached: [test_gefahrenkartierung_ili2pg3-11-2.log](https://github.com/claeis/ili2db/files/4235310/test_gefahrenkartierung_ili2pg3-11-2.log)

I'll do some more tests, but I think we can close the issue.

**Comment by edigonzales** [comment]
Please test it with v4.3.x too.

It's a matter of enough heap space?

**Comment by andreasneumann** [comment]
Yes, I think enough heap space solves the issue.

@schmandr and I are trying to add the additional heap space parameter in our start-gretl.sh script

**Comment by andreasneumann** [comment]
[test_gefahrenkartierung_ili2pg3-11-2.log](https://github.com/claeis/ili2db/files/4235766/test_gefahrenkartierung_ili2pg3-11-2.log)

Logfile from ili2pg3-11-2 export

**Comment by schmandr** [comment]
So started GRETL with
`gradle -Dorg.gradle.jvmargs=-Xmx2G --init-script /home/gradle/init.gradle`

But still no success in GRETL production:
`Error: No space left on device`

Now, from the logs, I read:
`Picked up JAVA_TOOL_OPTIONS: -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -Dsun.zip.disableMemoryMapping=true`

Maybe this interferes with -Dorg.gradle.jvmargs=-Xmx2G?

During container life, the memory usage of the container stayed for a long time at around 1.5GB. Then it increased to 8.4GB at the time when the error message occurred.

**Comment by schmandr** [comment]
> Maybe this interferes with -Dorg.gradle.jvmargs=-Xmx2G?

The _ili2pgExport_ step logs
`Info: maxMemory 1864192 KB`

So the `-Dorg.gradle.jvmargs=-Xmx2G` seems to work as expected.

**Comment by schmandr** [comment]
The `JAVA_TOOL_OPTIONS` are set by OpenShift. They say
> It is not recommended to override this.

But let's check out that bunch of options available for configuring memory usage for Jenkins Agent on https://docs.openshift.com/container-platform/3.11/using_images/other_images/jenkins_slaves.html#configuration-and-customization

**Comment by schmandr** [comment]
OK, more tests showed that it has nothing to do with the OpenShift memory settings. It turned out that ili2pg just needs around 35GB free space on /tmp for this area validation to succeed. This is actually independent of the max heap space setting (tested with 1GB, 2GB and 4GB).

Now in our OpenShift cluster it happens that there is only around 7GB free space on /tmp. @claeis can you think of any way to reduce the temp space needed?

At the same time, I'll check if and how we can increase the space available on /tmp in OpenShift.

**Comment by claeis** [comment]
https://github.com/claeis/ilivalidator/issues/384
