### ISSUE TITLE
new option to set JDBC fetchSize

### ISSUE THREAD

**Issue by claeis** [claeis/ili2db#334]

**Comment by edigonzales** [comment]
und batchSize.

**Comment by iimsand** [comment]
Es ist nur das Setzen auf der JDBC-Connection umzusetzen.

**Comment by claeis** [comment]
fetchSize::

        Statement stmt;
        stmt.setFetchSize(fetchSize);

batchSize::

		PreparedStatement ps;


		ps.clearParameters();
		...ps.set...();
		ps.addBatch();
		// 			
		if (k % batchSize == 0) {
			ps.executeBatch();
			ps.clearBatch();
		}

**Comment by rbotteon** [comment]
Salü Zäme,

ich habe die Umsetzung von diese Story gestartet aber ich brauche ein paar Abklärungen:

- Fetchsize
      
1. Wo genau soll die Fetchsize gesetzt werden? (Fachlicher Anwendungsfall, wann tritt hier ein Problem auf? z.B. beim export von riesigen Tabellen, aber sonst gibt es keine Probleme)
2. Der export "flow" nutz manchmal common Statements, sind auch diese betroffen?
        -> Ideal wäre genau zu wissen welche queries (Statements) angepasst werden müssen

- Batchsize

1. Wo genau soll die Batchsize gesetzt werden? (Fachlicher Anwendungsfall, z.B. beim import von riesigen xtf-Files wird es extrem langsam (gäbe es hier ein Beispiel), aber sonst gibt es keine Probleme)
2. Die Änderung hier ist komplexer als bei fetchsize, weil man über die preparedStatements iterieren muss und dann den Batch ausführt.
        -> Wie für Fetchsize wäre es ideal zu wissen welche queries genau (PreparedStatements) angepasst werden müssen
        
- Treten die Probleme die zu diesem Ticket führten, bei allen Datenbanken auf?
- Existiert ein Beispiel-xtf, dass beim Import Probleme macht? Und welche Probleme genau (Dauer?)?
- Existiert ein Beispiel für den Export das Probleme macht? Und welche Probleme genau?
    -> So könnten wir gezielt das Problem angehen und an der richtigen Stelle beheben.

Merci vielmal!
Ruggero Botteon

botteon@puzzle.ch

**Comment by claeis** [comment]
Für Batchsize #414

**Comment by claeis** [comment]
Bei allen Nutzdaten (bei den Tabellen, die sich aufgrund der Modelle ergeben). Nicht bei den Meta-Tabellen (die mit t_ili2db im Namen).

Wenn es nicht nötig ist, setzt der Benutzer die Kommandozeilen-Option nicht.
