### ISSUE TITLE
DatasetIdx16 - PostgreSQL-import of valid ilidata.xml throws error

### ISSUE THREAD

**Issue by zigertiger** [claeis/ili2db#336]
Ich habe DatasetIdx16 in unserer DB implementiert. Ich habe ein ilidata.xml von früher, welches ich von Hand geschrieben hatte. Ich wollte dieses in das DB-Schema importieren, aber es werden Fehler ausgegeben, die mir nicht klar sind.   Das ilidata.xml lief fehlerfrei durch den Validator.

[ilidata.zip](https://github.com/claeis/ili2db/files/4293017/ilidata.zip)

**Comment by claeis** [comment]
Workaround: ohne --createTidCol --importTid
