### ISSUE TITLE
ili2pg: import fails when a structure has a constraint

### ISSUE THREAD

**Issue by yesidpol** [claeis/ili2db#344]
[Levantamiento_Catastral.zip](https://github.com/claeis/ili2db/files/4417621/Levantamiento_Catastral.zip)

I have a model that has this constraint in a structure (lines 14 and 15 of *Levantamiento_Catastral.ili*):

	SET CONSTRAINT WHERE Tipo_Direccion == #No_Estructurada: 
		Nombre_Predio <> UNDEFINED;
When I tried to import *Levantamiento_Catastral.xtf*, got the following error:

	Info: writeObject(): INSERT INTO test1.extdireccion (T_Id,lc_predio_direccion,T_Seq,tipo_direccion,es_direccion_principal,nombre_predio) VALUES (?,?,?,?,?,?) (TransferFromXtf.java:1555)
	Info: createEnumValueMap(): SELECT iliCode,T_Id FROM test1.extdireccion_tipo_direccion WHERE thisClass = 'Levantamiento_Catastral.ExtDireccion.Tipo_Direccion' (EnumValueMap.java:52)
	Info: second validation pass...
	ch.interlis.ili2c.metamodel.Table cannot be cast to ch.interlis.ili2c.metamodel.AssociationDef
		ch.interlis.iox_j.validator.Validator.collectSetConstraintObjs(Validator.java:1114)
		ch.interlis.iox_j.validator.Validator.validateConstraints(Validator.java:838)
		ch.interlis.iox_j.validator.Validator.validateConstraints(Validator.java:880)
		ch.interlis.iox_j.validator.Validator.iterateThroughAllObjects(Validator.java:748)
		ch.interlis.iox_j.validator.Validator.doSecondPass(Validator.java:514)
		ch.interlis.iox_j.validator.Validator.validate(Validator.java:362)
		ch.ehi.ili2db.fromxtf.TransferFromXtf.doit(TransferFromXtf.java:629)
		ch.ehi.ili2db.base.Ili2db.transferFromXtf(Ili2db.java:2238)
		ch.ehi.ili2db.base.Ili2db.runUpdate(Ili2db.java:725)
		ch.ehi.ili2db.base.Ili2db.run(Ili2db.java:213)
		ch.ehi.ili2db.AbstractMain.domain(AbstractMain.java:555)
		ch.ehi.ili2pg.PgMain.main(PgMain.java:70)

I removed the constraint, executed a schema import and import again and **ili2pg did not fail**.

----

Schema import command:
`--dbdatabase lc --smart2Inheritance --dbusr postgres --createUnique --dbpwd 123456 --modeldir "E:\models" --setupPgExt --schemaimport --createFk --models Levantamiento_Catastral --createEnumTabsWithId --dbschema test1`

Import command:
`--import --dbdatabase lc --models Levantamiento_Catastral --dbschema test1 --dbusr postgres --dbpwd 123456 --trace  E:\models\Levantamiento_catastral.xtf`

**Comment by claeis** [comment]
A SET CONSTRAINT applies to a set of objects. Therefor it can not be defined in a STRUCTURE. But this constraint can by reformulated as

      MANDATORY CONSTRAINT Tipo_Direccion != #No_Estructurada OR 
        DEFINED(Nombre_Predio);
