### ISSUE TITLE
ili2gpk geopackage in German instead of French with French model

### ISSUE THREAD

**Issue by sjib** [claeis/ili2db#347]
When creating a geopackage with a French INTERLIS model, I get the package in German instead of French. The French model is a TRANSLATION OF the german one. Why does this happen. Is there any flag to set to change?

`java -jar ili2gpkg-4.4.2.jar --schemaimport --coalesceCatalogueRef --createEnumTabs --createNumChecks --coalesceMultiSurface --coalesceMultiLine --coalesceMultiPoint --coalesceArray --beautifyEnumDispName --createUnique --createGeomIdx --createFk --createFkIdx --createMetaInfo --expandMultilingual --createTypeConstraint --createEnumTabsWithId --createTidCol --importTid --smart2Inheritance --strokeArcs --defaultSrsCode 2056 --modeldir "C:\Daten\TestALRgeopackage\ili2gpk" --log VSA_EMRtest.log --dbfile VSA_EMRtest.gpkg --models VSA_EMR_2015_LV95`

Here the model header:

`INTERLIS 2.3

MODEL VSA_EMR_2015_LV95 (fr) AT "http://www.vsa.ch/models"
  VERSION "30.03.2020" TRANSLATION OF VSA_ALR_2015_LV95 [ "30.03.2020" ] = 

  IMPORTS UNQUALIFIED INTERLIS;     !! imports INTERLIS 2 Baseunits
  IMPORTS Units;
  IMPORTS Base_f_LV95;
  IMPORTS SIA405_Base_f_LV95;
  IMPORTS SDEE_2015_LV95;`

The result is in German instead of French:

![geopackage_emr](https://user-images.githubusercontent.com/1265865/78788243-ce8df600-79ab-11ea-9913-f7c99b2f38fb.png)

All models involved:
![modelle_ili2gpk](https://user-images.githubusercontent.com/1265865/78788698-70154780-79ac-11ea-9d34-4e3059659f97.png)

**Comment by claeis** [comment]
``--nameLang lang``

**Comment by sjib** [comment]
--nameLang lang | Für alle Tabellen- und Spaltennamen werden Namen aus dem  Interlis-Modell der gegebenen Sprache verwendet. Die möglichen  Sprachnamen ergeben sich aus den Interlis-Modellen (MODEL Name (lang) ...). Mehrere Sprachen können durch Semikolon getrennt werden, um die  Priorität zu regeln. Ist für einen Namen kein Modell in einer der  gegebenen Sprache vorhanden, wird der Namen aus dem Modell in der  Ursprungssprache verwendet.
-- | --

So geht es:  

`java -jar ili2gpkg-4.4.2.jar --schemaimport --coalesceCatalogueRef --createEnumTabs --createNumChecks --coalesceMultiSurface --coalesceMultiLine --coalesceMultiPoint --coalesceArray --beautifyEnumDispName --createUnique --createGeomIdx --createFk --createFkIdx --createMetaInfo --expandMultilingual --createTypeConstraint --createEnumTabsWithId --createTidCol --importTid --smart2Inheritance --strokeArcs --defaultSrsCode 2056 --modeldir "C:\Daten\TestALRgeopackage\ili2gpk" --log VSA_EMRtest.log --dbfile VSA_EMRtest.gpkg --models VSA_EMR_2015_LV95 --nameLang fr`

`--nameLang fr` : fr ist das Sprachkürzel der gewünschten Sprachversion.



Danke für den Tipp.
