### ISSUE TITLE
createEnumDescCol-Option

### ISSUE THREAD

**Issue by edigonzales** [claeis/ili2db#349]
Neue Option: Es wird eine zusätzlich Spalte in einer Tabelle mit Aufzähltyp erstellt. Diese enthält den Kommentar zum einzelnen Aufzähltypwert (`description` in der Enum-Tabelle).

**Comment by claeis** [comment]
see also #350

**Comment by edigonzales** [comment]
siehe `--createEnumTxtCol`. Macht es das eventuell schon?

**Comment by claeis** [comment]
Ja fast. ``@dispName`` wird noch nicht berücksichtigt

**Comment by rbotteon** [comment]
Salü Claude,

konntest du bitte uns (ich und iwan) zugriff auf die Repository geben?
Wir mochten neue branches pushen und pull request erstellen.

- botteon@puzzle.ch, user: rbotteon
- imsand@puzzle.ch, user: iimsand

Merci,
Ruggero

**Comment by edigonzales** [comment]
`--createEnumTxtCol` funktioniert nur mit `--createEnumTabs`. Sonst erscheinen Fehlermeldungen wie:

```

Error: Object ee6ea97e-f980-49b1-b505-90d1314eecd2 at (line 159,col 91)
Error:   [SQLITE_ERROR] SQL error or missing database (no such table: karstformen_typ)
```

Falls das Verhalten korrekt ist, sollte es dokumentiert sein?

**Comment by claeis** [comment]
```--createEnumTxtCol``` muss ohne ```--createEnumTabs``` funktionieren
