### ISSUE TITLE
helper table to support multi language user interfaces

### ISSUE THREAD

**Issue by claeis** [claeis/ili2db#350]
Add an option to create a new helper table t_ili2db_nls with multilingual labels, descriptions, ...

- ilielement qualified name of Interlis model element (table, attr, role, enumele, ...) in root original language 
- lang language code
- uivariant to distinguish between differen ui flavours (e.g. small/large screens)
-    label name of element
-    mnemonic short cut letter of element 
-    tooltip short description
-    description longer description
-    symbol icon (e.g. for use in toolbars)

**Comment by signedav** [comment]
Is this on the roadmap already? What would be needed to do it (time/price)?

**Comment by signedav** [comment]
> 8h effort

Is this estimate still valid @claeis ?

**Comment by claeis** [comment]
TODO doc um T_ILI2DB_NLS ergaenzen

**Comment by signedav** [comment]
I tested successfully on pg and gpkg. The table is generated and - as far as I checked - complete.

One question: When I import a translated model (only) -> means of course the original model is imported as well. But do I see somewhere what language is set at the model I imported? Since when a user imports Plandaffection and not Nutzungsplanung, they might prefer french. Is there an indicator for it the meta-tables?

```
java -jar /home/dave/dev/opengisch/QgisModelBakerLibrary/modelbaker/iliwrapper/bin/ili2gpkg-5.2.0-SNAPSHOT/ili2gpkg-5.2.0-SNAPSHOT.jar --schemaimport --dbfile /home/dave/qgis_projects/translation/plansdaffect2.gpkg [...] --createNlsTab --models PlansDAffectation_V1_2
```

**Comment by claeis** [comment]
Die Zeilen wo das ilielement keinen '.' enthält sind Zeilen für Modelle. (Und in der Spalte lang siehst Du die Sprache). Was du hier in der Tabelle t_ili2db_nls nicht siehtst, ist 

a) welches der übersetzte iliname des Modelles ist (die Spalte label kann das sein, muss aber nicht)
b) welches Sprache, welche andere Sprache übersetzt

Falls du a oder b brauchst müsste ich es  in t_ili2db_meta_attrs ergänzen.

**Comment by signedav** [comment]
> a) welches der übersetzte iliname des Modelles ist (die Spalte label kann das sein, muss aber nicht)

Verstehe ich nicht ganz. Wenn ein Modell übersetzt ist, dann ist der übersetzte Name doch im Label. In welchem Fall ist das nicht so? Wenn die Übersetzung dem Original enspricht?

Mein Problem ist, dass Model Baker wissen muss, welche Version er jetzt für die Benennung der QGIS Layer / Felder etc. verwenden soll. Er hat im Schema ja nun deutsche und französische Versionen. Er müsste also wissen, welches Modell die User angewählt haben. Mit b wär dies vermutlich umgesetzt. Existiert eine Übersetzung (zBs. de->fr), dann nutzt er grundsätzlich die Übersetzung (fr), denn würden die User keine Übersetzung wollen, hätten sie auch kein übersetztes Modell importiert.

**Comment by gacarrillor** [comment]
> I tested successfully on pg and gpkg. The table is generated and - as far as I checked - complete.
> 
> One question: When I import a translated model (only) -> means of course the original model is imported as well. But do I see somewhere what language is set at the model I imported? Since when a user imports Plandaffection and not Nutzungsplanung, they might prefer french. Is there an indicator for it the meta-tables?
> 
> ```
> java -jar /home/dave/dev/opengisch/QgisModelBakerLibrary/modelbaker/iliwrapper/bin/ili2gpkg-5.2.0-SNAPSHOT/ili2gpkg-5.2.0-SNAPSHOT.jar --schemaimport --dbfile /home/dave/qgis_projects/translation/plansdaffect2.gpkg [...] --createNlsTab --models PlansDAffectation_V1_2
> ```

Not sure if I'm missing something here, but the `t_ili2db_nls` table still does not contain translated domain values with the command you pasted, using `ili2gpkg-5.2.0-20240927.161320-6-bindist.zip`

For instance, I'd expect to find values `enVigueur`, `ModificationAvecEffetAnticipe`, `ModificationSansEffetAnticipe` (table `StatutJuridique`) in the `label` column, but they're not there. Can you please confirm @signedav?

**Comment by signedav** [comment]
It's about enumerations, right @gacarrillor ?

```
    RechtsStatus = (
      inKraft,
      AenderungMitVorwirkung,
      AenderungOhneVorwirkung
    );
```
```
    StatutJuridique = (
      enVigueur,
      ModificationAvecEffetAnticipe,
      ModificationSansEffetAnticipe
    );
```

Those values (in german) are written into the corresponding table `rechtsstatus`

I agree, there should be a translation of those values in the NFS tables or at least the table `rechtsstatus` should contain the french values as well. But I suppose the first is preferable since the data are handled in original language anyway (like on export etc.)...

**Comment by signedav** [comment]
@claeis Denkst du dass es dafür eine Lösung gibt? Und was meinst du zum zweiten Thema hier https://github.com/claeis/ili2db/issues/350#issuecomment-2413511929 ?

**Comment by claeis** [comment]
> Verstehe ich nicht ganz. Wenn ein Modell übersetzt ist, dann ist der übersetzte Name doch im Label. In welchem Fall ist das nicht so? Wenn die Übersetzung dem Original enspricht?

Wenn es mit einem Meta-Attribut übersteuert ist

**Comment by signedav** [comment]
Also ein `@ili2db.dispName` würde dann im Label stehen? Was wenn es einerseits übersetzt und andererseits in der Übersetzung einen `@ili2db.dispName` hat?

**Comment by claeis** [comment]
Ja (bzw. dispName gibt es aktuell beim Modell nicht, aber könnte es geben)
