### ISSUE TITLE
Unexpected behavior with EXTENDED enumerations

### ISSUE THREAD

**Issue by seralra96** [claeis/ili2db#362]
We tried to create an extended domain from a parent domain using the following model:

**UML**

![image](https://user-images.githubusercontent.com/25961499/91731951-2b619700-eb6d-11ea-9855-719eaa742028.png)

**ili File:**

```bash
INTERLIS 2.3;

MODEL Colors (es)
AT "mailto:PC-1@localhost"
VERSION "2020-08-26"  =

  DOMAIN

    DomBaseColorType = (
      Green,
      Red,
      Blue
    );

    DomChildColorType
    EXTENDS DomBaseColorType = (
      Blue(
        Dark_Blue,
        Light_Blue,
        Medium_Blue
      )
    );

  TOPIC Colors =

    CLASS BaseColor (ABSTRACT) =
      ColorType : Colors.DomBaseColorType;
    END BaseColor;

    CLASS ChildColor
    EXTENDS BaseColor =
      ColorType (EXTENDED) : Colors.DomChildColorType;
    END ChildColor;

  END Colors;

END Colors.
```

We generated a database schema using ili2pg using particularly the following options:

ili2pg-4.4.3.jar 
--schemaimport 
--dbhost localhost 
--dbport 5433 
--dbusr postgres 
--dbpwd ****** 
--dbdatabase ladm 
--dbschema colors_2 
--setupPgExt 
--createFk 
--createFkIdx 
--createEnumTabsWithId 
--smart2Inheritance 
--modeldir E:/DOCUMENTOS/Modelo Colores --models Colors

**This is the result:**

![image](https://user-images.githubusercontent.com/25961499/91734691-d9bb0b80-eb70-11ea-80f6-93c4e2bc594d.png)

![image](https://user-images.githubusercontent.com/25961499/91734756-f1928f80-eb70-11ea-94a2-6455e9451141.png)

The result is the parent domain table and inside of this the enumerations from the child domain, we expected this as separated tables, like this:

Parent table

![image](https://user-images.githubusercontent.com/25961499/91735319-bf356200-eb71-11ea-9b2f-ac9cf2856df1.png)

Child Table

![image](https://user-images.githubusercontent.com/25961499/91735438-ee4bd380-eb71-11ea-86bb-2d68d8bc29a3.png)

**Comment by claeis** [comment]
While it would be possible to improve the mapping for ```--smart2Inheritance``` so that the enumeration table contains only the values of one enumeration type, the improvement would not work for other mapping strategies (currently ```--smart1Inheritance``` and ```--noSmartMapping```; and other future ones).

**Comment by claeis** [comment]
A general solution should enable a client (e.g. ModelBaker) to discover the the correct domain for a class (multiple classes might be mapped to the same table; therefore all the sub-domains are mapped to the same enumeration table). 

To do that it should be enough to add an entry ```ch.ehi.ili2db.enumDomain``` to t_ili2db_column_prop (similar like ```ch.ehi.ili2db.foreignKey``` but with subtype set) that indicates the enumeration-subdomain (value of colum thisClass in enumeration table).
