### ISSUE TITLE
Model names must be unique

### ISSUE THREAD

**Issue by kglaus** [claeis/ili2db#364]
When I try the ili2db command on the DEV System geodienste.ch with the model: "SanierungWasserkraft_V1_1", the following Error occurs: The name of the model conflicts with MODEL WasserBase_LV03_V1_1. Model names must be unique; please use a different name. compiler failed.
The error looks similar to the issue: https://github.com/claeis/ilivalidator/issues/104. 
@dkottmann already tried to delete the cache (similiar to the issue 104). Unfortunatly the command still doesn't work.
Is an error in the https://models.geo.admin.ch/ilimodels.xml or https://models.geo.admin.ch/ilisite.xml possible and is there any workaround for the problem above?

**Comment by claeis** [comment]
There is no model ```SanierungWasserkraft_V1_1```. There is a model ```SanierungWasserkraft_LV95_V1_1``` or ```SanierungWasserkraft_LV03_V1_1```. Both work fine. 

    java -jar ili2gpkg.jar --schemaimport --dbfile lv95.gpkg --models SanierungWasserkraft_LV95_V1_1

**Comment by kglaus** [comment]
Vielen Dank für die Antwort. Ich habe noch einmal alle Namen überprüft. Leider besteht das Problem weiterhin. Zu erwähnen ist noch, dass der Fehler beim Anlegen der Schemas entsteht und nicht beim Import von Daten.

FehlerLog:

--------------------------------------------------------------------------------
Dropping schema ili_sanierung_wasserkraft_v1_1_staging
NOTICE:  schema "ili_sanierung_wasserkraft_v1_1_staging" does not exist, skipping
--------------------------------------------------------------------------------
Dropping schema ili_sanierung_wasserkraft_v1_1_lv95_staging
NOTICE:  schema "ili_sanierung_wasserkraft_v1_1_lv95_staging" does not exist, skipping
--------------------------------------------------------------------------------
Dropping schema ili_sanierung_wasserkraft_v1_1
NOTICE:  schema "ili_sanierung_wasserkraft_v1_1" does not exist, skipping
--------------------------------------------------------------------------------
Dropping schema ili_sanierung_wasserkraft_v1_1_lv95
NOTICE:  schema "ili_sanierung_wasserkraft_v1_1_lv95" does not exist, skipping
--------------------------------------------------------------------------------

Starting ili2pg schema import...
ili2pg:                       4.4.3
default options:              --schemaimport --createGeomIdx --defaultSrsCode 21781 --createBasketCol --createFkIdx --sqlEnableNull --idSeqMin 4600000000000000001 --idSeqMax 9223372036854775807
custom options:               --oneGeomPerTable --disableValidation
custom schemaimport options:  --models 'SanierungWasserkraft_LV03_V1_1;SanierungWasserkraft_Codelisten_V1_1;WasserBase_LV03_V1_1;WasserBase_Codelisten_V1_1'

java -Xmx2048m -jar /opt/ili/ili2pg-4.4.3/ili2pg.jar --dbport 5432 --dbdatabase wfs_agg --dbschema ili_sanierung_wasserkraft_v1_1_staging --dbusr 'rails' --dbpwd 'rPw85G2' --schemaimport --createGeomIdx --defaultSrsCode 21781 --createBasketCol --createFkIdx --sqlEnableNull --idSeqMin 4600000000000000001 --idSeqMax 9223372036854775807 --oneGeomPerTable --disableValidation --models 'SanierungWasserkraft_LV03_V1_1;SanierungWasserkraft_Codelisten_V1_1;WasserBase_LV03_V1_1;WasserBase_Codelisten_V1_1' /home/rails/geodienste-config/current/ili_agg/ili/sanierung_wasserkraft_v1_1/SanierungWasserkraft_LV03_V1_1.ili

Info: dburl <jdbc:postgresql:wfs_agg>
Info: dbusr <rails>
Info: ili2pg-4.4.3-658b7daf37ba45ed2330ca3e3a3c3d59c96e91fa
Info: ili2c-5.1.0-20200501
Info: iox-ili-1.21.0-731076775d8b9bd0599802cf5a0324bc3a1c21d8
Info: java.version 1.8.0_265
Info: user.name <kglaus>
Info: maxMemory 1864192 KB
Info: currentTime 2020-09-30 12:43:32
Info: dbschema <ili_sanierung_wasserkraft_v1_1_staging>
Info: dburl <jdbc:postgresql:wfs_agg>
Info: dbusr <rails>
Info: databaseProduct <PostgreSQL>
Info: databaseVersion <9.3.24>
Info: driverName <PostgreSQL JDBC Driver>
Info: driverVersion <42.1.4.jre6>
Info: postGISVersion <POSTGIS="2.2.6dev-curve-to-line-backport r14797" GEOS="3.6.2-CAPI-1.10.2 4d2925d6" PROJ="Rel. 4.8.0, 6 March 2012" GDAL="GDAL 2.2.3, released 2017/11/20" LIBXML="2.9.1" LIBJSON="0.11.99" RASTER>
Info: compile models...
Info: lookup model <SanierungWasserkraft_Codelisten_V1_1> 2.3 in repository </home/rails/geodienste-config/current/ili_agg/ili/sanierung_wasserkraft_v1_1/>
Info: lookup model <SanierungWasserkraft_Codelisten_V1_1> 2.3 in repository <http://models.interlis.ch/>
Info: lookup model <SanierungWasserkraft_Codelisten_V1_1> 2.3 in repository </opt/ili/ili2pg-4.4.3/>
Info: lookup model <SanierungWasserkraft_Codelisten_V1_1> 2.3 in repository <http://models.geo.admin.ch/>
Info: lookup model <WasserBase_LV03_V1_1> 2.3 in repository </home/rails/geodienste-config/current/ili_agg/ili/sanierung_wasserkraft_v1_1/>
Info: lookup model <WasserBase_Codelisten_V1_1> 2.3 in repository </home/rails/geodienste-config/current/ili_agg/ili/sanierung_wasserkraft_v1_1/>
Info: lookup model <WasserBase_Codelisten_V1_1> 2.3 in repository <http://models.interlis.ch/>
Info: lookup model <WasserBase_Codelisten_V1_1> 2.3 in repository </opt/ili/ili2pg-4.4.3/>
Info: lookup model <WasserBase_Codelisten_V1_1> 2.3 in repository <http://models.geo.admin.ch/>
Info: lookup model <LocalisationCH_V1> 2.3 in repository </home/rails/geodienste-config/current/ili_agg/ili/sanierung_wasserkraft_v1_1/>
Info: lookup model <LocalisationCH_V1> 2.3 in repository <http://models.interlis.ch/>
Info: lookup model <LocalisationCH_V1> 2.3 in repository </opt/ili/ili2pg-4.4.3/>
Info: lookup model <LocalisationCH_V1> 2.3 in repository <http://models.geo.admin.ch/>
Info: lookup model <CatalogueObjects_V1> 2.3 in repository </home/rails/geodienste-config/current/ili_agg/ili/sanierung_wasserkraft_v1_1/>
Info: lookup model <CatalogueObjects_V1> 2.3 in repository <http://models.interlis.ch/>
Info: lookup model <CatalogueObjects_V1> 2.3 in repository </opt/ili/ili2pg-4.4.3/>
Info: lookup model <CatalogueObjects_V1> 2.3 in repository <http://models.geo.admin.ch/>
Info: lookup model <GeometryCHLV03_V1> 2.3 in repository </home/rails/geodienste-config/current/ili_agg/ili/sanierung_wasserkraft_v1_1/>
Info: lookup model <GeometryCHLV03_V1> 2.3 in repository <http://models.interlis.ch/>
Info: lookup model <GeometryCHLV03_V1> 2.3 in repository </opt/ili/ili2pg-4.4.3/>
Info: lookup model <GeometryCHLV03_V1> 2.3 in repository <http://models.geo.admin.ch/>
Info: lookup model <CHAdminCodes_V1> 2.3 in repository </home/rails/geodienste-config/current/ili_agg/ili/sanierung_wasserkraft_v1_1/>
Info: lookup model <CHAdminCodes_V1> 2.3 in repository <http://models.interlis.ch/>
Info: lookup model <CHAdminCodes_V1> 2.3 in repository </opt/ili/ili2pg-4.4.3/>
Info: lookup model <CHAdminCodes_V1> 2.3 in repository <http://models.geo.admin.ch/>
Info: lookup model <Units> 2.3 in repository </home/rails/geodienste-config/current/ili_agg/ili/sanierung_wasserkraft_v1_1/>
Info: lookup model <Units> 2.3 in repository <http://models.interlis.ch/>
Info: lookup model <CoordSys> 2.3 in repository </home/rails/geodienste-config/current/ili_agg/ili/sanierung_wasserkraft_v1_1/>
Info: lookup model <CoordSys> 2.3 in repository <http://models.interlis.ch/>
Info: ilifile </home/kglaus/.ilicache/models.geo.admin.ch/CH/CHBase_Part3_CATALOGUEOBJECTS_20110830.ili>
Info: ilifile </home/kglaus/.ilicache/models.interlis.ch/refhb23/Units-20120220.ili>
Info: ilifile </home/kglaus/.ilicache/models.geo.admin.ch/CH/CHBase_Part2_LOCALISATION_20110830.ili>
Info: ilifile </home/kglaus/.ilicache/models.interlis.ch/refhb23/CoordSys-20151124.ili>
Info: ilifile </home/kglaus/.ilicache/models.geo.admin.ch/CH/CHBase_Part4_ADMINISTRATIVEUNITS_20110830.ili>
Info: ilifile </home/kglaus/.ilicache/models.geo.admin.ch/CH/CHBase_Part1_GEOMETRY_20110830.ili>
Info: ilifile </home/kglaus/.ilicache/models.geo.admin.ch/BAFU/WasserBase_V1_1.ili>
Info: ilifile </home/rails/geodienste-config/current/ili_agg/ili/sanierung_wasserkraft_v1_1/WasserBase_LV03_V1_1.ili>
Info: ilifile </home/kglaus/.ilicache/models.geo.admin.ch/BAFU/SanierungWasserkraft_V1_1.ili>
Info: ilifile </home/rails/geodienste-config/current/ili_agg/ili/sanierung_wasserkraft_v1_1/SanierungWasserkraft_LV03_V1_1.ili>
Error: /home/rails/geodienste-config/current/ili_agg/ili/sanierung_wasserkraft_v1_1/WasserBase_LV03_V1_1.ili:29:The name of the model conflicts with MODEL WasserBase_LV03_V1_1. Model names must be unique; please use a different name.
compiler failed

**Comment by edigonzales** [comment]
```
java -Xmx2048m -jar /Users/stefan/apps/ili2pg-4.3.1/ili2pg.jar --dbhost localhost --dbport 54321 --dbdatabase edit --dbschema fubar --dbusr admin --dbpwd admin --schemaimport --createGeomIdx --defaultSrsCode 21781 --createBasketCol --createFkIdx --sqlEnableNull --idSeqMin 4600000000000000001 --idSeqMax 9223372036854775807 --oneGeomPerTable --disableValidation --models 'SanierungWasserkraft_LV03_V1_1;SanierungWasserkraft_Codelisten_V1_1;WasserBase_LV03_V1_1;WasserBase_Codelisten_V1_1'
```
Funktioniert bei mir. Scheint mir der identische Befehl zu sein bis auf das Fehlen der ili-Datei ganz am Ende des Befehls. Sind die Modelldateien selber gemacht, die du verwendest? Im Repo finde ich nur Dateien _ohne_ Bezugsrahmenangabe im Filenamen, also z.B. WasserBase_V1_1.ili und nicht WasserBase_LV03_V1_1.ili.

**Comment by kglaus** [comment]
Die Modelldateien sind selber gemacht, beziehungsweise aus dem Repository kopiert.

**Comment by edigonzales** [comment]
Also, ich habe mir die Dateien http://models.geo.admin.ch/BAFU/SanierungWasserkraft_V1_1.ili und http://models.geo.admin.ch/BAFU/WasserBase_V1_1.ili heruntergeladen und dann folgenden Befehl erfolgreich ausgeführt:

```
java -Xmx2048m -jar /Users/stefan/apps/ili2pg-4.3.1/ili2pg.jar --dbhost localhost --dbport 54321 --dbdatabase edit --dbschema fubar --dbusr admin --dbpwd admin --schemaimport --createGeomIdx --defaultSrsCode 21781 --createBasketCol --createFkIdx --sqlEnableNull --idSeqMin 4600000000000000001 --idSeqMax 9223372036854775807 --oneGeomPerTable --disableValidation --models 'SanierungWasserkraft_LV03_V1_1;SanierungWasserkraft_Codelisten_V1_1;WasserBase_LV03_V1_1;WasserBase_Codelisten_V1_1' /Users/stefan/Downloads/SanierungWasserkraft_V1_1.ili
```

Warum heissen die Dateien bei euch "...LV03..."?

**Comment by kglaus** [comment]
Erst einmal vielen Dank für den Support Stefan.
Die Aufteilung der ili Dateien ist applikationsbedingt (Aufteilung der Bezugsrahmen). Ich lade hier noch einmal die Files hoch: 
[WasserBase_LV95_V1_1.txt](https://github.com/claeis/ili2db/files/5306169/WasserBase_LV95_V1_1.txt)
[SanierungWasserkraft_Codelisten_V1_1.txt](https://github.com/claeis/ili2db/files/5306170/SanierungWasserkraft_Codelisten_V1_1.txt)
[SanierungWasserkraft_LV03_V1_1.txt](https://github.com/claeis/ili2db/files/5306171/SanierungWasserkraft_LV03_V1_1.txt)
[SanierungWasserkraft_LV95_V1_1.txt](https://github.com/claeis/ili2db/files/5306172/SanierungWasserkraft_LV95_V1_1.txt)
[WasserBase_Codelisten_V1_1.txt](https://github.com/claeis/ili2db/files/5306173/WasserBase_Codelisten_V1_1.txt)
[WasserBase_LV03_V1_1.txt](https://github.com/claeis/ili2db/files/5306174/WasserBase_LV03_V1_1.txt)

Ausserdem wurde das Cache noch einmal geleert.

**Comment by edigonzales** [comment]
Jetzt passiert bei mir das Gleiche. Aufgefallen ist mir, dass - trotz des Löschen des ilicache - etwas im Cache ist. Siehe auch bei deinem Log-Output: 

`Info: ilifile </home/kglaus/.ilicache/models.geo.admin.ch/BAFU/SanierungWasserkraft_V1_1.ili>`

Ich denke aus diesem Grund erscheint die Fehlermeldung. Er findet das Modell nicht lokal und findet es im Bundes-Repo und lädt es herunter. Dann gibt es aber den Konflikt.

**Comment by edigonzales** [comment]
Habt ihr nicht bereits ähnlich Fälle? Ich weiss nicht wirklich genau wie der Ablauf der Modellsuche ist. Es dünkt mich gerade, dass nur das erste Modell (und nicht die Imports) lokal gesucht/gefunden (?) werden. Aber warum dann der Konflikt auftaucht, ist mir schleierhaft.

**Comment by claeis** [comment]
wegen claeis/ili2c#55 werden die lokalen ili-Dateien z.T. nicht gelesen, und dann werden die ili-Dateien aus model.geo.admin.ch verwendet, die dann auch die LV95 Modelle enthalten. Und dann entsteht der Konflikt.

**Comment by kglaus** [comment]
Vielen Dank an alle für die Hilfe.
Ich habe als Workaround nun die Kommentare am Ende von jedem ili File gelöscht. Die Anlegung des Schemas hat nun geklappt.

Old:
`  END Catalogs;                                             !! topic

END SanierungWasserkraft_Codelisten_V1_1.                   !! model`

New:
`  END Catalogs;                                             !! topic

END SanierungWasserkraft_Codelisten_V1_1.`
