### ISSUE TITLE
NoClassDefFoundError with sspi authentication

### ISSUE THREAD

**Issue by m-kuhn** [claeis/ili2db#369]
When "sspi" is enabled on a postgres server to connect using windows ad/single sign on, ili2pg raises an exception.
If sspi is diabled on the same server and "md5" is used (user/password based authentication), everything works fine.

```
java -Djava.security.auth.login.config=jaas.conf -jar ili2pg-4.4.2/ili2pg-4.4.2.jar --createEnumTxtCol --schemaimport --importTid --sqlEnableNull --createEnumTabs --createFk  --defaultSrsCode 2056  --noSmartMapping --dbusr user --dbhost host  --dbport 5432  --dbdatabase test --modeldir ili --dbschema vsa_dss_2015_d --log 00schema_VSA_DSS_2015_d.log VSA_DSS_2015_2_d_20170602.ili

Info: dburl <jdbc:postgresql://host:5432/test>
Info: dbusr <user>

Exception in thread "main" java.lang.NoClassDefFoundError: com/sun/jna/platform/win32/Win32Exception
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Unknown Source)
        at org.postgresql.core.v3.ConnectionFactoryImpl.createSSPI(ConnectionFactoryImpl.java:73)
        at org.postgresql.core.v3.ConnectionFactoryImpl.doAuthentication(ConnectionFactoryImpl.java:566)
        at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:222)
        at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:49)
        at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:194)
        at org.postgresql.Driver.makeConnection(Driver.java:450)
        at org.postgresql.Driver.connect(Driver.java:252)
        at java.sql.DriverManager.getConnection(Unknown Source)
        at java.sql.DriverManager.getConnection(Unknown Source)
        at ch.ehi.ili2db.base.AbstractJdbcMapping.connect(AbstractJdbcMapping.java:31)
        at ch.ehi.ili2db.base.Ili2db.connect(Ili2db.java:1795)
        at ch.ehi.ili2db.base.Ili2db.readSettingsFromDb(Ili2db.java:187)
        at ch.ehi.ili2db.AbstractMain.domain(AbstractMain.java:553)
        at ch.ehi.ili2pg.PgMain.main(PgMain.java:70)
Caused by: java.lang.ClassNotFoundException: com.sun.jna.platform.win32.Win32Exception
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        ... 16 more
```

Note: skipping jaas.conf in the parameters triggers the same error

The server configuration seems to be fine, plain `psql` can be used to send queries to the server successfully.

Is there a java module missing locally?

**Comment by edigonzales** [comment]
Are you running ili2pg on a windows os?

**Comment by m-kuhn** [comment]
yes

**Comment by edigonzales** [comment]
Does it need the JNA classes in the classpath? (never worked with this but sounds reasonable). https://github.com/java-native-access/jna#readme

I downloaded the two jars, put them in the libs folder, unpacked the ili2pg.jar and added the two jars in the manifest file, repacked the jar. 

Do you get the same error with the version attached?
[Archive.zip](https://github.com/claeis/ili2db/files/5695478/Archive.zip)

**Comment by edigonzales** [comment]
```
➜  Downloads jar -tf jna-platform-5.6.0.jar | grep Win32Exception
com/sun/jna/platform/win32/Win32Exception.class
```

**Comment by m-kuhn** [comment]
Thanks @edigonzales
It seems this was all that was missing :clap:

**Comment by edigonzales** [comment]
But I think you should address this issue to @claeis for a good and sustainable solution.

**Comment by m-kuhn** [comment]
Absolutely, will need to do some further tests to be sure it works.

**Comment by m-kuhn** [comment]
Further package missing: (at least) waffle-jna

**Comment by edigonzales** [comment]
https://mvnrepository.com/artifact/com.github.waffle/waffle-jna/2.3.0

**Comment by m-kuhn** [comment]
Added waffle-jna/2.3.0, downgraded jna and jna-platform to 5.5.0

```
Exception in thread "main" java.lang.NoSuchMethodError: com.sun.jna.platform.win32.Sspi$SecBufferDesc.<init>(I[B)V
        at org.postgresql.sspi.SSPIClient.continueSSPI(SSPIClient.java:195)
        at org.postgresql.core.v3.ConnectionFactoryImpl.doAuthentication(ConnectionFactoryImpl.java:604)
```

Will need to try again with 5.6.0 -- or stop doing dependency management and patching by hand.

**Comment by edigonzales** [comment]
https://github.com/edigonzales/ili2db
https://github.com/edigonzales/ili2db/commit/9f051a386295da9fc70cec5aa5173bb333241bf4 

I added the waffle-stuff as dependency. It takes care of the underlying libs. I had to bump the java version to 1.8 though. Can you try the attached version? 

[ili2pg-4.4.5-SNAPSHOT.zip](https://github.com/claeis/ili2db/files/5704127/ili2pg-4.4.5-SNAPSHOT.zip)

**Comment by edigonzales** [comment]
`gradle clean compileIli2pgJava ili2pgJar ili2pgBindist -x test -x ili2pgTest -x usrdoc`

**Comment by m-kuhn** [comment]
> I added the waffle-stuff as dependency. It takes care of the underlying libs. I had to bump the java version to 1.8 though. Can you try the attached version?
>
> ili2pg-4.4.5-SNAPSHOT.zip

```
Exception in thread "main" java.lang.NoSuchMethodError: com.sun.jna.platform.win32.Sspi$SecBufferDesc.<init>(I[B)V
        at org.postgresql.sspi.SSPIClient.continueSSPI(SSPIClient.java:195)
        at org.postgresql.core.v3.ConnectionFactoryImpl.doAuthentication(ConnectionFactoryImpl.java:604)
```

Same still.
There is a similar report but it seems to be related to other libs involved https://github.com/Waffle/waffle/issues/838

**Comment by edigonzales** [comment]
I downgraded waffle to 1.9.1. As far as I understand the ticket mentioned: Waffle - as of version 2.0.0 - stopped using SecBufferDesc. But the jdbc driver still uses / needs it. So this is the next try: 

[ili2pg-4.4.5-SNAPSHOT.zip](https://github.com/claeis/ili2db/files/5708549/ili2pg-4.4.5-SNAPSHOT.zip)

**Comment by m-kuhn** [comment]
There's still an error, but 

```
failed to insert meta info values to vsa_dss_2015_d1.T_ILI2DB_COLUMN_PROP
  FEHLER: Wert zu lang für Typ character varying(1024)
```

it looks pretty much like this happens on the DB already so auth must have been successful

This seems to have done it !

**Comment by edigonzales** [comment]
Yes. Seems to be able to connect to the db.

**Comment by edigonzales** [comment]
Can you try it without `--createMetaInfo `? (or whatever uses the column prop table). Just to be sure it works.

**Comment by m-kuhn** [comment]
Not sure what causes this ...

`java -Djava.security.auth.login.config=jaas.conf -jar ili2pg-4.4.5/ili2pg-4.4.5-SNAPSHOT.jar --createEnumTxtCol --schemaimport --importTid --sqlEnableNull --createEnumTabs --createFk  --defaultSrsCode 2056  --noSmartMapping --dbusr windowsUser --dbhost host  --dbport 5432  --dbdatabase test --modeldir ili  --dbschema vsa_dss_2015_d1 --log logfile VSA_DSS_2015_2_d_20170602.ili`

**Comment by edigonzales** [comment]
"--createMetaInfo: Erstellt zusätzliche Meta-Tabellen T_ILI2DB_TABLE_PROP, T_ILI2DB_COLUMN_PROP, T_ILI2DB_META_ATTRS mit weiteren Angaben aus dem Interlis Modell. (siehe Kapitel Metadaten)"

Same here. It creates these tables without `--createMetaInfo`. Just wondering what's longer than 1024. It's either "tag" or "setting".

`--trace`? And/or "dump" it into a sql file with `--createscript fubar.sql` 

 Can you open a new issue? And try sspi with another model?

**Comment by m-kuhn** [comment]
It works fine with a different model. Including these libs sounds like a good idea to me.

I was not able to track down the reason.

The postgresql server log also shows:

```
2020-12-22 13:06:23.042 UTC [311] docker@gis ERROR:  value too long for type character varying(1024)
2020-12-22 13:06:23.042 UTC [311] docker@gis STATEMENT:  INSERT INTO vsa_dss_2015_d3.T_ILI2DB_COLUMN_PROP (tablename,subtype,columnname,tag,setting) VALUES ($1,$2,$3,$4,$5)
```

the sql script is not written (might be only done once the process finishes successfully?)

**Comment by edigonzales** [comment]
It does not need a running database for creating the raw sql script:

```
java -jar /Users/stefan/apps/ili2pg-4.4.4/ili2pg-4.4.4.jar --dbschema fubar --nameByTopic --defaultSrsCode 2056 --modeldir "https://vsa.ch/models;http://models.geo.admin.ch" --models VSADSSMINI_2020_LV95 --createscript fubar.sql
```

Please note: it's 2020 version of vsa dss mini used in the command. Could not find 2015 version. Behind the vsa paywall?

**Comment by m-kuhn** [comment]
Yes ... Paywall. Happy they released the updated versions publicly.

Here we go:

```
INSERT INTO fubar2abcdefelkajdsflakjdsflaskdjfasdf.T_ILI2DB_COLUMN_PROP (tablename,subtype,columnname,tag,setting) VALUES ('baseclass',NULL,'T_Type','ch.ehi.ili2db.types','["absperr_drosselorgan","abwasserbauwerk_symbol","abwasserbauwerk_text","abwasserbehandlung","abwasserknoten","abwasserreinigungsanlage","abwasserverband","amt","arabauwerk","araenergienutzung","badestelle","bankett","beckenentleerung","beckenreinigung","brunnen","deckel","durchlass","einleitstelle","einstiegshilfe","einzelflaeche","einzugsgebiet","einzugsgebiet_text","elektrischeeinrichtung","elektromechanischeausruestung","entwaesserungssystem","erhaltungsereignis","ezg_parameter_allg","ezg_parameter_mouse1","feststoffrueckhalt","fischpass","fliessgewaesser","foerderaggregat","furt","gebaeude","gefahrenquelle","gemeinde","genossenschaft_korporation","geschiebesperre","gewaesserabschnitt","gewaesserabsturz","gewaesserschutzbereich","gewaessersektor","gewaessersohle","gewaesserwehr","grundwasserleiter","grundwasserschutzareal","grundwasserschutzzone","haltung","haltung_alternativverlauf","haltung_text","haltungspunkt","hq_relation","hydr_geometrie","hydr_geomrelation","hydr_kennwerte","kanal","kanton","leapingwehr","mechanischevorreinigung","messgeraet","messreihe","messresultat","messstelle","mutation","normschacht","planungszone","privat","reservoir","retentionskoerper","rohrprofil","rohrprofil_geometrie","rueckstausicherung","schlammbehandlung","schleuse","see","sohlrampe","spezialbauwerk","steuerungszentrale","stoff","streichwehr","trockenwetterfallrohr","trockenwetterrinne","ueberlaufcharakteristik","ufer","unfall","versickerungsanlage","versickerungsbereich","wasserfassung"]');
```

Note to self `--schemaimport` and `--createscript` are not compatible

**Comment by beistehen** [comment]
> Could not find 2015 version. Behind the vsa paywall?

Yes. You need a CD from 2014 that includes a file with a password. This password can be used on the .zip files published [here](https://vsa.ch/vsa-dss-interlis-cd/).
Idk how to obtain this CD nowadays though...
