### ISSUE TITLE
Gui and cmdline export not working

### ISSUE THREAD

**Issue by leader80** [claeis/ili2db#37]
Hi All,

the cmdline and the GUI export of XFT data from the DB is not working:

> Error: %XTF: model not found
> Error:     ch.interlis.ilirepository.IliManager.getConfigWithFiles(IliManager.java:191)
> Error:     ch.interlis.ili2c.Main.runCompiler(Main.java:468)
> Error:     ch.ehi.ili2db.base.Ili2db.runExport(Unknown Source)
> Error:     ch.ehi.ili2db.base.Ili2db.run(Unknown Source)
> Error:     ch.ehi.ili2db.AbstractMain.domain(Unknown Source)
> Error:     ch.ehi.ili2pg.PgMain.main(Unknown Source)
> compiler failed
>     ch.ehi.ili2db.base.Ili2db.runExport(Unknown Source)
>     ch.ehi.ili2db.base.Ili2db.run(Unknown Source)
>     ch.ehi.ili2db.AbstractMain.domain(Unknown Source)
>     ch.ehi.ili2pg.PgMain.main(Unknown Source)

Here my cmdline export:
java -jar c:\geo\ili2pg-3.6.0.jar --trace --export --dbdatabase postgres --dbusr postgres --dbpwd postgres "C:\geo\zpl\zpl.xtf"

I'm base on the sample directory provided in this project, I just tried an import (which is working) and an export (which is not).

Please help
Cheers
G.

**Comment by claeis** [comment]
you must say, what you want to export. For example with --models or with --dataset
