### ISSUE TITLE
ERROR: Dangling references

### ISSUE THREAD

**Issue by kglaus** [claeis/ili2db#370]
Folgender Fehler taucht beim Import von Testdaten von SH auf: [Logfile.txt](https://github.com/claeis/ili2db/files/5724731/Logfile.txt)
 Verwendete Modelle und Daten: 
ili:
[piano_direttore_energie_rinovabile_MN95_V1_0.txt](https://github.com/claeis/ili2db/files/5724761/piano_direttore_energie_rinovabile_MN95_V1_0.txt)
[plan_directeur_energies_renouvelables_MN95_V1_0.txt](https://github.com/claeis/ili2db/files/5724762/plan_directeur_energies_renouvelables_MN95_V1_0.txt)
[richtplanung_erneuerbare_energien_LV95_V1_0.txt](https://github.com/claeis/ili2db/files/5724763/richtplanung_erneuerbare_energien_LV95_V1_0.txt)
Kataloge:
[RPEE_Catalogues_it_V1_0.txt](https://github.com/claeis/ili2db/files/5724777/RPEE_Catalogues_it_V1_0.txt)
[RPEE_Catalogues_de_V1_0.txt](https://github.com/claeis/ili2db/files/5724778/RPEE_Catalogues_de_V1_0.txt)
[RPEE_Catalogues_fr_V1_0.txt](https://github.com/claeis/ili2db/files/5724779/RPEE_Catalogues_fr_V1_0.txt)
Testdaten
[SH_RPEE_DE.txt](https://github.com/claeis/ili2db/files/5724825/SH_RPEE_DE.txt)

Es wird die ili2pg Version 4.3.3 verwendet. Die t_ili_tid der Kataloge für Energieform sowie Aussageart wird ebenfalls mitgegeben und abgefüllt (ili2pg_options: 
[richtplanung_erneuerbare_energien_v1_0_lv95.txt](https://github.com/claeis/ili2db/files/5724892/richtplanung_erneuerbare_energien_v1_0_lv95.txt)).

Liegt hier ein Fehler mit ili2pg vor oder übersehe ich etwas?

**Comment by edigonzales** [comment]
Ich bin mir nicht sicher, ob sich was im Zusammenspiel mit den Katalogen in ili2pg-4 verändert hat. Jedenfalls funktioniert es wenn man das Schema mit `--createTidCol` anlegt und die Daten mit `--importTid` importiert.

```
java -jar /Users/stefan/apps/ili2pg-4.3.1/ili2pg-4.3.1.jar --dbhost localhost --dbport 54321 --dbdatabase edit --dbusr admin --dbpwd admin --dbschema fubar --models RichtplanungErneuerbareEnergien_V1 --nameByTopic --strokeArcs --disableValidation --defaultSrsCode 2056 --createFk --createTidCol --schemaimport
```

```
java -jar /Users/stefan/apps/ili2pg-4.3.1/ili2pg-4.3.1.jar --dbhost localhost --dbport 54321 --dbdatabase edit --dbusr admin --dbpwd admin --dbschema fubar --models RichtplanungErneuerbareEnergien_V1 --nameByTopic --strokeArcs --disableValidation --defaultSrsCode 2056 --importTid --import RPEE_Catalogues_de_V1_0.xml

java -jar /Users/stefan/apps/ili2pg-4.3.1/ili2pg-4.3.1.jar --dbhost localhost --dbport 54321 --dbdatabase edit --dbusr admin --dbpwd admin --dbschema fubar --models RichtplanungErneuerbareEnergien_V1 --nameByTopic --strokeArcs --disableValidation --defaultSrsCode 2056 --importTid --import SH_RPEE_DE.xtf
```

**Comment by edigonzales** [comment]
`--createTidCol ` scheint gemacht zu werden. Wird auch `--importTid` verwendet?

**Comment by mizehn** [comment]
Beim Katalogimport wird `--importTid` verwendet, beim Datenimport jedoch nicht. Kann es daran liegen?

**Comment by edigonzales** [comment]
Ohne `--importTid` beim Datenimport funktioniert es bei mir ebenfalls nicht: `Error:   dangling references`.

**Comment by kglaus** [comment]
@edigonzales @mizehn 
Vielen Dank euch zwei für die Hilfe. 
Ich habe nun die `--importTid` beim Datenimport verwendet. 
Es funktioniert jetzt einwandfrei.
