### ISSUE TITLE
KKGEO: ili2pg-4.4.1  failed to build polygons 

### ISSUE THREAD

**Issue by zenomonotti** [claeis/ili2db#376]
Der Fehler in ili2pg ist nicht eindeutig, und ich versuche seit Monaten, eine Lösung finden.  Mit ili2pg-3.12.3 werden die Daten geladen, aber die Geometrien mit Fehler werden gelöscht, ohne dass ein Fehler/Information ausgegeben wird. Mit ili2pg-4.4.1 die Daten werden nicht geladen und mann bekommt diese fehler:

Info: first validation pass...
Error: failed to build polygons of MD01MUCH24MN95I.Copertura_del_suolo.SuperficieCS.Geometria
Error:   java.lang.NullPointerExceptio

Datie:
Link: https://mft.ti.ch/?wtcQID=d21RRVZsS006MmRVTTJaWVU=
Die Freigabe ist aktiv bis 11.01.2021 11:09:33

**Comment by edigonzales** [comment]
Was möchtest du machen oder erreichen? 

Aufgrund der NullPointerException gehe ich davon aus, dass die Geometrie fehlerhaft sind und ein Fall auftritt, der von ili2db nicht abgefangen wird.

**Comment by zenomonotti** [comment]
Ich kann den geometrischen Fehler aus einer itf-Analyse nicht finden.
Mit dem alten ili2pg hätte ich das Dokument in die DB geladen und analysiert, welches grafische Element sich nicht dargestellt hat. Auch so, zusätzlich zu nicht in der Lage, das Element korrekt zu identifizieren, habe ich eine ganze Gemeinde nicht laden.

Daher wäre es ideal, eine Funktion zu implementieren, die alle Geometrien lädt, die korrekt sind.

**Comment by edigonzales** [comment]
Die NullPointerException kommt von hier: https://github.com/claeis/iox-ili/blob/master/jtsext/src/main/java/ch/interlis/iom_j/itf/impl/jtsext/operation/polygonize/EdgeRing.java#L58

Grund dafür ist, dass `testPt` = `null` ist. Null wird `testPt` auf Zeile 56 https://github.com/claeis/iox-ili/blob/master/jtsext/src/main/java/ch/interlis/iom_j/itf/impl/jtsext/operation/polygonize/EdgeRing.java#L56

testRing:
```
(2715889.618 1095611.897, 2715889.688 1095611.896), CIRCULARSTRING (2715889.688 1095611.896, 2715892.672 1095614.88, 2715889.688 1095617.864)CIRCULARSTRING (2715889.688 1095617.864, 2715887.578 1095616.99, 2715886.704 1095614.88)CIRCULARSTRING (2715886.704 1095614.88, 2715887.553 1095612.795, 2715889.618 1095611.897)
```

tryShellRing:
```
CIRCULARSTRING (2715889.688 1095617.864, 2715892.672 1095614.88, 2715889.688 1095611.896), (2715889.688 1095611.896, 2715889.618 1095611.897), CIRCULARSTRING (2715889.618 1095611.897, 2715887.553 1095612.795, 2715886.704 1095614.88)CIRCULARSTRING (2715886.704 1095614.88, 2715887.578 1095616.99, 2715889.688 1095617.864)
```

Warum das so ist, weiss ich nicht.
