### ISSUE TITLE
ILI2pg ---> toml konfigurieren

### ISSUE THREAD

**Issue by zenomonotti** [claeis/ili2db#377]
Ich möchte in einem Toml den Parameter --skipGeometryErrors einführen, damit ich Daten zu geodienste.ch hochladen kann. 
Eine Korrektur der Daten durch Geometer wäre unmöglich.

Oder: die Geometrieprüfung in den betroffenen Klassen im config.toml zu konfigurieren?

**Comment by edigonzales** [comment]
Geht das? Oder macht das was anderes?

```
["PARAMETER"] 
defaultGeometryTypeValidation="off"
```

**Comment by claeis** [comment]
Fehlerhafte AREA Attribute können für den ganzen Datensatz nicht als Polygone gelesen werden, weil ein Programm nicht erkennen kann, welche Linien und Punkte falsch sind (Punkt/Linie zu viel, zu wenig; Linie zu kurz, zu  lang); und somit nicht erkennen können, bei welchem Polygon der Fehler ist. Das diese Daten nicht gelsen werden können, hat also nicht in erster Linie mit der Validierung zu tun, sondern damit, dass aus den Linien+Punkten keine Polygone gebildet werden können.

Um solche Daten zu flicken: import mit --skipPolygonBuilding --skipGeometryErrors --sqlEnableNull --disableValidation

**Comment by edigonzales** [comment]
Ein Problem ist, dass man keinen Anhaltspunkt hat, wo der Fehler sein könnte. Siehe #376. Der Polygonizer bricht ab, ohne eine Koordinatenangabe.

**Comment by zenomonotti** [comment]
Ich habe versucht, die Dokumente mit der vorgeschlagenen config.toml (["PARAMETER"] 
defaultGeometryTypeValidation="off"
[LOG.test_config.txt](https://github.com/claeis/ili2db/files/5769532/LOG.test_config.txt)
) zu senden.
Mit den Parametern --skipPolygonBuilding --skipGeometryErrors --sqlEnableNull --disableValidation werden die Daten geladen. Diese Parameter können aber bei den von geodienste.ch bereitgestellten Ladeverfahren nicht "eingefügt" werden.
