### ISSUE TITLE
model not found

### ISSUE THREAD

**Issue by kuhnpa** [claeis/ili2db#378]
Für einen Testfall habe ich ein Interlismodell im kantonalen Repository abgelegt (http://models.geo.be.ch/obsolete/test_mgdm_LV95_V1_1.ili) und im 'ilimodels.xml' ergänzt.
Beim Aufruf wird das Modell nicht gefunden.
Den Cache (.ilicache) habe ich bereits geleert.

Weiss jemand warum das Modell nicht gefunden wird?

**Comment by beistehen** [comment]
In der Datei test_mgdm_LV95_V1_1.ili sehe ich zwei Modelle: `test_mgdm_LV95_V1_1` und `test_mgdm_LV95_V1_1_base`. Es ist aber nur eines in ilimodels.xml registriert. Zudem fehlt die Abhängigkeit (dependsOnModel) zwischen den beiden Modellen.

**Comment by edigonzales** [comment]
Was heisst "beim Aufruf" genau? Beim mir stolpert ili2gpkg/ili2c über den Syntaxfehler des fehlenden "AT", wenn ich z.B.
```
java -jar /Users/stefan/apps/ili2gpkg-4.4.5/ili2gpkg-4.4.5.jar --dbfile fubar.gpkg --models test_mgdm_LV95_V1_1 --schemaimport
```
ausführe:

```
Info: ilifile </Users/stefan/.ilicache/models.geo.be.ch/obsolete/test_mgdm_LV95_V1_1.ili>
Error: /Users/stefan/.ilicache/models.geo.be.ch/obsolete/test_mgdm_LV95_V1_1.ili:4:expecting "AT", found 'VERSION'
Error: /Users/stefan/.ilicache/models.geo.be.ch/obsolete/test_mgdm_LV95_V1_1.ili:85:expecting "AT", found 'VERSION'
```

**Comment by edigonzales** [comment]
Ganz praktisch ist: `java -jar /Users/stefan/apps/ili2c-5.1.5/ili2c.jar --check-repo-ilis http://models.geo.be.ch/`

**Comment by kuhnpa** [comment]
Offenbar habe ich so ziemlich alles vergessen, was ich noch hätte anpassen müssen. Danke für die hilfreichen Tipps.
"Aufruf" heisst Kommandozeile via Python-Methode.
ili2c kannte ich so nicht. Ist total praktisch. Merci.

**Comment by kuhnpa** [comment]
Nun hat es geklappt und das Repo ist auch ordentlich aufgeräumt.
