### ISSUE TITLE
ili2pg primarykey creation

### ISSUE THREAD

**Issue by leader80** [claeis/ili2db#38]
Hi, 
is it possible to change the primarykey creation to <class>_id instead of T_id?

thanks
G

**Comment by edigonzales** [comment]
Take a  look at the `--t_id_Name` option:  "change name of t_id column (T_Id)"

**Comment by leader80** [comment]
@edigonzales I tried the option but is static for all the tables and I would like some dynamic key, for example if the class is Police the key should be police_id, in the same schema I would like that the class building has id building_id and not police_id.

thanks
G

**Comment by leader80** [comment]
this happens if I use: --t_id_Name class_Id

![err](https://cloud.githubusercontent.com/assets/73665/22098985/a85ce188-de29-11e6-8df4-c664748a7ecd.png)

**Comment by edigonzales** [comment]
Just out of curiosity: why would you need this?

**Comment by leader80** [comment]
good question, we are just trying to figure out the best way to define the FK.
Usually for the PK of an entity we just use id and then the FK becomes table_id.
