### ISSUE TITLE
[ili2h2gis] missing schema support

### ISSUE THREAD

**Issue by edigonzales** [claeis/ili2db#383]
`--dbschema: unknown option`

**Comment by claeis** [comment]
could not find sql grammar for CREATE SCHEMA at http://www.h2database.com/html/grammar.html

**Comment by edigonzales** [comment]
http://www.h2database.com/html/features.html -> SQL Support -> "Support for multiple schemas, information schema".

Seems to work: `CREATE SCHEMA FUBAR;`

**Comment by claeis** [comment]
https://www.h2database.com/html/commands.html#create_schema
