### ISSUE TITLE
Error: illegal value null

### ISSUE THREAD

**Issue by TI-CCGEO** [claeis/ili2db#388]
Hi,

By exporting with ili2pg 4.4.1 we have following error message:

«Error: illegal value null for Bemerkungen»

Effectively the problem are two single quote (‘’) in some records, but validation only says error without specify row or tid.

Tobia

[export_284053_.log](https://github.com/claeis/ili2db/files/6083030/export_284053_.log)

**Comment by edigonzales** [comment]
Can you export the data with `--disableValidation` and share the data?

**Comment by edigonzales** [comment]
If this does not work: what is exactly the value of the attribute in the database?

**Comment by TI-CCGEO** [comment]
The exact value is a double single quote (''), not escaped. Attribute datatype is of normal TEXT type.
Exporting with --disableValidation returns an uncompleted record (the attribute simply is not exported).

By removing the double single quote from the attribute or by escaping it (\'\') export and validation are successful.

**Comment by claeis** [comment]
Can not reproduce (single and double quites work fine). See new/modified testcase.

**Comment by olivierdalang** [comment]
Here this happens with empty strings (not NULLs, but strings of length 0).

This happens even if `--disableValidation` is provided (an worth noting, the concerned fields are not mandatory).

**Comment by claeis** [comment]
a detailed log (with --trace) would really helped me a lot
