### ISSUE TITLE
[ili2gpkg] create spatial index

### ISSUE THREAD

**Issue by edigonzales** [claeis/ili2db#391]
Spatial Index wird zur Zeit nicht erstellt.

Siehe http://www.geopackage.org/spec120/#extension_rtree und beiliegendes Beispiel mit QGIS (ogr) erzeugt auf der Bodenbedeckungs-Tabelle.

[2421.gpkg.zip](https://github.com/claeis/ili2db/files/6135071/2421.gpkg.zip)

**Comment by claeis** [comment]
DDL für GPKG ist in in https://github.com/claeis/ehisqlgen/blob/master/src/ch/ehi/sqlgen/generator_impl/jdbc/GeneratorGeoPackage.java

**Comment by hpfammatter** [comment]
Hallo und Guten Tag

Ich würde mich freuen, die Interlis-Tools um eine Funktion zur Erstellung eines Spatial Index für GeoPackage-Datenbanken erweitern zu können.

**Implementierung: Index**

Die SQL-Statements zur Erstellung eines rtree Spatial Index sind innerhalb der Klasse `GeneratorGeoPackage` (https://github.com/hpfammatter/ehisqlgen/commit/75cfe0244c10bac1a7dc7a1e3c769c445ce0de4b) der dependency `ehisqlgen` implementiert (siehe Kommentar https://github.com/claeis/ili2db/issues/391#issuecomment-898261491).

Die Statements sind an der Stelle implementiert, an der das Programm durch die columns geht, für die ein Index erstellt werden soll und testet, ob es sich bei einer column um eine geometry column handelt. 

Es wird zusätzlich getestet, ob die aktuelle Tabelle einen Primärschlüssel hat, weil man für die Erstellung eines rtree Spatial Index einen Primärschlüssel benötigt. 

Create-Script und Drop-Script für die Optionen `--createscript` und `--dropscript` sollten korrekt erstellt werden.

**Implementierung: SQL-Funktionen**

Nun ist es leider so, dass ein rtree Spatial Index die SQL-Funktionen `ST_IsEmpty`, `ST_MinX`, `ST_MaxX`, `ST_MinY` und `ST_MaxY` benötigt. Diese Funktionen werden beim auffüllen des Index benötigt, und auch wenn man inserts, updates oder deletes auf einer Tabelle mit Index ausführt (die Funktionen werden dann "getriggert").

Die Funktionen sind in der Klasse `GpkgMapping` (https://github.com/hpfammatter/ili2db/commit/686ec65bc07936d632e959f113f2e39245d1c62b) des Projekts implementiert und werden geladen, wenn die Option `--createGeomIdx=true` gesetzt ist. 

**Optionen auf der Kommandozeile**

Der rtree Spatial Index wird nur beim `--schemaimport` erstellt. Zum Erstellen eines Index muss `--createGeomIdx=true` beim `--schemaimport` gesetzt sein.

Die beim `--schemaimport` auf der Kommandozeile verwendeten Optionen werden von `ili2db` in der GeoPackage-Datenbank gespeichert und geladen, wenn die Datenbank erneut geöffnet wird. Dieses Verhalten garantiert, dass bei einem Geopackage mit rtree Spatial Index die SQL-Funktionen erneut geladen werden, wenn die Datenbank erneut geöffnet wird.

--

Im Prinzip sind es nur zwei Änderungen, die Implementierung der SQL-Statements zur Erstellung des Spatial Index, sowie die Implementierung der SQL-Funktionen, die vom Spatial Index benötigt werden. Die Änderung der Programmlogik sollte minimal sein.

Viele Grüsse
Hannes 

pfammatter@puzzle.ch

**Comment by claeis** [comment]
@hpfammatter bitte je als github pull request, damit ich es via github kommentieren/reviewen kann

**Comment by hpfammatter** [comment]
Sorry, ich habe mir gedacht ich warte gerade auf eine Antwort, und erstelle nachher die pull requests. Die pull requests sollten jetzt erstellt sein, ich kann dann gerade die Kommentare im Review bearbeiten.
