### ISSUE TITLE
implement --metaConfig

### ISSUE THREAD

**Issue by claeis** [claeis/ili2db#392]
Aufruf:

    ili2db --metaConfig ilidata:metconfigId --schemaimport --db....
    ili2db --metaConfig ilidata:metconfigId --import --db....

Import ohne Datei Argument importiert die im Metaconfig-File definierten Referenz-/Katalogdaten.

Um eigene Daten zu importieren:

    ili2db --metaConfig ilidata:metconfigId --import --db....  data.xtf

Um die Daten zu exportieren:

    ili2db --metaConfig ilidata:metconfigId --export --db....  data.xtf

Oder lokales Metaconfig-File:

    ili2db --metaConfig localfile.ini --import --db....  data.xtf

```
[ch.ehi.ili2db]
defaultSrsCode = 2056
smart2Inheritance = true
strokeArcs = false
importTid = true
iliMetaAttrs = ilidata:that_toml_file_id
```

Die Einträge wenn immer möglich so benennen, wie die Option heisst.

Im Aufruf evtl. vorhandene Kommandozeilenargumente übersteuern die Angaben im Metaconfig-File (benötigt #393).

Siehe auch claeis/iox-ili#91

**Comment by signedav** [comment]
Ich nehme an, dass Metaattribute-Files (toml), prescripts und postscripts auch über eine ilidata-id referenziert werden können, richtg?

```
[ch.ehi.ili2db]
iliMetaAttrs = ilidata:that_toml_file_id
```

**Comment by claeis** [comment]
Ja

**Comment by signedav** [comment]
Sofern ich die Implementierung hier #418 richtig interpretiere, dann müsste man einen Inheritance-Parameter folgendermassen übersteuern, richtig?

`--smart1Inheritance=false --smart2Inheritance=true`

Ähnlich mit `--createEnumTabsWithId` und `--createEnumColAsItfCode`.

Gibt es eine Liste solcher "sich ausschliessender" Parameter bzw. Parameter, die dasselbe Setting ansteuern?

**Comment by claeis** [comment]
> Gibt es eine Liste solcher "sich ausschliessender" Parameter bzw. Parameter, die dasselbe Setting ansteuern?

nein
