### ISSUE TITLE
fix case sensitivity for file names

### ISSUE THREAD

**Issue by SinimRocky** [claeis/ili2db#398]
Wenn man in der Konsole beim Schemaimport (zumindest bei ili2fgdb und ili2gpkg) die .ili Datei, welche bei mir automatisch zu .Ili geändert wurde (grosses "i"), mit der Endung ".Ili" angibt, dann findet das Programm die Datei nicht und man erhält die Fehlermeldung "no models given".

**Comment by claeis** [comment]
Not a ili2db issue.

**Comment by sfkeller** [comment]
> Not a ili2db issue.

Dann gehört das aber in die Doku. von ili2db bzw. ilid2...

Kannst du evt. hier so ein erster Doku.-Draft eröffnen? (Wohl https://github.com/claeis/ili2db/tree/master/docs ).

Möchte es dir überlassen, ob du eine allgemeine zu ili2db willst oder je eine pro ili2... Tool haben willst.

**Comment by beistehen** [comment]
Kann dies gerne ins ili2db-Kochbuch einfliessen lassen, das sich in Entstehung befindet.
cc @aviquerat
