### ISSUE TITLE
ili2pg crashes with VD cadastral data

### ISSUE THREAD

**Issue by 3nids** [claeis/ili2db#4]
With cadastral data in Interlis 1 from the canton VD, I get this crash:

```
Error: failed to build polygons of MD01MOCH24MN95F.Points_fixesCategorie3.Mise_a_jourPFP3.Perimetre
Error:   no polygon
Info: Basket MD01MOCH24MN95F.Couverture_du_sol(oid itf3)...
java.lang.NullPointerException
```

Can you provide any information on this?
Thank you very much.

**Comment by edigonzales** [comment]
Are you allowed to share the data?

**Comment by edigonzales** [comment]
btw: can you please show the output with `--trace` option?

**Comment by 3nids** [comment]
Last lines are 
```java.lang.NullPointerException
    ch.interlis.iom_j.itf.impl.LineSet.buildBoundaries(LineSet.java:51)
    ch.interlis.iom_j.itf.impl.ItfSurfaceLinetable2Polygon.buildSurfaces(ItfSurfaceLinetable2Polygon.java:228)
    ch.interlis.iom_j.itf.ItfReader2.read(ItfReader2.java:313)
    ch.ehi.ili2db.fromxtf.TransferFromXtf.doit(TransferFromXtf.java:389)
    ch.ehi.ili2db.base.Ili2db.transferFromXtf(Ili2db.java:1786)
    ch.ehi.ili2db.base.Ili2db.runUpdate(Ili2db.java:598)
    ch.ehi.ili2db.base.Ili2db.runImport(Ili2db.java:195)
    ch.ehi.ili2db.base.Ili2db.run(Ili2db.java:175)
    ch.ehi.ili2db.AbstractMain.domain(AbstractMain.java:367)
    ch.ehi.ili2pg.PgMain.main(PgMain.java:71)
```

more lines here http://pastebin.com/bSLNztHW

sending you by mail some data.

Thanks a lot for taking time at looking at this!

**Comment by claeis** [comment]
which program version do you use?
and what are the first lines of the trace output?

**Comment by 3nids** [comment]
version 3.4.0

here is the full trace https://gist.github.com/3nids/7e43ac80d03a68b6047317eb7e8e0076

**Comment by edigonzales** [comment]
Take a look at line number 271540 of your transfer file:

`OBJE 98624113 98624113`
`ELIN`

A line w/o any points.

**Comment by edigonzales** [comment]
`IomObject polyline=lines.get(line_tid).getattrobj(helperTableGeomAttrName, 0);`

`polyline` is `null` in this case and `getattrobj()` cannot be called (line 58).

**Comment by edigonzales** [comment]
After removing this empty object I get other errors:

`Error: MD01MOCH24MN95F.Couverture_du_sol.Mise_a_jourCS.Perimetre: multipolygon (tid 81022754)`

Multiple polygons from `Mise_a_jourCS.Perimetre` are referencing the same object from `Mise_a_jourCS` which is not allowed (?).

**Comment by 3nids** [comment]
Thanks a lot for digging in!

Well, this bring to the question: is my data compliant with the official model? These are official data from the canton and they are supposed to go through the checkers if I'm right. What would you suggest to do?

**Comment by edigonzales** [comment]
No, it isn't.

You can check the cadastral surveying data with the official check service: [http://www.cadastre.ch/checkservice](http://www.cadastre.ch/checkservice) 

I think they have to activate your email adress (or at least they used to some time ago). I uploaded your data and attached the output.

[vd-1_output.zip](https://github.com/claeis/ili2db/files/541653/vd-1_output.zip)

The non-model-compliant errors are the ones starting with "INT" (as far as I remember). Others can be cadastral surveying specific checks/errors.

The cantons are encouraged (by the Federal Directorate of Cadastral Surveying) to reduce these kind of errors. So I guess you should ask the guys from your cadastral suryeing department to fix these errors.

**Comment by 3nids** [comment]
Thanks again, things are a bit clearer to me now.
So, basically, there is no chance for me to use ili2pg with this dataset?
(I just tried with data from Wallis, and got some troubles too).

**Comment by edigonzales** [comment]
No. At least not at the moment. For now ili2pg can handle missing mandatory attributes. And I don't think that it should be too generous with non-compliant data. Of course there is always a gray area but what is the point in exchanging INTERLIS when you just receive (technical) rubbish... Which is difficult to handle for the interface software / database etc. etc. 

You just have chosen the wrong cantons. Enough said... :-)

**Comment by claeis** [comment]
--skipPolygonBuilding might help in this case

**Comment by edigonzales** [comment]
I love `--skipPolygonBuilding` for debugging the data since you can often import the data into the database. You lose the polygons and you end up with linestrings.

**Comment by 3nids** [comment]
I am trying with canton specific format now....
I am getting this error:
```
Info: read(): Bord_de_plan... (ItfReader.java:203)
Info: read(): Description_plan... (ItfReader.java:203)
Info: read(): PosDescription_plan... (ItfReader.java:203)
Info: read(): Indication_coordonnees... (ItfReader.java:203)
Info: read(): PosIndication_coord... (ItfReader.java:203)
Info: read(): Element_lineaire... (ItfReader.java:203)
Info: read(): Ligne_coordonnees... (ItfReader.java:203)
Info: read(): Surface_representation... (ItfReader.java:203)
Info: read(): Surface_representation_Geometrie... (ItfReader.java:203)
Info: read(): SymboleBord_de_plan... (ItfReader.java:203)
Info: read(): Croix_filet... (ItfReader.java:203)
Info: writeImportBasketStat(): INSERT INTO vaud.T_ILI2DB_IMPORT_BASKET(T_Id, import, basket, objectCount, start_t_id, end_t_id) VALUES (?,?,?,?,?,?) (TransferFromXtf.java:1364)
Info: getSeqCount(): SELECT nextval('vaud.t_ili2db_seq') (PgSequenceBasedIdGen.java:161)
Error: failed to read data file
Error:   dangling references
Error:       ch.ehi.ili2db.fromxtf.TransferFromXtf.doit(TransferFromXtf.java:399)
Error:       ch.ehi.ili2db.base.Ili2db.transferFromXtf(Ili2db.java:1786)
Error:       ch.ehi.ili2db.base.Ili2db.runUpdate(Ili2db.java:598)
Error:       ch.ehi.ili2db.base.Ili2db.runImport(Ili2db.java:195)
Error:       ch.ehi.ili2db.base.Ili2db.run(Ili2db.java:175)
Error:       ch.ehi.ili2db.AbstractMain.domain(AbstractMain.java:367)
Error:       ch.ehi.ili2pg.PgMain.main(PgMain.java:71)
...import failed
    ch.ehi.ili2db.base.Ili2db.runUpdate(Ili2db.java:621)
    ch.ehi.ili2db.base.Ili2db.runImport(Ili2db.java:195)
    ch.ehi.ili2db.base.Ili2db.run(Ili2db.java:175)
    ch.ehi.ili2db.AbstractMain.domain(AbstractMain.java:367)
    ch.ehi.ili2pg.PgMain.main(PgMain.java:71)
```

From this, can you tell me if it's still related to data problem or it might be an ili2pg issue?
Thanks again!

**Comment by claeis** [comment]
There was an error in ili2pg that lead to the "dangling references" message, which was fixed in ili2pg-3.4.1
But it might be still a data problem.
Please use www.interlis2.ch for support questions.

**Comment by 3nids** [comment]
Already on 3.4.1.
Will switch for the support, thanks for your reply.

**Comment by claeis** [comment]
Which version of ili2fme and iox-ili? (see the log in FME)

**Comment by ponceta** [comment]
ili2fme-6.1.5-20161102
ili2c-4.5.27-20161102
java.version 1.8.0_161
