### ISSUE TITLE
Which databases are supported by ili2db?

### ISSUE THREAD

**Issue by nicpitsch** [claeis/ili2db#400]
## Download links

The readme doc of this repo contains download links for PostGIS and GeoPackage only. [INTERLIS Downloads](https://www.interlis.ch/downloads/ili2db) has additionally *ili2fgdb*. I would propose to actualize the link(s) under [*Download ili2db*](https://github.com/claeis/ili2db#download-ili2db) accordingly.

## Further repos/databases supported?

The repo here has further *ili2h2gis*, *ili2mssql*, *ili2mysql* and *ili2ora* folders. 

- Are those databases supported too, or will they be supported in future? 
- What is it particularly about  about *ili2ora* in especially? 
- If some are supported, where are the actual download packages?

**Comment by claeis** [comment]
Releases are here https://downloads.interlis.ch/

**Comment by claeis** [comment]
Supported are: ili2fgdb, ili2gpkg, ili2h2gis, ili2mssql, ili2mysql, ili2ora, ili2pg

**Comment by nicpitsch** [comment]
> Supported are: ili2fgdb, ili2gpkg, ili2h2gis, ili2mssql, ili2mysql, ili2ora, ili2pg

Fantastic, all of them officially supported, means long-term maintained?

**Comment by claeis** [comment]
It's a comunity project. Versions/funtions are supported, as needed. (No (real) need -> no resources -> no support).
