### ISSUE TITLE
[feature request] Add a --increaseMaxLength (or similar) argument 

### ISSUE THREAD

**Issue by olivierdalang** [claeis/ili2db#402]
Currently, postgres field length (such as TEXT(20)) act as hard constraints on data, meaning you cannot copy invalid data into the ili2pg schema without truncating, which obviously can be quite bad for certain types of values.

In the same spirit of `--sqlEnableNull`, `--createXxxChecks` etc., we would like to still be able to copy the complete data, and get a working XTF file (containing invalid data).

Does it make sense ? The same applies for other types (e.g. numeric). For each case, we could take the database provider's highest supported length.

**Comment by claeis** [comment]
:+1:

**Comment by claeis** [comment]
What about a more extrem/general mode: create _all_ attributes as text columns?

**Comment by olivierdalang** [comment]
> What about a more extrem/general mode: create _all_ attributes as text columns?

I think that would work for us. I think this makes sense for attributes that get serialized as simple XML elements which in the end is text anyway. Unsure about geometry columns though.

**Comment by claeis** [comment]
yes, all with simpleContent in XML.
