### ISSUE TITLE
--nameLang argument is not honored on export

### ISSUE THREAD

**Issue by olivierdalang** [claeis/ili2db#403]
Currently, the `--nameLang` argument has no effect on export.

Not really sure if this is a feature request or a bug report, but I would have expected this to output translated XTFs if the requested language is available in the modeldir.

Without this, the only way to output translated XTFs would be to create a translated schema, which in turn requires to translate all the pipeline (SQL scripts, software configuration, etc.), which of course would be completely unmaintainable.

Thanks !

**Comment by claeis** [comment]
``--nameLang`` is a --schemaimport option; it controls the mapping of ili-names to sql-names

To export into another/translated model, use ``--exportModels``

**Comment by sjib** [comment]
@claeis Should it not be `--export --models MODELNAME` 

https://github.com/claeis/ili2db/blob/master/docs/ili2db.rst#fall-32

With `--exportModels MODELNAME` I get an error: **Model not found**

**Comment by claeis** [comment]
``--exportModels`` is *not* a replacement for ``--models``! It's used as an *additional* option to control the way, that the data is export (and can also be used to export data according to a base model). It's not used to select the data, that gets exported.

``--models`` (or ``--topics`` or ``--baskets`` or ``--dataset``) with ``--export`` is used to select the data that gets exported.

**Comment by sjib** [comment]
So is this a valid call?

`java -jar ili2pg-4.5.0.jar --modeldir "C:\Daten\Firma\2_Softwareentwicklung\20_DABASE\203_QEP\vsakek\5617_E\ili2pg-4.5.0\"  --export --models VSA_KEK_2019_LV95 --exportModels VSA_IVI_2019_LV95  --skipReferenceErrors --sqlEnableNull --createEnumTabs --createFk  --noSmartMapping --defaultSrsAuth EPSG --defaultSrsCode 2056 --dbhost localhost --dbport 5432 --dbdatabase testdata_vsa_kek_2019 --dbschema vsa_kek_2019_2_d_446 --dbusr postgres --dbpwd ***   --log exportdaten_testdata_vsa_kek_2019_channel_damage_8486_f_exportmodels.log --trace "C:\Daten\Firma\2_Softwareentwicklung\20_DABASE\203_QEP\vsakek\5617_E\ili2pg-4.5.0\testdata_vsa_kek_2019_channel_damage_8486_f_exportmodels.xtf"`

`--models VSA_KEK_2019_LV95` is the German model name
`--exportModels VSA_IVI_2019_LV95` is the corresponding French Modell name 

MODEL VSA_IVI_2019_LV95 (fr) AT "http://www.vsa.ch/models"
  VERSION "06.05.2021" TRANSLATION OF VSA_KEK_2019_LV95 [ "16.04.2021" ] =

**Comment by claeis** [comment]
Yes (as far as I see...)

**Comment by sjib** [comment]
Thanks. Any hint why it cannot find the French model and crashes? All models are in the same model folder.

`...
Info: data <C:\Daten\Firma\2_Softwareentwicklung\20_DABASE\203_QEP\vsakek\5617_E\ili2pg-4.5.0\testdata_vsa_kek_2019_channel_damage_8486_f_exportmodels.xtf>
Error: unknown model <VSA_IVI_2019_LV95>
Error:     ch.ehi.ili2db.base.Ili2db.getModels(Ili2db.java:2518)
Error:     ch.ehi.ili2db.base.Ili2db.buildModelList(Ili2db.java:2392)
Error:     ch.ehi.ili2db.base.Ili2db.transferToXtf(Ili2db.java:2367)
Error:     ch.ehi.ili2db.base.Ili2db.runExport(Ili2db.java:1781)
Error:     ch.ehi.ili2db.base.Ili2db.run(Ili2db.java:219)
Error:     ch.ehi.ili2db.AbstractMain.domain(AbstractMain.java:567)
Error:     ch.ehi.ili2pg.PgMain.main(PgMain.java:70)`

[testdata_vsa_kek_2019_channel_damage_8486_f_exportmodels.zip](https://github.com/claeis/ili2db/files/6442818/testdata_vsa_kek_2019_channel_damage_8486_f_exportmodels.zip)

**Comment by claeis** [comment]
How did you do the ``--schemaimport``? It schould include the translated model (``--models VSA_IVI_2019_LV95;VSA_KEK_2019_LV95`` )
