### ISSUE TITLE
ili2pg-4.5.0.zip not downloadable

### ISSUE THREAD

**Issue by vvmruder** [claeis/ili2db#404]
I found the file under the following link not to be downloadable:
https://downloads.interlis.ch/ili2pg/ili2pg-4.5.0.zip

![Selection_011](https://user-images.githubusercontent.com/3714179/117156748-4d777d00-adbe-11eb-962b-06ed7ea66ce4.png)

Version 4.4.6 works:
https://downloads.interlis.ch/ili2pg/ili2pg-4.4.6.zip

**Comment by sjib** [comment]
Seems to be fixed - I was able to download now.

**Comment by vvmruder** [comment]
True, it works now
