### ISSUE TITLE
Data not completly translated to other language (German -> French)

### ISSUE THREAD

**Issue by sjib** [claeis/ili2db#405]
I tried to translate data with ili2pg 4.4.6 and 4.5.0 (but no difference) that I imported with `--import` in postgres using` --export FRENCHMODELNAME `

All German and French ili Files are in the same model directory.

Data export is generating the following kind of errors (see attached log for more details). 
`Error: line 0: VSA_IVI_2019_LV95.IVI.EXAMEN: tid fk11abk6w70lohup: Attribute METAATTRIBUTS has wrong number of values
Error: line 0: VSA_IVI_2019_LV95.IVI.EXAMEN: tid fk11abk6w70lohup: unknown property <Metaattribute>
Info: VSA_KEK_2019_LV95.KEK.Kanalschaden...
Info: dumpObjHelper(): SELECT r0.T_Id, r0.T_Ili_Tid,r1.obj_id,r2.anmerkung,r2.ansichtsparameter,r2.einzelschadenklasse,r2.streckenschaden,r2.verbindung,r2.videozaehlerstand,r2.untersuchungref,r3.distanz,r3.kanalschadencode,r3.quantifizierung1,r3.quantifizierung2,r3.schadenlageanfang,r3.schadenlageende FROM vsa_kek_2019_2_d_446.baseclass r0 LEFT JOIN vsa_kek_2019_2_d_446.sia405_baseclass r1 ON r0.T_Id=r1.T_Id LEFT JOIN vsa_kek_2019_2_d_446.schaden r2 ON r0.T_Id=r2.T_Id LEFT JOIN vsa_kek_2019_2_d_446.kanalschaden r3 ON r0.T_Id=r3.T_Id WHERE r0.T_Type='kanalschaden' (TransferToXtf.java:1091)
Info: dumpStructs(): SELECT r0.T_Id, r0.T_Type, r0.T_Seq FROM (SELECT r1.T_Id,'metaattribute' AS T_Type,r1.T_Seq FROM vsa_kek_2019_2_d_446.metaattribute r1 WHERE r1.sia405_baseclass_metaattribute=7 ) r0 ORDER BY T_Seq ASC (TransferToXtf.java:888)
Info: dumpObjHelper(): SELECT r0.T_Id, r0.sia405_baseclass_metaattribute, r0.T_Seq,r0.datenherr,r0.datenlieferant,r0.letzte_aenderung FROM vsa_kek_2019_2_d_446.metaattribute r0 WHERE r0.sia405_baseclass_metaattribute=? ORDER BY r0.T_Seq ASC (TransferToXtf.java:1091)`

Final error in second validation (I don't know whether this is a follow up)
`Info: second validation pass...
Info: validate unique constraint SIA405_Base_LV95.SIA405_BaseClass.Constraint1...
Info: validate multiplicity of role SIA405_ABWASSER_2015_LV95.SIA405_Abwasser.Abwasserbauwerk_BetreiberAssoc.Abwasserbauwerk_BetreiberAssocRef...
Info: validate multiplicity of role SIA405_ABWASSER_2015_LV95.SIA405_Abwasser.Organisation_Teil_vonAssoc.Organisation_Teil_vonAssocRef...
Info: validate multiplicity of role SIA405_ABWASSER_2015_LV95.SIA405_Abwasser.Abwasserbauwerk_EigentuemerAssoc.Abwasserbauwerk_EigentuemerAssocRef...
Info: validate multiplicity of role SIA405_ABWASSER_2015_LV95.SIA405_Abwasser.Organisation_Teil_vonAssoc.Teil_vonRef...
Info: validate multiplicity of role VSA_KEK_2019_LV95.KEK.Erhaltungsereignis_Ausfuehrende_FirmaAssoc.Erhaltungsereignis_Ausfuehrende_FirmaAssocRef...
Info: validate unique constraint SIA405_Base_f_LV95.SIA405_BaseClass.Constraint1...
Info: validate target of role VSA_IVI_2019_LV95.IVI.FICHIER_SUPPORT_DONNEESAssoc.SUPPORT_DONNEESRef...
Info: validate multiplicity of role VSA_IVI_2019_LV95.IVI.FICHIER_SUPPORT_DONNEESAssoc.SUPPORT_DONNEESRef...
Info: validate target of role VSA_IVI_2019_LV95.IVI.EVENEMENT_MAINTENANCE_BUREAU_EXECUTANTAssoc.BUREAU_EXECUTANTRef...
Error: line 0: VSA_IVI_2019_LV95.IVI.EXAMEN: tid fk11abk6w70lohup: wrong class SIA405_ABWASSER_2015_LV95.SIA405_Abwasser.Organisation of target object ch080qwzPR000017 for role VSA_IVI_2019_LV95.IVI.EVENEMENT_MAINTENANCE_BUREAU_EXECUTANTAssoc.BUREAU_EXECUTANTRef.
Info: validate target of role VSA_IVI_2019_LV95.IVI.EVENEMENT_MAINTENANCE_OUVRAGE_RESEAU_ASAssoc.OUVRAGE_RESEAU_ASRef...
Info: validate target of role VSA_IVI_2019_LV95.IVI.EXAMEN_POINT_TRONCONAssoc.POINT_TRONCONRef...
Info: validate multiplicity of role VSA_IVI_2019_LV95.IVI.EVENEMENT_MAINTENANCE_OUVRAGE_RESEAU_ASAssoc.OUVRAGE_RESEAU_ASRef...
Info: validate multiplicity of role VSA_IVI_2019_LV95.IVI.EVENEMENT_MAINTENANCE_BUREAU_EXECUTANTAssoc.BUREAU_EXECUTANTRef...
Info: validate multiplicity of role VSA_IVI_2019_LV95.IVI.EXAMEN_POINT_TRONCONAssoc.POINT_TRONCONRef...
Info: validate multiplicity of role VSA_IVI_2019_LV95.IVI.DOMMAGE_EXAMENAssoc.DOMMAGE_EXAMENAssocRef...
Info: validate target of role VSA_IVI_2019_LV95.IVI.DOMMAGE_EXAMENAssoc.EXAMENRef...
Info: validate multiplicity of role VSA_IVI_2019_LV95.IVI.DOMMAGE_EXAMENAssoc.EXAMENRef...
Info: validate multiplicity of role VSA_IVI_2019_LV95.IVI.FICHIER_SUPPORT_DONNEESAssoc.FICHIER_SUPPORT_DONNEESAssocRef...
Error: ...export failed
Error:     ch.ehi.ili2db.base.Ili2db.runExport(Ili2db.java:1783)
Error:     ch.ehi.ili2db.base.Ili2db.run(Ili2db.java:219)
Error:     ch.ehi.ili2db.AbstractMain.domain(AbstractMain.java:567)
Error:     ch.ehi.ili2pg.PgMain.main(PgMain.java:70)
`

A translated data file is anyway generated, but strangely the class Organisation is not translated to French and in all other classes the Metaattribute / METAATTRIBUTS are missing. 

![zone_e_vergleich_de_fr_xtf_class_organisation_not_translated](https://user-images.githubusercontent.com/1265865/117451419-cbfd2780-af42-11eb-8e03-5e220d188127.jpg)
CLASS organisation - not translated in the French export xtf

![zone_e_vergleich_de_fr_xtf_missing_metaattributes_in_class_examen](https://user-images.githubusercontent.com/1265865/117451429-d0294500-af42-11eb-9cbb-4e607f7fed8c.jpg)

![zone_e_vergleich_de_fr_xtf_missing_metaattributes_in_class_fichier](https://user-images.githubusercontent.com/1265865/117451434-d28b9f00-af42-11eb-8532-fba94684ecab.jpg)
Missing metatttributes in all other classes

Any hint why this happens? Do we push the limits of ili2pg here?

All data, models and scripts here:
[i2_exportdaten_vsa_kek_2019_2_f_446_testdata_vsa_kek_2019_channel_damage_8486.zip](https://github.com/claeis/ili2db/files/6441632/i2_exportdaten_vsa_kek_2019_2_f_446_testdata_vsa_kek_2019_channel_damage_8486.zip)

**Comment by sjib** [comment]
https://github.com/claeis/ili2db/issues/403

**Comment by sjib** [comment]
Based on the comment in #403 I have include German and French model in the --schemaimport statement:
`java -jar ili2pg-4.5.0.jar --modeldir "C:/Daten/Firma/2_Softwareentwicklung/20_DABASE/203_QEP/vsakek/5617_E/ili2pg-4.5.0" --createEnumTxtCol --schemaimport --importTid --sqlEnableNull --createEnumTabs --createFk  --noSmartMapping --defaultSrsAuth EPSG --defaultSrsCode 2056 --dbhost localhost --dbport 5432 --dbdatabase testdata_vsa_kek_2019 --dbschema vsa_kek_2019_2_d_f_450 --dbusr postgres --dbpwd sjib  --log createschema_vsa_kek_2019_2_d_f_450.log --trace --models VSA_IVI_2019_LV95; VSA_KEK_2019_LV95;`

And then imported the data and now reexported:
`java -jar ili2pg-4.5.0.jar --modeldir "C:/Daten/Firma/2_Softwareentwicklung/20_DABASE/203_QEP/vsakek/5617_E/ili2pg-4.5.0" --export --models VSA_IVI_2019_LV95 --exportModels VSA_IVI_2019_LV95 --skipReferenceErrors --sqlEnableNull --createEnumTabs --createFk --noSmartMapping --defaultSrsAuth EPSG --defaultSrsCode 2056 --dbhost localhost --dbport 5432 --dbdatabase testdata_vsa_kek_2019 --dbschema vsa_kek_2019_2_d_f_450 --dbusr postgres --dbpwd sjib --log exportdaten_testdata_vsa_kek_2019_2_d_f_450_vsa_kek_2019_channel_damage_8486_f_exportmodels_V2.log --trace testdata_vsa_kek_2019_channel_damage_8486_f_exportmodels_V2.xtf`

I still get the same problems of missing translations:
[exportdaten_testdata_vsa_kek_2019_2_d_f_450_vsa_kek_2019_channel_damage_8486_f_exportmodels_V2.zip](https://github.com/claeis/ili2db/files/6466000/exportdaten_testdata_vsa_kek_2019_2_d_f_450_vsa_kek_2019_channel_damage_8486_f_exportmodels_V2.zip)

Could it be that ili2pg does not considers that the German and French Classname are both the same name ? **Organisation - ORGANISATION** (almost the same - ili2pg considers small and capital letters as different?)

![Organisation_d_f_comparison](https://user-images.githubusercontent.com/1265865/117973534-d2b5e100-b32c-11eb-9a8d-ce194c00d4d5.jpg)

And the same thing with **SIA405_BaseClass** - here it is an exact match of the name. Could this be the reason?:
![SIA405_Base_same_name_SIA405_BaseClass](https://user-images.githubusercontent.com/1265865/117973265-73f06780-b32c-11eb-83d7-d3d5d1c1532f.jpg)

The compiler has no problems with that.

**Comment by beistehen** [comment]
I could reproduce the error. _It occurs even when validating the data in the database._
For further analysis I provide a minimal setup an walkthrough below. Minimal input data, models and logfiles are attached at the end of this post.

### generate schema
using the following relevant options:
```
--modeldir <path/to/models>
--schemaimport
--noSmartMapping
--models VSA_IVI_2019_LV95;VSA_KEK_2019_LV95
```
_(VSA_IVI_2019_LV95 is the translated model of VSA_KEK_2019_LV95)_

result: no errors, see `1_schemaimport.log`

### import data
using the following relevant options:
```
--import

```
result: no errors, see `2_dataimport.log`

### validate data in db (focus on the same model VSA_KEK_2019_LV95 as the provided data)
using the following relevant options:
```
--validate
--models `
```
result: no errors, see `3a_validate_kek.log`

### validate data in db (focus on the translated model VSA_IVI_2019_LV95)
using the following relevant options:
```
--validate
--models VSA_IVI_2019_LV95
```
result: errors for every `Metaattribute` structure in the following manner:
```
Info: VSA_KEK_2019_LV95.KEK.Untersuchung...
Info: dumpObjHelper(): SELECT <--snipped--> WHERE r0.T_Type='untersuchung' (TransferToXtf.java:1091)
Info: dumpStructs(): SELECT <--snipped--> WHERE r1.sia405_baseclass_metaattribute=3 ) r0 ORDER BY T_Seq ASC (TransferToXtf.java:888)
Info: dumpObjHelper(): SELECT <--snipped--> WHERE r0.sia405_baseclass_metaattribute=? ORDER BY r0.T_Seq ASC (TransferToXtf.java:1091)
Error: line 0: VSA_IVI_2019_LV95.IVI.EXAMEN: tid fk11abk6w70lohup: Attribute METAATTRIBUTS has wrong number of values
Error: line 0: VSA_IVI_2019_LV95.IVI.EXAMEN: tid fk11abk6w70lohup: unknown property <Metaattribute>
```

see `3b_validate_ivi.log`

[setup#405.zip](https://github.com/claeis/ili2db/files/6513754/setup.405.zip)

@claeis may the cause of this error be an inheritance mix up because abstract `SIA405_BaseClass` is used in model `SIA405_ABWASSER_2015_LV95` as well as in `VSA_KEK_2019_LV95`?

**Comment by sjib** [comment]
I did the following checks: 

1. I adapted the models so that there is no duplicate between German and French: BaseClass -> new BaseClass_f in French, SIA405_BaseClass -> new SIA405_BaseClass_f in French
2. I have renamde ORGANISATION to ORGANISATION2 in French - to eliminate same name as German (just different Cases): Organisation

So no change in Errorlogs. So these issues cannot be the reason.

It looks like STRUCTURE is not supported in the translation process with ili2pg450 yet.

@claeis Can you give some feedback on this - we would need this functionality in an NGDI project.
[exportdaten_testdata_vsa_kek_2019_2_d_f_450_vsa_kek_2019_channel_damage_8486_f_exportmodels_V3.zip](https://github.com/claeis/ili2db/files/6869757/exportdaten_testdata_vsa_kek_2019_2_d_f_450_vsa_kek_2019_channel_damage_8486_f_exportmodels_V3.zip)

**Comment by claeis** [comment]
I'm working on it

**Comment by claeis** [comment]
please retest with the latest 4.5.1 SNAPSHOT

**Comment by claeis** [comment]
my tests worked 
[kek_data_stub-out-ivi.zip](https://github.com/claeis/ili2db/files/6908686/kek_data_stub-out-ivi.zip)
