### ISSUE TITLE
ili2pg fails for linear referenced data

### ISSUE THREAD

**Issue by msuetterlin** [claeis/ili2db#407]
The import of data with linear referencing for the MGDM Revitalisierung Fliessgewässer ([ili](http://models.geo.admin.ch/BAFU/Revitalisierung_Fliessgewaesser_V1_1.ili)) results in the following error message:
`Error: unknown referenced object WasserBase_LV95_V1_1.Gewaesser.Gewaesserlauf TID 6213 referenced from Revitalisierung_Fliessgewaesser_V1_1.RevitOeko.AbschOekomorph TID 13759`
`...`
`Error: failed to transfer data from file to db`
`Error:   dangling references`
`...replace failed`

The import of the same data with planar referencing, however, works without any problems. 

Sample data (linear referenced):
[PlanRevitEaux_VS_Linear_SU.zip](https://github.com/claeis/ili2db/files/6694437/PlanRevitEaux_VS_Linear_SU.zip)

**Comment by edigonzales** [comment]
Vielleicht blöde Frage. Aber liegt es nicht "nur" daran, dass es das Objekt mit der TID= 6213 in der DB nicht gibt? Im Gegensatz zu "planar", hat die die lineare Struktur eine (externe) Referenz: `Gewaesser : MANDATORY REFERENCE TO (EXTERNAL) Gewaesserlauf`.

**Comment by msuetterlin** [comment]
Die Tabelle Gewasserlauf wird erstellt. aber bleibt leer. Während dies für die planaren Daten keine Rolle spielt, fehlt für die linearen Daten die Referenz. Da besteht also vermutlich eine Zusammenhang. Ich verstehe jedoch nicht, warum die Referenz resp. der Fremdschlüssel nicht abgefüllt wird.

**Comment by edigonzales** [comment]
Der Datensatz verweist auf den Gewässerverlauf mit TID=6213. Dieses Objekt gibt es aber nicht in dem XTF. Was meinst du mit "Ich verstehe jedoch nicht, warum die Referenz resp. der Fremdschlüssel nicht abgefüllt wird."

**Comment by msuetterlin** [comment]
Im xtf exisitiert ein Objekt mit TID=6231 
![grafik](https://user-images.githubusercontent.com/85698006/122963170-54664900-d386-11eb-9ecc-8586a2d0b6be.png)
Dies scheint aber tatsächlich nicht für alle bei der Fehlermeldung aufgelisteten TIDs der Fall zu sein (https://integration.geodienste.ch/data_agg/import_tasks/9276/logs).

Alle der in der Fehlermeldung nach "WasserBase_LV95_V1_1.Gewaesser.Gewaesserlauf " aufgelisteten TIDs sind jedoch im xtf als REF="..:" aufgeführt.
Ist nicht die "Nummer" nach REF der Verweis auf den Gewässerlauf?

Was bedeutet das jetzt? Gehst du davon aus, dass in den Daten (xtf) die notwendigen Angaben für die Referenzierung fehlen?

_(Entschuldige, aber mir fehlt noch der Durchblick bei der Verwendung des WasserBase, insbesondere mit linearer Referenzierung.)_

**Comment by edigonzales** [comment]
Also ich finde im XTF einfach kein Objekt mit TID="6213".

Was mich irritiert ist, dass ilivalidator trotz `--allObjectsAccessible` keinen Fehler meldet. Entweder bin ich wirklich zu blöd das Objekt in der Datei zu finden, oder aber die Option funktioniert nicht mit Referenzattributen.

**Comment by claeis** [comment]
Die Daten sind nicht korrekt: es fehlt ein WasserBase_LV95_V1_1.Gewaesser.Gewaesserlauf mit der TID=6213. Alle REFs müssen aufgelöst werden können, entweder indem das referenzierte Objekt schon vor aus einer anderen Datei importiert wurde, oder nun in dieser Datei vorhanden ist.
