### ISSUE TITLE
Cannot use the asset name on multiple association between two classes

### ISSUE THREAD

**Issue by signedav** [claeis/ili2db#411]
On validating this model I get errors considering the role names:
```
INTERLIS 2.3;
MODEL GeolAssets (de)
AT "mailto:signe@dav.ch"
VERSION "2019-02-15"  =
  IMPORTS GeometryCHLV95_V1,Units;

  TOPIC CoreGeolAsset =

    CLASS Asset =
      Description : MANDATORY TEXT*256;
      Restriction : MANDATORY BOOLEAN;
    END Asset;

    CLASS Contact =
      Name : MANDATORY TEXT*20;
    END Contact;

    ASSOCIATION Asset_Contact_Autor =
      Asset -- {1..*} Asset;
      Author -- {0..*} Contact;
    END Asset_Contact_Autor;
    
    ASSOCIATION Asset_Contact_Contractor =
      Asset -- {1..*} Asset;
      Contractor -- {0..*} Contact;
    END Asset_Contact_Contractor;

    ASSOCIATION Asset_Contact_Supplier =
      Asset -- {1..*} Asset;
      Supplier -- {0..*} Contact;
    END Asset_Contact_Supplier;

  END CoreGeolAsset;

END GeolAssets.
```
```
Error: /home/dave/projects/landesgeologie/Daten/GeolAsset.ili:25:There can not be a role "Asset", because there is already an attribute or role with the same name in role Contractor's target (Contact).
Error: /home/dave/projects/landesgeologie/Daten/GeolAsset.ili:30:There can not be a role "Asset", because there is already an attribute or role with the same name in role Supplier's target (Contact).
```

Why's that? I doubt that it's a bug but I'm confused still, that this is not accepted.
It's no big deal to rename the roles "Asset" to "AutoredAssed", "ContractedAssed" or "SuppliedAsset". Is this the way to go?

**Comment by edigonzales** [comment]
I looked through some very old emails since we had once the same problem:

> das Problem sind die beiden Rollen "Vorschrift" in den beiden Assoziationen.
> 
> ASSOCIATION Dokument_Ueberlagernd_Flaeche =
> Vorschrift (EXTERNAL) -<#> {0..1} SO_Nutzungsplanung_20161129.Rechtsvorschriften.Dokument;
> Ueberlagernd_Flaeche -- {1..*} Ueberlagernd_Flaeche;
> END Dokument_Ueberlagernd_Flaeche;
> 
> ASSOCIATION Plandokument_Ueberlagernd_Flaeche =
> Vorschrift (EXTERNAL) -- {0..1} SO_Nutzungsplanung_20161129.Rechtsvorschriften.Plandokument;
> Ueberlagernd_Flaeche -- {0..*} Ueberlagernd_Flaeche;
> END Plandokument_Ueberlagernd_Flaeche;
> 
> Ein Rollenname muss nicht nur innerhalb der Assoziation eindeutig sein (in der die Rolle definiert ist), sondern auch in Bezug auf die gegenüberliegende Klasse (also im vorliegenden Fall Ueberlagernd_Flaeche). Was nicht der Fall ist, und somit unzulässig.
> 
> Einen expliziten Text habe ich im Referenzhandbuch (leider) nicht gefunden, aber es ergibt sich aus Kap. 2.5.4, 2.7.5, 2.13 bzw. 3.3.7, 3.3.9.1. Einerseits würde die ganze Navigierbarkeit im Objektgeflecht (via ObjectOrAttributePath) nicht mehr funktionieren, und andererseits wären die XML-Instanzen (also die Daten) nicht mehr konformes XML (im vorliegenden Fall wäre für ein XML-Parser nicht entscheidbar, welche "Vorschrift" gemeint ist).

As far as I understand it's the same problem: role name "Asset" and gegenüberliegende Klasse "Contact" which is not unique in your model.

**Comment by claeis** [comment]
yes, same problem
