### ISSUE TITLE
--sqlExtRefCols fails

### ISSUE THREAD

**Issue by sjib** [claeis/ili2db#422]
Wenn ich die neue Option [--sqlExtRefCols](https://github.com/claeis/ili2db/commit/a63aa1d3b4cd1f2c6512c1bf00884104f6b45a57) mit dem neuesten ili2pg 4.6.0 nutzen will erhalte ich folgenden Fehler:

Error:     FEHLER: Spalte »haltungspunktref« hat Typ bigint, aber der Ausdruck hat Typ character varying
  Hinweis: Sie müssen den Ausdruck umschreiben oder eine Typumwandlung vornehmen.
  Position: 259
  
  Im xtf nutze ich STANDARDOID's für OID und Fremdschlüssel.
  
  Muss ich noch ein anderes Flag setzen, damit es funktioniert?
  
  `java -jar ili2pg-4.6.0.jar --sqlExtRefCols --createEnumTxtCol --import --deleteData  --sqlEnableNull --createEnumTabs --createFk  --noSmartMapping --defaultSrsAuth EPSG --defaultSrsCode 2056 --dbhost localhost --dbport 5432 --dbdatabase testdata_vsa_kek_2019 --dbschema vsa_kek_2019_2_d_f_460 --dbusr postgres --dbpwd *** --log importdaten_vsa_kek_2019_2_d_f_460_testdata_vsa_kek_2019_channel_damage_8486.log --trace testdata_vsa_kek_2019_channel_damage_8486.xtf`
  
  nachdem ich vorher das schema so erzeugt habe:
  `java -jar ili2pg-4.6.0.jar --modeldir "C:/Daten/Firma/2_Softwareentwicklung/20_DABASE/203_QEP/vsakek/5617_E/ili2pg-4.6.0" --createEnumTxtCol --schemaimport --importTid --sqlEnableNull --createEnumTabs --createFk  --noSmartMapping --defaultSrsAuth EPSG --defaultSrsCode 2056 --dbhost localhost --dbport 5432 --dbdatabase testdata_vsa_kek_2019 --dbschema vsa_kek_2019_2_d_f_460 --dbusr postgres --dbpwd *** --log createschema_vsa_kek_2019_2_d_f_460.log --trace --models VSA_IVI_2019_LV95; VSA_KEK_2019_LV95;`
  
  Testdaten: 
  
[testdata_vsa_kek_2019_channel_damage_8486.zip](https://github.com/claeis/ili2db/files/7144815/testdata_vsa_kek_2019_channel_damage_8486.zip)

**Comment by beistehen** [comment]
Ohne die neue Funktion im Detail zu kennen, aber müsste diese nicht beim Anlegen des Schemas angewandt werden und nicht erst beim Import?

**Comment by sjib** [comment]
@beistehen danke für den Tipp - jetzt sieht es besser aus.

`java -jar ili2pg-4.6.0.jar --modeldir "C:/Daten/Firma/2_Softwareentwicklung/20_DABASE/203_QEP/vsakek/5617_E/ili2pg-4.6.0"  --sqlExtRefCols --createEnumTxtCol --schemaimport --importTid --sqlEnableNull --createEnumTabs --createFk --noSmartMapping --defaultSrsAuth EPSG --defaultSrsCode 2056 --dbhost localhost --dbport 5432 --dbdatabase testdata_vsa_kek_2019 --dbschema vsa_kek_2019_2_d_f_460 --dbusr postgres --dbpwd *** --log createschema_vsa_kek_2019_2_d_f_460.log --trace --models VSA_IVI_2019_LV95; VSA_KEK_2019_LV95;`

**Comment by claeis** [comment]
Ja, --sqlExtRefCols ist eine --schemaimport Option (beim --import bringt sie nichts)
