### ISSUE TITLE
[ili2fgdb] Tabelle lineare Referenzierung nicht in xtf exportiert

### ISSUE THREAD

**Issue by msuetterlin** [claeis/ili2db#425]
Mit ili2fgdb werden beim Export von Daten mit linearer Referenzierung _(z.B. Fliessgewässer (ID 191.1) des Kanton VS)_ die Tabelle "gewaesserlauf" und die FeatureClass gewaesserlaufabschnittgeometrie nicht in das xtf exportiert. Die Tabelle ist notwendig als Referenz für die linearen Daten im Zusammenhang mit dem Modell WasserBase.

Ist dies bereits bekannt resp. wurden ähnliche Probleme mit anderen Daten mit linearer Referenzierung festgestellt?

Aufgrund der fehlenden REF erhalten wir anschliessend bei dem Import mit ili2pg natürlich eine Fehlermeldung. 

Anbei die gdb für die Daten mit linearer Referenzierung und das Log-file in dem ersichlitlich ist, dass "gewaesserlauf" und gewaesserlaufabschnittgeometrie nicht exportiert wurden:
[Revitalisierung_Fliessgewaesser_Linear_VS.zip](https://github.com/claeis/ili2db/files/7217319/Revitalisierung_Fliessgewaesser_Linear_VS.zip)

Der für den Export verwendete command:
`"C:\Program Files (x86)\Java\jre1.8.0_161\bin\java" -jar ili2fgdb-4.4.1.jar --log "PlanRevitEaux\PlanRevitEaux_Linear.log" --disableValidation --export --models Revitalisierung_Fliessgewaesser_V1_1 --dbfile "PlanRevitEaux\PlanRevitEaux_Linear.gdb" "PlanRevitEaux\PlanRevitEaux_VS_Linear.xtf"`

**Comment by msuetterlin** [comment]
@claeis Sind weitere Angaben notwendig, um den Problem auf die Schliche zu kommen?

**Comment by claeis** [comment]
Die Tabellen sind von Klassen aus einem anderen Modell (WasserBase_LV95_V1_1), also muss dieses Modell auch für den export ausgewählt werden: somit beim Export also ``--models Revitalisierung_Fliessgewaesser_V1_1;WasserBase_LV95_V1_1``
