### ISSUE TITLE
More descriptive error message when exporting DB with NaN Z coordinate

### ISSUE THREAD

**Issue by gacarrillor** [claeis/ili2db#427]
When I run an export on [this GPKG](https://downloads.tuxfamily.org/tuxgis/tmp/issue_1.gpkg), I get the following error message: 

```
Info: Modelo_Aplicacion_LADMCOL_Lev_Cat_V1_0.Levantamiento_Catastral.LC_Terreno...
java.lang.NumberFormatException
Finished (1)
```

The error corresponds to a NaN value in the Z coordinate of one vertex.

Would it be possible to throw an error message like this (or just more descriptive for the user)?

`Error: line 0: Modelo_Aplicacion_LADMCOL_Lev_Cat_V1_0.Levantamiento_Catastral.LC_Terreno: tid 8f6675c2-5c7a-4dee-92b4-9a47e4f47d39: value NaN is out of range for z-coordinate in attribute Geometria java.lang.NumberFormatException`

**Comment by claeis** [comment]
can not reproduce with my current SNAPSHOT (4.6.1)

**Comment by claeis** [comment]
[ceis1.zip](https://github.com/claeis/ili2db/files/7468430/ceis1.zip)

**Comment by gacarrillor** [comment]
My fault, I missed important details in the issue.

The GPKG I linked to works with ili2gpkg <= v4.4.3. Newer versions of ili2gpkg have more strict validations on INTERLIS models that shouldn't allow you to export with a command like this:

`/usr/bin/java -jar /tmp/ili2gpkg/ili2gpkg-4.6.1-SNAPSHOT.jar --dbfile /tmp/issue_1.gpkg --export --exportTid --modeldir "/home/germap/.local/share/QGIS/QGIS3/profiles/ambiente/python/plugins/asistente_ladm_col/resources/models" --models "Modelo_Aplicacion_LADMCOL_Lev_Cat_V1_0;Submodelo_Insumos_Gestor_Catastral_V1_0;Submodelo_Insumos_SNR_V1_0;Submodelo_Integracion_Insumos_V1_0" /tmp/issue_1_snapshot.xtf`

-----------------------------

So, I just updated the sample GPKG database (download it [from here](https://downloads.tuxfamily.org/tuxgis/tmp/issue_1_lev_cat_1_1.gpkg)) that works with ili2gpkg > v4.4.3.

When testing against ili2gpkg v4.4.4 I got this error message:

```
Error: line 0: Modelo_Aplicacion_LADMCOL_Lev_Cat_V1_1.Levantamiento_Catastral.LC_Terreno: tid ae7cfff5-7eb6-49f7-bba8-03cfcf0d1c56: value <NaN> is not a number
illegal value null for C3
Terminado (1)
```
which is much better and gives users a clear hint on what's wrong. Therefore, I consider this issue as solved.

Thank you!
