### ISSUE TITLE
More descriptive error message when exporting DB which doesn't meet a mandatory relationship

### ISSUE THREAD

**Issue by gacarrillor** [claeis/ili2db#428]
When exporting [this GPKG](https://downloads.tuxfamily.org/tuxgis/tmp/issue_2.gpkg), we get a `NullPointerException`.

```
Info: Modelo_Aplicacion_LADMCOL_Lev_Cat_V1_0.Levantamiento_Catastral.LC_UnidadConstruccion...
java.lang.NullPointerException
Finished (1)
```

The error corresponds to a missing value in a relationship (any of those "punto" fields should be set for each record).

![image](https://user-images.githubusercontent.com/652785/139752456-838eab75-ce92-4a12-af00-185622c4128f.png)

Would it be possible to throw an error message like this? 

`Info: LADM_COL_V3_0.LADM_Nucleo.col_puntoFuente: tid  138b5d59-dc67-4b8a-9a76-5735975e3cc7 should associate 1 LADM_COL_V3_0.LADM_Nucleo.col_punto record.`

**Comment by claeis** [comment]
can not reproduce with my current SNAPSHOT (4.6.1)
[ceis2.zip](https://github.com/claeis/ili2db/files/7468445/ceis2.zip)

**Comment by gacarrillor** [comment]
My fault, I missed important details in the issue.

The GPKG I linked to works with ili2gpkg <= v4.4.3. Newer versions of ili2gpkg have more strict validations on INTERLIS models that shouldn't allow you to export with a command like this:

`/usr/bin/java -jar /tmp/ili2gpkg/ili2gpkg-4.6.1-SNAPSHOT.jar --dbfile /tmp/issue_2.gpkg --export --exportTid --modeldir "/docs/dev/LADM_COL3" --models "Modelo_Aplicacion_LADMCOL_Lev_Cat_V1_0;Submodelo_Insumos_Gestor_Catastral_V1_0;Submodelo_Insumos_SNR_V1_0;Submodelo_Integracion_Insumos_V1_0" /tmp/issue_2.xtf`

-----------------------------

So, I just updated the sample GPKG database (download it [from here](https://downloads.tuxfamily.org/tuxgis/tmp/issue_2_lev_cat_1_1.gpkg)) that works with ili2gpkg > v4.4.3.

When testing against this [ili2gpkg SNAPTHOT v4.6.1](http://jars.interlis.ch/ch/interlis/ili2gpkg/4.6.1-SNAPSHOT/ili2gpkg-4.6.1-20211105.102616-4-bindist.zip) I got this error message in the export operation:

```
Error: line 0: LADM_COL_V3_0.LADM_Nucleo.col_puntoFuente: Role LADM_COL_V3_0.LADM_Nucleo.col_puntoFuente.punto requires a reference to another object
Error: line 0: LADM_COL_V3_0.LADM_Nucleo.col_puntoFuente: Role LADM_COL_V3_0.LADM_Nucleo.col_puntoFuente.punto requires a reference to another object
```
which is much better and gives users a clear hint on what's wrong. Therefore, I consider this issue as solved.

Thank you!
