### ISSUE TITLE
Is information about MTEXT datatypes already available from the created postgres database?

### ISSUE THREAD

**Issue by m-kuhn** [claeis/ili2db#43]
CC @andreasneumann

**Comment by claeis** [comment]
no

**Comment by m-kuhn** [comment]
I think a new column `ilitype` (or similar) in the table `t_ili2db_attrname` would be handy. Does that sound like a good approach?

**Comment by andreasneumann** [comment]
PostgreSQL does not have a special data type for MTEXT. Everything is just text or character varying for length constrained text.

For QGIS we would like to show a multiline text widget instead of a single line text widget in the case of MTEXT.

So yes, storing the original Interlis data type in t_ili2db_attrname sounds like a good idea!

**Comment by claeis** [comment]
I assume, in the future there are multiple/different (sub-)forms for the same table. I would separate attribute type info from widget hints. And I would assume that one field is not enough (except you want to parse some syntax).

**Comment by m-kuhn** [comment]
Is it feasible to extract multiple forms from an ili file?

My idea was:

 * Use attribute information as widget hints
 * Allow further configuration in (yaml) config files, initially populated with hints extracted from attribute information

The field was just mentioned to serve as an example, I assume additional fields like `length` or `precision` etc. make sense.

**Comment by claeis** [comment]
Why not multiple forms? Similar as you can have multiple maps out of the same table; it's not a question of the model. But you might do this also in the yaml file.

But still, I would base the table on the tables and columns and not on the ili-model attributes. And I would choose a flexible structure to avoid later schema changes.

I would suggest a table like 

    CREATE TABLE t_ili2db_column_prop (
     tablename varchar(255) NOT NULL,
     columnname varchar(255) NOT NULL,
     tag character varying(1024) NOT NULL,
     setting character varying(1024) NOT NULL
    );

**Comment by m-kuhn** [comment]
> Why not multiple forms? Similar as you can have multiple maps out of the same table; it's not a question of the model. But you might do this also in the yaml file.

Sorry, I probably expressed myself badly. Yes, I agree, multiple forms are desirable at some point but I don't think there is a dependency on this question (unless there is already information that could be used to pre-configure multiple forms present in an ili file).

> But still, I would base the table on the tables and columns and not on the ili-model attributes.

Are you referring to the columns in postgres? That's what is being done so far, but I think we can't extract multiline information from there, that's why some additional information from the ili-file will need to be proxied to the form configuration somehow. I was thinking to use `t_ili2db_attrname` a bit like `pg_attribute` with structured information. But a different table is also ok. For unstructured information we could also have something like the following - which looks cleaner but not sure if that's compatible with geopackage etc.

```
CREATE TABLE t_ili2db_columns (
 tablename name NOT NULL,
 columnname name NOT NULL,
 properties jsonb
);
```

**Comment by claeis** [comment]
Yes, the "PK" of the new table should be PG table/attr names and not ILI table/attr names (because you want to use it without ili2pg). (And I wouldn't use jsonb in this case, to make qry/ins/del operations simple and portable)

**Comment by m-kuhn** [comment]
> PG table/attr names and not ILI table/attr names

Ah, that's the point I was missing :)

> And I wouldn't use jsonb in this case, to make qry/ins/del operations simple and portable

No particular preference from my side, I can handle the query part whatever it may look like.

I still could imagine a structured layout similar to `pg_attribute` but if key-value pairs are preferred it definitely also serves the purpose.

**Comment by claeis** [comment]
Is there already a stable/more complete list of required additional ili-model information?

**Comment by m-kuhn** [comment]
No, the list will be populated as we stumble upon things that could be added.
If you prefer, we can make it one issue on which we edit the first post and maintain a list of items.

**Comment by claeis** [comment]
yes, please populate in #63
