### ISSUE TITLE
export by --topics with no baskets should create an empty transfer file

### ISSUE THREAD

**Issue by claeis** [claeis/ili2db#432]
similar to export by --models but different to export by --baskets. Clarify documentation.

**Comment by signedav** [comment]
Since I considered this topic in the Model Baker implementation lately, I would like to clarify the following:
> In the ili2db doc it said you can use models or alternatively topics or datasets or baskets (so this implies that you only use usually one of them). And it makes no conjunction (AND) but a disjunction (OR) if multiple parameters are given. A conjunction can still be done by selecting the smallest instance (baskets). Anyway. In the real use cases only one filter-mode (models XOR topics XOR datasets XOR baskets)

Is this correct?

**Comment by claeis** [comment]
yes
