### ISSUE TITLE
[ili2fgdb] Fehler bei Katalogimport mit --smart2Inheritance

### ISSUE THREAD

**Issue by mizehnder** [claeis/ili2db#433]
ili2fgdb-Parameter V4.5.0: 

- Schemaimport: --smart2Inheritance --schemaimport --fgdbXyResolution 0.00005 --fgdbXyTolerance 0.0004 --createEnumTabs --createBasketCol --models Nutzungsplanung_V1_2

- Katalogimport: --smart2Inheritance --import --dataset Nutzungsplanung_Catalogue_CH_V1_2_20210901.xml --models Nutzungsplanung_V1_2

Modell: https://models.geo.admin.ch/ARE/Nutzungsplanung_V1_2.ili 
Katalog: https://models.geo.admin.ch/ARE/Nutzungsplanung_Catalogue_CH_V1_2_20210901.xml 
Error-Log: [test3_catalogueimport_NPL.log](https://github.com/claeis/ili2db/files/7519989/test3_catalogueimport_NPL.log)
`Error: no ViewableWrapper found for LocalisationCH_V1.MultilingualText`

Mit der zusätzlichen Modellangabe `LocalisationCH_V1` beim Schema- und Katalogimport, kann der Katalog erfolgreich importiert werden. 
Dann wird aber das Schema entsprechend verändert und es gibt mehrere localisedtext- und multilingulatext-Tabellen. 
![grafik](https://user-images.githubusercontent.com/82505753/141290155-4b34536c-0c26-4df5-acb8-da573a57b39a.png)

Mit --smart1Inheritance (Default) konnte der Katalog ohne das zusätzliche Modell `LocalisationCH_V1` importiert werden.

Gibt es ein Problem bei der Abbildung oder fehlt einfach das Modell `LocalisationCH_V1` bei den Import-Parametern im Nutzungsplanungsmodell?
![grafik](https://user-images.githubusercontent.com/82505753/141290786-ff61b8c5-247e-405a-a50f-8ba48aeef520.png)

**Comment by edigonzales** [comment]
Ahhh ja, da scheint doch etwas nicht zusammen zu passen. -> @ltzur (Rolf?)

Jetzt verstehe ich was anderes nicht mehr ganz. Im Modell steht:

```
    CLASS Catalogue_CH (FINAL) =
      OID AS TypeID;
      Code : MANDATORY 11 .. 99;
      Designation : MANDATORY Localisation_V1.MultilingualText;
    END Catalogue_CH;
```

Da will man also ein MultilingualText von Localisation_V1. Die Daten selber (also das XML) verwenden beim Attribut Designation jedoch Localisation**CH**_V1. Warum validiert die XML-Datei mit ilivalidator?

**Comment by claeis** [comment]
claeis/ilivalidator#328
