### ISSUE TITLE
[ili2fgdb] Wrong Data Type for T_basket / T_Id

### ISSUE THREAD

**Issue by mizehnder** [claeis/ili2db#434]
BID Definition:
http://models.geo.admin.ch/ARE/Nutzungsplanung_V1_2.ili 
` TypeID = OID TEXT*60;`
 `TOPIC Catalogue_CH =
    BASKET OID AS TypeID;`
`TOPIC Geobasisdaten =
    BASKET OID AS TypeID;`

Die Felder werden als Long Integer angelegt statt als Text.
z.B. T_basket in der Tabelle catalogue_ch:
![grafik](https://user-images.githubusercontent.com/82505753/141294578-2d4fe13c-71d0-4522-9e44-65a0896b837c.png)
T_Id in der Tabelle T_ILI2DB_BASKET:
![grafik](https://user-images.githubusercontent.com/82505753/141294839-e3dc21de-bd51-4957-b60c-fbe6e5c022f7.png)

Was dann zu Fehlern beim Export führt:
`Info: Nutzungsplanung_V1_2.Geobasisdaten BID <2>...
Error: Nutzungsplanung_V1_2.Geobasisdaten: tid 2: value <2> is not a valid BID`

**Comment by edigonzales** [comment]
BID ist in der Tabelle T_ILI2DB_BASKET das Attribut T_Ili_Tid. Das scheint Text zu sein. Steht bei diesem Attrbut ein Wert bei euch?

**Comment by mizehnder** [comment]
Ah, stimmt. Da steht bereits die BID vom Katalog drin: ch.admin.are.nutzungsplanung_catalogue_ch_v1_2_20210901
Danke, das könnte es lösen.

**Comment by claeis** [comment]
Die Spalte t_id in der DB ist ein interner Identifikator (und unabhängig vom ili-Modell immer long) und nicht das XML-Attribut TID/BID aus der Transferdatei! Die Spalte t_ili_tid ist die TID/BID aus der Transferdatei.
