### ISSUE TITLE
Imported geometry may not fulfil OGC Validity

### ISSUE THREAD

**Issue by Philippluca** [claeis/ili2db#437]
Derived of: https://github.com/claeis/ilivalidator/issues/298

Gemäss INTERLIS 2.4 ([Spez S. 57](https://www.ech.ch/de/dokument/266625ed-0a4a-4c20-b7ff-504cd908c0d6)) darf sich ein Polygon in Stützpunkten berühren. Nach [OGC](https://www.ogc.org/standards/sfa) erfüllt ein Solches Polygon nicht die Bedingung für Validity. PostGIS zeigt dies sehr anschaulich anhand des "banana polygon". Gewisse Operationen erfordern diese Validity. Mit ili2db importierte Geometrien sind also gemäss INTERLIS korrekt, führen jedoch je nach Anwendungsfall dennoch zu Problemen. 
Achtung PostGIS erwähnt, dass ESRI nochmals eine eigene definition von Validity verwendet.

Beispiel "banana polygon":
![Geometrie](https://user-images.githubusercontent.com/2191817/143851874-bda0da10-acf9-4e25-9784-cf9958c2921f.png)
WKT: `POLYGON ((2648560 1249140, 2648560 1246588, 2653030 1246588, 2653030 1247821, 2652372 1247468, 2651777 1247821, 2652372 1248220, 2653030 1247821, 2653030 1249140, 2648560 1249140))`.

## Variante 1:
Es wird ein neues Argument für den Import eingeführt (z.B. `--repairInvalidity`).  
Das Argument bewirkt, dass vor dem Import versucht wird die Validity für betroffene Geometrien zu reparieren.

## Variante 2:
Für die Validierung (ilivalidator bzw. `--validate`) wird ein neues Argument eingeführt. (z.B. `--checkOgcValidity`)
Das Argument bewirkt, dass bei einer Validierung die Geometrien, welche die OGC Bedingungen für Validity nicht erfüllen ein Fehler produzieren.

@edigonzales & @claeis. Welches ist die bevorzugte Variante? Gibt es Einwände?
Testdaten: [banana polygon example.zip](https://github.com/claeis/ili2db/files/7617601/banana.polygon.example.zip)

**Comment by edigonzales** [comment]
Braucht es dazu ein neues Argument? Ich kann mir nicht wirklich einen Fall vorstellen, wo man nicht-Postgis-konforme Geometrien in der DB halten wie, die ja eigentlich korrekt sind. Für mich ist es ein Versäumnis der Umwandlung der Geometrie von XTF nach PostGIS. Vielleicht vergleichbar in der Argumentation, wie wenn man die Geometrie als Topologie-Geometrietyp abspeichern würde. Die sieht dann ja auch völlig anders aus als im XTF.

**Comment by Philippluca** [comment]
@edigonzales So wie ich das sehe kann eine Geometrie momentan mit ili2db importiert & wieder exportiert werden, ohne dass sich an der Repräsentation etwas ändert. Diese Roundtripfähigkeit geht ohne ein Argument verloren. Je nach Nutzer kann ich mir auch vorstellen, dass das Reparieren nur auf ausgewählten Klassen gebraucht wird. Dies könnte dann in einem weiteren Schritt beispielsweise als Metaattribut umgesetzt werden.

**Comment by edigonzales** [comment]
Roundtrip: Du meinst im Original-XTF ist es eine Banane ohne Loch, dann wird importiert und es entsteht ein Loch. Dann wieder exportiert und im neuen XTF hat die Banane ein Loch?

Mmmh. Ja, aber ist das schlimm / falsch? Ist es nicht die gleiche Aussage, nur halt anders repräsentiert?

Wie macht das zB ogr2ogr? Da können ja auch Shapefile nach ESRI-Bananenstyle daherkommen. Wie sehen die in Postgis aus?

Ich weiss einfach nicht was ich mit invaliden Geometrien in der DB machen soll (ausser immer korrigieren), die eigentlich valide sind.

**Comment by claeis** [comment]
m.E. macht ein neues Argument keinen Sinn. ili2db kann beim importieren stillschweigen aus der einen Linie (für den äusseren und den inneren Rand) zwei Linien machen (eine für den äusseren Rand und eine für den innerern Rand). Und beim Export sind es halt dann zwei Rändern (mit je einer Linie); also nicht genau identisch, aber gleichwertig.

**Comment by claeis** [comment]
claeis/ilivalidator#331

**Comment by Philippluca** [comment]
> Roundtrip: Du meinst im Original-XTF ist es eine Banane ohne Loch, dann wird importiert und es entsteht ein Loch. Dann wieder exportiert und im neuen XTF hat die Banane ein Loch?

@edigonzales: Genau das verstehe ich unter Roundtrip-Fähigkeit.

> Wie macht das zB ogr2ogr? Da können ja auch Shapefile nach ESRI-Bananenstyle daherkommen. Wie sehen die in Postgis aus?

ogr2ogr bietet die Option `-makevalid` an. Ich verstehe es so, dass der Default hier keine Änderung an der Geometrie vornimmt.

> Ja, aber ist das schlimm / falsch? Ist es nicht die gleiche Aussage, nur halt anders repräsentiert?

Stimmt schon, falsch ist es nicht. Schlimm auch nicht. Ich kann diese Option durchaus unterstützen.

@edigonzales @claeis Wir setzen Variante 1 ohne Argument für den Import um.
