### ISSUE TITLE
ili2pg tables creation inheritance issue

### ISSUE THREAD

**Issue by leader80** [claeis/ili2db#44]
Hi all,

we are facing a problem while creating table from ili files with ili2pg.
If we extend a Model then it generates two tables, one for the basic ili and the second for the extended model, so far so good. 
The problem appears by entering data. since the second table isn't inheriting from the first one, so the data is not propagated, can you fix this issue?

Here an example:
CREATE TABLE cities (
  name       text,
  population real,
  altitude   int     -- (in ft)
);

CREATE TABLE capitals (
  state      char(2)
) INHERITS (cities);
Bests
G.

**Comment by claeis** [comment]
Please read the manual https://github.com/claeis/ili2db/blob/master/docs/ili2db.rst#vererbung

**Comment by leader80** [comment]
the documentation is not really updated, thanks for the tip. can you please point me the location of the ili2c-core.jar and ili2c-tool.jar?

thanks
G.

**Comment by claeis** [comment]
the documentation is up-to-date (except where not yet done, marked with TODO). 

The ili2c sources are at https://sourceforge.net/p/umleditor/code/HEAD/tree/ili2c/trunk/
