### ISSUE TITLE
--update funktioniert nicht

### ISSUE THREAD

**Issue by edigonzales** [claeis/ili2db#450]
Schemadefinition:
```
java -jar /Users/stefan/apps/ili2pg-4.7.0/ili2pg-4.7.0.jar --dbhost localhost --dbport 54323 --dbdatabase oereb --dbusr gretl --dbpwd gretl --nameByTopic --strokeArcs --defaultSrsCode 2056 --createTidCol --createFk --createBasketCol --createTypeDiscriminator --dbschema fubar --models "OeREBKRM_V2_0;OeREBKRMkvs_V2_0;OeREBKRMtrsfr_V2_0" --schemaimport
```

Update Ämter:
```
java -jar /Users/stefan/apps/ili2pg-4.7.0/ili2pg-4.7.0.jar --dbhost localhost --dbport 54323 --dbdatabase oereb --dbusr gretl --dbpwd gretl --defaultSrsCode 2056 --models OeREBKRM_V2_0 --dataset zustaendigestellen --importBid --importTid --dbschema fubar --update Downloads/ch.so.agi.oereb_zustaendigestellen_V2_0.xtf
```

Update Dokumente:
```
java -jar /Users/stefan/apps/ili2pg-4.7.0/ili2pg-4.7.0.jar --dbhost localhost --dbport 54323 --dbdatabase oereb --dbusr gretl --dbpwd gretl --defaultSrsCode 2056 --models OeREBKRM_V2_0 --dataset gesetze --importBid --importTid --dbschema fubar --trace --update ch.so.agi.oereb_gesetze_V2_0.xtf
```

Update (nach erstmaligem Import) Dokumente führt zu folgendem Fehler:
```
Error: commit failed
Error:   ERROR: update or delete on table "dokumente_dokument" violates foreign key constraint "multilingualuri_dokumente_dokument_txtmweb_fkey" on table "multilingualuri"
  Detail: Key (t_id)=(342) is still referenced from table "multilingualuri".
Error:       org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2553)
Error:       org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2285)
Error:       org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:323)
Error:       org.postgresql.jdbc.PgConnection.executeTransactionCommand(PgConnection.java:857)
Error:       org.postgresql.jdbc.PgConnection.commit(PgConnection.java:879)
Error:       ch.ehi.ili2db.base.Ili2db.runUpdate(Ili2db.java:792)
Error:       ch.ehi.ili2db.base.Ili2db.run(Ili2db.java:215)
Error:       ch.ehi.ili2db.AbstractMain.domain(AbstractMain.java:639)
Error:       ch.ehi.ili2pg.PgMain.main(PgMain.java:72)
...update failed
    ch.ehi.ili2db.base.Ili2db.runUpdate(Ili2db.java:795)
    ch.ehi.ili2db.base.Ili2db.run(Ili2db.java:215)
    ch.ehi.ili2db.AbstractMain.domain(AbstractMain.java:639)
    ch.ehi.ili2pg.PgMain.main(PgMain.java:72)
```

Auf der ersten Blick verwirrend warum die Ämter funktionieren, die Dokumente jedoch nicht. Beide verwenden die Multilingual-URI. Andererseits find ich komisch, dass gemäss Logfile sämtliche Dokumente gelöscht werden sollen (aber es sind die identischen): `Info: deleteExistingObjectsHelper(): DELETE FROM fubar.dokumente_dokument WHERE T_Id in (342,343,344,345,346,347,348,349,350) (TransferFromXtf.java:880)`. 

Die Dokumente "replacen" funktioniert.

[ch.so.agi.oereb_gesetze_V2_0.xtf.zip](https://github.com/claeis/ili2db/files/7888383/ch.so.agi.oereb_gesetze_V2_0.xtf.zip)

[ch.so.agi.oereb_zustaendigestellen_V2_0.xtf.zip](https://github.com/claeis/ili2db/files/7888384/ch.so.agi.oereb_zustaendigestellen_V2_0.xtf.zip)

[ili2db.log.zip](https://github.com/claeis/ili2db/files/7888380/ili2db.log.zip)

**Comment by edigonzales** [comment]
Ohne `--createFk` läuft ili2pg durch. Aber es führt dazu, dass die Dokumente gelöscht werden und keine neuen importiert werden.

**Comment by patrickackermann** [comment]
Ein Dokument hat eine (externe) Referenz auf ein Amt:
```
    ASSOCIATION ZustaendigeStelleDokument =
      ZustaendigeStelle (EXTERNAL) -- {1} OeREBKRM_V2_0.Amt.Amt;
      Dokument -<> {0..*} Dokument;
    END ZustaendigeStelleDokument;
```

Weil die Transferdatei nur die Dokumente enthält sind während dem Lesen der Transferdatei nicht alle Referenzen resolved und das Updaten der Dokumente wird auf später verschoben.

Am Ende des Baskets wird noch einmal kontrolliert, ob alle Referenzen verfügbar sind. Hier wird momentan nicht in der DB gesucht und somit wird nichts gefunden. Anschliessend werden alle Dokumente gelöscht! Es wird wohl fälschlicherweise angenommen, dass sie nicht mehr vorhanden sind obwohl nur die ZustaendigeStelleDokument-Referenz nicht resolved werden kann.

Am Ende des Transfers werden noch einmal die Referenzen, der Objekte mit fehlenden Referenzen überprüft. Dabei wird in der DB gesucht und das Amt gefunden. Anschliessend wird versucht mit einem `UPDATE` statement das Dokument zu aktualisieren, da es aber am Ende des Baskets gelöscht wurde funktioniert das nicht. Beim Schreiben des dazugehörigen structs `MultilingualUri` entsteht dann die foreign key constraint violation, weil das zugehörige Dokument nicht mehr existiert.
Der Update des anderen Transferfiles funktioniert darum, weil vom Amt zum Dokument keine Referenz im Transferfile kommt.

Weiteres Vorgehen:
Das Löschen muss Objekte, die fehlende Referenzen haben ignorieren. Je nachdem müssen am Ende des Transfers dann alle Objekte, bei denen die Referenzen nicht resolved werden konnten auch noch gelöscht werden.

@claeis Was meinst du dazu? (Wir probieren das Ändern des Löschens mal aus)

**Comment by edigonzales** [comment]
@patrickackermann Abgefahren... :)
