### ISSUE TITLE
Set the modeldir option globally

### ISSUE THREAD

**Issue by schmandr** [claeis/ili2db#453]
Is it possible to set the `modeldir` option globally via an environment variable or a similar thing, instead of passing it as an option to every single `ili2pg` command?

**Comment by sjib** [comment]
The default model pathes for ili2pg are defined as: %ILI_FROM_DB;%XTF_DIR;http://models.interlis.ch/;%JAR_DIR
(see [documentation](https://github.com/claeis/ili2db/blob/master/docs/ili2db.rst) --modeldir

Ilivalidator and [ModelBaker](https://github.com/opengisch/QgisModelBaker-docs/blob/master/en/user-guide.rst#id5) have a user menu to change those settings and add additional pathes or delete some of them. I do not know if they set --modeldir each time as to be more user friendly.

**Comment by schmandr** [comment]
Nice idea to check how ModelBaker is solving this. I found that the `--modeldir` is set each time according to the user setting value. So ModelBaker unfortunately doesn't help me...

And I already fiddled with placing some settings in _~/.ili2c_, but with no success. (ili2pg probably doesn't read anything from this file.)

**Comment by claeis** [comment]
see claeis/ili2c#64

**Comment by claeis** [comment]
see #485
