### ISSUE TITLE
--import ID 153.1/.6 (landw. Nutzflächen und Betriebseinheiten) fails

### ISSUE THREAD

**Issue by pramisters** [claeis/ili2db#454]
Tried to import XTFs of ID 153.1/.6 (landw. Nutzflächen und Betriebseinheiten) into PostGIS with ili2pg.
(ZIP of XTFs: see below)

Schemadefinition: No Problem!
`java -jar T:\GIS\ili2pg\ili2pg-4.7.0.jar --schemaimport --defaultSrsAuth EPSG --defaultSrsCode 2056 --dbhost localhost --dbdatabase test_database --dbschema landuse_lnf_blw --dbusr test_user --dbpwd test_user --createBasketCol --createDatasetCol --createTidCol --createEnumTabs --createEnumTxtCol --createGeomIdx --createFk --createFkIdx --createNumChecks --smart2Inheritance --coalesceCatalogueRef --expandMultilingual --expandLocalised --createMetaInfo --log .\lnf_schema.log  --models Nutzungsflaechen_LV95_V1_4`

Import Kataloge Nutzungsflächen: No problem!
`java -jar T:\GIS\ili2pg\ili2pg-4.7.0.jar --import --replace --dataset kat_lnf --importTid --defaultSrsAuth EPSG --defaultSrsCode 2056 --dbhost localhost --dbdatabase test_database --dbschema landuse_lnf_blw --dbusr test_user --dbpwd test_user --createBasketCol --createDatasetCol --createTidCol --createEnumTabs --createEnumTxtCol --createGeomIdx --createFk --createFkIdx --createNumChecks  --smart2Inheritance --coalesceCatalogueRef --expandMultilingual --expandLocalised --createMetaInfo --log .\lnf_catalog_import.log T:\_Geodaten\LNF\_DB_Import\Nutzungsflaechen_V1_4_Kataloge_20200101.xml`

Import Kataloge Bearbeitungsstatus: No problem!
`java -jar T:\GIS\ili2pg\ili2pg-4.7.0.jar --import --replace --dataset kat_bbs --importTid --defaultSrsAuth EPSG --defaultSrsCode 2056 --dbhost localhost --dbdatabase test_database --dbschema landuse_lnf_blw --dbusr test_user --dbpwd test_user --createBasketCol --createDatasetCol --createTidCol --createEnumTabs --createEnumTxtCol --createGeomIdx --createFk --createFkIdx --createNumChecks  --smart2Inheritance --coalesceCatalogueRef --expandMultilingual --expandLocalised --createMetaInfo --log .\bbs_catalog_import.log T:\_Geodaten\LNF\_DB_Import\bearbeitungsstatus_kataloge_20140701.xml `

Import Bewirtschaftungseinheiten (153.6) before Nutzungsflächen (ID153.1) as NFs reference BEs: 
`java -jar T:\GIS\ili2pg\ili2pg-4.7.0.jar --import --replace --dataset zg_153_6 --importTid --defaultSrsAuth EPSG --defaultSrsCode 2056 --dbhost localhost --dbdatabase test_database --dbschema landuse_lnf_blw --dbusr test_user --dbpwd test_user --createBasketCol --createDatasetCol --createTidCol --createEnumTabs --createEnumTxtCol --createGeomIdx --createFk --createFkIdx --createNumChecks  --smart2Inheritance --coalesceCatalogueRef --expandMultilingual --expandLocalised --createMetaInfo --log .\lnf_153.6_import.log T:\_Geodaten\LNF\_DB_Import\ZG_a_153_6.xtf`

throws the error (excerpt):
``Info: data <T:\_Geodaten\LNF\_DB_Import\ZG_a_153_6.xtf>
Info: assume unknown external objects
Info: first validation pass...
Info: Basket Bewirtschaftungseinheit_LV95_V1_3.Gueltigkeitsdauer(oid Bewirtschaftungseinheit_LV95_V1_3.Gueltigkeitsdauer)...
Error: Object d0b6e866-5d69-43b6-8b13-21511f919a84 at (line 5,col 108)
Error:   FEHLER: Relation »landuse_lnf_blw.bewrtsc95_v1_3gueltigkeitsdauer_bezugsjahr« existiert nicht
  Position: 13
Info: Basket Bewirtschaftungseinheit_LV95_V1_3.Landw_Betrieb(oid Bewirtschaftungseinheit_LV95_V1_3.Landw_Betrieb)...
Error: failed to query landuse_lnf_blw.t_ili2db_seq
Error:   FEHLER: aktuelle Transaktion wurde abgebrochen, Befehle werden bis zum Ende der Transaktion ignoriert
Error:     FEHLER: Relation »landuse_lnf_blw.bewrtsc95_v1_3gueltigkeitsdauer_bezugsjahr« existiert nicht
  Position: 13
Error: org.postgresql.util.PSQLException: FEHLER: aktuelle Transaktion wurde abgebrochen, Befehle werden bis zum Ende der Transaktion ignoriert
Error:   FEHLER: aktuelle Transaktion wurde abgebrochen, Befehle werden bis zum Ende der Transaktion ignoriert
Error:     FEHLER: Relation »landuse_lnf_blw.bewrtsc95_v1_3gueltigkeitsdauer_bezugsjahr« existiert nicht
  Position: 13``

The relevant line 5 of the XTF-Data is:
```
<Bewirtschaftungseinheit_LV95_V1_3.Gueltigkeitsdauer.Bezugsjahr TID="d0b6e866-5d69-43b6-8b13-21511f919a84"><Bezugsjahr>2021</Bezugsjahr></Bewirtschaftungseinheit_LV95_V1_3.Gueltigkeitsdauer.Bezugsjahr>
</Bewirtschaftungseinheit_LV95_V1_3.Gueltigkeitsdauer>
```

Why is ili2pg trying to access a table named "`landuse_lnf_blw.bewrtsc95_v1_3gueltigkeitsdauer_bezugsjahr`" ?
The table in the DB (that exists) is: `landuse_lnf_blw.bezugsjahr`

ili2pg somehow unnecessarily adds the shortened model name (`bewrtsc95_v1_3`) and the topic name (`gueltigkeitsdauer`) as prefix to the class name (`bezugsjahr`) ???

Any hints what's going on here are very welcome!

I tried the same with ili2gpkg: Same problem.

[ID_153_1_6_ZG.zip](https://github.com/claeis/ili2db/files/7971611/ID_153_1_6_ZG.zip)

**Comment by edigonzales** [comment]
Perhaps @msuetterlin or @dkottmann can provide the commands from geodienste.ch?

**Comment by dkottmann** [comment]
> Perhaps @msuetterlin or @dkottmann can provide the commands from geodienste.ch?

@kglaus could you check on this?

**Comment by pramisters** [comment]
I just got a hint from @romefi.

Apparently, there's is a modelling error in some of the ILIs of ID153.x at the TOPIC Gueltigkeitsdauer (missing reference to other TOPICs of the model), so that ili2pg generates the table bezugsjahr only once instead of three times as intended and therefore the import fails.
The problem was discussed in June 2020 by @claeis, @zigertiger and @romefi and BLW, KOGIS and KKGEO were informed about it, so that the models can be corrected in the next version.

The workaround is:
Mention all 3 main models when generating the schema:
`--models Biodiversitaetsfoerderflaechen_Qualitaetsstufe_II_und_Vernetzung_LV95_V1_4;Nutzungsflaechen_LV95_V1_4;Bewirtschaftungseinheit_LV95_V1_3`
