### ISSUE TITLE
Option to switch off "readSettingsFromDb"

### ISSUE THREAD

**Issue by edigonzales** [claeis/ili2db#456]
Für den Fall, dass im Schema mehrere von einander unabhängige Modelle mit unterschiedlichen Settings implementiert sind. Z.B. ein Modell mit --createBasketCol, eines ohne. Dann kann man das Modell ohne Basket-Col nicht exportieren. Ich bin mir aber nicht sicher, ob es an diesem Setting liegt.

**Comment by claeis** [comment]
Innerhalb eines DB-Schemas müssen alle ili-Modelle mit den selben Einstellung auf Tabellen abgebildet werden (sonst gäbe es bei Tabellen aus Basis-Modellen ein Durcheinander).

**Comment by edigonzales** [comment]
Ja, da habe ich eben getrickst: 
- SQL mit --createscript herstellen
- SQL anpassen wegen einigen unique constraints, die Probleme machen (t_ili2db_models)

Aber wenn Rahmenbedingung ("ili-Modelle mit den selben Einstellung ") hart ist, lässt man das wohl lieber sein, weil sonst endlos (?).

**Comment by claeis** [comment]
Ja, endlos, weil zuviele neue Kombinationsmöglichkeiten
