### ISSUE TITLE
export according to base model

### ISSUE THREAD

**Issue by giodegiorgi** [claeis/ili2db#46]
Dear all,

we are extending the basemodel domains for example:

```
Model A
  Prozess_Typ = (
        Wasser,
        Lawine,
        Sturz,
        Rutschung
      );

Model B
Prozess_Typ_TI EXTENDS Prozess_Typ = (
	  Wasser(  hoch, tief)
	);

```
So far so good, but if we gather the information with the extended ili and then we try to export the information with the BASE ili model, then we get and error: "Wasser.tief is not a member of the ENUM...."

Is it normal, and in that case how should we export the data?

Bests
G

**Comment by giodegiorgi** [comment]
this issue is very important for us. thanks for taking into account.
Bests

**Comment by giodegiorgi** [comment]
I need to clarify but I suppose we could support this implementation, this will include:
- schemaimport with inheritance support for pg
- data export with the correct model

But I need an estimation of the amount of time/costs.

Bests
G

**Comment by zigertiger** [comment]
CE estimated two days.

**Comment by edigonzales** [comment]
@zigertiger 2 days for polymorphism? read and write? The inheritance feature is not covered by the 2 days, is it?

@giodegiorgi By "schemaimport with inheritance support for pg" you mean this: [https://www.postgresql.org/docs/9.5/static/tutorial-inheritance.html](https://www.postgresql.org/docs/9.5/static/tutorial-inheritance.html) ?

Do you see a big advantage in having a vendor specific o/r mapping variant? We used inheritance in postgresql ages ago but we were not happy with it and never used it again. Was a problem with pk/fk handling as far as I remember. Not sure if this stil exists.

**Comment by zigertiger** [comment]
2d for polymorphism, only. I suppose this feature is well prepared inside the ili2db library...

**Comment by giodegiorgi** [comment]
we can discuss about polymorphism very long, in our specific case we use it **only** to avoid duplication of data, meaning that we start from the MGDM we specialize our Cantonal and then we have also one specific version for the Offices. 
The user is entitled to enter the data only on the lowest level and therefore we permit only read access on the higher table and write access to the lowest one.
I sent a mail to CE to have an official offer.

Best
G

**Comment by claeis** [comment]
3.10.10
