### ISSUE TITLE
ili2fgdb with French Model produces German dispName

### ISSUE THREAD

**Issue by sjib** [claeis/ili2db#460]
I created a gdb file with the following command:
`java -jar ili2fgdb-4.7.0.jar --schemaimport --createEnumTabs --createBasketCol --defaultSrsCode 2056 --models VSASDEEMINI_2020_LV95 --dbfile test2.gdb VSASDEEMINI_2020_LV95.ili`

and still get a gdb file with German instead of French headers
![test2gdb_catalogue](https://user-images.githubusercontent.com/1265865/158207942-4990721d-bff8-407b-a091-f8ebf4c3b31a.png)

Adding the flag --models VSASDEEMINI_2020_LV95 did not change anything?

Do I need to set another flag to have the gdb with French Headers and aliases?
[test2.gdb.zip](https://github.com/claeis/ili2db/files/8246720/test2.gdb.zip)

Models see https://www.vsa.ch/models/2020/ - I have German and French Models made available

**Comment by claeis** [comment]
Default name/language for the table/column names is the language of the model without TRANSLATION OF. To use a different one use ```--nameLang lang``` at schema import time.

**Comment by sjib** [comment]
Great - works perfectly now! Thanks a lot.

**Comment by KaeserD** [comment]
Indeed, many thanks

**Comment by sjib** [comment]
Still another issue related here that is not changed with `--nameLang fr:` 

`java -jar ili2fgdb-4.7.0.jar --schemaimport --createEnumTabs --createBasketCol --defaultSrsCode 2056 --models VSASDEEMINI_2020_LV95 --nameLang fr --dbfile test3.gdb VSASDEEMINI_2020_LV95.ili`

How can the display name (dispName and / or ilicode) be changed to French also in the value list tables eg. in ft_bassin_canal_rete_bep_disposition

![ft_bassin_canal_rete_bep_disposition](https://user-images.githubusercontent.com/1265865/159301217-a98c7a2e-dc89-47bb-9869-4a6adaafdcc8.png)
?

Do I have to choose another option for `--createEnumTabs` ? see https://github.com/claeis/ili2db/blob/master/docs/ili2db.rst#aufz%C3%A4hlungen

**Comment by sjib** [comment]
I tested with the new 4.8.0. Generally this looks now as expected.

There is one open issue with the attribut Status


![test6 gdb_etat_valeur_in_Betrieb_fehlt_nur_10_statt_11_Werte](https://user-images.githubusercontent.com/1265865/166468930-a5d36432-c1f2-4d40-afd3-7ca6d48cf34d.jpg)

Here we have the following INTERLIS definitions:

 !!@comment = "Betriebs- und Planungszustand. neu 2010: Erweiterungen dazu in den einzelnen Medien definieren"

`    Status= (   `
`             ausser_Betrieb,`  
`             in_Betrieb,`
`             tot,  `
`             unbekannt,` 
`             weitere `
`            );`

and then extended:

!!@ comment = "Erweitert Wertebereich von SIA405 Status Betriebs- und Planungszustand."

`Statuswerte EXTENDS SIA405_Base_Abwasser_LV95.Status = (  `
!!@ comment = "Erweiterung Basiswerte im Medium, hierarchische Modellierung und Anpassung mit Compiler 4.5.13"
	  !!@ comment = "fasst in_Betrieb und folgende Werte zusammen"
`      in_Betrieb (`
`         provisorisch,`
`         wird_aufgehoben`
`      ),`
	  !!@ comment = "fasst tot und folgende Werte zusammen"
`      tot (`
         !!@ comment = "  tot,   !! existiert nicht im Medium Abwasser"
`        aufgehoben_nicht_verfuellt,`
`        aufgehoben_unbekannt,`
`        verfuellt`
`      ),`
	  !!@ comment = "fasst weitere und folgende Werte zusammen"
`      weitere (`
`         Berechnungsvariante,`
`         geplant,`
`         Projekt`
`      )`
 `   );    `
!!@ comment = "neu 17.7.2015 Erweitert Wertebereich von SIA405 Status"
`    Status = ALL OF Statuswerte;`

So `ausser_Betrieb` is currently twice in the value list - that is a bit strange and not correct. As far as I understand ALL OF should give me 14 different values, now I have 15 because `ausser_Betrieb`  is listed twice. So I even cannot JOIN the two table easily.

Nice would be also to have all values of Statuswerte in one table. How could this be influenced? 
With an ini / toml file configuration or should this be corrected in the code.

**Comment by claeis** [comment]
> So ausser_Betrieb is currently twice in the value list - that is a bit strange and not correct.

Das ist jetzt (zwar das selbe Modell) aber ein anderes Problem; bitte ein neues Issue machen.
