### ISSUE TITLE
[ili2gpkg] Invalid Default Constraint in Generated Geopackage

### ISSUE THREAD

**Issue by tgerstendoerfer** [claeis/ili2db#462]
When using _ili2gpkg_ to generate a new, empty geopackage from an INTERLIS model, the default constraint for the `gpkg.contents.last_change` field is invalid (there is a spurious blank).

The issue was observed with ili2gpkg 4.7.0.

## Steps to Reproduce

1. Download https://downloads.interlis.ch/ili2gpkg/ili2gpkg-4.7.0.zip and extract its contents
2. Download the test example model https://www.interlis.ch/download/interlis2/Testbeispiel_20160812.zip and extract `RoadsSimple.ili` (this model is also included in the attached [RoadSimple-ili2gpkg-4.7.0.zip](https://github.com/claeis/ili2db/files/8339778/RoadSimple-ili2gpkg-4.7.0.zip))
3. Generate a new, empty geopackage based on the INTERLIS model:

       java -jar ili2gpkg-4.7.0.jar --schemaimport --defaultSrsAuth EPSG --defaultSrsCode 2056 --dbfile RoadsSimple.gpkg RoadsSimple.ili

## Expected

A new geopackage that additionally contains the ili2db-tables as per the model.

Particularly, the `gpk_contents` table should be defined as follows (copied from [OGC® GeoPackage Encoding Standard, Version 1.0.1, annex C.2. gpkg_contents](https://www.geopackage.org/spec101/index.html#_gpkg_contents):

    CREATE TABLE gpkg_contents (
      table_name TEXT NOT NULL PRIMARY KEY,
      data_type TEXT NOT NULL,
      identifier TEXT UNIQUE,
      description TEXT DEFAULT '',
      last_change DATETIME NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
      min_x DOUBLE,
      min_y DOUBLE,
      max_x DOUBLE,
      max_y DOUBLE,
      srs_id INTEGER,
      CONSTRAINT fk_gc_r_srs_id FOREIGN KEY (srs_id) REFERENCES gpkg_spatial_ref_sys(srs_id)
    );

## Observed

The table `gpk_contents` is defined as follows (note the spurious space in `' now'` ):

    CREATE TABLE gpkg_contents (
      table_name TEXT NOT NULL PRIMARY KEY,
      data_type TEXT NOT NULL,
      identifier TEXT UNIQUE,
      description TEXT DEFAULT '',
      last_change DATETIME NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', ' now')),
      min_x DOUBLE,
      min_y DOUBLE,
      max_x DOUBLE,
      max_y DOUBLE,
      srs_id INTEGER,
      CONSTRAINT fk_gc_r_srs_id FOREIGN KEY (srs_id) REFERENCES gpkg_spatial_ref_sys(srs_id)
    );

The model and the table are attached in [RoadSimple-ili2gpkg-4.7.0.zip](https://github.com/claeis/ili2db/files/8339778/RoadSimple-ili2gpkg-4.7.0.zip).

## Impact

When attempting to use ArcGIS Pro to add a feature class to this geopackage, the operation fails with

> EnterGpkgContents failed with SQLite error 19:'NOT NULL constraint failed: gpkg_contents.last_change':[5]

**Comment by beistehen** [comment]
workaround until this bug is fixed:

- rename `ili2gpkg-4.7.0.jar` to `ili2gpkg-4.7.0.zip`
- open the .zip file (e. g. using 7zip in Windows) and navigate to the folder `\ch\ehi\ili2gpkg\`
- replace the file `init.sql` with the correct file in this zip [replace.zip](https://github.com/claeis/ili2db/files/8344028/replace.zip) per drag and drop
- close 7zip
- rename `ili2gpkg-4.7.0.zip` back to `ili2gpkg-4.7.0.jar`
- recreate .gpkg file using the patched `ili2gpkg-4.7.0.jar`
- a new ArcGIS FC should now be correctly registered in table `gpk_contents `
