### ISSUE TITLE
ili2gpkg - can't generate tables in french

### ISSUE THREAD

**Issue by palight** [claeis/ili2db#467]
Hi, 

I'm trying to create gpkg from SIA405 files for waste water in french (https://405.sia.ch/models/2015/SIA405_Eaux_usees_2015_2_f-20180417.ili). I use this command :

java -jar ili2gpkg-4.6.1.jar --schemaimport --dbfile test20.gpkg  --nameLang fr --coalesceCatalogueRef --createEnumTabs --createNumChecks --createUnique --createFk --createFkIdx --coalesceMultiSurface --coalesceMultiLine --coalesceMultiPoint --coalesceArray --beautifyEnumDispName --createGeomIdx --createMetaInfo --createTypeConstraint --createEnumTabsWithId --createTidCol --importTid --smart2Inheritance --strokeArcs --createBasketCol --defaultSrsCode 2056 --models SIA405_EAUX_USEES_2015_LV95 SIA405/2015/SIA405_Eaux_usees_2015_2_f-20180417.ili

When I open the gpkg in qgis, all the names are in German :-(((

Can someone help me to make it in french ?

**Comment by sjib** [comment]
See https://github.com/claeis/ili2db/issues/460 for a solution. with ili2fgdb. May be it helps also with ili2gpkg
