### ISSUE TITLE
Inline enums are not listed in t_ili2db_column_prop (ili2pg V 4.7.0)

### ISSUE THREAD

**Issue by ojeker** [claeis/ili2db#469]
For inline enums, no rows are created in t_ili2db_column_prop

Expecting row to be created, with similar content for "named" and "inline" enums. Row "setting" should contain a "generic" String - for example "ch.ehi.ili2db.enumDomain".

ILI-extract for a "inline" enum:

      CLASS ClassWithEnum =
        Id : MANDATORY 0 .. 2147483647;
        NamedEnum: TestEnum;
        InlineEnum: (CodeVal1, CodeVal2);
      END ClassWithEnum;

Entry in t_ili2db_column_prop for named enum:

|tablename|subtype|columnname|tag|setting|
|---------|-------|----------|---|-------|
|classwithenum|classwithenum|namedenum|ch.ehi.ili2db.enumDomain|SO_SrEnums.TestEnum|

**Comment by claeis** [comment]
There is no ``ch.ehi.ili2db.enumDomain`` entry for this attribute, because there is no DOMAIN used (it is a enum type). (``--createEnumTabs`` (or ``--createSingleEnumTab`` or ``--createEnumTabsWithId``) create the enum table/entries for this (inline) type; maybe this helps)

**Comment by claeis** [comment]
ein neuer tag ch.ehi.ili2db.typeKind

bei einer Aufzählung (Domain basiert oder Inline) steht ENUM

Generell: Domain basiert oder Inline wird nicht unterschieden.

TextType: MTEXT | TEXT | NAME | URI
EnumerationType: ENUM
EnumTreeValueType: ENUMTREE
AlignmentType: HALIGNMENT | VALIGNMENT
BooleanType: BOOLEAN
NumericType: NUMERIC
FormattedType: FORMATTED
DateTimeType: DATE | TIMEOFDAY | DATETIME
CoordinateType: COORD | MULTICOORD
OIDType: OID
BlackboxType: XML | BINARY
ClassType: CLASSNAME
AttributePathType: ATTRIBUTENAME
LineType: POLYLINE | SURFACE | AREA | MULTIPOLYLINE | MULTISURFACE | MULTIAREA
ReferenceAttr: REFERENCE
RestrictedStructureRef: STRUCTURE

**Comment by claeis** [comment]
Ab TextType steht, bei welchem ili-Datentyp (siehe Syntaxregeln im ili RefHB) welcher Wert für die Spalte Setting benutzt wird

**Comment by claeis** [comment]
ili2db.jar; aktuell aber kein Termin/Version definiert

**Comment by claeis** [comment]
für hierarchische und flache ENUM (und alle anderen ili Datentypen auch) immer ch.ehi.ili2db.typeKind
