### ISSUE TITLE
Encoding issues with Umlaute

### ISSUE THREAD

**Issue by edigonzales** [claeis/ili2db#47]
Ubuntu 16.04 with locale set to utf-8:
`LANG=en_US.UTF-8`
`LANGUAGE=en_US`
`LC_CTYPE="en_US.UTF-8"`
`LC_NUMERIC=de_CH.UTF-8`
`LC_TIME=de_CH.UTF-8`
`LC_COLLATE="en_US.UTF-8"`
`LC_MONETARY=de_CH.UTF-8`
`LC_MESSAGES="en_US.UTF-8"`
`LC_PAPER=de_CH.UTF-8`
`LC_NAME=de_CH.UTF-8`
`LC_ADDRESS=de_CH.UTF-8`
`LC_TELEPHONE=de_CH.UTF-8`
`LC_MEASUREMENT=de_CH.UTF-8`
`LC_IDENTIFICATION=de_CH.UTF-8`
`LC_ALL=`

PostgreSQL 9.5.5 and database is utf8 encoded:
`SHOW SERVER_ENCODING`shows `UTF8`

The comments of classes etc do not show correct umlauts:

![screenshot_2017-02-23_12-46-47](https://cloud.githubusercontent.com/assets/2767800/23257939/46509ce2-f9c6-11e6-8fdc-0850d2a04089.png)

**Comment by claeis** [comment]
This is an ili2c.jar issue

**Comment by claeis** [comment]
see claeis/ili2c#14
