### ISSUE TITLE
ili24: LIST/BAG mit primitiven Typen (nicht nur mit Strukturen)

### ISSUE THREAD

**Issue by claeis** [claeis/ili2db#471]

**Comment by olivergrimm** [comment]
@claeis Wir sehen nun vor, dass für jeden Attributtyp, welcher als primitiver Typ in einer BAG oder LIST verwendet wird, eine eigene entsprechende Tabelle erstellt wird. (Damit wird für primitive Typen in BAG / LIST der Parameter `--structWithGenericRef` keine Wirkung haben)
