### ISSUE TITLE
ili2fgdb produces duplicate value with ALL OF in French

### ISSUE THREAD

**Issue by sjib** [claeis/ili2db#476]
New issue following up https://github.com/claeis/ili2db/issues/460

There is one open issue with the attribut Status

![test6 gdb_etat_valeur_in_Betrieb_fehlt_nur_10_statt_11_Werte](https://user-images.githubusercontent.com/1265865/166468930-a5d36432-c1f2-4d40-afd3-7ca6d48cf34d.jpg)

Here we have the following INTERLIS definitions:

 !!@comment = "Betriebs- und Planungszustand. neu 2010: Erweiterungen dazu in den einzelnen Medien definieren"

`    Status= (   `
`             ausser_Betrieb,`  
`             in_Betrieb,`
`             tot,  `
`             unbekannt,` 
`             weitere `
`            );`

and then extended:

!!@ comment = "Erweitert Wertebereich von SIA405 Status Betriebs- und Planungszustand."

`Statuswerte EXTENDS SIA405_Base_Abwasser_LV95.Status = (  `
!!@ comment = "Erweiterung Basiswerte im Medium, hierarchische Modellierung und Anpassung mit Compiler 4.5.13"
	  !!@ comment = "fasst in_Betrieb und folgende Werte zusammen"
`      in_Betrieb (`
`         provisorisch,`
`         wird_aufgehoben`
`      ),`
	  !!@ comment = "fasst tot und folgende Werte zusammen"
`      tot (`
         !!@ comment = "  tot,   !! existiert nicht im Medium Abwasser"
`        aufgehoben_nicht_verfuellt,`
`        aufgehoben_unbekannt,`
`        verfuellt`
`      ),`
	  !!@ comment = "fasst weitere und folgende Werte zusammen"
`      weitere (`
`         Berechnungsvariante,`
`         geplant,`
`         Projekt`
`      )`
 `   );    `
!!@ comment = "neu 17.7.2015 Erweitert Wertebereich von SIA405 Status"
`    Status = ALL OF Statuswerte;`

So `ausser_Betrieb` is currently twice in the value list - that is a bit strange and not correct. As far as I understand ALL OF should give me 14 different values, now I have 15 because `ausser_Betrieb`  is listed twice. So I even cannot JOIN the two table easily.

- Nice would be also to have all values of Statuswerte in one table. 
- How could this be influenced? 
- With an ini / toml file configuration or should this be corrected in the code.

**Comment by claeis** [comment]
The issue is, that a DOMAIN based on ALL OF is not mapped at all.

**Comment by claeis** [comment]
Pls retest with current snapshot
