### ISSUE TITLE
ili2pg-4.8.0: itf-Codierung Aufzählwerte

### ISSUE THREAD

**Issue by leafelber** [claeis/ili2db#478]
Beim AV-Schemaimport ([DM01AV_ZG_V24_01_02LV95](https://models.geo.zg.ch/AGG/DM01AV_ZG_V24_01_02LV95.ili)) werden **ab/mit ili2pg-Version 4.8.0** plötzlich andere (willkürliche?) itfcodes für die Domänen in der PG-DB angelegt (Beispiel Bodenbedeckungsart):

![grafik](https://user-images.githubusercontent.com/73577577/183405340-b5284813-c585-4aa8-ba03-d644f7561f0b.png)

Dies entspricht nicht der Codierung gemäss Datenmodell:
`BBArt = (
        Gebaeude,
        befestigt (
          Strasse_Weg,
          Trottoir,
          Verkehrsinsel,
          Bahn,
          Flugplatz,
          Wasserbecken,
          uebrige_befestigte),
        humusiert (
          Acker_Wiese_Weide,
          Intensivkultur (
            Reben,
            uebrige_Intensivkultur),
          Gartenanlage,
          Hoch_Flachmoor,
          uebrige_humusierte),
        Gewaesser (
          stehendes,
          fliessendes,
          Schilfguertel),
        bestockt (
          geschlossener_Wald,
          Wytweide (  !! Wytweide = bestockte Weide
            Wytweide_dicht,
            Wytweide_offen),
          uebrige_bestockte),
        vegetationslos (
          Fels,
          Gletscher_Firn,
          Geroell_Sand,
          Abbau_Deponie,
          uebrige_vegetationslose));`

Dieses Verhalten können wir bei allen Codierungen der Aufzählwerte feststellen.
Am Importskript selbst hat sich nichts geändert. Wir greifen lediglich auf die neue ili2pg-Version 4.8.0 zu.

Was könnte das Problem sein?

**Comment by edigonzales** [comment]
Ich glaube es ist dieser Commit https://github.com/claeis/ili2db/commit/6378999cfc6c55d2b11551389ecf83adfe7cedae 
Mit der Snapshot-Version davor ist es noch richtig. Mit der Snapshot-Version, die aufgrund des Commits erstellt wurde, ist es falsch.
