### ISSUE TITLE
ili2pg export of multiple datasets with --baskets

### ISSUE THREAD

**Issue by mwa** [claeis/ili2db#48]
I am trying to export a subset of my imported datasets.
As `--export --dataset` only supports a single dataset, I tried to use `--export --baskets` with the BIDs of the baskets of the desired datasets.

I observed the following (using ili2pg 3.6.1):
* the basket BID seems to refer to the `t_ili2db_basket.t_ili_tid` column and not to `t_ili2db_basket.t_id`
* different datasets still get the same `t_ili2db_basket.t_ili_tid` values for the same topic
* only data from a single dataset is exported if there are multiple instances of the same `t_ili2db_basket.t_ili_tid`

#### table t_ili2db_dataset
t_id | datasetname
--- | ---
123 | A
456 | B
789 | C

#### table t_ili2db_basket
t_id | dataset | topic | t_ili_tid | attachmentkey
--- | --- | --- | --- | ---
10 | 123 | Topic | itf0 | a.itf
11 | 123 | Topic2 | itf1 | a.itf
20 | 456 | Topic | itf0 | b.itf
21 | 456 | Topic2 | itf1 | b.itf
30 | 789 | Topic | itf0 | c.itf
31 | 789 | Topic2 | itf1 | c.itf

To export the datasets B and C, I would like to select only their baskets `t_id` (20, 21, 30, 31), e.g.

    ili2pg ... --export --baskets "20;21;30;31" output.xtf

Possible solutions:
* the basket BID could refer to the `t_ili2db_basket.t_id` column (instead of `t_ili2db_basket.t_ili_tid`)
* or the import could generate unique values for `t_ili2db_basket.t_ili_tid` for each dataset
* or support for multiple `--datasets` when exporting data

**Comment by claeis** [comment]
The --basket BID refers to the t_ili2db_basket.t_ili_tid column and not to t_ili2db_basket.t_id. The t_id is an internal id.
ITF files have not BID. ili2pg generates in this case the BID (which not unique). Will change the BID generation to $dataset.$topicname if --dataset is used.
