### ISSUE TITLE
--createGeomIdx does not work/index name not unique

### ISSUE THREAD

**Issue by edigonzales** [claeis/ili2db#49]
`java -jar apps/ili2pg-3.6.1/ili2pg.jar --dbhost 192.168.50.4 --dbport 5432 --dbdatabase xanadu2 --dbschema av_lro_neua --dbusr stefan --dbpwd XXXXX --disableValidation --sqlEnableNull --nameByTopic --defaultSrsCode 2056 --strokeArcs --createGeomIdx --skipPolygonBuilding --createBasketCol --models DM01AVCH24DLV95 --schemaimport`

`java.io.IOException: failed to add index on column av_lro_neua.fixpunktktgrie1_hfp1nachfuehrung_perimeter._geom
  failed to add index on column av_lro_neua.fixpunktktgrie1_hfp1nachfuehrung_perimeter._geom
    ERROR: relation "fixpnktktgr1_hfhrng_prmter__geom_idx" already exists`

**Comment by claeis** [comment]
analysis: ili2pg creates a unique index name per table (but must be unique per schema)
