### ISSUE TITLE
Automatische Übersetzungen von Domänen in der entsprechenden Tabelle

### ISSUE THREAD

**Issue by kglaus** [claeis/ili2db#490]
Bei der Erstellung von mehrsprachigen Modellen mit ili2db wäre es sehr hilfreich, wenn die Domänennamen in den jeweiligen Tabellen ebenfalls noch mit den anderen vorhanden Sprachen ergänzt werden.
Dies könnte z.B. mit einem optionalen Befehl wie `--createDomainTranslation` geschehen. Dies macht die Weiterverarbeitung der Daten in ein mehrsprachiges Benutzerderivat viel weniger aufwändig.

**Comment by claeis** [comment]
Welche "Domain"-Namen genau? Bitte kleines Modell hinzufügen.

**Comment by kglaus** [comment]
Zum Beispiel die Nutzungsplanung 1.2:
Hier gibt es die Modelle in allen drei Sprachen mittels Tranlsation-Of:
https://models.geo.admin.ch/ARE/Nutzungsplanung_V1_2.ili
https://models.geo.admin.ch/ARE/PlansDAffectation_V1_2.ili
https://models.geo.admin.ch/ARE/PianiDiUtilizzazione_V1_2.ili

Dies habe drei Domains (RechtsStatus, DokumentTyp & Verbindlichkeit). Wenn ich bei mir nun das deutsche Modell anlege und die anderen beiden Modelle zusätzlich mitgebe, wäre es super, wenn diese Domänen direkt auch mit den Übersetzungen in der "Domänentabelle" erstellt werden. 
Ich hoffe das war etwas verständlicher.

**Comment by claeis** [comment]
Also die Wertenamen, z.B.

      enVigueur,
      ModificationAvecEffetAnticipe,
      ModificationSansEffetAnticipe

**Comment by kglaus** [comment]
Genau, damit man bei einer Weiterverarbeitung der Daten aus dem Ilischema auch direkt die Übersetzungen der Domänenwerte hat.

**Comment by claeis** [comment]
#350
