### ISSUE TITLE
[ili2pg] no gui on macOS 

### ISSUE THREAD

**Issue by edigonzales** [claeis/ili2db#496]
Since v4.6.0 there is no more GUI showing up on a Apple M1. It's only showing some error window. I'm using Java 11. 

<img width="644" alt="Screenshot 2022-10-26 at 20 04 51" src="https://user-images.githubusercontent.com/2767800/198102744-944b24d7-0de7-4292-bd28-2aae0058579f.png">

**Comment by edigonzales** [comment]
Und sollte im "no-gui"-Modus dann dafür überhaupt kein GUI kommen und nur in die Konsole geloggt werden (wie bei ili2c), dass kein GUI vorhanden ist. Jetzt wird in einem Swing-GUI geloggt, dass keine GUI vorhanden ist, was wiederum nicht GraalVM-tauglich ist.

**Comment by claeis** [comment]
so wie es im ili2c ist, ist es ok?

**Comment by edigonzales** [comment]
Sicher so wie beim ilivalidator. Dort funktioniert es prima.
