### ISSUE TITLE
MultilingualText issue with ili2gpkg

### ISSUE THREAD

**Issue by edigonzales** [claeis/ili2db#50]
Create schema, import external xml and import some data:

`java -jar apps/ili2gpkg-3.6.1/ili2gpkg.jar --dbfile data/gpkg/ch_bazl_safetyzones.gpkg --importTid --sqlEnableNull --createFkIdx --createGeomIdx --createBasketCol --models OeREBKRM09trsfr --disableValidation --nameByTopic --defaultSrsCode 21781 --schemaimport`

`java -jar apps/ili2gpkg-3.6.1/ili2gpkg.jar --dbfile  data/gpkg/ch_bazl_safetyzones.gpkg --importTid --sqlEnableNull --createFkIdx --createGeomIdx --createBasketCol --models OeREBKRM09trsfr --disableValidation --nameByTopic --defaultSrsCode 21781 --import data/ch_bazl_safetyzones/oerebkrm09gesetze.xml`

`java -jar apps/ili2gpkg-3.6.1/ili2gpkg.jar --dbfile  data/gpkg/ch_bazl_safetyzones.gpkg --importTid --sqlEnableNull --createFkIdx --createGeomIdx --createBasketCol --models OeREBKRM09trsfr --disableValidation --nameByTopic --defaultSrsCode 21781 --import data/ch_bazl_safetyzones/108_1_SafetyZonePlans_OerebTransfer_V1_20130909.xtf`

Export it again:

`java -jar apps/ili2gpkg-3.6.1/ili2gpkg.jar --dbfile  data/gpkg/ch_bazl_safetyzones.gpkg --importTid --sqlEnableNull --createFkIdx --createGeomIdx --createBasketCol --models OeREBKRM09trsfr --disableValidation --nameByTopic --defaultSrsCode 21781 --export fubar.xtf`

Throws a lot of errors like:

`Error: failed to query structure elements MultilingualText09.MultilingualText`
`Error:   no such column: 'T_Id'`

**Comment by CoNussberger** [comment]
The same error is appearing when trying to export data for the model http://models.geo.admin.ch/BLW/Nutzungsflaechen_V1_4.ili  of the MGDM Landwirtschaftliche Bewirtschaftung.

There are two structures for wich the error is thrown:
1.
```
Error: failed to query structure elements Nutzungsflaechen_LV95_V1_4.MultiPoint
Error:   no such column: 'id_neu'
```

2.
```
Error: failed to query structure elements Nutzungsflaechen_Kataloge_V1_4.LNF_Kataloge.LNF_Katalog_ProgrammRef
Error:   no such column: 'id_neu'
```

The following Command is used to export:
`java -jar ili2gpkg.jar --export --models Nutzungsflaechen_LV95_V1_4 --dbfile Y:\Anwend\AGRAR\MGDM_LandwirtschaftlicheBewirschaftung\GELAN\nutzungsflaechen_SO_20170331_2.gpkg --log Y:\Anwend\AGRAR\MGDM_LandwirtschaftlicheBewirschaftung\XTF\log_nutzungsflaechen.txt Y:\Anwend\AGRAR\MGDM_LandwirtschaftlicheBewirschaftung\XTF\nutzungsflaechen_V1_4_2017_SO.xtf`

The Geopackage with data can be provided if needed.

**Comment by claeis** [comment]
while fixing this issue, discovered new issue #77
