### ISSUE TITLE
tid: value <...> is not a valid OID

### ISSUE THREAD

**Issue by jb202302** [claeis/ili2db#506]
Guten Tag

Beim Import von Interlis Daten in unsere PG Datenbank mittels dem ili2db Tool kommt es zu folgendem Fehler mit der tid. Beispiel:

tid 454553F2-E5B8-42CC-961C-1DFB7A448FB9: value <454553F2-E5B8-42CC-961C-1DFB7A448FB9> is not a valid OID

Bei anderen Interlis Files, welche eine tid in form einer ch-ID (z.B. ch198xawGRmmhtbj) haben, gibt es diesen Fehler nicht.

Bezieht sich folgender Eintrag aus der Anleitung auf dieses Problem?

"PostGIS: Als Datenbank muss mindestens PostgreSQL 8.3 und PostGIS 1.5 vorhanden sein. Falls das Interlis Datenmodell INTERLIS.UUIDOID als OID verwendet, wird die Funktion uuid_generate_v4() verwendet. Dazu muss die PostgreSQL-Erweiterung uuid-ossp konfiguriert sein (CREATE EXTENSION "uuid-ossp";). Mit der Option --setupPgExt erstellt ili2pg die fehlenden notwendigen Erweiterungen."

Wenn ja, muss der Parameter --setupPgExt in der Erstellung der PG-Datenbank integriert werden, oder kann dieser auch in einem --replace Statement verwendet werden?

Wenn nein, gibt es sonst eine Lösung ausser der Anpassung der TID während des Interlis Exports?

Vielen Dank für die Antwort im Voraus!

**Comment by beistehen** [comment]
Falls im Datenmodell die OID als `STANDARDOID` definiert ist, so ist die Verwendung einer UUID wie _454553F2-E5B8-42CC-961C-1DFB7A448FB9_ nicht erlaubt und wird zurecht als Fehler gemeldet.

**Comment by claeis** [comment]
Das ili-Modell ist nicht ganz korrekt. Um eine UUID zu definieren, muss INTERLIS.UUIDOID benutzt werden.
Die Fehlermeldung ist ein Validierungsfehler; der Workaround besteht somit darin, die Validierung auszuschalten (--disableValidation)

**Comment by jb202302** [comment]
Vielen Dank für die rasche Antwort. Mit diesen Inputs lässt sich das Problem lösen
