### ISSUE TITLE
--createEnumTabs creates unnecessary enum tables for Boolean types

### ISSUE THREAD

**Issue by gacarrillor** [claeis/ili2db#51]
`BOOLEAN` attributes from the `ili` file (see first line in the image below, attribute `cabeza_hogar`) are created in PostgreSQL as `booleans`. So far so good.

![BOOLEAN from the ili](http://downloads.tuxfamily.org/tuxgis/tmp/ai/inline_enum_01.png)

However, when using `--createEnumTabs` an unnecessary enum table is being created for such attribute:

![Extra enum table](http://downloads.tuxfamily.org/tuxgis/tmp/ai/boolean_enum_table_01.png)

**Comment by edigonzales** [comment]
duplicate #5
