### ISSUE TITLE
ili2db - error EPSG does not exist

### ISSUE THREAD

**Issue by S4mHi6ru** [claeis/ili2db#520]
Hi

Ich muss ein xtf des kantonalen Modells GL_Gefahrenkartierung_v1_3 in ein QGIS GeoPackage importieren. 
Vor einigen Updates hatte das mal funktioniert. Nun erhalte ich beim Import folgende Fehlermeldung
`EPSG/2056 does not exist`

Die XTF Daten sind fehlerfrei. Der Log ist beigelegt. 
[GL_Gefahrenkartierung_20230623-02_LOG.log](https://github.com/claeis/ili2db/files/11868137/GL_Gefahrenkartierung_20230623-02_LOG.log)

Kennt wer eine Lösung zu diesem Fehler oder woher dieser kommt?

**Comment by S4mHi6ru** [comment]
Vollständiger Log des Model Baker:
`"C:\Program Files\Common Files\Oracle\Java\javapath\java.exe" -jar C:\Users\username\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\QgisModelBaker\libs\modelbaker\iliwrapper\bin\ili2gpkg-4.10.0\ili2gpkg-4.10.0.jar --schemaimport --dbfile C:/Temp/_Geomedia/Gefahrenkartierung/02_Bearbeitung/DB/GL_Gefahrenkartierung.gpkg --coalesceCatalogueRef --createEnumTabs --createNumChecks --createUnique --createFk --createFkIdx --coalesceMultiSurface --coalesceMultiLine --coalesceMultiPoint --coalesceArray --beautifyEnumDispName --createGeomIdx --createMetaInfo --expandMultilingual --createTypeConstraint --createEnumTabsWithId --createTidCol --smart1Inheritance --strokeArcs=False --createBasketCol --defaultSrsAuth EPSG --defaultSrsCode 2056 --preScript NULL --postScript NULL --models GL_Gefahrenkartierung_V1_3 --iliMetaAttrs NULL
Info: dburl <jdbc:sqlite:C:/Temp/_Geomedia/Gefahrenkartierung/02_Bearbeitung/DB/GL_Gefahrenkartierung.gpkg>
Info: dbusr <>
Info: ili2gpkg-4.10.0-c2af4b50c5475f788286f974812b52bb0f9b19bc
Info: ili2c-5.3.2-6fb5df2877070aeb16c7b39a206a61e2518682c8
Info: iox-ili-1.21.15-f055cd0e781e5b2754c475ec4573eb3bed12bd8b
Info: java.version 19.0.2
Info: user.name <username>
Info: maxMemory 8310784 KB
Info: currentTime 2023-06-26 13:48:45
Info: dburl <jdbc:sqlite:C:/Temp/_Geomedia/Gefahrenkartierung/02_Bearbeitung/DB/GL_Gefahrenkartierung.gpkg>
Info: dbusr <>
Info: databaseProduct <SQLite>
Info: databaseVersion <3.8.11>
Info: driverName <SQLiteJDBC>
Info: driverVersion <native>
Info: max active DB statements <0>
Info: compile models...
Info: lookup model <GL_Gefahrenkartierung_V1_3> in repository <http://models.interlis.ch/>
Info: lookup model <GL_Gefahrenkartierung_V1_3> in repository <http://models.geo.admin.ch/>
Info: lookup model <GL_Gefahrenkartierung_V1_3> in repository <https://models.kgk-cgc.ch/>
Info: lookup model <GL_Gefahrenkartierung_V1_3> in repository <https://models.interlis.ch/>
Info: lookup model <GL_Gefahrenkartierung_V1_3> in repository <https://models.geo.llv.li/>
Info: lookup model <GL_Gefahrenkartierung_V1_3> in repository <https://405.sia.ch/models/>
Info: lookup model <GL_Gefahrenkartierung_V1_3> in repository <https://repositorio.proadmintierra.info/>
Info: lookup model <GL_Gefahrenkartierung_V1_3> in repository <http://models.geo.ai.ch/>
Info: lookup model <GL_Gefahrenkartierung_V1_3> in repository <https://models.geo.kgk-cgc.ch/>
Info: lookup model <GL_Gefahrenkartierung_V1_3> in repository <https://models.geo.ar.ch/>
Info: lookup model <GL_Gefahrenkartierung_V1_3> in repository <http://models.geo.kgk-cgc.ch/>
Info: lookup model <GL_Gefahrenkartierung_V1_3> in repository <https://models.geo.be.ch/>
Info: lookup model <GL_Gefahrenkartierung_V1_3> in repository <http://models.geo.bl.ch/>
Info: lookup model <GL_Gefahrenkartierung_V1_3> in repository <https://models.geo.bs.ch/>
Info: lookup model <GL_Gefahrenkartierung_V1_3> in repository <https://models.geo.gl.ch/>
Info: lookup model <GeometryCHLV95_V1> 2.3 in repository <http://models.interlis.ch/>
Info: lookup model <GeometryCHLV95_V1> 2.3 in repository <http://models.geo.admin.ch/>
Info: lookup model <Hazard_Mapping_LV95_V1_3> 2.3 in repository <http://models.interlis.ch/>
Info: lookup model <Hazard_Mapping_LV95_V1_3> 2.3 in repository <http://models.geo.admin.ch/>
Info: lookup model <CoordSys> 2.3 in repository <http://models.interlis.ch/>
Info: lookup model <Units> 2.3 in repository <http://models.interlis.ch/>
Info: ilifile <C:\Users\username\.ilicache\models.interlis.ch\refhb23\CoordSys-20151124.ili>
Info: ilifile <C:\Users\username\.ilicache\models.interlis.ch\refhb23\Units-20120220.ili>
Info: ilifile <C:\Users\username\.ilicache\models.geo.admin.ch\CH\CHBase_Part1_GEOMETRY_V1.ili>
Info: ilifile <C:\Users\username\.ilicache\models.geo.admin.ch\BAFU\Hazard_Mapping_V1_3.ili>
Info: ilifile <C:\Users\username\.ilicache\models.geo.gl.ch\ili\GL_Gefahrenkartierung_V1_3_2021-04-28.ili>
EPSG/2056 does not exist
Mit Fehlern beendet!`

**Comment by edigonzales** [comment]
Funktioniert bei mir auf in der Konsole (macOS). 

Kannst du den Befehl mit `--trace` starten? Dann sieht man eventuell mehr resp. vielleicht sogar die SQL-Query (?) oder was auch immer schief läuft.

**Comment by beistehen** [comment]
Ich habe deinen Befehl in der Kommandozeile nachgestellt:

`java -jar C:\Software\ili2gpkg\bin\ili2gpkg-4.10.0\ili2gpkg-4.10.0.jar --schemaimport --dbfile .\temp.gpkg --coalesceCatalogueRef --createEnumTabs --createNumChecks --createUnique --createFk --createFkIdx --coalesceMultiSurface --coalesceMultiLine --coalesceMultiPoint --coalesceArray --beautifyEnumDispName --createGeomIdx --createMetaInfo --expandMultilingual --createTypeConstraint --createEnumTabsWithId --createTidCol --smart1Inheritance --strokeArcs=False --createBasketCol --defaultSrsAuth EPSG --defaultSrsCode 2056 --preScript NULL --postScript NULL --models GL_Gefahrenkartierung_V1_3 --iliMetaAttrs NULL`

Dies führt zu folgendem, erfolgreichem Output:

```
Info: dburl <jdbc:sqlite:.\temp.gpkg>
Info: dbusr <>
Info: ili2gpkg-4.10.0-c2af4b50c5475f788286f974812b52bb0f9b19bc
Info: ili2c-5.3.2-6fb5df2877070aeb16c7b39a206a61e2518682c8
Info: iox-ili-1.21.15-f055cd0e781e5b2754c475ec4573eb3bed12bd8b
Info: java.version 1.8.0_282
Info: user.name <stehen>
Info: maxMemory 3690496 KB
Info: currentTime 2023-06-26 14:12:43
Info: dburl <jdbc:sqlite:.\temp.gpkg>
Info: dbusr <>
Info: databaseProduct <SQLite>
Info: databaseVersion <3.8.11>
Info: driverName <SQLiteJDBC>
Info: driverVersion <native>
Info: max active DB statements <0>
Info: compile models...
Info: lookup model <GL_Gefahrenkartierung_V1_3> in repository <http://models.interlis.ch/>
Info: lookup model <GL_Gefahrenkartierung_V1_3> in repository <http://models.geo.admin.ch/>
Info: lookup model <GL_Gefahrenkartierung_V1_3> in repository <https://models.kgk-cgc.ch/>
Info: lookup model <GL_Gefahrenkartierung_V1_3> in repository <https://models.interlis.ch/>
Info: lookup model <GL_Gefahrenkartierung_V1_3> in repository <https://models.geo.llv.li/>
Info: lookup model <GL_Gefahrenkartierung_V1_3> in repository <https://405.sia.ch/models/>
Info: lookup model <GL_Gefahrenkartierung_V1_3> in repository <https://repositorio.proadmintierra.info/>
Info: lookup model <GL_Gefahrenkartierung_V1_3> in repository <http://models.geo.ai.ch/>
Info: lookup model <GL_Gefahrenkartierung_V1_3> in repository <https://models.geo.kgk-cgc.ch/>
Info: lookup model <GL_Gefahrenkartierung_V1_3> in repository <https://models.geo.ar.ch/>
Info: lookup model <GL_Gefahrenkartierung_V1_3> in repository <http://models.geo.kgk-cgc.ch/>
Info: lookup model <GL_Gefahrenkartierung_V1_3> in repository <https://models.geo.be.ch/>
Info: lookup model <GL_Gefahrenkartierung_V1_3> in repository <http://models.geo.bl.ch/>
Info: lookup model <GL_Gefahrenkartierung_V1_3> in repository <https://models.geo.bs.ch/>
Info: lookup model <GL_Gefahrenkartierung_V1_3> in repository <https://models.geo.gl.ch/>
Info: lookup model <GeometryCHLV95_V1> 2.3 in repository <http://models.interlis.ch/>
Info: lookup model <GeometryCHLV95_V1> 2.3 in repository <http://models.geo.admin.ch/>
Info: lookup model <Hazard_Mapping_LV95_V1_3> 2.3 in repository <http://models.interlis.ch/>
Info: lookup model <Hazard_Mapping_LV95_V1_3> 2.3 in repository <http://models.geo.admin.ch/>
Info: lookup model <Units> 2.3 in repository <http://models.interlis.ch/>
Info: lookup model <CoordSys> 2.3 in repository <http://models.interlis.ch/>
Info: ilifile <C:\Users\stehen\.ilicache\models.interlis.ch\refhb23\CoordSys-20151124.ili>
Info: ilifile <C:\Users\stehen\.ilicache\models.interlis.ch\refhb23\Units-20120220.ili>
Info: ilifile <C:\Users\stehen\.ilicache\models.geo.admin.ch\CH\CHBase_Part1_GEOMETRY_V1.ili>
Info: ilifile <C:\Users\stehen\.ilicache\models.geo.admin.ch\BAFU\Hazard_Mapping_V1_3.ili>
Info: ilifile <C:\Users\stehen\.ilicache\models.geo.gl.ch\ili\GL_Gefahrenkartierung_V1_3_2021-04-28.ili>
Info: create table structure, if not existing...
Info: ...done
```

Der einzige Unterschied, den ich gerade erkennen kann, ist die unterschiedliche Java-Version (`java.version 19.0.2` vs. `java.version 1.8.0_282`.

Falls du nichts an den Modellen in .ilicache\ herumgebastelt hast, so sollte also alles normal durchlaufen.

Vorschlag von @edigonzales mit `--trace` ist ein guter nächster Schritt...

**Comment by edigonzales** [comment]
Funktioniert bei mir auch mit Java 19.

**Comment by S4mHi6ru** [comment]
hmm. 

mit einer neuen gpkg Datei hat es nun auch funktioniert. 

` > ---------- Model Baker - Workflow Wizard
 > ---------- Source Selektion
Add source GL_Gefahrenkartierung_V1_3 (repository) Vom Benutzer über den Wizard hinzugefügt.
 > ---------- Datenbank Konfiguration
Aktualisiere verfügbare Modelle:
 > ---------- Schema Import Konfiguration
 > ---------- Schema Import Sessions
"C:\Program Files\Common Files\Oracle\Java\javapath\java.exe" -jar C:\Users\samuel.hirsbrunner.g\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\QgisModelBaker\libs\modelbaker\iliwrapper\bin\ili2gpkg-4.10.0\ili2gpkg-4.10.0.jar --schemaimport --dbfile C:/Temp/_Geomedia/Gefahrenkartierung/02_Bearbeitung/DB/GL_Gefahrenkartierung4.gpkg --coalesceCatalogueRef --createEnumTabs --createNumChecks --createUnique --createFk --createFkIdx --coalesceMultiSurface --coalesceMultiLine --coalesceMultiPoint --coalesceArray --beautifyEnumDispName --createGeomIdx --createMetaInfo --expandMultilingual --createTypeConstraint --createEnumTabsWithId --createTidCol --smart1Inheritance --strokeArcs=False --createBasketCol --defaultSrsAuth EPSG --defaultSrsCode 2056 --preScript NULL --postScript NULL --models GL_Gefahrenkartierung_V1_3 --iliMetaAttrs NULL
Info: dburl <jdbc:sqlite:C:/Temp/_Geomedia/Gefahrenkartierung/02_Bearbeitung/DB/GL_Gefahrenkartierung4.gpkg>
Info: dbusr <>
Info: ili2gpkg-4.10.0-c2af4b50c5475f788286f974812b52bb0f9b19bc
Info: ili2c-5.3.2-6fb5df2877070aeb16c7b39a206a61e2518682c8
Info: iox-ili-1.21.15-f055cd0e781e5b2754c475ec4573eb3bed12bd8b
Info: java.version 19.0.2
Info: user.name <samuel.hirsbrunner.g>
Info: maxMemory 8310784 KB
Info: currentTime 2023-06-26 14:48:50
Info: dburl <jdbc:sqlite:C:/Temp/_Geomedia/Gefahrenkartierung/02_Bearbeitung/DB/GL_Gefahrenkartierung4.gpkg>
Info: dbusr <>
Info: databaseProduct <SQLite>
Info: databaseVersion <3.8.11>
Info: driverName <SQLiteJDBC>
Info: driverVersion <native>
Info: max active DB statements <0>
Info: compile models...
Info: lookup model <GL_Gefahrenkartierung_V1_3> in repository <http://models.interlis.ch/>
Info: lookup model <GL_Gefahrenkartierung_V1_3> in repository <http://models.geo.admin.ch/>
Info: lookup model <GL_Gefahrenkartierung_V1_3> in repository <https://models.kgk-cgc.ch/>
Info: lookup model <GL_Gefahrenkartierung_V1_3> in repository <https://models.interlis.ch/>
Info: lookup model <GL_Gefahrenkartierung_V1_3> in repository <https://models.geo.llv.li/>
Info: lookup model <GL_Gefahrenkartierung_V1_3> in repository <https://405.sia.ch/models/>
Info: lookup model <GL_Gefahrenkartierung_V1_3> in repository <https://repositorio.proadmintierra.info/>
Info: lookup model <GL_Gefahrenkartierung_V1_3> in repository <http://models.geo.ai.ch/>
Info: lookup model <GL_Gefahrenkartierung_V1_3> in repository <https://models.geo.kgk-cgc.ch/>
Info: lookup model <GL_Gefahrenkartierung_V1_3> in repository <https://models.geo.ar.ch/>
Info: lookup model <GL_Gefahrenkartierung_V1_3> in repository <http://models.geo.kgk-cgc.ch/>
Info: lookup model <GL_Gefahrenkartierung_V1_3> in repository <https://models.geo.be.ch/>
Info: lookup model <GL_Gefahrenkartierung_V1_3> in repository <http://models.geo.bl.ch/>
Info: lookup model <GL_Gefahrenkartierung_V1_3> in repository <https://models.geo.bs.ch/>
Info: lookup model <GL_Gefahrenkartierung_V1_3> in repository <https://models.geo.gl.ch/>
Info: lookup model <GeometryCHLV95_V1> 2.3 in repository <http://models.interlis.ch/>
Info: lookup model <GeometryCHLV95_V1> 2.3 in repository <http://models.geo.admin.ch/>
Info: lookup model <Hazard_Mapping_LV95_V1_3> 2.3 in repository <http://models.interlis.ch/>
Info: lookup model <Hazard_Mapping_LV95_V1_3> 2.3 in repository <http://models.geo.admin.ch/>
Info: lookup model <CoordSys> 2.3 in repository <http://models.interlis.ch/>
Info: lookup model <Units> 2.3 in repository <http://models.interlis.ch/>
Info: ilifile <C:\Users\samuel.hirsbrunner.g\.ilicache\models.interlis.ch\refhb23\CoordSys-20151124.ili>
Info: ilifile <C:\Users\samuel.hirsbrunner.g\.ilicache\models.interlis.ch\refhb23\Units-20120220.ili>
Info: ilifile <C:\Users\samuel.hirsbrunner.g\.ilicache\models.geo.admin.ch\CH\CHBase_Part1_GEOMETRY_V1.ili>
Info: ilifile <C:\Users\samuel.hirsbrunner.g\.ilicache\models.geo.admin.ch\BAFU\Hazard_Mapping_V1_3.ili>
Info: ilifile <C:\Users\samuel.hirsbrunner.g\.ilicache\models.geo.gl.ch\ili\GL_Gefahrenkartierung_V1_3_2021-04-28.ili>
Info: create table structure, if not existing...
Info: ...done
Interlis Modelle wurden erfolgreich in die Datenbank importiert!
Erstelle Standard-Dataset Baseset
Successfully created dataset "Baseset".
- Successfully created basket for topic "GL_Gefahrenkartierung_V1_3.Gefahrenkartierung".
- Successfully created basket for topic "Hazard_Mapping_LV95_V1_3.hazard_mapping".
Done!`
