### ISSUE TITLE
ili2pg text constaint fails with NULL values

### ISSUE THREAD

**Issue by ojeker** [claeis/ili2db#534]
Having a non mandatory text field like 

    /** Bemerkungen, z.B. wenn Makrozoobentos gesichtet wurden
     */
    Bemerkungen : MTEXT*1000;

Inserting a row with NULL for attribute "Bemerkungen" fails with error "...violates check constraint **quelle_ungefasst_bemerkungen_check**"

    INSERT INTO afu_quellen_ungefasst_v1.quelle_ungefasst (id_quelle, flurname, quellenname, hoehe, austrittsform, quellgroesse, schuettungsverhalten, quellschuettung, vernetzung, austrittsanzahl, bemerkungen, fassung, wasserentnahme, trittschaeden, sommerbeschattung, substrate, revitobjekt, gesamtbewertung, punkt, datum, gemeindename, x_koordinate, y_koordinate, bioerhebung, importdatum) VALUES ('SO_LB_0134', 'Chrumrain', 'Chrumrain', 605, 'Fliessquelle', 'klein', 'ganzjährig', '<1', 'Einzelquelle', 1, ' ', 'keine', 'keine', 'keine', 'nicht definiert', 'Steine,Kies,Sand,Feinmaterial,Moospolster,Wurzeln,Totholz,Pflanzen,Falllaub,Org. Schlamm', 'unklar', 'bedingt_naturnah', '0101000020080800000000008020E543410F000000DCCD3241', '2023-08-08 +00', 'Rüttenen', 2607681, 1232348, NULL, '2024-03-07 +00') was aborted: ERROR: new row for relation "quelle_ungefasst" violates check constraint "quelle_ungefasst_bemerkungen_check"

**Comment by edigonzales** [comment]
@ojeker Irgendwie kenne ich das Problem (glaubs). Es könnte eine Kombination sein mit dem Parameter `createTextChecks = true`, der bei uns default auf True ist. Wie sieht der Constraint genau aus?

**Comment by claeis** [comment]
https://www.postgresql.org/docs/current/ddl-constraints.html#DDL-CONSTRAINTS-CHECK-CONSTRAINTS

    It should be noted that a check constraint is satisfied if the check expression evaluates to true or the null value. Since most expressions will evaluate to the null value if any operand is null, they will not prevent null values in the constrained columns.

Scheint mir nicht korrekt von PG, wenn hier im Fall eines NULL das Constraint anschlägt.

**Comment by claeis** [comment]
PG ist korrekt, weil der Wert ist nicht ``NULL`` sondern ``' '`` und genau das will ja das Constraint verhindern...
