### ISSUE TITLE
support CHBase V2 Localisation smart mapping

### ISSUE THREAD

**Issue by claeis** [claeis/ili2db#547]

**Comment by olivergrimm** [comment]
this relates to the behaviour, that `--expandMultilingual` does currently not work with `LocalisationCH_V2.MultilingualText`, right?
(respectively it needs a basemodel with this addition)
```  
  !!@ili2db.mapping=Multilingual
  STRUCTURE MultilingualText EXTENDS Localisation_V2.MultilingualText =
    LocalisedText (EXTENDED) : BAG {1..*} OF LocalisedText;
  END MultilingualText;```

**Comment by claeis** [comment]
> this relates to the behaviour, that `--expandMultilingual` does currently not work with `LocalisationCH_V2.MultilingualText`, right?

ja

**Comment by patrickackermann** [comment]
GeoWerkstatt bearbeitet dieses Issue.
