### ISSUE TITLE
ili2pg does not support special characters in password

### ISSUE THREAD

**Issue by cymed** [claeis/ili2db#553]
see https://github.com/teksi/wastewater/issues/478

**Comment by beistehen** [comment]
@cymed 
Hast du geprüft, ob es nicht ein Problem im Aufruf von ili2db durch QGEP ist (wie z. B. fehlende Anführungszeichen und deshalb wird das @ im Passwort falsch interpretiert)?

**Comment by edigonzales** [comment]
@cymed Ich denke, dass es nicht ili2pg ist. Die Fehlermeldungen stammen alle von SQLAlchemy (Python). Die Fehlermeldung googlen, führt zu Stackoverflow: https://stackoverflow.com/questions/72049617/operationalerror-psycopg2-operationalerror-could-not-translate-host-name-143
