### ISSUE TITLE
ili2gpkg - support more srs

### ISSUE THREAD

**Issue by mejiafabiandj** [claeis/ili2db#60]
Currently, only supports 4326, 21781, 2056 and 'undefined'

**Comment by claeis** [comment]
Which additional ones do you want to see?

**Comment by mejiafabiandj** [comment]
Initially the most used in Colombia: 3116 and 4686, thanks

**Comment by juusechec** [comment]
Hello, for this purpose, we want to add some changes to init SQL script. I've do a Pull Request of this changes. https://github.com/claeis/ili2db/pull/64
