### ISSUE TITLE
How to identify ili DOMAINs in PostgreSQL?

### ISSUE THREAD

**Issue by gacarrillor** [claeis/ili2db#61]
In the context of the Project Generator (QGIS plugin), tables in PostgreSQL that come from ili `DOMAIN`s should be shown as drop down lists in QGIS, e.g., using the `DispName` attribute.

But, how could I distinguish PostgreSQL tables coming for ili classes from those coming from ili domains? Can this be found somewhere in the metadata tables generated by ili2pg? If it is missing, what do you think about implementing it there (perhaps in the `t_ili2db_classname` table as an additional attribute)? 

As last resort, one could have a look at each table's set of attributes to find out if `itfcode` and `ilicode` are there (in that case, the table is most likely a DOMAIN), but I think that metadata would be more convenient.

**Comment by claeis** [comment]
see also #43

**Comment by claeis** [comment]
also other requirements, see #63
