### ISSUE TITLE
QGIS INTERLIS Tools ili2pg

### ISSUE THREAD

**Issue by sjib** [claeis/ili2db#62]
Are the ili2pg Tools updated for QGIS 2.18?
Where can I find the help file? Is it elsewhere online?

![interlis_help](https://cloud.githubusercontent.com/assets/1265865/24168209/c7b59180-0e79-11e7-9522-84ba26d17d27.jpg)

**Comment by claeis** [comment]
The most up to date doc is here: https://github.com/claeis/ili2db/docs/ili2db.rst
Issues about the QGIS plugin should be created there: https://github.com/sourcepole/ogrtools
