### ISSUE TITLE
expose additional ili-model information

### ISSUE THREAD

**Issue by claeis** [claeis/ili2db#63]

**Comment by m-kuhn** [comment]
* MTEXT
* DOMAIN

(I cannot edit the top issue text in here)

**Comment by claeis** [comment]
Must also handle the case of EXTENDED attributes (in the same table, see also #19).  Use

    CREATE TABLE t_ili2db_column_prop (
     tablename varchar(255) NOT NULL,
     subtype varchar(255) NOT NULL,   -- t_type in table 'tablename'
     columnname varchar(255) NOT NULL,
     tag character varying(1024) NOT NULL,
     setting character varying(1024) NOT NULL
    );

**Comment by m-kuhn** [comment]
Should include information about many-to-many relations

**Comment by claeis** [comment]
should include information about tables that are enumerations

**Comment by claeis** [comment]
should include information about tables that are extensions of CatalogueObjects.Item

**Comment by claeis** [comment]
should include information about UNITs

**Comment by claeis** [comment]
add as option --createMetaInfo

**Comment by gacarrillor** [comment]
Summarizing:

- [x]  --createMetaInfo option
- [x]  `t_ili2db_column_prop` and `t_ili2db_table_prop` tables
- [x]  UNIT
- [x]  Kind of Table (Enum, Catalogue, Structure)
- [ ]  MTEXT (PR #96)
- [ ]  Many-to-many relations
