### ISSUE TITLE
Compiling issue by new release

### ISSUE THREAD

**Issue by giodegiorgi** [claeis/ili2db#65]
Please find attached error:

```
Buildfile: /ili2db/build-ili2pg.xml

init:

compile:
    [javac] /ili2db/build-ili2pg.xml:29: warning: 'includeantruntime' was not set, defaulting to build.sysclasspath=last; set to false for repeatable builds
    [javac] Compiling 79 source files to /ili2db/build/classes
    [javac] warning: [options] bootstrap class path not set in conjunction with -source 1.6
    [javac] /ili2db/src/ch/ehi/basics/jdbc/DriverInfo.java:24: error: error while writing DriverInfo: /ili2db/build/classes/ch/ehi/basics/jdbc/DriverInfo.class (Permission denied)
    [javac] public class DriverInfo {
    [javac]        ^
    [javac] Note: Some input files use or override a deprecated API.
    [javac] Note: Recompile with -Xlint:deprecation for details.
    [javac] Note: Some input files use unchecked or unsafe operations.
    [javac] Note: Recompile with -Xlint:unchecked for details.
    [javac] 1 error
    [javac] 1 warning

BUILD FAILED
/ili2db/build-ili2pg.xml:29: Compile failed; see the compiler error output for details.
```

**Comment by claeis** [comment]
check the permissions of the destinations file/folders ``/ili2db/build/classes/ch/ehi/basics/jdbc/DriverInfo.class``

**Comment by giodegiorgi** [comment]
just the warning present :)

`λ ant fatjar -f build-ili2pg.xml
Buildfile: E:\develop\ili2db\build-ili2pg.xml

init:

compile:
    [javac] E:\develop\ili2db\build-ili2pg.xml:29: warning: 'includeantruntime' was not set, defaulting to build.sysclasspath=last; set to false for repeatable builds
    [javac] Compiling 10 source files to E:\develop\ili2db\build\classes
    [javac] warning: [options] bootstrap class path not set in conjunction with -source 1.6
    [javac] Note: Some input files use or override a deprecated API.
    [javac] Note: Recompile with -Xlint:deprecation for details.
    [javac] Note: Some input files use unchecked or unsafe operations.
    [javac] Note: Recompile with -Xlint:unchecked for details.
    [javac] 1 warning

fatjar:
      [jar] Building jar: E:\develop\ili2db\build\jar\ili2pg-3.7.0.jar

BUILD SUCCESSFUL
Total time: 3 seconds`
