### ISSUE TITLE
Schemaimport fails when using switch epsg:2056

### ISSUE THREAD

**Issue by uncoyote** [claeis/ili2db#70]
Ciao Claude - hab ein komischer Effekt beim Nutzen von --defaultSrsAuth epsg --defaultSrsCode 2056

Das funktioniert:
~/javaora/jre1.8.0_121/bin/java -jar ~/eclipse_ws/lib/ili2pg370/ili2pg.jar --schemaimport --strokeArcs  --dbhost 192.168.56.2 --dbusr godfather --dbpwd xxx --dbdatabase sogis --dbschema afu_gewaesserschutz_export --models PlanerischerGewaesserschutz_LV95_V1_1 ~/eclipse_ws/gewschutz/tmp/ili_model/PlanerischerGewaesserschutz_V1_1.ili

Das funktioniert nicht:
~/javaora/jre1.8.0_121/bin/java -jar ~/eclipse_ws/lib/ili2pg370/ili2pg.jar --schemaimport --strokeArcs **--defaultSrsAuth epsg --defaultSrsCode 2056** --dbhost 192.168.56.2 --dbusr godfather --dbpwd xxx --dbdatabase sogis --dbschema afu_gewaesserschutz_export --models PlanerischerGewaesserschutz_LV95_V1_1 ~/eclipse_ws/gewschutz/tmp/ili_model/PlanerischerGewaesserschutz_V1_1.ili

Geht sowohl in v 3.6.1 wie v 3.7.0 nicht. Ili2pg-Log:
Info: dburl <jdbc:postgresql://192.168.56.2/sogis>
Info: dbusr <godfather>
Info: ili2pg-3.7.0-20170326
Info: ili2c-4.6.1-20170109
Info: iox-ili-1.16.0-master-20170326
Info: java.version 1.8.0_121
Info: user.name <bjsvwjek>
Info: maxMemory 3626496 KB
Info: dbschema <afu_gewaesserschutz_export>
Info: dburl <jdbc:postgresql://192.168.56.2/sogis>
Info: dbusr <godfather>
Info: databaseProduct <PostgreSQL>
Info: databaseVersion <9.2.20>
Info: driverName <PostgreSQL Native Driver>
Info: driverVersion <PostgreSQL 9.4.1208.jre6>
Info: postGISVersion <POSTGIS="1.5.8" GEOS="3.4.2-CAPI-1.8.2 r3921" PROJ="Rel. 4.8.0, 6 March 2012" LIBXML="2.9.1" USE_STATS>
Info: compile models...
Info: lookup model <CHAdminCodes_V1> 2.3 in repository </home/bjsvwjek/eclipse_ws/gewschutz/tmp/ili_model>
Info: lookup model <CHAdminCodes_V1> 2.3 in repository <http://models.interlis.ch/>
Info: lookup model <CHAdminCodes_V1> 2.3 in repository </home/bjsvwjek/eclipse_ws/lib/ili2pg370>
Info: lookup model <CHAdminCodes_V1> 2.3 in repository <http://models.geo.admin.ch>
Info: lookup model <LocalisationCH_V1> 2.3 in repository </home/bjsvwjek/eclipse_ws/gewschutz/tmp/ili_model>
Info: lookup model <LocalisationCH_V1> 2.3 in repository <http://models.interlis.ch/>
Info: lookup model <LocalisationCH_V1> 2.3 in repository </home/bjsvwjek/eclipse_ws/lib/ili2pg370>
Info: lookup model <LocalisationCH_V1> 2.3 in repository <http://models.geo.admin.ch>
Info: lookup model <GeometryCHLV03_V1> 2.3 in repository </home/bjsvwjek/eclipse_ws/gewschutz/tmp/ili_model>
Info: lookup model <GeometryCHLV03_V1> 2.3 in repository <http://models.interlis.ch/>
Info: lookup model <GeometryCHLV03_V1> 2.3 in repository </home/bjsvwjek/eclipse_ws/lib/ili2pg370>
Info: lookup model <GeometryCHLV03_V1> 2.3 in repository <http://models.geo.admin.ch>
Info: lookup model <Units> 2.3 in repository </home/bjsvwjek/eclipse_ws/gewschutz/tmp/ili_model>
Info: lookup model <Units> 2.3 in repository <http://models.interlis.ch/>
Info: lookup model <CoordSys> 2.3 in repository </home/bjsvwjek/eclipse_ws/gewschutz/tmp/ili_model>
Info: lookup model <CoordSys> 2.3 in repository <http://models.interlis.ch/>
Info: ilifile </home/bjsvwjek/.ilicache/models.geo.admin.ch/CH/CHBase_Part2_LOCALISATION_20110830.ili>
Info: ilifile </home/bjsvwjek/.ilicache/models.interlis.ch/refhb23/Units-20120220.ili>
Info: ilifile </home/bjsvwjek/.ilicache/models.interlis.ch/refhb23/CoordSys-20151124.ili>
Info: ilifile </home/bjsvwjek/.ilicache/models.geo.admin.ch/CH/CHBase_Part4_ADMINISTRATIVEUNITS_20110830.ili>
Info: ilifile </home/bjsvwjek/.ilicache/models.geo.admin.ch/CH/CHBase_Part1_GEOMETRY_20110830.ili>
Info: ilifile </home/bjsvwjek/eclipse_ws/gewschutz/tmp/ili_model/PlanerischerGewaesserschutz_V1_1.ili>
Info: create table structure...
java.io.IOException: failed to add comment to table afu_gewaesserschutz_export.gsbereich
  failed to add comment to table afu_gewaesserschutz_export.gsbereich
    ERROR: column "geometrie" of relation "afu_gewaesserschutz_export.gsbereich" does not exist

**Comment by edigonzales** [comment]
`--trace` ? Kannst du das Modell anhängen?

Funktionieren andere Modell mit EPSG:2056? 

Eventuell hat das was mit der PostGIS-Version (1.5) zu tun.

**Comment by uncoyote** [comment]
Hab gerade kein anderes Modell "zur Hand" mit EPSG:2056 - sprich ich kann nicht sagen ob andere funktionieren.


[PlanerischerGewaesserschutz_V1_1.txt](https://github.com/claeis/ili2db/files/882385/PlanerischerGewaesserschutz_V1_1.txt)
**Trace:**

Info: dburl <jdbc:postgresql://192.168.56.2/sogis>
Info: dbusr <godfather>
Info: ili2pg-3.6.1-20170120
Info: ili2c-4.6.1-20170109
Info: java.version 1.8.0_121
Info: user.name <bjsvwjek>
Info: maxMemory 3626496 KB
Info: dbschema <afu_gewaesserschutz_export>
Info: dburl <jdbc:postgresql://192.168.56.2/sogis>
Info: dbusr <godfather>
Info: databaseProduct <PostgreSQL>
Info: databaseVersion <9.2.20>
Info: driverVersion <PostgreSQL 9.4.1208.jre6>
Info: postGISVersion <POSTGIS="1.5.8" GEOS="3.4.2-CAPI-1.8.2 r3921" PROJ="Rel. 4.8.0, 6 March 2012" LIBXML="2.9.1" USE_STATS>
Info: compile models...
Info: getModelRepos(): pathmap key <%ILI_FROM_DB> (Main.java:734)
Info: getModelRepos(): pathmap key <%XTF_DIR> (Main.java:734)
Info: getModelRepos(): pathmap key <%JAR_DIR> (Main.java:734)
Info: setRepositories(): uri </home/bjsvwjek/eclipse_ws/gewschutz/tmp/ili_model> (IliManager.java:87)
Info: setRepositories(): uri <http://models.interlis.ch/> (IliManager.java:87)
Info: setRepositories(): uri </home/bjsvwjek/eclipse_ws/lib/ili2pg361> (IliManager.java:87)
Info: lookup model <CHAdminCodes_V1> 2.3 in repository </home/bjsvwjek/eclipse_ws/gewschutz/tmp/ili_model>
Info: getIliFiles(): scan ili-files in folder </home/bjsvwjek/eclipse_ws/gewschutz/tmp/ili_model>... (RepositoryAccess.java:94)
Info: lookup model <CHAdminCodes_V1> 2.3 in repository <http://models.interlis.ch/>
Info: getIliFiles(): read ilimodels.xml from <http://models.interlis.ch/>... (RepositoryAccess.java:108)
Info: lookup model <CHAdminCodes_V1> 2.3 in repository </home/bjsvwjek/eclipse_ws/lib/ili2pg361>
Info: getIliFiles(): scan ili-files in folder </home/bjsvwjek/eclipse_ws/lib/ili2pg361>... (RepositoryAccess.java:94)
Info: getIliSite(): read ilisite.xml from </home/bjsvwjek/eclipse_ws/gewschutz/tmp/ili_model>... (RepositoryAccess.java:129)
Info: getIliSite(): read ilisite.xml from <http://models.interlis.ch/>... (RepositoryAccess.java:129)
Info: getIliSite(): read ilisite.xml from </home/bjsvwjek/eclipse_ws/lib/ili2pg361>... (RepositoryAccess.java:129)
Info: lookup model <CHAdminCodes_V1> 2.3 in repository <http://models.geo.admin.ch>
Info: getIliFiles(): read ilimodels.xml from <http://models.geo.admin.ch>... (RepositoryAccess.java:108)
Info: lookup model <LocalisationCH_V1> 2.3 in repository </home/bjsvwjek/eclipse_ws/gewschutz/tmp/ili_model>
Info: lookup model <LocalisationCH_V1> 2.3 in repository <http://models.interlis.ch/>
Info: lookup model <LocalisationCH_V1> 2.3 in repository </home/bjsvwjek/eclipse_ws/lib/ili2pg361>
Info: lookup model <LocalisationCH_V1> 2.3 in repository <http://models.geo.admin.ch>
Info: lookup model <GeometryCHLV03_V1> 2.3 in repository </home/bjsvwjek/eclipse_ws/gewschutz/tmp/ili_model>
Info: lookup model <GeometryCHLV03_V1> 2.3 in repository <http://models.interlis.ch/>
Info: lookup model <GeometryCHLV03_V1> 2.3 in repository </home/bjsvwjek/eclipse_ws/lib/ili2pg361>
Info: lookup model <GeometryCHLV03_V1> 2.3 in repository <http://models.geo.admin.ch>
Info: lookup model <Units> 2.3 in repository </home/bjsvwjek/eclipse_ws/gewschutz/tmp/ili_model>
Info: lookup model <Units> 2.3 in repository <http://models.interlis.ch/>
Info: lookup model <CoordSys> 2.3 in repository </home/bjsvwjek/eclipse_ws/gewschutz/tmp/ili_model>
Info: lookup model <CoordSys> 2.3 in repository <http://models.interlis.ch/>
Info: ilifile </home/bjsvwjek/.ilicache/models.interlis.ch/refhb23/CoordSys-20151124.ili>
Info: ilifile </home/bjsvwjek/.ilicache/models.geo.admin.ch/CH/CHBase_Part2_LOCALISATION_20110830.ili>
Info: ilifile </home/bjsvwjek/.ilicache/models.interlis.ch/refhb23/Units-20120220.ili>
Info: ilifile </home/bjsvwjek/.ilicache/models.geo.admin.ch/CH/CHBase_Part4_ADMINISTRATIVEUNITS_20110830.ili>
Info: ilifile </home/bjsvwjek/.ilicache/models.geo.admin.ch/CH/CHBase_Part1_GEOMETRY_20110830.ili>
Info: ilifile </home/bjsvwjek/eclipse_ws/gewschutz/tmp/ili_model/PlanerischerGewaesserschutz_V1_1.ili>
Info: doSmart1(): viewable Localisation_V1.LocalisedText newClass, localisedtext (Viewable2TableMapper.java:217)
Info: doSmart1(): viewable Localisation_V1.LocalisedMText newClass, localisedmtext (Viewable2TableMapper.java:217)
Info: doSmart1(): viewable Localisation_V1.MultilingualText newClass, multilingualtext (Viewable2TableMapper.java:217)
Info: doSmart1(): viewable LocalisationCH_V1.LocalisedText superClass, localisationch_v1_localisedtext (Viewable2TableMapper.java:217)
Info: doSmart1(): viewable LocalisationCH_V1.LocalisedMText superClass, localisationch_v1_localisedmtext (Viewable2TableMapper.java:217)
Info: doSmart1(): viewable LocalisationCH_V1.MultilingualText superClass, localisationch_v1_multilingualtext (Viewable2TableMapper.java:217)
Info: doSmart1(): viewable PlanerischerGewaesserschutz_LV95_V1_1.GSBereiche.GSBereich newClass, gsbereich (Viewable2TableMapper.java:217)
Info: doSmart1(): viewable PlanerischerGewaesserschutz_LV95_V1_1.GWSZonen.Kanton_ newClass, kanton_ (Viewable2TableMapper.java:217)
Info: doSmart1(): viewable PlanerischerGewaesserschutz_LV95_V1_1.GWSZonen.Status newClass, status (Viewable2TableMapper.java:217)
Info: doSmart1(): viewable PlanerischerGewaesserschutz_LV95_V1_1.GWSZonen.GWSAreal newClass, gwsareal (Viewable2TableMapper.java:217)
Info: doSmart1(): viewable PlanerischerGewaesserschutz_LV95_V1_1.GWSZonen.GWSZone newClass, gwszone (Viewable2TableMapper.java:217)
Info: doSmart1(): viewable PlanerischerGewaesserschutz_LV95_V1_1.GWSZonen.StatusGWSAreal newClass, statusgwsareal (Viewable2TableMapper.java:217)
Info: doSmart1(): viewable PlanerischerGewaesserschutz_LV95_V1_1.GWSZonen.StatusGWSZone newClass, statusgwszone (Viewable2TableMapper.java:217)
Info: doSmart1(): viewable PlanerischerGewaesserschutz_LV95_V1_1.GWSZonen.Dokument newClass, dokument (Viewable2TableMapper.java:217)
Info: doSmart1(): viewable PlanerischerGewaesserschutz_LV95_V1_1.GWSZonen.HinweisWeitereDokumente newClass, hinweisweiteredokumente (Viewable2TableMapper.java:217)
Info: doSmart1(): viewable PlanerischerGewaesserschutz_LV95_V1_1.GWSZonen.RechtsvorschriftGWSAreal newClass, rechtsvorschriftgwsareal (Viewable2TableMapper.java:217)
Info: doSmart1(): viewable PlanerischerGewaesserschutz_LV95_V1_1.GWSZonen.RechtsvorschriftGWSZone newClass, rechtsvorschriftgwszone (Viewable2TableMapper.java:217)
Info: doSmart1(): viewable PlanerischerGewaesserschutz_LV95_V1_1.TransferMetadaten.Amt newClass, amt (Viewable2TableMapper.java:217)
Info: doSmart1(): viewable PlanerischerGewaesserschutz_LV95_V1_1.TransferMetadaten.Darstellungsdienst newClass, darstellungsdienst (Viewable2TableMapper.java:217)
Info: doSmart1(): viewable PlanerischerGewaesserschutz_LV95_V1_1.TransferMetadaten.Datenbestand newClass, datenbestand (Viewable2TableMapper.java:217)
Info: doSmart1(): viewable PlanerischerGewaesserschutz_LV95_V1_1.TransferMetadaten.zustaendigeStelleDatenbestand newClass, zustaendigestelledatenbestand (Viewable2TableMapper.java:217)
Info: doSmart1(): viewable PlanerischerGewaesserschutz_LV95_V1_1.TransferMetadaten.DarstellungsdienstDatenbestand newClass, darstellungsdienstdatenbestand (Viewable2TableMapper.java:217)
Info: create table structure...
Info: generateViewable(): wrapper of viewable STRUCTURE Localisation_V1.LocalisedText (TransferFromIli.java:222)
Info: generateViewable(): wrapper of viewable STRUCTURE Localisation_V1.LocalisedMText (TransferFromIli.java:222)
Info: generateViewable(): wrapper of viewable STRUCTURE Localisation_V1.MultilingualText (TransferFromIli.java:222)
Info: generateViewable(): wrapper of viewable STRUCTURE Localisation_V1.LocalisedText (TransferFromIli.java:222)
Info: generateViewable(): wrapper of viewable STRUCTURE Localisation_V1.LocalisedMText (TransferFromIli.java:222)
Info: generateViewable(): wrapper of viewable STRUCTURE Localisation_V1.MultilingualText (TransferFromIli.java:222)
Info: generateViewable(): wrapper of viewable CLASS PlanerischerGewaesserschutz_LV95_V1_1.GSBereiche.GSBereich (TransferFromIli.java:222)
Info: generateViewable(): wrapper of viewable STRUCTURE PlanerischerGewaesserschutz_LV95_V1_1.GWSZonen.Kanton_ (TransferFromIli.java:222)
Info: generateViewable(): wrapper of viewable CLASS PlanerischerGewaesserschutz_LV95_V1_1.GWSZonen.Status (TransferFromIli.java:222)
Info: generateViewable(): wrapper of viewable CLASS PlanerischerGewaesserschutz_LV95_V1_1.GWSZonen.GWSAreal (TransferFromIli.java:222)
Info: generateViewable(): wrapper of viewable CLASS PlanerischerGewaesserschutz_LV95_V1_1.GWSZonen.GWSZone (TransferFromIli.java:222)
Info: generateViewable(): wrapper of viewable CLASS PlanerischerGewaesserschutz_LV95_V1_1.GWSZonen.Dokument (TransferFromIli.java:222)
Info: generateViewable(): wrapper of viewable ASSOCIATION PlanerischerGewaesserschutz_LV95_V1_1.GWSZonen.HinweisWeitereDokumente (TransferFromIli.java:222)
Info: generateViewable(): wrapper of viewable ASSOCIATION PlanerischerGewaesserschutz_LV95_V1_1.GWSZonen.RechtsvorschriftGWSAreal (TransferFromIli.java:222)
Info: generateViewable(): wrapper of viewable ASSOCIATION PlanerischerGewaesserschutz_LV95_V1_1.GWSZonen.RechtsvorschriftGWSZone (TransferFromIli.java:222)
Info: generateViewable(): wrapper of viewable CLASS PlanerischerGewaesserschutz_LV95_V1_1.TransferMetadaten.Amt (TransferFromIli.java:222)
Info: generateViewable(): wrapper of viewable CLASS PlanerischerGewaesserschutz_LV95_V1_1.TransferMetadaten.Darstellungsdienst (TransferFromIli.java:222)
Info: generateViewable(): wrapper of viewable CLASS PlanerischerGewaesserschutz_LV95_V1_1.TransferMetadaten.Datenbestand (TransferFromIli.java:222)
Info: generateViewable(): wrapper of viewable STRUCTURE Localisation_V1.LocalisedText (TransferFromIli.java:222)
Info: generateViewable(): wrapper of viewable STRUCTURE Localisation_V1.LocalisedMText (TransferFromIli.java:222)
Info: generateViewable(): wrapper of viewable STRUCTURE Localisation_V1.MultilingualText (TransferFromIli.java:222)
Info: generateViewable(): wrapper of viewable STRUCTURE Localisation_V1.LocalisedText (TransferFromIli.java:222)
Info: generateViewable(): wrapper of viewable STRUCTURE Localisation_V1.LocalisedMText (TransferFromIli.java:222)
Info: generateViewable(): wrapper of viewable STRUCTURE Localisation_V1.MultilingualText (TransferFromIli.java:222)
Info: generateViewable(): wrapper of viewable CLASS PlanerischerGewaesserschutz_LV95_V1_1.GSBereiche.GSBereich (TransferFromIli.java:222)
Info: generateViewable(): wrapper of viewable STRUCTURE PlanerischerGewaesserschutz_LV95_V1_1.GWSZonen.Kanton_ (TransferFromIli.java:222)
Info: generateViewable(): wrapper of viewable CLASS PlanerischerGewaesserschutz_LV95_V1_1.GWSZonen.Status (TransferFromIli.java:222)
Info: generateViewable(): wrapper of viewable CLASS PlanerischerGewaesserschutz_LV95_V1_1.GWSZonen.GWSAreal (TransferFromIli.java:222)
Info: generateViewable(): wrapper of viewable CLASS PlanerischerGewaesserschutz_LV95_V1_1.GWSZonen.GWSZone (TransferFromIli.java:222)
Info: generateViewable(): wrapper of viewable CLASS PlanerischerGewaesserschutz_LV95_V1_1.GWSZonen.Dokument (TransferFromIli.java:222)
Info: generateViewable(): wrapper of viewable ASSOCIATION PlanerischerGewaesserschutz_LV95_V1_1.GWSZonen.HinweisWeitereDokumente (TransferFromIli.java:222)
Info: generateViewable(): wrapper of viewable ASSOCIATION PlanerischerGewaesserschutz_LV95_V1_1.GWSZonen.RechtsvorschriftGWSAreal (TransferFromIli.java:222)
Info: generateViewable(): wrapper of viewable ASSOCIATION PlanerischerGewaesserschutz_LV95_V1_1.GWSZonen.RechtsvorschriftGWSZone (TransferFromIli.java:222)
Info: generateViewable(): wrapper of viewable CLASS PlanerischerGewaesserschutz_LV95_V1_1.TransferMetadaten.Amt (TransferFromIli.java:222)
Info: generateViewable(): wrapper of viewable CLASS PlanerischerGewaesserschutz_LV95_V1_1.TransferMetadaten.Darstellungsdienst (TransferFromIli.java:222)
Info: generateViewable(): wrapper of viewable CLASS PlanerischerGewaesserschutz_LV95_V1_1.TransferMetadaten.Datenbestand (TransferFromIli.java:222)
Info: initDbDefs(): CREATE SEQUENCE afu_gewaesserschutz_export.t_ili2db_seq; (PgSequenceBasedIdGen.java:124)
Info: visit1TableEnd(): CREATE TABLE afu_gewaesserschutz_export.gwsareal (
  T_Id bigint PRIMARY KEY DEFAULT nextval('afu_gewaesserschutz_export.t_ili2db_seq')
  ,identifikator varchar(255) NULL
  ,typ varchar(255) NOT NULL
  ,istaltrechtlich boolean NOT NULL
  ,status bigint NOT NULL
) (GeneratorJdbc.java:175)
Info: visit1TableEnd(): SELECT AddGeometryColumn('afu_gewaesserschutz_export','gwsareal','geometrie',(SELECT srid FROM SPATIAL_REF_SYS WHERE AUTH_NAME='epsg' AND AUTH_SRID=2056),'POLYGON',2) (GeneratorPostgresql.java:191)
Info: visit1TableEnd(): COMMENT ON TABLE afu_gewaesserschutz_export.gwsareal IS '@iliname PlanerischerGewaesserschutz_LV95_V1_1.GWSZonen.GWSAreal' (GeneratorPostgresql.java:244)
Info: visit1TableEnd(): COMMENT ON COLUMN afu_gewaesserschutz_export.gwsareal.identifikator IS '@iliname Identifikator' (GeneratorPostgresql.java:269)
Info: visit1TableEnd(): COMMENT ON COLUMN afu_gewaesserschutz_export.gwsareal.geometrie IS '@iliname Geometrie' (GeneratorPostgresql.java:269)
java.io.IOException: failed to add comment to table afu_gewaesserschutz_export.gwsareal
    ch.ehi.ili2db.base.Ili2db.runSchemaImport(Ili2db.java:1023)
    ch.ehi.ili2db.base.Ili2db.run(Ili2db.java:187)
    ch.ehi.ili2db.AbstractMain.domain(AbstractMain.java:387)
    ch.ehi.ili2pg.PgMain.main(PgMain.java:71)
  failed to add comment to table afu_gewaesserschutz_export.gwsareal
      ch.ehi.sqlgen.generator_impl.jdbc.GeneratorPostgresql.visit1TableEnd(GeneratorPostgresql.java:275)
      ch.ehi.sqlgen.generator.GeneratorDriver.visit1Table(GeneratorDriver.java:89)
      ch.ehi.sqlgen.generator.GeneratorDriver.visitSchema(GeneratorDriver.java:55)
      ch.ehi.ili2db.base.Ili2db.runSchemaImport(Ili2db.java:978)
      ch.ehi.ili2db.base.Ili2db.run(Ili2db.java:187)
      ch.ehi.ili2db.AbstractMain.domain(AbstractMain.java:387)
      ch.ehi.ili2pg.PgMain.main(PgMain.java:71)
    ERROR: column "geometrie" of relation "afu_gewaesserschutz_export.gwsareal" does not exist
        org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2284)
        org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2003)
        org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:200)
        org.postgresql.jdbc.PgStatement.execute(PgStatement.java:424)
        org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:321)
        org.postgresql.jdbc.PgStatement.execute(PgStatement.java:313)
        ch.ehi.sqlgen.generator_impl.jdbc.GeneratorPostgresql.visit1TableEnd(GeneratorPostgresql.java:270)
        ch.ehi.sqlgen.generator.GeneratorDriver.visit1Table(GeneratorDriver.java:89)
        ch.ehi.sqlgen.generator.GeneratorDriver.visitSchema(GeneratorDriver.java:55)
        ch.ehi.ili2db.base.Ili2db.runSchemaImport(Ili2db.java:978)
        ch.ehi.ili2db.base.Ili2db.run(Ili2db.java:187)
        ch.ehi.ili2db.AbstractMain.domain(AbstractMain.java:387)
        ch.ehi.ili2pg.PgMain.main(PgMain.java:71)

**Comment by edigonzales** [comment]
[http://geo.so.ch/models/ARP/SO_Nutzungsplanung_20170105.ili](http://geo.so.ch/models/ARP/SO_Nutzungsplanung_20170105.ili)

**Comment by edigonzales** [comment]
Macht er *ohne* `--defaultSrsAuth` und `--defaultSrsCode` auch 

`Info: visit1TableEnd(): SELECT AddGeometryColumn('afu_gewaesserschutz_export','gwsareal','geometrie',(SELECT srid FROM SPATIAL_REF_SYS WHERE AUTH_NAME='epsg' AND AUTH_SRID=2056),'POLYGON',2) (GeneratorPostgresql.java:191)
`

**Comment by edigonzales** [comment]
Irgendwie kommt mir das bekannt vor. Ich hab es damals glaub der alten PostGIS-Version zugeschrieben und nicht weiter verfolgt. Wäre aber verwundert, weil wir haben ja "kleine" Modelle mit EPSG:2056.

**Comment by dkottmann** [comment]
schemaimport mit lv95 funktioniert bei anderen Modellen mit ili2pg 3.7.0. 
siehe z.B. https://github.com/claeis/ili2db/issues/66
--defaultSrsAuth ist nicht nötig (default ist EPSG)
Ist der Wert case-sensitive?

**Comment by edigonzales** [comment]
Try capital letters instead:

`--defaultSrsAuth epsg` fail
`--defaultSrsAuth EPSG` success

Not sure if the authority is case sensitive?!

**Comment by edigonzales** [comment]
Mist, 2 Minuten schneller :-)

**Comment by uncoyote** [comment]
Danke euch - bei Verwendung von EPSG uppercase funktionierts - Hab spezifischen Issue #71 eröffnet damit dies nicht weiter Verwirrung stiftet.
