### ISSUE TITLE
ili2pg sequences and fme

### ISSUE THREAD

**Issue by aipog** [claeis/ili2db#75]
When I make a schema import with ili2pg the procedure create all my tables and only one sequence is created for all my objects (t_ili2db_seq). Why only one sequence is created for all my tables?

Problem: if I want to load data in my new tables with a FME Workbench and write my data with a postgis writer I have errors because the implementation of autoincrement maded in ili2pg is made in a old syntax. The right implementation is to use the data type serial. For example: `t_id serial NOT NULL` replace the old `t_id bigint NOT NULL DEFAULT nextval('t_ili2db_seq'::regclass)`. 

Is it possible to fix the code and renew postgresql statement?

Thank you.

**Comment by claeis** [comment]
What is your Table Settings: Allow Serial Column Writing in the FME Workbench? Do you set the column t_id in the workbench or not?

**Comment by aipog** [comment]
Thank you for the reply. The column t_id is not setted in the writer and allow serial column writing is no.
But there is a specific reason to have only one sequence and don't want to use the serial data type?
Thank you

**Comment by claeis** [comment]
``serial`` is just a notational convenience: see https://www.postgresql.org/docs/9.6/static/datatype-numeric.html#DATATYPE-SERIAL

And yes, two reasons: 1) easier to locate errors in records and 2) more control (see ili2pg option --idSeqMin, --idSeqMax)

**Comment by aipog** [comment]
Ok is only a notational convenience but is the state of the art for sequences. See [fme issue serial](https://knowledge.safe.com/questions/1703/serial-data-types-and-insert-into-postgresql.html)

Honestly I don't understand the easy way to find a id in multiple tables and what's the point limiting my sequence?
