### ISSUE TITLE
Export data based on translated MGDM

### ISSUE THREAD

**Issue by giodegiorgi** [claeis/ili2db#86]
Dear all,

following the Interlis specifications we build a translated (IT) ili model of the MGDM model, with same structure and same parameters, just with the values translated in italian.

After gathering some data, we tried to export them and with the translated model (IT) is working well, while with the "original" (DE) is working but the content of the XTF is empty!

please find attached the models as well as the exports.

[Schutzbauten_de_V1.xtf.txt](https://github.com/claeis/ili2db/files/1037773/Schutzbauten_de_V1.xtf.txt)
[Schutzbauten_it_V1.ili.txt](https://github.com/claeis/ili2db/files/1037772/Schutzbauten_it_V1.ili.txt)
[Schutzbauten_it_V1.xtf.txt](https://github.com/claeis/ili2db/files/1037774/Schutzbauten_it_V1.xtf.txt)
[Schutzbauten_V1.ili.txt](https://github.com/claeis/ili2db/files/1037775/Schutzbauten_V1.ili.txt)

Thanks for a fix.

Bests
G

**Comment by claeis** [comment]
If you import elementi_protezione_LV03_V1, you can export elementi_protezione_LV03_V1. An automatic translation, as part of the export, to Schutzbauten_LV03_V1 is doable, but a new function.

This is not a bug, but a new feature request. Similar to Issue #46.

**Comment by giodegiorgi** [comment]
the decision to merge the two issues is debatable since not belonging to the same topic.

**Comment by claeis** [comment]
This issue and issue #46 are not the same thing, just similar. No reason to merge them.

**Comment by claeis** [comment]
see #222. Use --exportModels to control according what model the export is done
