### ISSUE TITLE
NullPointerException bei XML-Katalog Import

### ISSUE THREAD

**Issue by dkottmann** [claeis/ili2db#9]
Nach dem Schemaimport des Datensatzes "nutzungsflaechen" ist ein einmaliger Import des XML-Kataloges "Nutzungsflaechen_kataloge_20160801.xml" erforderlich. 
Dabei kommt es mit ili2pg 3.4.0 zur Fehlermeldung mapping failed / NullPointerException. 

Log: 
> Info: dburl <jdbc:postgresql:wfs_agg>
Info: dbusr <rails>
Info: ili2pg-3.4.0-20160917
Info: ili2c-4.5.23-20160708
Info: java.version 1.7.0_111
Info: user.name <ikgeo>
Info: maxMemory 1818624 KB
Info: dbschema <ili_nutzungsflaechen>
Info: dburl <jdbc:postgresql:wfs_agg>
Info: dbusr <rails>
Info: databaseProduct <PostgreSQL>
Info: databaseVersion <9.3.14>
Info: driverVersion <PostgreSQL 9.4.1208.jre6>
Info: postGISVersion <POSTGIS="2.1.2 r12389" GEOS="3.4.2-CAPI-1.8.2 r3921" PROJ="Rel. 4.8.0, 6 March 2012" GDAL="GDAL 1.10.1, released 2013/08/26" LIBXML="2.9.1" LIBJSON="UNKNOWN" RASTER>
Info: compile models...
Info: lookup model <Nutzungsflaechen_Kataloge_V1_3> in repository <jdbc:postgresql:wfs_agg/ili_nutzungsflaechen>
Info: lookup model <CatalogueObjects_V1> 2.3 in repository <jdbc:postgresql:wfs_agg/ili_nutzungsflaechen>
Info: lookup model <LocalisationCH_V1> 2.3 in repository <jdbc:postgresql:wfs_agg/ili_nutzungsflaechen>
Info: lookup model <Bewirtschaftungseinheit_V1_2> 2.3 in repository <jdbc:postgresql:wfs_agg/ili_nutzungsflaechen>
Info: lookup model <Units> 2.3 in repository <jdbc:postgresql:wfs_agg/ili_nutzungsflaechen>
Info: lookup model <GeometryCHLV03_V1> 2.3 in repository <jdbc:postgresql:wfs_agg/ili_nutzungsflaechen>
Info: lookup model <Bearbeitungsstatus_V1_2> 2.3 in repository <jdbc:postgresql:wfs_agg/ili_nutzungsflaechen>
Info: lookup model <CoordSys> 2.3 in repository <jdbc:postgresql:wfs_agg/ili_nutzungsflaechen>
Info: lookup model <CHAdminCodes_V1> 2.3 in repository <jdbc:postgresql:wfs_agg/ili_nutzungsflaechen>
Info: lookup model <Landwirtschaftliche_Zonengrenzen_Kataloge_V1_2> 2.3 in repository <jdbc:postgresql:wfs_agg/ili_nutzungsflaechen>
Info: ilifile </home/ikgeo/.ilicache/jdbc&003apostgresql&003awfs_agg/ili_nutzungsflaechen/CoordSys-20151124.ili>
Info: ilifile </home/ikgeo/.ilicache/jdbc&003apostgresql&003awfs_agg/ili_nutzungsflaechen/Units-20120220.ili>
Info: ilifile </home/ikgeo/.ilicache/jdbc&003apostgresql&003awfs_agg/ili_nutzungsflaechen/CHBase_Part2_LOCALISATION_20110830.ili>
Info: ilifile </home/ikgeo/.ilicache/jdbc&003apostgresql&003awfs_agg/ili_nutzungsflaechen/CHBase_Part3_CATALOGUEOBJECTS_20110830.ili>
Info: ilifile </home/ikgeo/.ilicache/jdbc&003apostgresql&003awfs_agg/ili_nutzungsflaechen/CHBase_Part1_GEOMETRY_20110830.ili>
Info: ilifile </home/ikgeo/.ilicache/jdbc&003apostgresql&003awfs_agg/ili_nutzungsflaechen/CHBase_Part4_ADMINISTRATIVEUNITS_20110830.ili>
Info: ilifile </home/ikgeo/.ilicache/jdbc&003apostgresql&003awfs_agg/ili_nutzungsflaechen/bearbeitungsstatus_20140701.ili>
Info: ilifile </home/ikgeo/.ilicache/jdbc&003apostgresql&003awfs_agg/ili_nutzungsflaechen/landwirtschaftliche_zonengrenzen_20140701.ili>
Info: ilifile </home/ikgeo/.ilicache/jdbc&003apostgresql&003awfs_agg/ili_nutzungsflaechen/bewirtschaftungseinheit_20140701.ili>
Info: ilifile </home/ikgeo/.ilicache/jdbc&003apostgresql&003awfs_agg/ili_nutzungsflaechen/nutzungsflaechen_LV03_V1_3.ili>
Info: create table structure...
mapping of ili-classes to sql-tables failed
  mapping of Nutzungsflaechen_Kataloge_V1_3.LNF_Kataloge.LNF_Katalog_NutzungsartRef failed
    CatalogueObjects_V1.Catalogues.CatalogueReference.Reference
      java.lang.NullPointerException

Modell (nur Teil LV03 getestet): 
http://models.geo.admin.ch/BLW/nutzungsflaechen_20160101.ili 

XML-Katalog: 
http://models.geo.admin.ch/BLW/nutzungsflaechen_kataloge_20160801.xml 

Fehler kann mit anderen Modellen / Katalogen reproduziert werden (vgl. http://models.geo.admin.ch/BLW : Modelle Biodiversitätsförderflächen und Bewirtschaftungseinheit)

**Comment by edigonzales** [comment]
Schemaimport:

`java -jar /home/stefan/Apps/ili2pg-3.4.0-orig/ili2pg.jar --dbhost localhost --dbdatabase xanadu2 --dbusr stefan --dbpwd XXX --dbschema nfl_13 --schemaimport --createGeomIdx --defaultSrsCode 21781 --createBasketCol --sqlEnableNull --createEnumTxtCol  --models Nutzungsflaechen_V1_3 `

Katalogimport:

`java -jar /home/stefan/Apps/ili2pg-3.4.0-orig/ili2pg.jar --dbhost localhost --dbdatabase xanadu2 --dbusr stefan --dbpwd XXX --dbschema nfl_13 --import --createGeomIdx --defaultSrsCode 21781 --createBasketCol --sqlEnableNull --createEnumTxtCol  --models Nutzungsflaechen_V1_3 nutzungsflaechen_kataloge_20160801.xml`

Fehlermeldung:

`Info: process data file...
Info: data <nutzungsflaechen_kataloge_20160801.xml>
Info: Basket Nutzungsflaechen_Kataloge_V1_3.LNF_Kataloge(oid 2)...
Error: Object 89d74853-2425-102f-bec9-597a5b569e17 at (line 3191,col 119)
Error:   ERROR: value too long for type character varying(255)
Error: failed to query nfl_13.t_ili2db_seq
Error:   ERROR: current transaction is aborted, commands ignored until end of transaction block
org.postgresql.util.PSQLException: ERROR: current transaction is aborted, commands ignored until end of transaction block
  ERROR: current transaction is aborted, commands ignored until end of transaction block`

LocalisedText ist vom Typ `TEXT`. ili2db macht ein `character varying(255)` in der Datenbank, was manchmal nicht reicht.

Soweit meine Verständnis der Problematik.

Interessant wären jeweils auch die genauen Programmaufrufe.

**Comment by edigonzales** [comment]
Wenn ich in der Tabelle `lnf_katalog_nutzungsart` die erlaubte Anzahl Zeichen erhöhe (z.B. 1255) funktionert es:

`Info: process data file...
Info: data <nutzungsflaechen_kataloge_20160801.xml>
Info: Basket Nutzungsflaechen_Kataloge_V1_3.LNF_Kataloge(oid 2)...
Info: nutzungsflaechen_kataloge_20160801.xml: Nutzungsflaechen_Kataloge_V1_3.LNF_Kataloge BID=2
Info:      37 objects in CLASS Nutzungsflaechen_Kataloge_V1_3.LNF_Kataloge.LNF_Katalog_Num_Nutzung
Info:     148 objects in CLASS Nutzungsflaechen_Kataloge_V1_3.LNF_Kataloge.LNF_Katalog_Nutzungsart
Info:       3 objects in CLASS Nutzungsflaechen_Kataloge_V1_3.LNF_Kataloge.LNF_Katalog_Programm
Info: ...import done`

**Comment by edigonzales** [comment]
Hast du noch die Befehle? Also wie wurde das Schema erzeugt? Und mit welchem Befehl willst du den Katalog importieren?

**Comment by dkottmann** [comment]
D.h. es liegt an der erlaubten Anzahl Zeichen bzw. ili2pg dürfte die erlaubte Anzahl Zeichen nicht auf 255 beschränken?

1. Import-Befehl Schema (reproduziert für Bewirtschaftungseinheit): 
> java -Xmx256m -jar /opt/ili2pg/ili2pg.jar --dbport 5432 --dbdatabase wfs_agg --dbschema ili_bewirtschaftungseinheit --dbusr '-' --dbpwd '-' --schemaimport --createGeomIdx --defaultSrsCode 21781 --createBasketCol --createFkIdx --sqlEnableNull --idSeqMin 4600000000000000001 --idSeqMax 9223372036854775807 --createEnumTxtCol /home/rails/geodienste-config/current/ili_agg/ili/bewirtschaftungseinheit/bewirtschaftungseinheit_LV03_V1_2.ili

2. Import-Befehl Katalog (reproduziert für Bewirtschaftungseinheit): 
> java -jar /opt/ili2pg/ili2pg.jar --dbport 5432 --dbdatabase wfs_agg --dbschema ili_bewirtschaftungseinheit --dbusr '-' --dbpwd '-' --import /home/rails/geodienste-config/current/ili_agg/ili/bewirtschaftungseinheit/bearbeitungsstatus_kataloge_20140701.xml

**Comment by edigonzales** [comment]
Funktioniert bei mir auch nicht. Mit `--noSmartMapping` funktioniert es. Viel mehr konnte ich in dieser Objektkatalog-Hölle nicht rausfinden.

**Comment by claeis** [comment]
fixed

**Comment by dkottmann** [comment]
Mit ili2pg 3.5.0 sollte das gefixed sein, oder? 
Retest mit ili2pg 3.5.0 und analogen Befehlen wie oben --> erneut Fehlermeldungen beim Import des XML-Katalogs: 
```
Error: failed to create sequence ili_bewirtschaftungseinheit.t_ili2db_seq
Error:   ERROR: relation "t_ili2db_seq" already exists
Info: create table structure...
mapping of ili-classes to sql-tables failed
  mapping of Bearbeitungsstatus_V1_2.Status.BS_Katalog_Prozess_StatusRef failed
    CatalogueObjects_V1.Catalogues.CatalogueReference.Reference
      java.lang.NullPointerException
```

**Comment by claeis** [comment]
Ja, diese issue ist mit 3.5.0 gefixed.
Neuer Fehler hat wahrscheinlich mit Fix von Issue #17 zu tun.
