### ISSUE TITLE
Geometry unique constraint issue

### ISSUE THREAD

**Issue by edigonzales** [claeis/ili2db#95]
I get an error importing data with `--unique`:

`Info: doObject(): DM01AVCH24LV95D.Liegenschaften.Grenzpunkt oid 79691 {LageZuv ja, HoheitsgrenzsteinAlt nein, Entstehung -> 79351 REF {}, LageGen 2.0, Geometrie COORD {C1 2605575.997, C2 1228561.745}, Punktzeichen unversichert, ExaktDefiniert Ja} (TransferFromXtf.java:950)`
`Error: Object 79691 at (line 351499,col 0)`
`Error:   ERROR: duplicate key value violates unique constraint "liegenschaften_grenzpunkt_geometrie_key"`
 `Detail: Key (geometrie)=(0101000020080800002DB29DFF03E14341EC51B8BE11BF3241) already exists.`

Could be something like this: [https://gis.stackexchange.com/questions/81123/what-is-the-precision-of-select-distinct-on-postgis-geometry-column](https://gis.stackexchange.com/questions/81123/what-is-the-precision-of-select-distinct-on-postgis-geometry-column). Some time ago a struggled with this behaviour. Perhaps `ST_AsBinary()` in the constraint definition does the trick? Similar here: [https://smathermather.com/2009/10/22/unique-constraint-on-geometry-continued/](https://smathermather.com/2009/10/22/unique-constraint-on-geometry-continued/)

I can test it if you point me to the right direction. Somewhere around here: [https://github.com/claeis/ehisqlgen/blob/master/src/ch/ehi/sqlgen/generator_impl/jdbc/GeneratorJdbc.java#L255](https://github.com/claeis/ehisqlgen/blob/master/src/ch/ehi/sqlgen/generator_impl/jdbc/GeneratorJdbc.java#L255)?

Data attached:
[ch_260100.zip](https://github.com/claeis/ili2db/files/1089322/ch_260100.zip)

**Comment by claeis** [comment]
UNIQUE syntax is DB specific. see also https://github.com/claeis/ehisqlgen/blob/master/src/ch/ehi/sqlgen/generator_impl/jdbc/GeneratorGeoPackage.java#L190

**Comment by edigonzales** [comment]
See [https://github.com/claeis/ehisqlgen/pull/1](https://github.com/claeis/ehisqlgen/pull/1).

Some early tests show:
* Does *not* complain about the "duplicate" geometry reported above. -> Ok.
* Does complain about a combined unique constraint (nbident and nummer from lfp3). -> Ok.
* Does complain about a real duplicate (point) geometry. -> Ok.

Find attached ili2pg-3.9.0 with patched ehisqlgen.jar.
[ili2pg-3.9.0-unique.zip](https://github.com/claeis/ili2db/files/1091541/ili2pg-3.9.0-unique.zip)
